// Cooking guides. Body blocks: {h}, {p}, {ul}, {ol}, {table: {head, rows, note?}}, {chart: name, caption},
// {img: name, caption}, {cuts: true} (knife-cut diagrams), {tip}. Text may contain links as {{recipe:slug}} / {{guide:slug}}.

// Knife cuts, shared by both languages; `shape` picks the SVG drawn in build.mjs.
export const CUTS = [
  { id: 'wagiri', shape: 'rounds', en: ['Rounds', 'Wa-giri', '5 mm–2 cm thick slices across a carrot or daikon.', 'Simmered daikon, oden'], ja: ['輪切り', 'わぎり', 'にんじんや大根を端から5mm〜2cmの厚さに切る。', 'ふろふき大根、おでん'] },
  { id: 'hangetsu', shape: 'halfmoons', en: ['Half-moons', 'Hangetsu-giri', 'Halve lengthways, then slice across, 5–8 mm thick.', 'Minato-nabe daikon'], ja: ['半月切り', 'はんげつぎり', '縦半分に切り、端から5〜8mmの厚さに切る。', 'みなと鍋の大根'] },
  { id: 'icho', shape: 'quarters', en: ['Quarter-moons', 'Ichō-giri (ginkgo leaf)', 'Quarter lengthways, then slice across, 3–5 mm thick.', 'Miso soup, mushroom rice carrot'], ja: ['いちょう切り', 'いちょうぎり', '縦4等分に切り、端から3〜5mmの厚さに切る。', 'みそ汁、炊き込みご飯のにんじん'] },
  { id: 'rangiri', shape: 'rangiri', en: ['Rolling wedges', 'Ran-giri', 'Cut on the diagonal, roll a quarter turn, cut again. Pieces about 3 cm with many cut faces, so they cook evenly and soak up sauce.', 'Nikujaga, curry'], ja: ['乱切り', 'らんぎり', '斜めに切り、手前に4分の1回して、また斜めに切る。約3cm。断面が多く、味がしみやすい。', '肉じゃが、カレー'] },
  { id: 'kushigata', shape: 'wedges', en: ['Wedges', 'Kushigata-giri', 'Halve an onion or tomato through the root, then cut in 6–8 wedges towards the centre.', 'Nikujaga onion, sheet-pan onion'], ja: ['くし形切り', 'くしがたぎり', '玉ねぎやトマトを縦半分に切り、中心に向かって6〜8等分に切る。', '肉じゃがの玉ねぎ、天板焼き'] },
  { id: 'sengiri', shape: 'julienne', en: ['Fine julienne', 'Sen-giri', 'Strips 1–2 mm wide and 4–5 cm long. For cabbage, roll several leaves and slice as thinly as you can.', 'Cabbage for ginger pork, ginger for mackerel'], ja: ['せん切り', 'せんぎり', '幅1〜2mm、長さ4〜5cmの細切り。キャベツは数枚重ねて丸め、端からできるだけ細く。', '生姜焼きのキャベツ、サバの味噌煮のしょうが'] },
  { id: 'tanzaku', shape: 'tanzaku', en: ['Thin rectangles', 'Tanzaku-giri', 'Planks 1 cm wide, 4–5 cm long and 1–2 mm thick, like a paper poem card.', 'Miso soup, stir-fries'], ja: ['短冊切り', 'たんざくぎり', '幅1cm、長さ4〜5cm、厚さ1〜2mmの薄い長方形。', 'みそ汁、炒め物'] },
  { id: 'sainome', shape: 'dice', en: ['Dice', 'Sainome-giri', '1 cm cubes: cut into 1 cm sticks, then across.', 'Soups, salads'], ja: ['さいの目切り', 'さいのめぎり', '1cm角の拍子木切りにしてから、端から1cmに切る。', 'スープ、サラダ'] },
  { id: 'mijin', shape: 'mince', en: ['Fine mince', 'Mijin-giri', 'Pieces of 1–2 mm. For onion, make close vertical and horizontal cuts without cutting through the root, then slice across.', 'Hamburg steak onion, ginger, garlic'], ja: ['みじん切り', 'みじんぎり', '1〜2mm角。玉ねぎは根元を残して縦横に細かく切り込みを入れ、端から切る。', 'ハンバーグの玉ねぎ、しょうが、にんにく'] },
  { id: 'naname', shape: 'diagonal', en: ['Diagonal slices', 'Naname-giri', 'Slices at about 45° across a long vegetable, 5 mm–1 cm thick.', 'Green onion for hot pot'], ja: ['斜め切り', 'ななめぎり', '細長い野菜を45度くらいに斜めに切る。厚さ5mm〜1cm。', '鍋の長ねぎ'] },
  { id: 'koguchi', shape: 'rings', en: ['Thin rings', 'Koguchi-giri', 'Rings of 1–3 mm across green onions or cucumbers.', 'Garnish for oyakodon, agedashi tofu'], ja: ['小口切り', 'こぐちぎり', '長ねぎやきゅうりを端から1〜3mmの輪に切る。', '親子丼や揚げ出し豆腐の薬味'] },
  { id: 'sasagaki', shape: 'shavings', en: ['Shavings', 'Sasagaki', 'Shave thin slivers off burdock as if sharpening a pencil, rotating as you go. Drop into water at once.', 'Burdock in minato-nabe'], ja: ['ささがき', 'ささがき', '鉛筆を削るように、ごぼうを回しながら薄くそぐ。すぐに水にさらす。', 'みなと鍋のごぼう'] },
];

export const GUIDES = {
  'knife-cuts': {
    image: null, chartThumb: 'cut-rangiri',
    en: {
      title: 'Japanese knife cuts, with diagrams', teaser: 'Twelve cuts used in Japanese recipes: what they look like, their sizes, and where we use them.',
      body: [
        { p: 'Japanese recipes name the cut rather than describe it: "cut the carrot in ran-giri" or "slice the green onion koguchi-giri". The cut matters: pieces of the same size cook in the same time, and cuts with many faces (like ran-giri) soak up a simmering sauce faster. Here are the twelve cuts used on Daily Table, with a diagram of each.' },
        { h: 'Holding the knife' },
        { p: 'Hold the handle with three fingers and pinch the blade between your thumb and the side of your index finger. The other hand makes a "cat\'s paw": fingertips curled under, knuckles against the flat of the blade, so the blade can never reach your fingertips. Push the knife forward and down as you cut, rather than pressing straight down.' },
        { h: 'The cuts' },
        { cuts: true },
        { h: 'Sizes at a glance' },
        { table: { head: ['Cut', 'Japanese', 'Size', 'Used in'], cutsTable: true } },
        { tip: 'Soak cut burdock, lotus root and eggplant in water for 5 minutes so they do not turn brown. Cut potatoes can wait in water for up to 30 minutes, but for nikujaga drain them well: the surface starch helps thicken the sauce.' },
      ],
    },
    ja: {
      title: '和食の切り方（図解）', teaser: '和食のレシピでよく使う12の切り方。形、大きさ、使う料理を図で紹介します。',
      body: [
        { p: '和食のレシピは「にんじんは乱切り」「長ねぎは小口切り」と、切り方の名前で書かれていることがほとんどです。切り方には意味があります。大きさをそろえれば火の通りがそろい、乱切りのように断面の多い切り方は、煮汁が早くしみ込みます。デイリーテーブルで使う12の切り方を図にまとめました。' },
        { h: '包丁の持ち方' },
        { p: '柄を3本の指で握り、刃の付け根を親指と人さし指の側面ではさみます。食材を押さえる手は「猫の手」。指先を内側に丸め、関節を包丁の腹に添えれば、刃が指先に当たりません。真上から押すのではなく、前に押し出すように切ります。' },
        { h: '切り方いろいろ' },
        { cuts: true },
        { h: '大きさの目安一覧' },
        { table: { head: ['切り方', '読み', '大きさ', '使う料理'], cutsTable: true } },
        { tip: 'ごぼう、れんこん、なすは切ったらすぐ水に5分ほどさらすと変色しません。じゃがいもは30分まで水につけておけますが、肉じゃがの場合はしっかり水けをきって。表面のでんぷんが煮汁にとろみをつけてくれます。' },
      ],
    },
  },
  'measurement-conversions': {
    image: null, chartThumb: 'cup-weights',
    en: {
      title: 'Measurement conversions: cups, spoons and grams', teaser: 'How many grams is a cup of flour? Spoon and cup sizes, weights of common ingredients, ounces and millilitres.',
      body: [
        { p: 'I write every recipe in grams because weighing is the most reliable way to cook, and because a "cup" means three different things depending on where you are. Our English editor Ryo converts every recipe to US cups using the weights below, which we measured ourselves (flour spooned into the cup and levelled with a knife, not scooped).' },
        { h: 'Spoons and cups' },
        { table: { head: ['Measure', 'Millilitres', 'Notes'], rows: [
          ['1 teaspoon (tsp)', '5 ml', 'Japanese 小さじ1'],
          ['1 tablespoon (tbsp)', '15 ml', '= 3 tsp. Japanese 大さじ1'],
          ['1 US cup', '240 ml', '= 16 tbsp. Used in our US measurements'],
          ['1 Japanese measuring cup', '200 ml', 'Older Japanese recipes; we never use it'],
          ['1 rice cup (1 gō, 1合)', '180 ml', 'About 150 g of uncooked rice. Comes with every rice cooker'],
          ['1 metric cup (UK, Australia)', '250 ml', ''],
          ['1 US fluid ounce', '30 ml', 'Exactly 29.6 ml'],
        ] } },
        { tip: 'Watch out for the rice cooker cup: it holds 180 ml, not 240 ml. If a recipe says "2 cups of rice" and means rice cooker cups, that is 360 ml (300 g).' },
        { h: 'How much does a cup weigh?' },
        { p: 'A cup of flour does not weigh the same as a cup of sugar. The chart shows the weight of one US cup (240 ml) of the ingredients we use most often; the table lists the baking staples.' },
        { chart: 'cup-weights', caption: 'Weight of 1 US cup, in grams' },
        { table: { head: ['Ingredient', '1 US cup', '½ cup', '1 tbsp'], rows: [
          ['All-purpose (plain) flour', '125 g', '63 g', '8 g'],
          ['Cake flour (hakurikiko)', '125 g', '63 g', '8 g'],
          ['Bread flour (kyōrikiko)', '130 g', '65 g', '8 g'],
          ['Granulated sugar', '200 g', '100 g', '12 g'],
          ['Japanese white sugar (jōhakutō)', '155 g', '78 g', '9 g'],
          ['Brown sugar, packed', '220 g', '110 g', '14 g'],
          ['Butter', '227 g', '113 g (1 stick)', '14 g'],
          ['Uncooked short-grain rice', '200 g', '100 g', '–'],
          ['Milk', '245 g', '122 g', '15 g'],
          ['Honey', '340 g', '170 g', '21 g'],
        ] } },
        { h: 'Japanese seasonings by the spoon' },
        { p: 'Japanese recipes measure seasonings with spoons; these are the weights if you prefer to use a scale (or want to know how much salt is in a tablespoon of soy sauce: about 2.6 g).' },
        { table: { head: ['Seasoning', '1 tsp (5 ml)', '1 tbsp (15 ml)'], rows: [
          ['Water, sake, vinegar', '5 g', '15 g'],
          ['Soy sauce', '6 g', '18 g'],
          ['Mirin', '6 g', '18 g'],
          ['Miso', '6 g', '18 g'],
          ['Fine salt', '6 g', '18 g'],
          ['Coarse sea salt', '5 g', '15 g'],
          ['Japanese white sugar', '3 g', '9 g'],
          ['Granulated sugar', '4 g', '12 g'],
          ['Honey', '7 g', '21 g'],
          ['Vegetable oil, sesame oil', '4 g', '12 g'],
          ['Potato starch, flour', '3 g', '9 g'],
          ['Instant dry yeast', '3 g', '9 g'],
          ['Baking powder', '4 g', '12 g'],
          ['Mayonnaise', '4 g', '12 g'],
          ['Ketchup', '5 g', '15 g'],
        ] } },
        { h: 'Weights: grams and ounces' },
        { table: { head: ['Grams', 'Ounces', 'Grams', 'Ounces / pounds'], rows: [
          ['10 g', '⅓ oz', '200 g', '7 oz'],
          ['25 g', '1 oz', '250 g', '8¾ oz'],
          ['50 g', '1¾ oz', '300 g', '10½ oz'],
          ['75 g', '2⅔ oz', '450 g', '1 lb'],
          ['100 g', '3½ oz', '500 g', '1 lb 1½ oz'],
          ['125 g', '4½ oz', '1 kg', '2 lb 3 oz'],
        ] } },
        { h: 'Liquids' },
        { table: { head: ['Metric', 'US'], rows: [
          ['50 ml', '3 tbsp + 1 tsp'], ['100 ml', 'scant ½ cup (6⅔ tbsp)'], ['120 ml', '½ cup'], ['180 ml', '¾ cup'],
          ['200 ml', '¾ cup + 4 tsp'], ['240 ml', '1 cup'], ['500 ml', '2 cups + 1 tbsp'], ['1 litre', '4¼ cups'],
        ] } },
        { h: 'Pans and eggs' },
        { ul: ['An 18 cm loaf pan is about 7 × 3½ inches; a 20 cm round pan is 8 inches; a 24 cm pot is 9½ inches.', 'A Japanese "1.5-kin" bread pan is about 20 × 10 × 10 cm, close to a US 9 × 4 inch Pullman pan.', 'Japanese M-size eggs weigh 58–64 g in the shell, about 50 g without: the same as a US large egg.', 'A US stick of butter is 113 g, 8 tablespoons or ½ cup. Japanese butter comes in 200 g blocks; mark it in 10 g slices.'] },
        { p: 'Temperatures are on the {{guide:oven-temperatures}} page, and rice is measured by the rice cup on the {{guide:rice-water-ratios}} page.', link: true },
      ],
    },
    ja: {
      title: '計量の換算表：カップ・スプーン・グラム', teaser: '小麦粉1カップは何グラム？スプーンとカップの容量、よく使う食材の重さ、オンスとミリリットル。',
      body: [
        { p: '当サイトのレシピは、すべてグラムで書いています。量るのがいちばん確実ですし、「1カップ」は国によって容量が違うからです。英語版編集の石田が、下の表の重さ（実際に計量した値。粉はスプーンでカップに入れ、すり切り）を使って、すべてのレシピをUSカップに換算しています。' },
        { h: 'スプーンとカップの容量' },
        { table: { head: ['計量', '容量', 'メモ'], rows: [
          ['小さじ1', '5ml', ''],
          ['大さじ1', '15ml', '小さじ3杯分'],
          ['USカップ1', '240ml', '大さじ16杯分。英語版のUS表記で使用'],
          ['計量カップ1（日本）', '200ml', '当サイトでは使いません'],
          ['1合（炊飯用カップ）', '180ml', '米約150g。炊飯器に付属'],
          ['メトリックカップ1（英国・豪州）', '250ml', ''],
          ['USオンス（液量）1', '30ml', '正確には29.6ml'],
        ] } },
        { tip: '炊飯器の計量カップは180ml。海外のレシピの「cup」（240ml）とは違います。「米2カップ」が炊飯器のカップなら360ml（300g）です。' },
        { h: '1カップは何グラム？' },
        { p: '同じ1カップでも、小麦粉と砂糖では重さがまったく違います。グラフはよく使う材料のUSカップ1杯（240ml）の重さ、表はお菓子作りの基本材料です。' },
        { chart: 'cup-weights', caption: 'USカップ1杯の重さ（g）' },
        { table: { head: ['材料', 'USカップ1', 'USカップ1/2', '大さじ1'], rows: [
          ['中力粉（オールパーパス）', '125g', '63g', '8g'],
          ['薄力粉', '125g', '63g', '8g'],
          ['強力粉', '130g', '65g', '8g'],
          ['グラニュー糖', '200g', '100g', '12g'],
          ['上白糖', '155g', '78g', '9g'],
          ['ブラウンシュガー（詰めて）', '220g', '110g', '14g'],
          ['バター', '227g', '113g（米国の1スティック）', '14g'],
          ['米（生）', '200g', '100g', '－'],
          ['牛乳', '245g', '122g', '15g'],
          ['はちみつ', '340g', '170g', '21g'],
        ] } },
        { h: '調味料の重さ（スプーン1杯）' },
        { p: '和食の調味料はスプーンで量るのが基本ですが、はかりを使いたい方のために重さをまとめました（しょうゆ大さじ1の塩分は約2.6gです）。' },
        { table: { head: ['調味料', '小さじ1（5ml）', '大さじ1（15ml）'], rows: [
          ['水・酒・酢', '5g', '15g'], ['しょうゆ', '6g', '18g'], ['みりん', '6g', '18g'], ['みそ', '6g', '18g'],
          ['精製塩', '6g', '18g'], ['あら塩', '5g', '15g'], ['上白糖', '3g', '9g'], ['グラニュー糖', '4g', '12g'],
          ['はちみつ', '7g', '21g'], ['サラダ油・ごま油', '4g', '12g'], ['片栗粉・小麦粉', '3g', '9g'],
          ['ドライイースト', '3g', '9g'], ['ベーキングパウダー', '4g', '12g'], ['マヨネーズ', '4g', '12g'], ['ケチャップ', '5g', '15g'],
        ] } },
        { h: 'グラムとオンス' },
        { table: { head: ['グラム', 'オンス', 'グラム', 'オンス・ポンド'], rows: [
          ['10g', '1/3オンス', '200g', '7オンス'], ['25g', '1オンス', '250g', '8と3/4オンス'], ['50g', '1と3/4オンス', '300g', '10と1/2オンス'],
          ['75g', '2と2/3オンス', '450g', '1ポンド'], ['100g', '3と1/2オンス', '500g', '1ポンド1と1/2オンス'], ['125g', '4と1/2オンス', '1kg', '2ポンド3オンス'],
        ] } },
        { h: '液体の換算' },
        { table: { head: ['メートル法', 'US表記'], rows: [
          ['50ml', '大さじ3＋小さじ1'], ['100ml', 'USカップ1/2弱（大さじ6と2/3）'], ['120ml', 'USカップ1/2'], ['180ml', 'USカップ3/4'],
          ['200ml', 'USカップ3/4＋小さじ4'], ['240ml', 'USカップ1'], ['500ml', 'USカップ2＋大さじ1'], ['1L', 'USカップ4と1/4'],
        ] } },
        { h: '型と卵' },
        { ul: ['18cmのパウンド型は約7×3.5インチ、20cmの丸型は8インチ、24cmの鍋は9.5インチ。', '1.5斤の食パン型は約20×10×10cmで、米国の9×4インチのプルマン型に近い大きさです。', '卵のMサイズは殻つきで58〜64g、中身は約50g。米国のLサイズとほぼ同じです。', '米国のバター1スティックは113g（大さじ8、USカップ1/2）。日本のバターは200g入りが多いので、10gごとに印をつけておくと便利です。'] },
        { p: '温度は{{guide:oven-temperatures}}、お米の量り方は{{guide:rice-water-ratios}}のページをご覧ください。', link: true },
      ],
    },
  },
  'oven-temperatures': {
    image: null, chartThumb: 'oven-scale',
    en: {
      title: 'Oven, frying and cooking temperatures', teaser: 'Celsius, Fahrenheit and gas marks, fan-oven adjustments, oil temperatures for frying, and when meat is done.',
      body: [
        { p: 'All Daily Table recipes give oven temperatures for a conventional oven (top and bottom heat, no fan). If your oven has a fan (convection) setting, lower the temperature by 20°C (about 25°F), or keep the temperature and check 5–10 minutes early. Ovens are often 10–20°C off what the dial says, so an oven thermometer (about ¥1,500) is the best ¥1,500 you will spend.' },
        { chart: 'oven-scale', caption: '' },
        { h: 'Oven temperature chart' },
        { table: { head: ['Celsius', 'Fahrenheit', 'Gas mark', 'Description', 'Fan oven', 'What we bake at this temperature'], rows: [
          ['140°C', '275°F', '1', 'Very low', '120°C', 'Drying yuzu peel, meringues'],
          ['150°C', '300°F', '2', 'Low', '130°C', 'Slow-roasting, cheesecake'],
          ['160°C', '325°F', '3', 'Moderately low', '140°C', 'Kabocha pudding in a water bath, beef stew in the oven'],
          ['170°C', '340°F', '3½', 'Moderate', '150°C', 'Yuzu pound cake (US recipes round this to 325°F or 350°F)'],
          ['180°C', '350°F', '4', 'Moderate', '160°C', 'Milk bread, most cakes and cookies'],
          ['190°C', '375°F', '5', 'Moderately hot', '170°C', 'Muffins, gratins'],
          ['200°C', '400°F', '6', 'Hot', '180°C', 'Yuzu miso salmon, roast vegetables'],
          ['220°C', '425°F', '7', 'Hot', '200°C', 'Sheet-pan miso chicken'],
          ['230°C', '450°F', '8', 'Very hot', '210°C', 'Crisping, browning'],
          ['250°C', '480°F', '9', 'Very hot', '230°C', 'Pizza, flatbreads'],
        ] } },
        { p: 'To convert yourself: °F = °C × 1.8 + 32, and °C = (°F − 32) ÷ 1.8. A Japanese toaster oven at 1,000 W runs at about 230°C, at 1,300 W about 250°C.' },
        { h: 'Oil temperatures for deep-frying' },
        { p: 'You do not need a thermometer: dip a dry wooden chopstick into the oil, or drop in a little batter, and watch.' },
        { table: { head: ['Temperature', 'Chopstick test', 'Batter test', 'Used for'], rows: [
          ['150–160°C (low)', 'Small bubbles rise slowly from the tip', 'Sinks to the bottom, rises slowly', 'Sweet potatoes (daigaku-imo), first fry of karaage'],
          ['170–180°C (medium)', 'Steady small bubbles from the whole chopstick', 'Sinks halfway, comes straight back up', 'Agedashi tofu, tempura, most frying'],
          ['190°C and above (high)', 'Lots of large bubbles at once', 'Stays on the surface and sizzles', 'Second fry of karaage (briefly)'],
        ] } },
        { tip: 'Fill the pan with at least 3 cm of oil and fry in small batches: adding too much cold food at once drops the oil by 20–30°C and makes it greasy.' },
        { h: 'When is it done? Inside temperatures' },
        { table: { head: ['Food', 'Centre temperature', 'Other signs'], rows: [
          ['Chicken, minced meat (hamburg steak)', '75°C (167°F) for 1 minute', 'Juices run clear, not pink'],
          ['Pork', '75°C (167°F) for 1 minute', 'Slices are pale all the way through'],
          ['Salmon, mackerel', '60–65°C (140–150°F)', 'Flakes easily, opaque in the middle'],
          ['Enriched bread (milk bread)', '93°C (199°F)', 'Sounds hollow when tapped on the base'],
          ['Pound cake', '96–98°C (205–208°F)', 'A skewer comes out clean'],
          ['Custard pudding', '80–85°C (176–185°F)', 'Set at the edge, a slight wobble in the centre'],
        ] } },
        { h: 'Microwave power' },
        { p: 'Our microwave times are for 600 W. For 500 W multiply the time by 1.2; for 700 W multiply by 0.85.' },
        { table: { head: ['600 W', '500 W', '700 W'], rows: [['30 seconds', '40 seconds', '25 seconds'], ['1 minute', '1 min 10 s', '50 seconds'], ['2 minutes', '2 min 25 s', '1 min 40 s'], ['3 minutes', '3 min 35 s', '2 min 35 s'], ['5 minutes', '6 minutes', '4 min 15 s']] } },
      ],
    },
    ja: {
      title: 'オーブン・揚げ油・加熱の温度', teaser: '摂氏・華氏・ガスマーク、ファン付きオーブンの調整、揚げ油の温度の見分け方、肉の中心温度。',
      body: [
        { p: 'デイリーテーブルのオーブン温度は、ファンのない一般的なオーブン（上下ヒーター）のものです。コンベクション（ファン）機能を使う場合は20℃下げるか、温度はそのままで5〜10分早めに様子を見てください。オーブンは表示と実際の温度が10〜20℃ずれていることがよくあります。オーブン用温度計（1,500円ほど）があると安心です。' },
        { chart: 'oven-scale', caption: '' },
        { h: 'オーブン温度の早見表' },
        { table: { head: ['摂氏', '華氏', 'ガスマーク', '目安', 'ファン付き', 'この温度で焼くもの'], rows: [
          ['140℃', '275°F', '1', 'ごく低温', '120℃', 'ゆずの皮の乾燥、メレンゲ'],
          ['150℃', '300°F', '2', '低温', '130℃', '低温ロースト、チーズケーキ'],
          ['160℃', '325°F', '3', 'やや低温', '140℃', 'かぼちゃプリン（湯せん焼き）、オーブンで煮込むビーフシチュー'],
          ['170℃', '340°F', '3と1/2', '中温', '150℃', 'ゆずのパウンドケーキ（米国のレシピでは325°Fか350°Fに丸めることが多い）'],
          ['180℃', '350°F', '4', '中温', '160℃', 'ミルク食パン、ほとんどのケーキやクッキー'],
          ['190℃', '375°F', '5', 'やや高温', '170℃', 'マフィン、グラタン'],
          ['200℃', '400°F', '6', '高温', '180℃', '鮭のゆず味噌焼き、焼き野菜'],
          ['220℃', '425°F', '7', '高温', '200℃', '鶏とかぼちゃの味噌焼き（天板焼き）'],
          ['230℃', '450°F', '8', 'ごく高温', '210℃', '焼き色をつける'],
          ['250℃', '480°F', '9', 'ごく高温', '230℃', 'ピザ、平焼きパン'],
        ] } },
        { p: '計算式は、華氏＝摂氏×1.8＋32、摂氏＝（華氏−32）÷1.8。オーブントースターは1,000Wで約230℃、1,300Wで約250℃です。' },
        { h: '揚げ油の温度の見分け方' },
        { p: '温度計がなくても大丈夫。乾いた菜箸を油に入れるか、衣を少し落として様子を見ます。' },
        { table: { head: ['温度', '菜箸', '衣', '使う料理'], rows: [
          ['150〜160℃（低温）', '箸先から小さな泡がゆっくり出る', '底まで沈み、ゆっくり浮く', '大学いも、唐揚げの1度目'],
          ['170〜180℃（中温）', '箸全体から細かい泡が出続ける', '途中まで沈んで、すぐ浮く', '揚げ出し豆腐、天ぷら、ほとんどの揚げ物'],
          ['190℃以上（高温）', '大きな泡が勢いよく出る', '沈まず、表面で散る', '唐揚げの2度揚げ（短時間）'],
        ] } },
        { tip: '油は3cm以上の深さに。一度にたくさん入れると油の温度が20〜30℃下がり、べたっと揚がります。少しずつ揚げましょう。' },
        { h: '火が通ったかどうか：中心温度' },
        { table: { head: ['食材', '中心温度', 'そのほかの目安'], rows: [
          ['鶏肉、ひき肉（ハンバーグ）', '75℃で1分以上', '透明な肉汁が出る'],
          ['豚肉', '75℃で1分以上', '中まで白っぽくなっている'],
          ['鮭、サバ', '60〜65℃', '身がほぐれ、中心まで不透明'],
          ['リッチなパン（ミルク食パン）', '93℃', '底をたたくと軽い音がする'],
          ['パウンドケーキ', '96〜98℃', '竹串を刺して何もついてこない'],
          ['プリン', '80〜85℃', '縁が固まり、中心が少しゆれる'],
        ] } },
        { h: '電子レンジのワット数' },
        { p: '当サイトの電子レンジの加熱時間は600Wのものです。500Wなら1.2倍、700Wなら0.85倍にしてください。' },
        { table: { head: ['600W', '500W', '700W'], rows: [['30秒', '40秒', '25秒'], ['1分', '1分10秒', '50秒'], ['2分', '2分25秒', '1分40秒'], ['3分', '3分35秒', '2分35秒'], ['5分', '6分', '4分15秒']] } },
      ],
    },
  },
  'rice-water-ratios': {
    image: 'kinoko-takikomi-gohan', chartThumb: 'rice-water',
    en: {
      title: 'Rice-to-water ratios for every kind of rice', teaser: 'How much water for Japanese rice, new-crop rice, brown rice, mixed rice and porridge, in a pot, a donabe or a rice cooker.',
      body: [
        { p: 'Japanese rice is measured with a rice cup (1 gō, 合), which holds 180 ml, about 150 g of uncooked rice. Two gō make about 660 g of cooked rice: four rice bowls, or six onigiri. In a rice cooker you simply fill to the line for the number of gō; in a pot you need the ratios below.' },
        { chart: 'rice-water', caption: '' },
        { h: 'Water for 1 gō (180 ml) of rice' },
        { table: { head: ['Rice', 'Water per gō', 'Ratio by volume', 'Soak', 'Notes'], rows: [
          ['Japanese white rice', '200 ml', '1.1×', '30 min (summer) to 1 hr (winter)', 'Our everyday ratio'],
          ['New-crop rice (shinmai, Sept–Nov)', '180 ml', '1.0×', '30 min', 'Fresh rice holds more moisture: use about 10% less water'],
          ['Sushi rice', '180 ml', '1.0×', '30 min', 'Slightly firm, because the vinegar is added after'],
          ['Mixed rice (takikomi gohan)', '200 ml including the seasonings', '1.1×', '30 min in plain water', 'Add soy sauce and mirin first, then top up with dashi; see the note below'],
          ['Brown rice', '270 ml', '1.5×', '6 hrs or overnight', 'Pot: 40–45 min on low'],
          ['Rice with mixed grains (zakkoku)', '200 ml + 2 tbsp per tbsp of grains', '1.1× + extra', '1 hr', 'Use 1 tbsp of grain mix per gō'],
          ['Long-grain (jasmine)', '225 ml', '1.25×', 'None', 'Not Japanese; for curries'],
          ['Basmati', '270 ml', '1.5×', '20–30 min', 'Not Japanese; for curries'],
          ['Rice porridge, okayu (zen-gayu)', '900 ml', '5×', '30 min', 'Simmer 40 min on the lowest heat, lid ajar'],
          ['Soft porridge (shichibu-gayu)', '1,260 ml', '7×', '30 min', 'For a poorly stomach'],
        ] } },
        { tip: 'For mixed rice, the seasonings count as water. Put the drained rice in the pot, add the soy sauce, mirin and sake first, then top up with dashi to the normal amount (or to the line on the rice cooker). Do not stir in the vegetables: lay them on top, or the rice underneath cooks unevenly.' },
        { h: 'Cooking rice in a pot' },
        { ol: ['Rinse the rice: cover with water, swirl quickly and pour off at once (the first water is absorbed fastest). Repeat 3–4 times. The water does not need to run clear.', 'Soak in the measured water for 30 minutes (1 hour in winter). The grains turn from translucent to opaque white.', 'Cover and bring to the boil over medium-high heat, about 5–7 minutes.', 'Turn the heat to its lowest and cook 12–13 minutes. Do not lift the lid.', 'Turn the heat to high for 10 seconds to dry the bottom, then switch off.', 'Leave covered for 10 minutes, then fluff with a wet paddle, cutting and turning from the bottom.'] },
        { h: 'Cooking rice in a donabe' },
        { p: 'A donabe (clay pot) holds heat beautifully and makes a little crust (okoge) at the bottom. Use the same water, cook on medium heat until steam puffs from the lid hole (about 10–12 minutes), then on low for 15 minutes, and rest 10 minutes. Never put an empty or wet-bottomed donabe on the flame: it can crack.' },
        { p: 'Recipes on this page\'s ratios: {{recipe:kinoko-takikomi-gohan}}, {{recipe:oyakodon}} and {{recipe:autumn-vegetable-curry}}.', link: true },
      ],
    },
    ja: {
      title: 'お米と水の割合（炊き方別）', teaser: '白米、新米、玄米、炊き込みご飯、おかゆ。鍋・土鍋・炊飯器での水の量。',
      body: [
        { p: 'お米は1合（180ml、生米約150g）で量ります。2合で炊きあがりは約660g、茶碗4杯分、おにぎりなら6個分です。炊飯器なら目盛りまで水を入れるだけですが、鍋で炊くときは下の割合を目安にしてください。' },
        { chart: 'rice-water', caption: '' },
        { h: '米1合（180ml）に対する水の量' },
        { table: { head: ['お米', '1合あたりの水', '体積比', '浸水', 'メモ'], rows: [
          ['白米', '200ml', '1.1倍', '30分（夏）〜1時間（冬）', 'わが家の基本'],
          ['新米（9〜11月）', '180ml', '1.0倍', '30分', '水分が多いので水を1割ほど減らす'],
          ['すし飯', '180ml', '1.0倍', '30分', 'あとで合わせ酢を加えるので固めに'],
          ['炊き込みご飯', '調味料を含めて200ml', '1.1倍', '真水で30分', 'しょうゆ・みりんを先に入れてから、だしで規定量に（下のメモ参照）'],
          ['玄米', '270ml', '1.5倍', '6時間〜一晩', '鍋なら弱火で40〜45分'],
          ['雑穀ごはん', '200ml＋雑穀大さじ1につき大さじ2', '1.1倍＋α', '1時間', '雑穀は1合に大さじ1が目安'],
          ['長粒米（ジャスミン）', '225ml', '1.25倍', 'なし', 'カレーに'],
          ['バスマティ', '270ml', '1.5倍', '20〜30分', 'カレーに'],
          ['全がゆ', '900ml', '5倍', '30分', 'ふたをずらしてごく弱火で40分'],
          ['七分がゆ', '1,260ml', '7倍', '30分', 'おなかの調子が悪いときに'],
        ] } },
        { tip: '炊き込みご飯は、調味料も水分に数えます。浸水した米の水けをきって鍋（内釜）に入れ、先にしょうゆ・みりん・酒を加えてから、だしで規定量（炊飯器なら目盛り）まで足します。具は混ぜずに上にのせること。混ぜると下のお米に炊きむらが出ます。' },
        { h: '鍋での炊き方' },
        { ol: ['米をとぐ：たっぷりの水を注いでさっと混ぜ、すぐに捨てる（最初の水がいちばん吸われるため）。これを3〜4回。水が完全に透明になるまでとがなくてOK。', '分量の水に30分（冬は1時間）浸水。半透明だった米が白く不透明になります。', 'ふたをして中強火にかけ、5〜7分で沸騰させる。', 'ごく弱火にして12〜13分。ふたは開けないこと。', '最後に10秒だけ強火にして底の水分を飛ばし、火を止める。', 'ふたをしたまま10分蒸らし、ぬらしたしゃもじで底から切るように混ぜる。'] },
        { h: '土鍋での炊き方' },
        { p: '土鍋は保温性が高く、底においしいおこげができます。水の量は同じ。中火でふたの穴から蒸気が勢いよく出るまで（10〜12分）、弱火で15分、火を止めて10分蒸らします。空だきや、底がぬれたまま火にかけるのは割れる原因になるので避けてください。' },
        { p: 'この割合を使うレシピ：{{recipe:kinoko-takikomi-gohan}}、{{recipe:oyakodon}}、{{recipe:autumn-vegetable-curry}}', link: true },
      ],
    },
  },
  'seasonal-produce': {
    image: null, chartThumb: 'produce-calendar',
    en: {
      title: 'Seasonal produce calendar for Harvest Prefecture', teaser: 'What is in season month by month, from Mirror valley yuzu to Harvest Bay oysters.',
      body: [
        { p: 'Harvest Prefecture runs from the warm coast of Harvest Bay up to the cool valleys around Mount Moonview, so the season for the same vegetable can differ by a few weeks between the coast and the mountains. This calendar is what I see at the Ferry Port morning market (Saturdays 6–10 am) and the farm stands along the Mirror Line. The darker bar is the peak: cheapest, tastiest and most plentiful.' },
        { chart: 'produce-calendar', caption: '' },
        { h: 'What to buy in October' },
        { ul: ['<strong>Green yuzu</strong>, the last of them: make {{recipe:yuzu-kosho}} before they turn yellow in November.', '<strong>Kabocha</strong>: local kabocha harvested in August is at its sweetest now, after curing. Choose one that feels heavy, with a dry, corky stem.', '<strong>Sweet potatoes</strong> and <strong>chestnuts</strong>: the Lantern Festival stalls sell both roasted.', '<strong>Mushrooms</strong>: log-grown shiitake from the Moonview forests start in October; maitake and shimeji are cheap all autumn.', '<strong>New-crop rice</strong> (shinmai): use about 10% less water. See the {{guide:rice-water-ratios}}.', '<strong>Autumn mackerel</strong> (aki-saba) and <strong>Pacific saury</strong> (sanma) at Ferry Port; yellowtail (buri) gets fattier from November.'] },
        { tip: 'Late-autumn eggplant (aki-nasu) has fewer seeds and a tighter skin than summer eggplant. There is an old saying that it is too good to give your daughter-in-law.' },
      ],
    },
    ja: {
      title: 'みのり県の旬の食材カレンダー', teaser: '鏡川の谷のゆずから、みのり湾のかきまで。月ごとの旬の食材。',
      body: [
        { p: 'みのり県は、温暖なみのり湾の沿岸から、月見山周辺の涼しい山あいまで広がっているので、同じ野菜でも海側と山側で旬が数週間ずれることがあります。このカレンダーは、みのり港朝市（毎週土曜6〜10時）や鏡線沿いの直売所で私が見ているものをまとめたものです。濃い色の部分が最盛期（安くて、おいしくて、たくさん出回る時期）です。' },
        { chart: 'produce-calendar', caption: '' },
        { h: '10月に買いたいもの' },
        { ul: ['<strong>青ゆず</strong>はそろそろ終わり。11月に黄色くなる前に{{recipe:yuzu-kosho}}を作りましょう。', '<strong>かぼちゃ</strong>：8月に収穫した地元産が、追熟して今いちばん甘い時期。ずっしり重く、へたが乾いてコルク状のものを。', '<strong>さつまいも</strong>と<strong>栗</strong>：灯籠まつりの屋台でも焼きいもと焼き栗が並びます。', '<strong>きのこ</strong>：月見の森の原木しいたけが10月から。まいたけ、しめじも秋はずっと手ごろです。', '<strong>新米</strong>：水を1割ほど減らして。{{guide:rice-water-ratios}}を参照。', 'みのり港では<strong>秋さば</strong>と<strong>さんま</strong>。ぶりは11月から脂がのってきます。'] },
        { tip: '秋なすは夏のなすより種が少なく、皮がしまっています。「秋なすは嫁に食わすな」ということわざがあるほどです。' },
      ],
    },
  },
  'pantry-staples': {
    image: null, chartThumb: null,
    en: {
      title: 'Japanese pantry staples, and how to keep them', teaser: 'Soy sauce, mirin, sake, miso, kombu and more: what they are, how long they keep once opened, and what to use instead.',
      body: [
        { p: 'With about a dozen bottles and packets you can cook almost every recipe on this site. Here is what is in my cupboard and fridge, how I store each one, and what to use if you cannot find it. Most of these are sold at any Japanese supermarket; abroad, look in Asian grocers or on Marketa.' },
        { h: 'The essentials' },
        { table: { head: ['Staple', 'What it is', 'After opening', 'Instead, use'], rows: [
          ['Soy sauce (koikuchi)', 'Regular dark soy sauce, about 16% salt', 'Fridge; best within 1 month, safe for much longer', 'Tamari for gluten-free'],
          ['Light soy sauce (usukuchi)', 'Paler in colour but saltier, about 18% salt', 'Fridge, 1 month', 'Regular soy sauce with a pinch of salt'],
          ['Mirin (hon-mirin)', 'Sweet rice wine, about 14% alcohol', 'Cool cupboard, 3 months (it crystallises in the fridge)', 'Per 1 tbsp: 1 tbsp sake + 1 tsp sugar; alcohol-free: 1 tbsp water + 1 tsp sugar'],
          ['Mirin-style seasoning', 'Under 1% alcohol, cheaper, less flavour', 'Fridge, 3 months', 'Hon-mirin'],
          ['Sake', 'Use a dry drinking sake; "cooking sake" contains about 2% salt', 'Cool cupboard, 2–3 months', 'Dry sherry, dry white wine; water for no alcohol'],
          ['Rice vinegar', 'Mild vinegar, about 4.5% acidity', 'Cupboard, 6 months', 'Apple cider vinegar'],
          ['Miso', 'White (sweet, light) or red/awase (saltier, deeper)', 'Fridge, 6–12 months; it never freezes hard, so you can freeze it and spoon straight out', 'Another miso; add sugar to red miso to imitate white'],
          ['Kombu', 'Dried kelp for dashi; the white powder is flavour, not mould', 'Airtight in a dry cupboard, 1 year', 'Kombu dashi granules'],
          ['Katsuobushi', 'Shaved smoked dried bonito', 'Seal tightly, fridge, 1 month', 'Instant dashi granules'],
          ['Dried shiitake', 'For vegetarian dashi and simmered dishes', 'Airtight, cupboard, 1 year', 'Fresh shiitake (less flavour)'],
          ['Potato starch (katakuriko)', 'For crisp coatings and thickening', 'Cupboard, 1 year', 'Cornstarch (slightly less crisp)'],
          ['Panko', 'Japanese breadcrumbs, light and coarse', 'Cupboard, 1 month; freezer, 3 months', 'Dry breadcrumbs (use 20% less)'],
          ['Toasted sesame oil', 'Dark, nutty, for flavour not frying', 'Cool cupboard, 3 months', '–'],
          ['Instant dashi granules', 'Contain salt (about 40%)', 'Cupboard, 6 months', 'Real dashi: see {{guide:dashi}}'],
          ['Sake lees (sake kasu)', 'The pressed lees from sake brewing, about 8% alcohol', 'Fridge 1 month, freezer 1 year', 'White miso + a little sake (not the same)'],
          ['Yuzu kosho', 'Salty paste of yuzu zest and chilli', 'Fridge, 6 months', 'Lime zest + chilli + salt'],
        ] } },
        { tip: 'Instant dashi and cooking sake both contain salt. If you use them instead of real dashi or drinking sake, cut the salt or soy sauce in the recipe by about a quarter, then taste.' },
        { h: 'Flours and starches' },
        { ul: ['<strong>Hakurikiko</strong> (cake flour, about 8% protein): for cakes and tempura.', '<strong>Kyōrikiko</strong> (bread flour, about 12% protein): for bread.', '<strong>Shiratamako</strong>: glutinous rice flour, for soft, chewy dango. Mochiko is similar but finer.', '<strong>Jōshinko</strong>: non-glutinous rice flour, for firmer dango. Mix it half and half with shiratamako for festival-style dango that hold their shape.'] },
        { h: 'How I organise the fridge door' },
        { p: 'Top shelf: miso, yuzu kosho, sake lees. Middle: soy sauce, light soy sauce, mirin-style seasoning. Bottom: dashi in a 1-litre bottle (2–3 days), opened katsuobushi in a clip-top jar. If a bottle has no date, write the opening date on a piece of masking tape.' },
      ],
    },
    ja: {
      title: '和食の常備調味料と保存のしかた', teaser: 'しょうゆ、みりん、酒、みそ、昆布など。開封後の保存期間と、代わりに使えるもの。',
      body: [
        { p: '十数本の調味料と乾物があれば、このサイトのほとんどのレシピが作れます。わが家の棚と冷蔵庫にあるもの、それぞれの保存のしかた、手に入らないときの代わりをまとめました。' },
        { h: '基本の調味料・乾物' },
        { table: { head: ['調味料・乾物', '特徴', '開封後の保存', '代わりに'], rows: [
          ['こいくちしょうゆ', '一般的なしょうゆ。塩分約16%', '冷蔵。風味は1か月以内が目安', 'グルテンフリーならたまりしょうゆ'],
          ['うすくちしょうゆ', '色は薄いが塩分は高め（約18%）', '冷蔵、1か月', 'こいくちしょうゆ＋塩少々'],
          ['本みりん', 'アルコール約14%の甘い酒', '冷暗所で3か月（冷蔵すると糖が結晶化）', '大さじ1につき酒大さじ1＋砂糖小さじ1。アルコールなしなら水大さじ1＋砂糖小さじ1'],
          ['みりん風調味料', 'アルコール1%未満。安価だが風味は控えめ', '冷蔵、3か月', '本みりん'],
          ['酒', '辛口の清酒を。「料理酒」には塩分が約2%含まれる', '冷暗所で2〜3か月', '辛口のシェリー、白ワイン。アルコールなしなら水'],
          ['米酢', 'まろやかな酢。酸度約4.5%', '常温で6か月', 'りんご酢'],
          ['みそ', '白みそ（甘口）、赤みそ・合わせみそ（塩分高め）', '冷蔵で6〜12か月。冷凍しても固まらないので、そのまますくえる', 'ほかのみそ。赤みそに砂糖を足すと白みそ風に'],
          ['昆布', 'だし用の乾燥昆布。表面の白い粉はうまみでカビではない', '密閉して乾燥した場所で1年', '昆布だしの素'],
          ['かつお節', 'かつおの燻製を削ったもの', 'しっかり密閉して冷蔵、1か月', '顆粒だし'],
          ['干ししいたけ', '精進だしや煮物に', '密閉して常温で1年', '生しいたけ（風味は弱め）'],
          ['片栗粉', 'カリッとした衣、とろみづけに', '常温で1年', 'コーンスターチ（やや軽い仕上がり）'],
          ['パン粉', '軽くて粗い日本のパン粉', '常温で1か月、冷凍で3か月', '乾燥パン粉（2割減らす）'],
          ['ごま油（焙煎）', '香りづけ用。揚げ油には使わない', '冷暗所で3か月', '－'],
          ['顆粒だし', '塩分を含む（約40%）', '常温で6か月', '本格的なだし（{{guide:dashi}}参照）'],
          ['酒かす', '日本酒をしぼったあとのかす。アルコール約8%', '冷蔵で1か月、冷凍で1年', '白みそ＋酒少々（風味は別物）'],
          ['ゆずこしょう', 'ゆずの皮と唐辛子、塩のペースト', '冷蔵で6か月', 'ライムの皮＋唐辛子＋塩'],
        ] } },
        { tip: '顆粒だしと料理酒には塩分が含まれています。本物のだしや清酒の代わりに使うときは、レシピの塩やしょうゆを4分の1ほど減らし、味見して調整してください。' },
        { h: '粉類' },
        { ul: ['<strong>薄力粉</strong>（たんぱく質約8%）：ケーキや天ぷらに。', '<strong>強力粉</strong>（たんぱく質約12%）：パンに。', '<strong>白玉粉</strong>：もち米の粉。やわらかく、もちもちのだんごに。', '<strong>上新粉</strong>：うるち米の粉。歯ごたえのあるだんごに。白玉粉と半量ずつ混ぜると、形がくずれにくい屋台風のだんごになります。'] },
        { h: 'わが家の冷蔵庫のドアポケット' },
        { p: '上段にみそ、ゆずこしょう、酒かす。中段にしょうゆ、うすくちしょうゆ、みりん風調味料。下段には1Lボトルのだし（2〜3日）と、開封したかつお節を入れた密閉びん。日付のない容器には、マスキングテープに開封日を書いて貼っています。' },
      ],
    },
  },
  dashi: {
    image: 'dashi', chartThumb: 'dashi-timeline',
    en: {
      title: 'How to make dashi (and the vegetarian kind)', teaser: 'Kombu and katsuobushi dashi in 45 minutes, cold-brew kombu dashi, kombu-shiitake dashi for vegetarians, and the instant shortcut.',
      body: [
        { p: 'Dashi is the stock behind miso soup, nikujaga, oyakodon and most of Japanese home cooking. Making it takes 45 minutes, most of it waiting, and the difference from instant granules is the first thing my children notice. My grandmother Fumi made a 5-litre pot every morning at the inn; I make one litre on Sunday night and it lasts until Wednesday.' },
        { img: 'dashi', caption: 'Kombu and katsuobushi: the two ingredients of awase dashi.' },
        { h: 'Ratios' },
        { table: { head: ['Dashi', 'Water', 'Ingredients', 'Method', 'Use for'], rows: [
          ['Awase dashi (first dashi)', '1 L', '10 g kombu + 20 g katsuobushi', 'Below', 'Clear soups, simmered dishes, everything'],
          ['Second dashi (niban dashi)', '500 ml', 'The used kombu and katsuobushi + 10 g fresh katsuobushi', 'Simmer 5 min, strain', 'Miso soup, nikujaga'],
          ['Cold-brew kombu dashi', '1 L', '10–15 g kombu', 'Fridge 8 hours or overnight', 'Vegan; tofu dishes'],
          ['Kombu-shiitake dashi', '1 L', '10 g kombu + 3 dried shiitake (about 10 g)', 'Fridge overnight; use the shiitake in the dish', 'Vegan; mushroom rice, agedashi tofu, curry'],
          ['Niboshi dashi', '1 L', '20 g dried sardines, heads and guts removed', 'Soak 30 min, simmer 5–10 min', 'Strong miso soup'],
          ['Instant dashi', '300 ml', '1 tsp (about 3 g) granules', 'Dissolve in hot water', 'Weeknights; reduce the salt in the recipe'],
        ] } },
        { h: 'Awase dashi, step by step' },
        { ol: ['Wipe the kombu lightly with a damp cloth. Do not wash it: the white powder is flavour.', 'Soak the kombu in 1 litre of water for 30 minutes (or overnight in the fridge for a deeper flavour).', 'Heat over low-medium heat for about 10 minutes. When tiny bubbles cling to the kombu and the edge of the pot, at about 90°C, take the kombu out. Boiling kombu makes the dashi slimy and bitter.', 'Bring the water to the boil, add the 20 g of katsuobushi all at once and turn off the heat straight away.', 'Leave for 2 minutes, until the flakes sink.', 'Strain through a sieve lined with a paper towel. Do not squeeze the flakes: that makes the dashi cloudy and fishy. You get about 900 ml.'] },
        { chart: 'dashi-timeline', caption: '' },
        { h: 'Storing dashi' },
        { ul: ['Fridge: 2–3 days in a closed bottle (vegetarian kombu-shiitake dashi: 3 days).', 'Freezer: 3 weeks. Freeze in an ice cube tray; one standard cube is about 30 ml, 2 tablespoons.', 'Miso soup for one is 150 ml of dashi and 2 teaspoons (12 g) of miso, added off the boil.'] },
        { tip: 'Do not throw away the used kombu: slice it thinly and simmer with soy sauce, mirin and sesame for a tsukudani to eat with rice, or keep it in the freezer until you have enough.' },
        { p: 'Recipes that start with dashi: {{recipe:nikujaga}}, {{recipe:oyakodon}}, {{recipe:agedashi-tofu}}, {{recipe:tamagoyaki}}, {{recipe:kinoko-takikomi-gohan}}.', link: true },
      ],
    },
    ja: {
      title: 'だしのとり方（精進だしも）', teaser: '45分でとる昆布とかつお節の合わせだし、水出し昆布だし、ベジタリアン向けの昆布しいたけだし、顆粒だしの使い方。',
      body: [
        { p: 'だしは、みそ汁、肉じゃが、親子丼など、和の家庭料理のほとんどの土台です。とるのに45分かかりますが、ほとんどは待つだけ。顆粒だしとの違いに、子どもたちはすぐ気づきます。祖母のふみは旅館で毎朝5Lのだしをとっていました。私は日曜の夜に1Lとって、水曜日まで使います。' },
        { img: 'dashi', caption: '合わせだしの材料は、昆布とかつお節の2つだけ。' },
        { h: 'だしの種類と分量' },
        { table: { head: ['だし', '水', '材料', 'とり方', '向いている料理'], rows: [
          ['合わせだし（一番だし）', '1L', '昆布10g＋かつお節20g', '下記参照', 'お吸い物、煮物、なんでも'],
          ['二番だし', '500ml', '一番だしの昆布とかつお節＋新しいかつお節10g', '5分煮てこす', 'みそ汁、肉じゃが'],
          ['水出し昆布だし', '1L', '昆布10〜15g', '冷蔵庫で8時間〜一晩', 'ヴィーガン、豆腐料理'],
          ['昆布しいたけだし', '1L', '昆布10g＋干ししいたけ3枚（約10g）', '冷蔵庫で一晩。しいたけは具に使う', 'ヴィーガン、炊き込みご飯、揚げ出し豆腐、カレー'],
          ['煮干しだし', '1L', '煮干し20g（頭とわたを取る）', '30分つけてから5〜10分煮る', 'こくのあるみそ汁'],
          ['顆粒だし', '300ml', '顆粒だし小さじ1（約3g）', 'お湯に溶かす', '平日に。レシピの塩分は控えめに'],
        ] } },
        { h: '合わせだしのとり方' },
        { ol: ['昆布はかたくしぼったふきんで軽くふく。洗わないこと（白い粉はうまみです）。', '水1Lに昆布を30分つける（冷蔵庫で一晩おくと、さらに深い味に）。', '弱めの中火で約10分加熱する。昆布や鍋肌に小さな泡がついてきたら（約90℃）昆布を取り出す。昆布を煮立てると、ぬめりと苦みが出ます。', '沸騰したらかつお節20gを一度に入れ、すぐに火を止める。', 'かつお節が沈むまで2分おく。', 'キッチンペーパーを敷いたざるでこす。かつお節はしぼらないこと。濁って生臭くなります。約900mlとれます。'] },
        { chart: 'dashi-timeline', caption: '' },
        { h: 'だしの保存' },
        { ul: ['冷蔵：ふたつきの容器で2〜3日（昆布しいたけだしは3日）。', '冷凍：3週間。製氷皿で凍らせると便利。1個約30ml（大さじ2）です。', 'みそ汁1人分は、だし150mlにみそ小さじ2（12g）。みそは火を止めてから溶き入れます。'] },
        { tip: 'だしがらの昆布は捨てないで。細く切ってしょうゆ、みりん、ごまと煮れば、ごはんのお供の佃煮になります。量がたまるまで冷凍しておいても。' },
        { p: 'だしから始めるレシピ：{{recipe:nikujaga}}、{{recipe:oyakodon}}、{{recipe:agedashi-tofu}}、{{recipe:tamagoyaki}}、{{recipe:kinoko-takikomi-gohan}}', link: true },
      ],
    },
  },
};

// Data for the charts drawn in build.mjs.
export const RICE_CHART = [
  { en: 'White rice', ja: '白米', ml: 200 },
  { en: 'New-crop rice', ja: '新米', ml: 180 },
  { en: 'Sushi rice', ja: 'すし飯', ml: 180 },
  { en: 'Mixed rice', ja: '炊き込みご飯', ml: 200 },
  { en: 'Brown rice', ja: '玄米', ml: 270 },
  { en: 'Jasmine', ja: 'ジャスミン米', ml: 225 },
  { en: 'Basmati', ja: 'バスマティ', ml: 270 },
];

export const CUP_CHART = [
  { en: 'Panko', ja: 'パン粉', g: 50 },
  { en: 'Rolled oats', ja: 'オートミール', g: 90 },
  { en: 'Icing sugar', ja: '粉砂糖', g: 120 },
  { en: 'All-purpose / cake flour', ja: '中力粉・薄力粉', g: 125 },
  { en: 'Bread flour', ja: '強力粉', g: 130 },
  { en: 'Potato starch', ja: '片栗粉', g: 155 },
  { en: 'Japanese white sugar', ja: '上白糖', g: 155 },
  { en: 'Uncooked rice', ja: '米（生）', g: 200 },
  { en: 'Granulated sugar', ja: 'グラニュー糖', g: 200 },
  { en: 'Brown sugar', ja: 'ブラウンシュガー', g: 220 },
  { en: 'Butter', ja: 'バター', g: 227 },
  { en: 'Milk', ja: '牛乳', g: 245 },
  { en: 'Honey', ja: 'はちみつ', g: 340 },
];

// [en, ja, available months, peak months] (1–12). Ranges may wrap the new year.
export const PRODUCE = [
  ['Green yuzu', '青ゆず', [8, 10], [9, 10]],
  ['Yellow yuzu', '黄ゆず', [11, 1], [11, 12]],
  ['Kabocha', 'かぼちゃ', [7, 12], [9, 10]],
  ['Sweet potato', 'さつまいも', [9, 2], [10, 11]],
  ['Chestnuts', '栗', [9, 10], [9, 10]],
  ['Shiitake (log-grown)', '原木しいたけ', [10, 4], [10, 11]],
  ['Maitake, shimeji', 'まいたけ・しめじ', [9, 12], [10, 11]],
  ['Persimmons', '柿', [10, 12], [10, 11]],
  ['Taro (satoimo)', '里いも', [9, 12], [10, 11]],
  ['Eggplant', 'なす', [6, 10], [7, 9]],
  ['Lotus root', 'れんこん', [10, 3], [11, 2]],
  ['Burdock', 'ごぼう', [11, 2], [11, 1]],
  ['Daikon', '大根', [10, 3], [12, 2]],
  ['Napa cabbage', '白菜', [11, 2], [12, 1]],
  ['Green onion (negi)', '長ねぎ', [11, 3], [12, 2]],
  ['Spinach', 'ほうれん草', [11, 3], [12, 2]],
  ['Bamboo shoots', 'たけのこ', [3, 5], [4, 4]],
  ['Strawberries', 'いちご', [12, 5], [2, 4]],
  ['New-crop rice', '新米', [9, 11], [9, 10]],
  ['Pacific saury (sanma)', 'さんま', [9, 11], [10, 10]],
  ['Mackerel (saba)', 'さば', [10, 2], [11, 1]],
  ['Yellowtail (buri)', 'ぶり', [11, 3], [12, 2]],
  ['Harvest Bay oysters', 'みのり湾のかき', [11, 3], [1, 2]],
];
