// Site-wide content for Daily Table: interface strings, categories, collections, ads,
// home, meal plan and about pages. Recipes are in content/recipes/*.json, guides in guides.mjs.

export const UI = {
  en: {
    siteName: 'Daily Table', tagline: 'Home cooking from Harukawa, tested in a real family kitchen',
    langName: '日本語', home: 'Home', recipes: 'Recipes', allRecipes: 'All recipes', collections: 'Collections', guides: 'Guides',
    mealPlan: 'Meal plan', shoppingList: 'Shopping list', about: 'About', search: 'Search', searchPlaceholder: 'Search recipes, ingredients…',
    saved: 'Shopping list', menu: 'Menu',
    promo: 'Lantern Festival is this weekend (10–11 Oct): our festival snack recipes →',
    footerNote: 'Fictional website made for research (UniLens user study).',
    by: 'by', updated: 'Updated', published: 'Published', ratings: 'ratings', comments: 'comments', reviews: 'reviews',
    jump: 'Jump to Recipe', print: 'Print Recipe', pin: 'Save', addList: 'Add to shopping list', added: 'Added to your shopping list',
    disclosure: 'This post may contain affiliate links. As a Marketa associate I earn a small commission from qualifying purchases, at no extra cost to you. Read our <a href="/en/about.html#advertising">disclosure policy</a>.',
    prep: 'Prep Time', cook: 'Cook Time', total: 'Total Time', course: 'Course', cuisine: 'Cuisine', servings: 'Servings', calories: 'Calories',
    difficulty: 'Difficulty', author: 'Author', kcal: 'kcal',
    ingredients: 'Ingredients', metric: 'Metric', us: 'US', equipment: 'Equipment', instructions: 'Instructions', notes: 'Notes',
    subs: 'Substitutions', subFrom: 'Instead of', subTo: 'Use', makeAhead: 'Make ahead', storage: 'Storage', nutrition: 'Nutrition',
    perServing: 'per serving', startTimer: 'Start timer', timerDone: 'Time is up', cookMode: 'Cook Mode', cookModeHelp: 'Keep the screen from going dark',
    scaleNote: 'Quantities in the instructions are for the original recipe.',
    nutriNote: 'Nutrition is estimated per serving from the ingredients as written, with optional ingredients left out.',
    triedIt: 'Tried this recipe?', triedText: 'Leave a rating and a comment below. I read every one!',
    rateThis: 'Rate this recipe', thanksRating: 'Thank you! Your rating has been saved.',
    leaveComment: 'Leave a comment', commentName: 'Name', commentEmail: 'Email (not published)', commentText: 'Comment', commentSubmit: 'Post comment',
    commentThanks: 'Thanks! Your comment is awaiting moderation.', reply: 'Reply', authorBadge: 'Author', outOf: 'out of 5',
    related: 'You might also like', moreIn: 'More', recipeBy: 'Recipe by',
    n: { calories: 'Calories', carbs: 'Carbohydrates', protein: 'Protein', fat: 'Fat', satFat: 'Saturated fat', cholesterol: 'Cholesterol', sodium: 'Sodium', fiber: 'Fiber', sugar: 'Sugar' },
    diets: { vegetarian: 'Vegetarian', vegan: 'Vegan', 'gluten-free': 'Gluten-free', 'dairy-free': 'Dairy-free', pescatarian: 'Pescatarian' },
    cuisines: { japanese: 'Japanese', harukawa: 'Harukawa (local)', western: 'Western', fusion: 'Fusion' },
    difficulties: { easy: 'Easy', medium: 'Medium', hard: 'Hard' },
    courses: { main: 'Main course', side: 'Side dish', soup: 'Soup', rice: 'Rice', noodles: 'Noodles & pasta', dessert: 'Dessert', bread: 'Bread', snack: 'Snack', condiment: 'Condiment' },
    defaultUnit: 'servings', ad: 'Advertisement', adClose: 'Close ad',
    newsletterTitle: 'Get the weekly menu', newsletterText: 'Five dinners, one shopping list, every Friday. Join 38,000 home cooks.',
    newsletterPopTitle: 'Before you go cooking…', newsletterPopText: 'Get my free autumn e-book "12 Yuzu Recipes" when you join the Daily Table newsletter. One email a week, no spam.',
    emailPlaceholder: 'Your email address', subscribe: 'Subscribe', noThanks: 'No thanks', subscribed: 'Thanks! Check your inbox to confirm.',
    cookieText: 'We use cookies to remember your settings, measure traffic and show ads. See our <a href="/en/about.html#privacy">privacy policy</a>.',
    cookieAccept: 'Accept all', cookieSettings: 'Settings',
    authorCardTitle: 'Hi, I\'m Natsuki!', authorCardText: 'Former school-lunch nutritionist, mum of two, and the cook behind Daily Table. I write the recipes my family actually eats in Harukawa.',
    readMore: 'Read more', popular: 'Popular this week', viewAll: 'View all', min: 'min',
    breadcrumbHome: 'Home', searchTitle: 'Search recipes', results: 'results', noResults: 'No recipes match. Try fewer filters or another word.',
    filterTime: 'Total time', filterDiet: 'Diet', filterCuisine: 'Cuisine', filterDifficulty: 'Difficulty', filterType: 'Show', any: 'Any',
    upTo: (m) => `Up to ${m} min`, clear: 'Clear filters', typeRecipe: 'Recipe', typeGuide: 'Guide', typeCollection: 'Collection',
    sortBy: 'Sort by', sortRelevance: 'Best match', sortRating: 'Top rated', sortTime: 'Quickest',
    guidesIntro: 'Kitchen basics I wish someone had handed me: cuts, conversions, temperatures and the things in a Japanese pantry.',
    collectionsIntro: 'Hand-picked sets of recipes for the way you cook this week.',
    allRecipesIntro: 'Every recipe on Daily Table, tested at least three times in my kitchen and once more by Kenta.',
    recipesCount: 'recipes', share: 'Share', tags: 'Tags',
  },
  ja: {
    siteName: 'デイリーテーブル', tagline: '春川の家庭料理。わが家の台所で試作したレシピ',
    langName: 'English', home: 'ホーム', recipes: 'レシピ', allRecipes: 'レシピ一覧', collections: '特集', guides: '基本のガイド',
    mealPlan: '献立表', shoppingList: '買い物リスト', about: 'このサイトについて', search: '検索', searchPlaceholder: 'レシピ・食材で検索',
    saved: '買い物リスト', menu: 'メニュー',
    promo: '今週末は春川灯籠まつり（10月10日・11日）。屋台気分のおやつレシピはこちら →',
    footerNote: '研究用に作成した架空のウェブサイトです（UniLens ユーザー調査）。',
    by: '', updated: '更新', published: '公開', ratings: '件の評価', comments: '件のコメント', reviews: '件のレビュー',
    jump: 'レシピへ移動', print: '印刷する', pin: '保存', addList: '買い物リストに追加', added: '買い物リストに追加しました',
    disclosure: 'この記事にはアフィリエイトリンクが含まれます。マルケタのアソシエイトとして、対象商品の購入により紹介料を受け取ることがあります（お客様の負担はありません）。詳しくは<a href="/ja/about.html#advertising">広告ポリシー</a>をご覧ください。',
    prep: '下ごしらえ', cook: '調理時間', total: '合計時間', course: '種類', cuisine: 'ジャンル', servings: '分量', calories: 'カロリー',
    difficulty: '難易度', author: '作者', kcal: 'kcal',
    ingredients: '材料', metric: 'メートル法', us: 'USカップ・オンス', equipment: '道具', instructions: '作り方', notes: 'メモ',
    subs: '代用できる材料', subFrom: '材料', subTo: '代わりに', makeAhead: '作り置き・前日準備', storage: '保存方法', nutrition: '栄養成分',
    perServing: '1人分', startTimer: 'タイマー開始', timerDone: '時間です', cookMode: '調理モード', cookModeHelp: '画面が暗くならないようにします',
    scaleNote: '作り方の中の分量は、元のレシピの分量です。',
    nutriNote: '栄養成分は記載の材料から計算した1人分の目安です（「お好みで」の材料は含みません）。',
    triedIt: '作ってみましたか？', triedText: 'ぜひ下から評価とコメントを残してください。すべて読んでいます！',
    rateThis: 'このレシピを評価する', thanksRating: 'ありがとうございます！評価を保存しました。',
    leaveComment: 'コメントを書く', commentName: 'お名前', commentEmail: 'メールアドレス（公開されません）', commentText: 'コメント', commentSubmit: 'コメントを送信',
    commentThanks: 'ありがとうございます。コメントは承認後に表示されます。', reply: '返信', authorBadge: '作者', outOf: '（5点満点）',
    related: 'こちらのレシピもおすすめ', moreIn: 'もっと見る', recipeBy: 'レシピ作成',
    n: { calories: 'エネルギー', carbs: '炭水化物', protein: 'たんぱく質', fat: '脂質', satFat: '飽和脂肪酸', cholesterol: 'コレステロール', sodium: 'ナトリウム', fiber: '食物繊維', sugar: '糖質（糖類）' },
    diets: { vegetarian: 'ベジタリアン', vegan: 'ヴィーガン', 'gluten-free': 'グルテンフリー', 'dairy-free': '乳製品不使用', pescatarian: 'ペスカタリアン' },
    cuisines: { japanese: '和食', harukawa: '春川の郷土料理', western: '洋食', fusion: '和洋折衷' },
    difficulties: { easy: 'かんたん', medium: 'ふつう', hard: 'むずかしい' },
    courses: { main: '主菜', side: '副菜', soup: '汁物・スープ', rice: 'ごはんもの', noodles: '麺・パスタ', dessert: 'デザート', bread: 'パン', snack: 'おやつ', condiment: '調味料' },
    defaultUnit: '人分', ad: '広告', adClose: '広告を閉じる',
    newsletterTitle: '今週の献立をメールで', newsletterText: '晩ごはん5日分と買い物リストを毎週金曜日にお届け。3万8千人が登録中です。',
    newsletterPopTitle: '料理を始める前に…', newsletterPopText: 'ニュースレターに登録すると、秋の電子レシピ集「ゆずレシピ12品」を無料でプレゼント。配信は週1回です。',
    emailPlaceholder: 'メールアドレス', subscribe: '登録する', noThanks: '今はしない', subscribed: 'ありがとうございます！確認メールをお送りしました。',
    cookieText: '当サイトでは、設定の保存、アクセス解析、広告表示のためにCookieを使用しています。詳しくは<a href="/ja/about.html#privacy">プライバシーポリシー</a>をご覧ください。',
    cookieAccept: 'すべて許可', cookieSettings: '設定',
    authorCardTitle: 'こんにちは、夏希です！', authorCardText: '元・学校給食の管理栄養士で、二児の母。春川のわが家で実際に食べているごはんを紹介しています。',
    readMore: '続きを読む', popular: '今週の人気レシピ', viewAll: 'すべて見る', min: '分',
    breadcrumbHome: 'ホーム', searchTitle: 'レシピ検索', results: '件', noResults: '該当するレシピがありません。条件を減らすか、別の言葉で検索してください。',
    filterTime: '合計時間', filterDiet: '食事制限', filterCuisine: 'ジャンル', filterDifficulty: '難易度', filterType: '表示', any: '指定なし',
    upTo: (m) => `${m}分以内`, clear: '条件をクリア', typeRecipe: 'レシピ', typeGuide: 'ガイド', typeCollection: '特集',
    sortBy: '並び替え', sortRelevance: '関連度順', sortRating: '評価順', sortTime: '時間が短い順',
    guidesIntro: '料理の基本をまとめました。切り方、計量の換算、温度、和食の常備調味料など、知っていると毎日の料理が楽になります。',
    collectionsIntro: '今週の料理に合わせて選んだレシピ特集です。',
    allRecipesIntro: 'デイリーテーブルの全レシピ。わが家の台所で3回以上試作し、さらに森健太が1回作って確認しています。',
    recipesCount: '品', share: 'シェア', tags: 'タグ',
  },
};

export const CATEGORIES = {
  japanese: { image: 'nikujaga', en: { name: 'Japanese home cooking', text: 'The everyday Japanese dishes we eat at home: simmered dishes, rice, eggs and fish, the way my grandmother Fumi made them in Tsukimi Onsen, adjusted for a busy family kitchen.' }, ja: { name: '和食・家庭料理', text: '煮物、ごはんもの、卵料理、魚料理。月見温泉の祖母ふみの味を、忙しい家庭でも作りやすいように整えた、毎日の和食です。' } },
  harukawa: { image: 'minato-nabe', en: { name: 'Harukawa specialities', text: 'Dishes from our corner of Minori Prefecture: fishermen\'s stews from Minori Port, yuzu from the Kagami valley, and the snacks sold at the Lantern Festival stalls.' }, ja: { name: '春川の郷土料理', text: 'みのり港の漁師鍋、鏡川流域のゆず、灯籠まつりの屋台の味。みのり県・春川ならではの料理を集めました。' } },
  western: { image: 'beef-stew', en: { name: 'Western & yōshoku', text: 'Western dishes as Japanese home cooks make them, yōshoku: hamburg steak, beef stew and creamy soups, rich but never heavy.' }, ja: { name: '洋食', text: 'ハンバーグ、ビーフシチュー、ポタージュ。家庭で作る、ほっとする洋食のレシピです。' } },
  weeknight: { image: 'ginger-pork', en: { name: 'Quick weeknight', text: 'Dinners on the table in about 30 minutes, with one pan and ingredients from an ordinary supermarket.' }, ja: { name: '平日のスピードごはん', text: '30分前後で作れる晩ごはん。フライパンひとつ、近所のスーパーでそろう材料で作れます。' } },
  baking: { image: 'milk-bread', en: { name: 'Baking & desserts', text: 'Soft bread, simple cakes and Japanese sweets, written with grams and cups and tested by Kenta, our former baker.' }, ja: { name: 'お菓子・パン', text: 'ふんわり食パン、素朴なケーキ、和のおやつ。元パン職人の森健太がグラムとカップの両方で試作しています。' } },
  vegetarian: { image: 'autumn-vegetable-curry', en: { name: 'Vegetarian', text: 'Meat-free and fish-free recipes, with kombu and shiitake dashi in place of bonito. Many are vegan as written.' }, ja: { name: 'ベジタリアン', text: '肉も魚も使わないレシピ。かつお節の代わりに昆布と干ししいたけのだしを使います。ヴィーガン対応のものも多数。' } },
};

export const COLLECTIONS = {
  'thirty-minute-dinners': {
    image: 'ginger-pork', pick: (r) => r.total <= 30 && !['condiment', 'dessert', 'snack'].includes(r.course),
    en: { name: '30-minute dinners', teaser: 'Start to finish in half an hour or less.', intro: ['These are the dinners I make on weekdays when Hana has swimming and Sota has homework questions, and dinner has to happen between 6:30 and 7. Every one is on the table in 30 minutes or less, counting the chopping.', 'The trick is the rice: start the rice cooker before anything else (the quick-cook setting takes about 35 minutes for 2 gō), or keep frozen portions of rice and reheat one for 2 minutes at 600 W.'], tips: ['Read the whole recipe before you start and line up the sauce ingredients in one bowl.', 'Use thinly sliced meat: it cooks in 2–3 minutes.', 'A pot of miso soup takes 8 minutes if your dashi is already made. Keep a jar in the fridge for up to 3 days.'] },
    ja: { name: '30分で晩ごはん', teaser: '下ごしらえから完成まで30分以内。', intro: ['花のスイミング、蒼太の宿題…平日は18時半から19時の間に晩ごはんを出さなければならない日がほとんどです。ここに集めたのは、切るところから数えても30分以内で作れる料理です。', 'コツはごはん。まず最初に炊飯器のスイッチを入れること（2合の早炊きで約35分）。冷凍ごはんがあれば600Wで2分温めればOKです。'], tips: ['作り始める前にレシピを最後まで読み、合わせ調味料はひとつのボウルにまとめておきましょう。', '薄切り肉なら2〜3分で火が通ります。', 'だしを作り置きしておけば、みそ汁は8分。冷蔵庫で3日ほど保存できます。'] },
  },
  'cooking-for-two': {
    image: 'oyakodon', pick: (r) => r.servings === 2,
    en: { name: 'Cooking for two', teaser: 'Recipes written for two, with no half-onion left over.', intro: ['When the children are at their grandparents\' in Tsukimi Onsen, Daisuke and I cook for two, and I learned that halving a family recipe rarely works: sauces reduce too fast in a big pan and you end up with half an egg.', 'These recipes are written for two servings from the start. Use the servings scaler on any recipe card if you want to cook for one (the timings stay the same, but use a smaller pan).'], tips: ['A 20 cm frying pan is the right size for two portions of most stir-fries.', 'Freeze leftover sliced meat flat in a freezer bag; it thaws in 15 minutes in cold water.', 'Leftover half onions keep 4–5 days wrapped in the fridge, and go straight into miso soup.'] },
    ja: { name: '2人分のごはん', teaser: '最初から2人分で書いたレシピ。中途半端に余る材料なし。', intro: ['子どもたちが月見温泉の祖父母の家に泊まりに行く日は、夫の大輔と2人分の料理。家族分のレシピを半分にすると、大きな鍋で煮汁が早く煮詰まったり、卵が半端に余ったりと、意外とうまくいきません。', 'ここに集めたのは、最初から2人分で考えたレシピです。1人分にしたいときはレシピカードの分量調整を使ってください（加熱時間はそのまま、小さめの鍋で）。'], tips: ['炒め物の2人分には直径20cmのフライパンがちょうどいい大きさです。', '余った薄切り肉は保存袋に平らに入れて冷凍。冷水につければ15分で解凍できます。', '残った玉ねぎ半分はラップで包んで冷蔵庫で4〜5日。みそ汁の具にどうぞ。'] },
  },
  'lantern-festival-snacks': {
    image: 'chochin-dango', slugs: ['chochin-dango', 'chicken-karaage', 'daigaku-imo', 'tamagoyaki', 'kinoko-takikomi-gohan', 'yuzu-pound-cake'],
    en: { name: 'Lantern Festival snacks', teaser: 'Stall favourites to make at home for the riverside picnic.', intro: ['On the second weekend of October the whole of Harukawa walks down to the Kagami River for the Lantern Festival. This year it is Saturday 10 and Sunday 11 October, and the lanterns are floated at 6:30 pm on the Sunday. The stalls along the riverbank sell glazed dango, karaage in paper cones and candied sweet potatoes, and the queues are long.', 'We take a picnic box and buy one or two things from the stalls. These are the recipes that go in our box: they are good at room temperature and travel well.'], tips: ['Pack fried food only after it has cooled completely, or it steams and goes soft.', 'Dango harden as they cool: make them no more than 4–5 hours before you eat them.', 'Mushroom rice makes excellent onigiri; wet your hands and salt them lightly before shaping.', 'Evenings by the river are cold in October (about 14°C at 8 pm). Bring a flask of hot tea.'] },
    ja: { name: '灯籠まつりのおやつ', teaser: '屋台の人気メニューを家で。川べりのピクニックに。', intro: ['10月の第2週末、春川の人はみんな鏡川へ灯籠まつりに出かけます。今年は10月10日（土）・11日（日）。灯籠流しは日曜日の18時30分からです。川沿いには、みたらしだんご、紙コップの唐揚げ、大学いもの屋台が並び、どこも長い行列です。', 'わが家はお弁当を持って行き、屋台では1〜2品だけ買います。ここに集めたのは、わが家のお弁当箱に入るレシピ。常温でもおいしく、持ち運びにも向いています。'], tips: ['揚げ物は完全に冷ましてから詰めること。温かいうちに詰めると蒸れてべちゃっとします。', 'だんごは冷めると固くなるので、食べる4〜5時間前までに作りましょう。', 'きのこの炊き込みご飯はおにぎりにぴったり。手を水でぬらし、塩を少しつけてにぎります。', '10月の夜の川べりは冷えます（20時で14℃前後）。温かいお茶を水筒にどうぞ。'] },
  },
  'yuzu-season': {
    image: 'yuzu-miso-salmon', slugs: ['yuzu-kosho', 'yuzu-miso-salmon', 'yuzu-pound-cake', 'minato-nabe', 'chochin-dango', 'wafu-mushroom-pasta'],
    en: { name: 'Yuzu season', teaser: 'Green yuzu in early autumn, yellow yuzu from November.', intro: ['Harukawa yuzu grow in the Kagami valley below Mount Tsukimi. In September and October the fruit is still green, sharp and fragrant, perfect for yuzu kosho. From November it turns yellow and juicy, and the farm stands along the Kagami Line sell bags of ten for about ¥500.', 'One yuzu gives about 1 tablespoon of juice and 1 teaspoon of packed zest. If you cannot find yuzu, use a mix of lemon and lime juice (half each) with a little mandarin zest.'], tips: ['Zest before you juice: it is almost impossible the other way round.', 'Freeze whole yuzu in a bag; grate the zest straight from frozen.', 'Use only the coloured part of the peel; the white pith is bitter.'] },
    ja: { name: 'ゆずの季節', teaser: '初秋は青ゆず、11月からは黄ゆず。', intro: ['春川のゆずは、月見山のふもと、鏡川の谷で育ちます。9月から10月は青ゆずの季節。香りが鋭く、ゆずこしょうにぴったりです。11月になると黄色く色づいて果汁もたっぷり。鏡線沿いの直売所では10個入りが500円ほどで並びます。', 'ゆず1個から、果汁は大さじ1ほど、皮のすりおろしは小さじ1ほど取れます。手に入らないときは、レモンとライムの果汁を半量ずつ混ぜ、みかんの皮を少し加えると近い香りになります。'], tips: ['皮をすりおろしてから果汁をしぼること。逆の順番だとほぼ無理です。', 'ゆずは丸ごと保存袋に入れて冷凍。凍ったまま皮をすりおろせます。', '使うのは色のついた表皮だけ。白いわたは苦みが出ます。'] },
  },
  'make-ahead-autumn': {
    image: 'beef-stew', slugs: ['beef-stew', 'nikujaga', 'autumn-vegetable-curry', 'kabocha-soup', 'kabocha-pudding', 'minato-nabe', 'milk-bread'],
    en: { name: 'Make-ahead autumn comfort', teaser: 'Cook on Sunday, eat well until Wednesday.', intro: ['Stews and simmered dishes taste better the next day, when the flavours have settled and the vegetables have soaked up the sauce. On Sunday afternoons I make one big pot and one dessert, and weekday dinners take ten minutes to reheat.', 'Each recipe card says which step you can stop at and how long it keeps. As a rule, cool food quickly (spread it in a shallow container), refrigerate within 2 hours, and reheat until it is steaming hot all the way through.'], tips: ['Potatoes go grainy in the freezer: freeze stews before adding them, or take them out.', 'Label freezer bags with the date; most stews keep 1 month frozen.', 'Thaw overnight in the fridge, not on the counter.'] },
    ja: { name: '作り置きの秋ごはん', teaser: '日曜日に作って、水曜日までおいしく。', intro: ['煮込み料理や煮物は、翌日のほうがおいしいもの。味がなじみ、野菜に煮汁がしみ込みます。わが家では日曜日の午後に大鍋をひとつとデザートをひとつ作り、平日は温め直すだけで10分の晩ごはんにしています。', '各レシピカードに、どの工程まで作っておけるか、何日もつかを書いています。基本は、浅い容器に広げて手早く冷まし、2時間以内に冷蔵庫へ。温め直すときは中まで熱々にしてください。'], tips: ['じゃがいもは冷凍するとボソボソになります。冷凍するなら入れる前か、取り除いてから。', '冷凍用保存袋には日付を書きましょう。煮込みの多くは冷凍で1か月もちます。', '解凍は常温ではなく、前の晩から冷蔵庫で。'] },
  },
};

// Ads between paragraphs and in the sidebar. Fictional advertisers from the shared world.
export const ADS = [
  { kind: 'pottery', en: { title: 'Harukawa Ware Autumn Kiln Market', text: '120 potters · 17–18 Oct · Harukawa Castle grounds', cta: 'Plan your visit' }, ja: { title: '春川焼 秋の窯元市', text: '窯元120軒・10月17日〜18日・春川城跡広場', cta: '詳しく見る' } },
  { kind: 'market', en: { title: 'Marketa Kitchen Week', text: 'Up to 30% off knives, pans and donabe. Free delivery over ¥3,000.', cta: 'Shop now' }, ja: { title: 'マルケタ キッチンウィーク', text: '包丁・フライパン・土鍋が最大30%OFF。3,000円以上で送料無料', cta: '今すぐチェック' } },
  { kind: 'onsen', en: { title: 'Autumn leaves at Tsukimi Onsen', text: 'Ride the limited express Tsukikage. Stay & dine plans from ¥14,800.', cta: 'See plans' }, ja: { title: '紅葉の月見温泉へ', text: '特急「月影」で行く、1泊2食付きプラン 14,800円から', cta: 'プランを見る' } },
  { kind: 'mobile', en: { title: 'Kumo Mobile Family Plan', text: 'Add a line for ¥990/month. Recipes load fast in your kitchen.', cta: 'Learn more' }, ja: { title: 'クモモバイル 家族割', text: '2回線目から月額990円。キッチンでもレシピがサクサク。', cta: '詳しくはこちら' } },
];

export const HOME = {
  en: {
    slides: [
      { image: 'chochin-dango', kicker: 'Lantern Festival · 10–11 Oct', title: 'Make the festival snacks at home', text: 'Glazed lantern dango, karaage and candied sweet potatoes for the riverside picnic.', href: '/en/collections/lantern-festival-snacks.html', cta: 'See the collection' },
      { image: 'yuzu-kosho', kicker: 'In season now', title: 'Green yuzu: make yuzu kosho this week', text: 'Ten minutes of zesting, one week in the fridge, and a jar that lasts until spring.', href: '/en/recipes/yuzu-kosho.html', cta: 'Get the recipe' },
      { image: 'milk-bread', kicker: 'Weekend baking', title: 'The softest milk bread', text: 'The tangzhong method, step by step, with photos of the dough before and after rising.', href: '/en/recipes/milk-bread.html', cta: 'Start baking' },
    ],
    seasonalTitle: 'Fresh this autumn', seasonalText: 'Kabocha, mushrooms, sweet potatoes and the first yuzu of the year.',
    categoriesTitle: 'Browse by category', collectionsTitle: 'Collections', guidesTitle: 'Cooking guides',
    aboutTitle: 'From my kitchen in Harukawa',
    aboutText: 'I\'m Natsuki. For nine years I planned school lunches for 600 children in Harukawa; now I write the recipes my own family eats. Every recipe here is tested at least three times, written in grams and cups, and checked by Kenta, our former baker.',
    planTitle: 'This week\'s meal plan', planText: 'Seven dinners for the week of 5 October, with one shopping list and a prep-ahead plan.',
  },
  ja: {
    slides: [
      { image: 'chochin-dango', kicker: '灯籠まつり・10月10日〜11日', title: '屋台の味をおうちで', text: '提灯だんご、唐揚げ、大学いも。川べりのピクニックにどうぞ。', href: '/ja/collections/lantern-festival-snacks.html', cta: '特集を見る' },
      { image: 'yuzu-kosho', kicker: '今が旬', title: '青ゆずで、ゆずこしょうを', text: '皮をすりおろして10分、冷蔵庫で1週間。春まで楽しめる一瓶に。', href: '/ja/recipes/yuzu-kosho.html', cta: 'レシピを見る' },
      { image: 'milk-bread', kicker: '週末のパン作り', title: 'ふわふわ湯種食パン', text: '湯種製法を写真つきで。一次発酵の前後の生地も紹介しています。', href: '/ja/recipes/milk-bread.html', cta: '作ってみる' },
    ],
    seasonalTitle: '秋のおすすめ', seasonalText: 'かぼちゃ、きのこ、さつまいも、そして今年最初のゆず。',
    categoriesTitle: 'カテゴリーから探す', collectionsTitle: '特集', guidesTitle: '料理の基本ガイド',
    aboutTitle: '春川の台所から',
    aboutText: '夏希です。春川の小学校で9年間、600人分の給食の献立を立てていました。今は、わが家で実際に食べている料理のレシピを書いています。どのレシピも3回以上試作し、グラムとカップの両方で表記、元パン職人の森健太が確認しています。',
    planTitle: '今週の献立', planText: '10月5日からの1週間、7日分の晩ごはんと買い物リスト、作り置きの段取りつき。',
  },
};

// Week of Monday 5 October 2026. Prices are estimates for the whole family of four.
export const MEAL_PLAN = {
  week: { en: 'Week of 5 October 2026', ja: '2026年10月5日（月）からの1週間' },
  days: [
    { day: { en: 'Mon 5 Oct', ja: '10/5（月）' }, recipe: 'oyakodon', side: { en: 'Miso soup with tofu and wakame', ja: '豆腐とわかめのみそ汁' }, lunch: { en: 'Leftover rice onigiri', ja: '残りごはんのおにぎり' }, prep: { en: 'Sunday night: soak kombu for a litre of dashi.', ja: '前日の夜：だし1L分の昆布を水につけておく' }, active: 25, cost: 1180 },
    { day: { en: 'Tue 6 Oct', ja: '10/6（火）' }, recipe: 'ginger-pork', side: { en: 'Shredded cabbage, kabocha soup from the freezer', ja: 'せん切りキャベツ、冷凍しておいたかぼちゃのポタージュ' }, lunch: { en: 'Ginger pork rice bowl', ja: '生姜焼き丼' }, prep: { en: 'Thaw the kabocha soup in the fridge in the morning.', ja: '朝、ポタージュを冷蔵庫に移して解凍' }, active: 20, cost: 1350 },
    { day: { en: 'Wed 7 Oct', ja: '10/7（水）' }, recipe: 'sheet-pan-miso-chicken', side: { en: 'Spinach with sesame dressing', ja: 'ほうれん草のごま和え' }, lunch: { en: 'Miso chicken and kabocha (cook 2 extra thighs)', ja: '鶏とかぼちゃの味噌焼き（2枚多めに焼く）' }, prep: { en: 'Make the kabocha pudding after dinner; it needs 4 hours in the fridge.', ja: '夕食後にかぼちゃプリンを作る（冷蔵庫で4時間）' }, active: 25, cost: 1620 },
    { day: { en: 'Thu 8 Oct', ja: '10/8（木）' }, recipe: 'wafu-mushroom-pasta', side: { en: 'Green salad; kabocha pudding for dessert', ja: 'グリーンサラダ、デザートにかぼちゃプリン' }, lunch: { en: 'Miso chicken leftovers', ja: '味噌焼きの残り' }, prep: { en: 'Buy double mushrooms: half go into Friday\'s rice.', ja: 'きのこは2倍買う（半分は金曜日の炊き込みご飯に）' }, active: 20, cost: 980 },
    { day: { en: 'Fri 9 Oct', ja: '10/9（金）' }, recipe: 'saba-misoni', side: { en: 'Autumn mushroom rice, miso soup', ja: 'きのこの炊き込みご飯、みそ汁' }, lunch: { en: 'Mushroom rice onigiri', ja: 'きのこご飯のおにぎり' }, prep: { en: 'Soak the rice for 30 minutes before cooking; make 4 extra onigiri for Saturday.', ja: '米は30分浸水。土曜日用におにぎりを4個多めに' }, active: 35, cost: 1460 },
    { day: { en: 'Sat 10 Oct', ja: '10/10（土）' }, recipe: 'chochin-dango', side: { en: 'Chicken karaage and tamagoyaki for the festival picnic', ja: 'まつり弁当に唐揚げと卵焼き' }, lunch: { en: 'Minori Port morning market (6–10 am): buy yellowtail for Sunday', ja: 'みのり港朝市（6〜10時）で日曜日用のぶりを買う' }, prep: { en: 'Marinate the karaage at noon; make the dango no earlier than 1 pm.', ja: '唐揚げは正午に下味。だんごは13時以降に作る' }, active: 70, cost: 2150 },
    { day: { en: 'Sun 11 Oct', ja: '10/11（日）' }, recipe: 'minato-nabe', side: { en: 'Udon to finish the pot, yuzu kosho', ja: 'しめのうどん、ゆずこしょう' }, lunch: { en: 'Lantern floating at 6:30 pm: eat early, at 5 pm', ja: '灯籠流しは18時30分。夕食は早めの17時に' }, prep: { en: 'Make the broth in the morning; add the fish just before eating.', ja: '朝のうちに煮汁を作り、魚は食べる直前に入れる' }, active: 45, cost: 2480 },
  ],
  en: { title: 'Weekly meal plan', intro: 'Seven family dinners for the week of the Lantern Festival, planned so that one cooking session feeds the next: extra chicken on Wednesday becomes Thursday\'s lunchboxes, double mushrooms on Thursday go into Friday\'s rice, and Saturday\'s market trip buys Sunday\'s fish. Prices are what I paid at the Harukawa Central supermarket for a family of four (two adults, two children).', cols: ['Day', 'Dinner', 'Side & extras', 'Lunchbox / plans', 'Prep ahead', 'Active time', 'Est. cost'], totals: 'Week total', addAll: 'Add the whole week to my shopping list', addedAll: 'Added 7 recipes to your shopping list', notes: ['Costs do not include rice (we use about 3 kg a week, ¥2,400) or pantry seasonings.', 'Swap any day for a recipe from the 30-minute dinners collection if your evening is short.', 'Vegetarian week: swap Monday for agedashi tofu, Tuesday for autumn vegetable curry and Sunday for kabocha soup.'] },
  ja: { title: '1週間の献立表', intro: '灯籠まつりの週の、家族の晩ごはん7日分。ひとつの料理が次の日につながるように組んでいます。水曜日に多めに焼いた鶏は木曜日のお弁当に、木曜日に2倍買ったきのこは金曜日の炊き込みご飯に、土曜日の朝市で日曜日の魚を買います。金額は春川中央駅前のスーパーで買った、4人家族（大人2人・子ども2人）の目安です。', cols: ['日付', '主菜', '副菜・その他', 'お弁当・予定', '前日までの準備', '調理時間', '材料費の目安'], totals: '1週間の合計', addAll: '1週間分を買い物リストに追加', addedAll: '7品を買い物リストに追加しました', notes: ['金額にお米（わが家は週に約3kg、2,400円）と常備調味料は含みません。', '帰りが遅い日は「30分で晩ごはん」特集のレシピと入れ替えてください。', 'ベジタリアン週にするなら、月曜日を揚げ出し豆腐、火曜日を秋野菜のカレー、日曜日をかぼちゃのポタージュに。'] },
};

export const ABOUT = {
  en: {
    title: 'About Daily Table',
    body: [
      'Daily Table is a home-cooking website written in Harukawa, Minori Prefecture. I\'m Natsuki Aoyama. I grew up in Tsukimi Onsen, where my grandmother Fumi ran a small inn with eight rooms and cooked breakfast and dinner for every guest. I spent my childhood in her kitchen, peeling chestnuts and watching the dashi.',
      'I trained as a registered dietitian at Harukawa University and spent nine years as the school-lunch nutritionist at Kawabata Elementary School, planning meals for 600 children on ¥290 a day. That job taught me three things that shape every recipe here: measure properly, plan the week, and never waste the second half of an onion.',
      'I started Daily Table in 2017 as a notebook for parents who asked for the school curry recipe. Today about 1.2 million people visit each month. I live in Harukawa with my husband Daisuke and our children Hana (12) and Sota (9), who are the first and harshest testers.',
    ],
    teamTitle: 'The team',
    team: [
      ['Natsuki Aoyama', 'Founder, recipe developer and writer. Registered dietitian.'],
      ['Kenta Mori', 'Recipe tester. Ran Mori Bakery near Harukawa Central for 14 years; answers most baking questions.'],
      ['Yui Tanabe', 'Photographer. Shoots every dish in natural light in our kitchen, usually before it goes cold.'],
      ['Ryo Ishida', 'English editor. Converts every recipe to US cups and ounces and checks them in a US-measure kitchen.'],
    ],
    testingTitle: 'How we test recipes',
    testing: ['Every recipe is cooked at least three times in my kitchen (gas hob, a combination oven-microwave without a fan, a 600 W microwave) and once more by Kenta from the written recipe only.', 'Weights are given in grams. US cups are converted with our own measurements: 1 cup of all-purpose flour is 125 g, spooned and levelled. See the measurement conversions guide.', '1 tablespoon is 15 ml and 1 teaspoon 5 ml. A Japanese measuring cup is 200 ml and a rice cup 180 ml; our recipes never use the Japanese cup for anything but rice.', 'Nutrition is calculated from the Standard Tables of Food Composition in Japan and is an estimate.'],
    faqTitle: 'Frequently asked questions',
    faq: [
      ['Can I use your recipes on my blog?', 'Please link to the recipe instead of copying it. You may use one photo with a clear link back.'],
      ['Why is there a long story before every recipe?', 'Because the tips are in there! But if you are in a hurry, every post has a "Jump to Recipe" button at the top.'],
      ['Do you have an app?', 'Not yet. The shopping list on this site works on your phone and remembers your recipes in your browser.'],
      ['Can I request a recipe?', 'Yes, write to us (below). We read every message, and many recipes, including the karaage, started as reader requests.'],
    ],
    adTitle: 'Advertising and disclosure', ad: 'Daily Table is free to read and is paid for by advertising and affiliate links. Ads are served by our advertising partner and are marked "Advertisement". When I link to a product on Marketa and you buy it, we may earn a small commission. We never accept payment for a recipe or a review.',
    privacyTitle: 'Privacy', privacy: 'We use cookies to remember your settings (such as Metric or US units), to count visits, and to show ads. Your shopping list and ratings are stored in your browser only. Newsletter addresses are used only to send the newsletter, and you can unsubscribe with one click.',
    contactTitle: 'Contact', contact: 'Email: hello@dailytable.example · Daily Table, 3-12-7 Kawabata, Harukawa, Minori Prefecture 870-0412. We usually reply within three working days. For press and partnerships, mark your subject "Partnership".',
  },
  ja: {
    title: 'デイリーテーブルについて',
    body: [
      'デイリーテーブルは、みのり県春川市で書いている家庭料理のサイトです。青山夏希と申します。月見温泉で育ち、祖母のふみは客室8部屋の小さな旅館を営み、お客さんの朝食と夕食をすべて自分で作っていました。私は子どものころ、祖母の台所で栗の皮をむき、だしの番をして過ごしました。',
      '春川大学で管理栄養士の資格を取り、川端小学校で9年間、給食の献立を担当しました。1日290円で600人分の給食を考える仕事から学んだのは、きちんと量ること、1週間単位で考えること、そして玉ねぎの残り半分を無駄にしないこと。この3つは、今もすべてのレシピの土台になっています。',
      '2017年、学校のカレーのレシピを知りたいという保護者の声に応えるノートとして始めたのがこのサイトです。今では毎月約120万人の方に見ていただいています。春川で夫の大輔、娘の花（12歳）、息子の蒼太（9歳）と暮らしています。家族はいちばん最初の、そしていちばん厳しい試食係です。',
    ],
    teamTitle: 'スタッフ',
    team: [
      ['青山 夏希', '代表・レシピ開発・執筆。管理栄養士。'],
      ['森 健太', 'レシピテスター。春川中央駅近くで「森ベーカリー」を14年営んでいました。お菓子・パンの質問にはだいたい彼が答えます。'],
      ['田辺 結衣', 'カメラマン。わが家の台所で、自然光で、冷める前に撮影しています。'],
      ['石田 亮', '英語版編集。すべてのレシピをUSカップ・オンスに換算し、アメリカ式の計量で確認しています。'],
    ],
    testingTitle: 'レシピの試作について',
    testing: ['どのレシピも、わが家の台所（ガスコンロ、ファン機能のないオーブンレンジ、600Wの電子レンジ）で3回以上作り、さらに森がレシピの文章だけを見て1回作っています。', '重さはグラムで表記しています。USカップへの換算は独自に計量した値を使っています（薄力粉1カップ＝125g、スプーンで入れてすり切り）。計量の換算ガイドもご覧ください。', '大さじ1は15ml、小さじ1は5mlです。日本の計量カップは200ml、炊飯用の1合は180ml。当サイトのレシピでは、お米以外に「カップ」は使いません。', '栄養成分は日本食品標準成分表をもとに計算した目安です。'],
    faqTitle: 'よくある質問',
    faq: [
      ['レシピをブログで紹介してもいいですか？', 'レシピの転載ではなく、リンクでのご紹介をお願いします。写真は1枚まで、リンクを明記のうえご利用いただけます。'],
      ['どうしてレシピの前に長い文章があるのですか？', 'コツがそこに書いてあるからです！お急ぎの方は、記事の上にある「レシピへ移動」ボタンをどうぞ。'],
      ['アプリはありますか？', 'まだありません。このサイトの買い物リストはスマートフォンでも使え、選んだレシピはブラウザに保存されます。'],
      ['レシピのリクエストはできますか？', 'はい、下記までご連絡ください。すべて読んでいます。唐揚げのレシピも読者の方のリクエストから生まれました。'],
    ],
    adTitle: '広告とアフィリエイトについて', ad: 'デイリーテーブルは無料でご覧いただけます。運営費は広告とアフィリエイトリンクでまかなっています。広告は広告パートナーが配信し、「広告」と表示しています。マルケタの商品へのリンクからご購入いただくと、紹介料を受け取ることがあります。レシピやレビューに対して報酬を受け取ることはありません。',
    privacyTitle: 'プライバシーポリシー', privacy: '当サイトでは、設定（メートル法・USカップなど）の保存、アクセス数の計測、広告の表示のためにCookieを使用しています。買い物リストと評価はお使いのブラウザにのみ保存されます。ニュースレターのメールアドレスは配信にのみ使用し、ワンクリックで解除できます。',
    contactTitle: 'お問い合わせ', contact: 'メール：hello@dailytable.example ・ 〒870-0412 みのり県春川市川端3-12-7 デイリーテーブル。通常3営業日以内にお返事します。取材・タイアップのご相談は件名に「タイアップ」とお書きください。',
  },
};
