// Headphones and earbuds (Electronics). Same shape as kettles.mjs.
export const cluster = {
  id: 'audio',
  compareRows: {
    en: ['Type', 'Noise cancelling', 'Battery', 'Water resistance', 'Weight', 'Warranty'],
    ja: ['タイプ', 'ノイズキャンセリング', 'バッテリー（連続再生）', '防水性能', '重量', '保証'],
  },
};

export default [
  {
    id: 'nami-buds',
    cat: 'electronics',
    cluster: 'audio',
    brand: { en: 'Nami', ja: 'ナミ' },
    seller: 'marketa',
    images: ['nami-buds'],
    title: {
      en: 'Nami Buds 2 Wireless Noise-Cancelling Earbuds, Bluetooth 5.3, Multipoint (2 Devices), 30 h Battery with Case, IPX4, Wireless Charging Case, USB-C, for iPhone and Android',
      ja: 'ナミ Buds 2 完全ワイヤレスイヤホン ノイズキャンセリング Bluetooth 5.3 マルチポイント対応 最大30時間再生 IPX4防水 ワイヤレス充電対応 USB-C iPhone/Android対応 NB-2',
    },
    short: { en: 'Nami Buds 2 Earbuds', ja: 'ナミ Buds 2 イヤホン' },
    rating: 4.3,
    ratings: 4512,
    hist: [62, 21, 6, 4, 7],
    added: '2025-03-14',
    badges: ['bestseller', 'deal'],
    coupon: { amount: 1000, member: true, en: 'Fast members: save ¥1,000 with coupon', ja: 'Fast会員限定 1,000円OFFクーポン' },
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'white', name: { en: 'White', ja: 'ホワイト' }, price: 12800, list: 16500, stock: 35, ship: 'fast' },
      { id: 'black', name: { en: 'Black', ja: 'ブラック' }, price: 12800, list: 16500, stock: 22, ship: 'fast' },
      { id: 'sand', name: { en: 'Sand', ja: 'サンド' }, price: 12800, list: 16500, stock: 5, ship: 'fast2' },
    ],
    returns: {
      en: 'In-ear earbuds: once the hygiene seal on the ear-tip tray is broken, they can be returned only if defective, damaged or the wrong item (free return, refund or replacement within 30 days). Unopened with the seal intact, they can be returned within 30 days of delivery for a full refund.',
      ja: 'カナル型イヤホンのため、イヤーピース部分の衛生シールを開封した後は、初期不良・配送中の破損・誤配送の場合を除き返品できません（該当する場合は30日以内なら送料無料で返金または交換）。衛生シール未開封なら、お届けから30日以内は全額返金します。',
    },
    bullets: {
      en: [
        'QUIET WHEN YOU NEED IT: hybrid active noise cancelling with three levels plus an ambient mode, so you can hear the announcements on a Vale Rail platform without taking a bud out.',
        'BATTERY: 8 h per charge (6.5 h with noise cancelling on). The case adds about three full charges: 30 h in total, about 24 h with noise cancelling. 10 minutes in the case gives about 1.5 h.',
        'TWO DEVICES AT ONCE: multipoint keeps a phone and a laptop connected together; a call on your phone interrupts music from the laptop automatically. Works with iPhone, Android, Windows and Mac (Bluetooth 5.3, SBC and AAC; no LDAC or aptX).',
        'CHARGE ANY WAY: USB-C cable or any Qi wireless charging pad. A USB-C cable is included; no wall charger in the box.',
        'FIT: four sizes of silicone ear tips (XS, S, M, L; M fitted). Each bud weighs 5.2 g. Sweat and splash resistant to IPX4: fine for the gym and rain, not for swimming or the shower.',
        'NAMI APP (iOS and Android): equaliser, noise-cancelling level, touch controls, an ear-tip fit test and firmware updates. No account needed.',
        'HYGIENE SEAL: as with all in-ear earbuds, change-of-mind returns are not accepted once the seal on the ear-tip tray is broken. 1-year Nami warranty.',
      ],
      ja: [
        '【必要なときに静かに】3段階のハイブリッドノイズキャンセリングと外音取り込みモードを搭載。イヤホンを外さなくても春川鉄道のホームのアナウンスが聞こえます。',
        '【最大30時間再生】イヤホン単体で8時間（ノイキャンON時6.5時間）。ケースで約3回分充電でき、合計30時間（ノイキャンON時約24時間）。ケースで10分充電すれば約1.5時間使えます。',
        '【2台同時接続のマルチポイント】スマホとノートPCに同時に接続。PCで音楽を聴いていてもスマホに着信があれば自動で切り替わります。iPhone・Android・Windows・Macに対応（Bluetooth 5.3、SBC/AAC対応。LDAC・aptXには非対応）。',
        '【2通りの充電方法】USB-Cケーブルのほか、Qi規格のワイヤレス充電器にも対応。USB-Cケーブル付属、ACアダプターは別売りです。',
        '【フィット感】シリコンイヤーピースはXS・S・M・Lの4サイズ（M装着済み）。片耳5.2g。IPX4の防滴性能で汗や雨は大丈夫ですが、水泳やシャワーでは使えません。',
        '【ナミ専用アプリ（iOS/Android）】イコライザー、ノイキャンの強さ、タッチ操作の割り当て、イヤーピースのフィットテスト、ファームウェア更新。アカウント登録は不要です。',
        '【衛生シールについて】カナル型イヤホンのため、イヤーピースの衛生シールを開封した後はお客様都合による返品はできません。メーカー保証1年。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Nami'], ['Model', 'NB-2'], ['Type', 'True wireless in-ear earbuds'], ['Noise cancelling', 'Hybrid ANC, 3 levels, plus ambient mode'],
        ['Battery', '8 h (6.5 h with ANC); 30 h with case (about 24 h with ANC)'],
        ['Charging', 'USB-C (case full in about 2 h) or Qi wireless (about 3.5 h); 10 min gives about 1.5 h'],
        ['Bluetooth', '5.3, range about 10 m'], ['Codecs', 'SBC, AAC (no LDAC or aptX)'], ['Multipoint', 'Yes, 2 devices at once (up to 8 remembered)'],
        ['Water resistance', 'IPX4 (earbuds only; the case is not water resistant)'], ['Microphones', '3 per earbud, with wind-noise reduction'],
        ['Controls', 'Touch (customisable in the Nami app)'], ['Weight', '5.2 g per earbud; case 46 g'], ['Case dimensions', '6.2 × 4.8 × 2.6 cm'],
        ['Country of origin', 'China'], ['Warranty', '1 year (manufacturer)'],
        ['In the box', 'Earbuds, charging case, silicone ear tips XS/S/M/L (M fitted), USB-C to USB-C cable (30 cm), quick guide'],
      ],
      ja: [
        ['ブランド', 'ナミ'], ['型番', 'NB-2'], ['タイプ', '完全ワイヤレス（カナル型）'], ['ノイズキャンセリング', 'ハイブリッドANC（3段階）、外音取り込みモード'],
        ['連続再生時間', '8時間（ANC ON時6.5時間）／ケース併用30時間（ANC ON時約24時間）'],
        ['充電', 'USB-C（ケース満充電約2時間）、Qiワイヤレス充電（約3.5時間）／10分充電で約1.5時間再生'],
        ['Bluetooth', '5.3（通信距離約10m）'], ['対応コーデック', 'SBC、AAC（LDAC・aptX非対応）'], ['マルチポイント', '対応（2台同時接続、最大8台まで登録）'],
        ['防水性能', 'IPX4（イヤホン本体のみ。ケースは防水ではありません）'], ['マイク', '片耳3基、風切り音低減機能付き'],
        ['操作', 'タッチ操作（アプリで変更可能）'], ['重量', '片耳約5.2g／ケース約46g'], ['ケースサイズ', '幅6.2×高さ4.8×厚さ2.6cm'],
        ['原産国', '中国'], ['保証', 'メーカー保証1年'],
        ['付属品', 'イヤホン本体、充電ケース、シリコンイヤーピースXS/S/M/L（M装着済み）、USB-C to USB-Cケーブル（30cm）、クイックガイド'],
      ],
    },
    compare: {
      en: ['In-ear (true wireless)', 'Yes (3 levels)', '8 h (6.5 h with ANC); 30 h with case', 'IPX4 (sweat, splashes)', '5.2 g per bud; case 46 g', '1 year'],
      ja: ['カナル型（完全ワイヤレス）', 'あり（3段階）', '8時間（ANC ON時6.5時間）／ケース併用30時間', 'IPX4（汗・水しぶき）', '片耳5.2g／ケース46g', '1年'],
    },
    description: {
      en: [
        'Nami Buds 2 are everyday noise-cancelling earbuds for commuting, working and calls. Noise cancelling has three levels: High for trains and planes, Medium for offices and cafés, and Low for windy streets, where strong cancelling can cause a whooshing sound. Ambient mode lets outside sound in so you can hear announcements or talk at a till without taking a bud out.',
        'They work with any Bluetooth phone, tablet or computer. iPhones use AAC; most Android phones use AAC or SBC. There is no LDAC or aptX, so Android users who want high-resolution Bluetooth audio should look at over-ear headphones such as the Seiran Studio NC. Multipoint is on by default: the buds stay connected to two devices, for example your phone and a laptop, and switch to whichever one plays sound or rings. In very crowded places such as station platforms at rush hour, turning multipoint off in the app can make the connection steadier.',
        'The buds come with the medium tips fitted. Most people get a better seal, and much better noise cancelling, with the right size, so try the fit test in the app. Very small ears may still find them loose when running. Each bud has three microphones; calls are clear indoors and on quiet streets, but in strong wind or on a bicycle callers will hear you less well.',
        'Care: wipe the ear tips and the gold charging contacts with a dry cloth once a week; earwax on the contacts is the most common reason one bud stops charging. Nami covers the earbuds and case for one year from purchase. A single lost earbud can be replaced through Nami support for ¥4,400 (case ¥5,500).',
      ],
      ja: [
        'ナミ Buds 2は、通勤・仕事・通話に毎日使えるノイズキャンセリングイヤホンです。ノイキャンは3段階。電車や飛行機には「強」、オフィスやカフェには「中」、強いノイキャンだと「ゴー」という音が気になりやすい風の強い屋外では「弱」がおすすめです。外音取り込みモードにすれば、イヤホンをつけたままアナウンスを聞いたり、レジで会話したりできます。',
        'Bluetooth対応のスマホ・タブレット・パソコンならどれでも使えます。iPhoneはAAC、Androidの多くはAACまたはSBCで接続します。LDACやaptXには対応していないため、Androidでハイレゾ相当のワイヤレス再生をしたい方は「セイラン Studio NC」などのヘッドホンをご検討ください。マルチポイントは初期設定でオン。スマホとノートPCなど2台に同時接続し、音が鳴ったほう・着信があったほうに自動で切り替わります。ラッシュ時の駅のホームなど非常に混雑した場所では、アプリでマルチポイントをオフにすると接続が安定しやすくなります。',
        '出荷時はMサイズのイヤーピースが装着されています。サイズが合うと密閉性が上がり、ノイキャンの効きも大きく変わるので、アプリのフィットテストをお試しください。耳がとても小さい方は、走ると緩むことがあります。マイクは片耳3基。室内や静かな道では通話もクリアですが、強風の中や自転車での通話では相手に声が届きにくくなります。',
        'お手入れ：週に1回、イヤーピースと金色の充電端子を乾いた布で拭いてください。片耳だけ充電されなくなる原因で最も多いのは、端子に付いた耳あかです。メーカー保証は購入日から1年間（イヤホン・ケース）。片耳を紛失した場合は、ナミのサポートで片耳4,400円（ケースは5,500円）で購入できます。',
      ],
    },
    tables: [
      {
        title: { en: 'Battery life by mode', ja: 'モード別の再生時間' },
        en: [['Mode', 'Earbuds (one charge)', 'With case'], ['Noise cancelling on', '6.5 h', 'About 24 h'], ['Ambient mode', '6 h', 'About 22 h'], ['Both off', '8 h', '30 h'], ['Calls', '5 h', 'About 18 h']],
        ja: [['モード', 'イヤホン単体', 'ケース併用'], ['ノイキャンON', '6.5時間', '約24時間'], ['外音取り込み', '6時間', '約22時間'], ['どちらもOFF', '8時間', '30時間'], ['通話', '5時間', '約18時間']],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-24', variant: 'white', helpful: 238, verified: true,
        en: { name: 'Haruka', title: 'My Mirror Line commute is finally quiet', body: 'I ride the Mirror Line 40 minutes each way and the old diesel cars are loud. On High the engine noise turns into a faint hum and I can listen to podcasts at half the volume I used before. Ambient mode is good enough to hear the announcements at Springvale Central. With the case, the battery easily lasts a week of commuting.' },
        ja: { name: 'はるか', title: '鏡線の通勤がやっと静かに', body: '鏡線で片道40分通勤しています。古い気動車なのでうるさいのですが、ノイキャンを「強」にするとエンジン音がかすかなうなり程度になり、ポッドキャストを前の半分くらいの音量で聞けるようになりました。外音取り込みでも春川中央駅のアナウンスは十分聞こえます。ケースと合わせれば1週間の通勤でも充電が持ちます。' } },
      { stars: 1, date: '2026-08-17', variant: 'black', helpful: 201, verified: true,
        en: { name: 'Kenji W.', title: 'Left bud stopped charging after four months', body: 'One morning the left earbud was at 0% even though it had been in the case all night. Cleaning the contacts helped for a week, then it died completely. Nami replaced the pair under warranty, but I had to send the whole set and was without earbuds for 13 days. The new pair has been fine for a month, but I clean the contacts every few days now.' },
        ja: { name: '渡辺', title: '4か月で左だけ充電されなくなった', body: '一晩ケースに入れておいたのに、朝になると左だけ0%。接点を掃除したら1週間ほどは直りましたが、その後まったく充電されなくなりました。メーカー保証で交換してもらえたものの、一式を送る必要があり、13日間イヤホンなしでした。交換品は1か月問題なし。今は数日おきに接点を拭いています。' } },
      { stars: 2, date: '2026-09-08', variant: 'white', helpful: 167, verified: true,
        en: { name: 'Sota', title: 'Drops out at Springvale Central at rush hour', body: 'At home and on the street the connection is perfect. On the platform at Springvale Central between 8 and 9 in the morning the sound cuts out every few seconds, usually the left bud first. Turning multipoint off in the app made it better but not perfect. My phone is in my left trouser pocket; with it in my chest pocket the drops are rare.' },
        ja: { name: 'そうた', title: '朝の春川中央駅で途切れる', body: '家や道を歩いているときは問題ありません。でも朝8時〜9時の春川中央駅のホームでは数秒おきに音が途切れ、たいてい左から切れます。アプリでマルチポイントをオフにしたら少しましになりましたが、完全ではありません。スマホはズボンの左ポケット。胸ポケットに入れると途切れることはほとんどなくなりました。' } },
      { stars: 5, date: '2026-07-29', variant: 'sand', helpful: 92, verified: true,
        en: { name: 'Midori', title: 'No dropouts at all for me', body: 'I see people complaining about drops at the station. I go through Springvale Central every day and have not had a single one in five months, with an Android phone in my bag. Maybe it depends on the phone. The Sand colour is a soft beige, a little darker than the photo, and it does not show dirt.' },
        ja: { name: 'みどり', title: '私は一度も途切れていません', body: '駅で途切れるというレビューを見かけますが、毎日春川中央駅を通っていて、5か月間一度も途切れたことはありません。スマホはAndroidでカバンの中。機種によるのかもしれません。サンドは写真より少し濃いやわらかいベージュで、汚れが目立ちません。' } },
      { stars: 3, date: '2026-09-15', variant: 'black', helpful: 118, verified: true,
        en: { name: 'Emi', title: 'Even the XS tips fall out when I run', body: 'Noise cancelling is great when I am sitting still. I have small ears, and even with the XS tips the buds work loose after ten minutes of jogging; the left one fell out on the Mirror River path. For running I now use the Kaze Open-Ear, which sits outside the ear. I could not return these because I had opened the seal, so they are my train earbuds now.' },
        ja: { name: 'えみ', title: 'XSイヤーピースでも走ると落ちる', body: '座っているときのノイキャンは最高です。ただ耳が小さく、XSのイヤーピースでも10分ジョギングするとゆるんできて、鏡川沿いの遊歩道で左が落ちました。ランニングには耳の穴に入れないカゼのオープンイヤーを使っています。衛生シールを開けたので返品できず、今は電車専用です。' } },
      { stars: 2, date: '2026-08-02', variant: 'white', helpful: 133, verified: true,
        en: { name: 'T. Fujii', title: 'Callers say I sound far away', body: 'Fine for music, poor for calls. Indoors people say I sound like I am in a tunnel, and on my bike with any wind they cannot understand me at all. I switched calls back to my phone. If you work from home and are on video calls all day, these are not the ones.' },
        ja: { name: '藤井', title: '通話だと声が遠いと言われる', body: '音楽は良いですが、通話はいまいち。室内でも「トンネルの中にいるみたい」と言われ、自転車で少しでも風があるとまったく聞き取れないそうです。通話はスマホ本体に戻しました。在宅勤務で一日中ビデオ会議をする人には向きません。' } },
      { stars: 4, date: '2026-06-21', variant: 'white', helpful: 74, verified: true,
        en: { name: 'Alex', title: 'Multipoint works well with a laptop and phone', body: 'Connected to my work laptop and my Android phone at the same time. Music from the laptop pauses when the phone rings and comes back after the call. No LDAC, but honestly I cannot hear a difference from AAC on the train. Minus one star because the touch controls trigger when I adjust the buds.' },
        ja: { name: 'アレックス', title: 'PCとスマホのマルチポイントが便利', body: '仕事のノートPCとAndroidスマホに同時接続しています。スマホに電話がかかってくるとPCの音楽が止まり、通話が終わると戻ります。LDACには非対応ですが、電車の中ではAACとの違いは正直わかりません。位置を直すときにタッチ操作が反応してしまうので星4つ。' } },
      { stars: 1, date: '2026-09-30', variant: 'black', helpful: 156, verified: true,
        en: { name: 'Naoko', title: 'Could not return them after trying them on', body: 'They hurt my ears after an hour, so I asked for a return the next day. Because I had opened the hygiene seal, they cannot be returned unless faulty. That is written on the page, so my fault, but I wish the box said it more clearly. If you are not sure in-ear buds suit you, try some in a shop first.' },
        ja: { name: 'なおこ', title: '試しにつけたら返品できなかった', body: '1時間で耳が痛くなったので翌日返品を申し込みましたが、衛生シールを開けたので不良品以外は返品不可とのこと。ページに書いてあるので確認不足ではありますが、箱にももっとわかりやすく書いてほしかったです。カナル型が合うか自信のない方は、先にお店で試してみてください。' } },
      { stars: 5, date: '2026-05-11', variant: 'black', helpful: 88, verified: true,
        en: { name: 'Kazu', title: 'Worth the step up from VoltX Pods', body: 'My ¥2,980 VoltX Pods kept losing the left bud and had no noise cancelling at all. These cost four times as much and are worth it: a steady connection, real noise cancelling, and wireless charging on the pad I already had.' },
        ja: { name: 'かず', title: 'ボルトX Podsから買い替えて正解', body: '2,980円のボルトX Podsは左がしょっちゅう切れるし、ノイキャンもありませんでした。こちらは4倍の値段ですが、その価値はあります。接続が安定していて、ノイキャンもしっかり効き、持っていたワイヤレス充電器でも充電できます。' } },
      { stars: 3, date: '2026-04-26', variant: 'white', helpful: 61, verified: true,
        en: { name: 'Yuta', title: 'Battery is shorter after a year', body: 'Bought in the first month they were sold. New, I got about 6.5 h with noise cancelling, as advertised. Thirteen months later it is closer to 5 h, and the warranty has just ended. Still good earbuds, but the batteries cannot be replaced.' },
        ja: { name: 'ゆうた', title: '1年でバッテリーが短くなった', body: '発売直後に購入。最初はノイキャンONで公称どおり約6.5時間持ちましたが、13か月経った今は5時間ほど。ちょうど保証が切れたところでした。イヤホンとしては今も満足ですが、バッテリーは交換できません。' } },
      { stars: 5, date: '2026-09-02', variant: 'sand', helpful: 27, verified: false,
        en: { name: 'Lena', title: 'These for the train, Seiran at home', body: 'I use the Seiran Studio NC over-ears at my desk and these on the train. The Seiran cancels more noise, but these fit in a pocket and the case charges on my wireless pad. The Sand colour arrived on Thursday rather than the next day.' },
        ja: { name: 'レナ', title: '外ではこれ、家ではセイラン', body: '自宅のデスクではセイランのヘッドホン、電車ではこちらを使っています。ノイキャンの強さはセイランが上ですが、こちらはポケットに入り、ケースはワイヤレス充電器にのせるだけ。サンドは翌日ではなく木曜日に届きました。' } },
      { stars: 4, date: '2026-07-03', variant: 'white', helpful: 45, verified: true,
        en: { name: 'Ishi', title: 'Good, but the case scratches easily', body: 'The sound is balanced and a bit light on bass; the equaliser in the app fixes that. The glossy white case got fine scratches within a week in a pocket with my keys.' },
        ja: { name: '石田', title: 'ケースに傷がつきやすい', body: '音はバランス型で低音はやや控えめ。アプリのイコライザーで調整できます。光沢のある白いケースは、鍵と同じポケットに入れていたら1週間で細かい傷だらけになりました。' } },
    ],
    qa: [
      { date: '2026-08-20', votes: 52,
        en: { q: 'Can I connect them to my iPhone and my Windows laptop at the same time?', a: 'Yes. Multipoint keeps two devices connected at once. Pair each device once, and the earbuds reconnect to both when you take them out of the case. Sound comes from whichever device is playing, and a call on either device takes priority.', by: 'Nami Support' },
        ja: { q: 'iPhoneとWindowsのノートPCに同時に接続できますか？', a: 'はい。マルチポイント機能で2台に同時接続できます。それぞれ一度ペアリングすれば、ケースから取り出したときに両方へ自動で再接続します。音は再生中の機器から流れ、どちらかに着信があれば通話が優先されます。', by: 'ナミ サポート' } },
      { date: '2026-09-14', votes: 47,
        en: { q: 'If they don\'t fit my ears, can I return them?', a: 'Only if the hygiene seal on the ear-tip tray has not been broken: unopened, you can return them within 30 days of delivery for a full refund. Once the seal is broken, in-ear earbuds can be returned only if they are defective, damaged or the wrong item.', by: 'Marketa Customer Service' },
        ja: { q: '耳に合わなかった場合、返品できますか？', a: 'イヤーピース部分の衛生シールが未開封の場合に限り、お届けから30日以内なら全額返金で返品いただけます。シール開封後のカナル型イヤホンは、初期不良・破損・誤配送の場合のみ返品を承ります。', by: 'マルケタ カスタマーサービス' } },
      { date: '2026-02-18', votes: 15,
        en: { q: 'Can I use just the left earbud?', a: 'No, only the right one works on its own. The left one needs the right one to connect.', by: 'Marketa customer (Taku)' },
        ja: { q: '左耳だけで使えますか？', a: 'いいえ、単体で使えるのは右だけです。左は右がないと接続できません。', by: 'マルケタ購入者（たく）' } },
      { date: '2026-07-07', votes: 31,
        en: { q: 'An earlier answer says only the right earbud works alone. Is that still true?', a: 'Not any more. Since firmware 1.4 (March 2026) either earbud can be used on its own, with noise cancelling. Update in the Nami app under Settings > Firmware.', by: 'Nami Support' },
        ja: { q: '右だけしか単体で使えないという回答がありますが、今もそうですか？', a: 'いいえ。2026年3月のファームウェア1.4以降、左右どちらでも片耳だけで使え、ノイキャンも有効です。ナミアプリの「設定＞ファームウェア」から更新してください。', by: 'ナミ サポート' } },
      { date: '2026-06-10', votes: 22,
        en: { q: 'Does it support LDAC on my Android phone?', a: 'No. Nami Buds 2 support SBC and AAC only. On Android they connect with AAC where the phone supports it.', by: 'Nami Support' },
        ja: { q: 'AndroidスマホでLDACは使えますか？', a: 'いいえ。ナミ Buds 2の対応コーデックはSBCとAACのみです。AndroidでもAAC対応機種ならAACで接続されます。', by: 'ナミ サポート' } },
      { date: '2026-05-22', votes: 13,
        en: { q: 'Can I wear them in the shower or at the pool?', a: 'No. IPX4 protects against sweat and splashes, not running water or swimming. The charging case has no water resistance, so dry the buds before putting them back.', by: 'Nami Support' },
        ja: { q: 'シャワーやプールで使えますか？', a: 'いいえ。IPX4は汗や水しぶきへの耐性で、流水や水泳には対応していません。充電ケースは防水ではないため、水滴を拭き取ってから収納してください。', by: 'ナミ サポート' } },
    ],
    similar: ['seiran-headphones', 'kaze-openear', 'voltx-pods'],
    fbt: ['ampora-slim-10k', 'kaze-openear'],
    alsoViewed: ['seiran-headphones', 'voltx-pods', 'kaze-openear', 'ampora-slim-10k', 'ampora-go-20k', 'kestrel-27k'],
  },
  {
    id: 'seiran-headphones',
    cat: 'electronics',
    cluster: 'audio',
    brand: { en: 'Seiran', ja: 'セイラン' },
    seller: 'marketa',
    images: ['seiran-headphones'],
    title: {
      en: 'Seiran Studio NC Wireless Noise-Cancelling Over-Ear Headphones, 40 h Battery, LDAC/AAC, Multipoint, Fold-Flat Design, 3.5 mm Wired Mode, 265 g, with Carry Case',
      ja: 'セイラン Studio NC ワイヤレスヘッドホン ノイズキャンセリング オーバーイヤー 最大40時間再生 LDAC/AAC対応 マルチポイント 3.5mm有線接続対応 フラット収納 265g ケース付き SR-NC1',
    },
    short: { en: 'Seiran Studio NC Headphones', ja: 'セイラン Studio NC ヘッドホン' },
    rating: 4.6,
    ratings: 1930,
    hist: [74, 16, 5, 2, 3],
    added: '2025-02-18',
    badges: ['choice'],
    coupon: null,
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'grey', name: { en: 'Grey', ja: 'グレー' }, price: 24800, list: 32000, stock: 15, ship: 'fast' },
      { id: 'navy', name: { en: 'Midnight Navy', ja: 'ミッドナイトネイビー' }, price: 24800, list: 32000, stock: 7, ship: 'fast2' },
    ],
    returns: {
      en: 'Returnable within 30 days of delivery: unused for a full refund, or opened in like-new condition with all accessories minus a 15% restocking fee (¥3,720) and ¥550 return shipping (return shipping is free for paid Fast members). Defective units are returned free within 30 days; after that the 2-year Seiran warranty applies.',
      ja: 'お届けから30日以内なら返品できます。未使用品は全額返金、開封済みの場合は付属品がすべてそろった新品同様の状態に限り、返品手数料15%（3,720円）と返送料550円（有料のFast会員は返送料無料）を差し引いて返金します。初期不良は30日以内なら送料無料で返品でき、その後はセイランの2年保証の対象です。',
    },
    bullets: {
      en: [
        'STRONG NOISE CANCELLING: eight microphones and adaptive noise cancelling that adjusts to your surroundings, from an aircraft cabin to an open-plan office. Ambient mode, and a speak-to-chat option that pauses music when you start talking.',
        'ALL-WEEK BATTERY: 40 h with noise cancelling off, 30 h with it on. 10 minutes of USB-C charging gives about 5 h; a full charge takes about 2.5 h.',
        'HIGH-RESOLUTION BLUETOOTH ON ANDROID: LDAC for compatible Android phones, AAC for iPhone, SBC for everything else. Multipoint connects two devices at once (not while LDAC is in use).',
        'PLUG IN WHEN THE BATTERY IS FLAT: the included 1.2 m 3.5 mm cable works even with the headphones switched off, for in-flight films or an audio interface. Airline adapter included.',
        'LIGHT AND FLAT: 265 g, with soft protein-leather pads and a padded band. The ear cups turn flat to fit the slim 5 cm case and to rest comfortably around your neck.',
        '2-YEAR WARRANTY from Seiran. Replacement ear pads (¥2,200 a pair) are available from Seiran support, so worn pads are not the end of the headphones.',
      ],
      ja: [
        '【強力なノイズキャンセリング】8基のマイクで周囲の騒音に合わせて自動調整するアダプティブノイキャン。飛行機の機内からオフィスまで対応します。外音取り込みモードと、話し始めると音楽が一時停止する「スピーク・トゥ・チャット」機能も搭載。',
        '【1週間持つバッテリー】ノイキャンOFFで40時間、ONで30時間。USB-Cで10分充電すれば約5時間使え、満充電は約2.5時間です。',
        '【AndroidでLDAC対応】対応AndroidスマホではLDAC、iPhoneではAAC、その他はSBCで接続。マルチポイントで2台同時接続も可能です（LDAC使用時は除く）。',
        '【電池切れでも有線で使える】付属の3.5mmケーブル（1.2m）なら電源オフでも音が聞けます。機内エンターテインメントやオーディオインターフェースにも。航空機用変換プラグ付き。',
        '【軽量265g・フラット収納】やわらかいプロテインレザーのイヤーパッドとクッション入りヘッドバンド。ハウジングを平らに回転させて厚さ5cmの薄型ケースに収納でき、首にかけても邪魔になりません。',
        '【メーカー保証2年】交換用イヤーパッド（1組2,200円）をセイランのサポートで購入できるので、パッドがへたっても長く使えます。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Seiran'], ['Model', 'SR-NC1'], ['Type', 'Over-ear, closed back, wireless'], ['Noise cancelling', 'Adaptive hybrid ANC (8 microphones), ambient mode'],
        ['Battery', '40 h (30 h with ANC)'], ['Charging', 'USB-C, full in about 2.5 h; 10 min gives about 5 h'], ['Bluetooth', '5.3, range about 10 m'],
        ['Codecs', 'SBC, AAC, LDAC'], ['Multipoint', 'Yes, 2 devices (not while LDAC is on)'], ['Wired', '3.5 mm; works powered off (no ANC) or on (ANC available)'],
        ['Driver', '40 mm dynamic'], ['Water resistance', 'None'], ['Weight', '265 g'], ['Size (cups flat)', '19.5 × 16.5 × 4.5 cm; case 21 × 18 × 5 cm'],
        ['Country of origin', 'Vietnam'], ['Warranty', '2 years (manufacturer)'],
        ['In the box', 'Headphones, carrying case, USB-C to USB-C cable (50 cm), 3.5 mm audio cable (1.2 m), airline adapter, quick guide'],
      ],
      ja: [
        ['ブランド', 'セイラン'], ['型番', 'SR-NC1'], ['タイプ', 'オーバーイヤー・密閉型・ワイヤレス'], ['ノイズキャンセリング', 'アダプティブハイブリッドANC（マイク8基）、外音取り込みモード'],
        ['連続再生時間', '40時間（ANC ON時30時間）'], ['充電', 'USB-C、満充電約2.5時間／10分充電で約5時間再生'], ['Bluetooth', '5.3（通信距離約10m）'],
        ['対応コーデック', 'SBC、AAC、LDAC'], ['マルチポイント', '対応（2台。LDAC使用時は不可）'], ['有線接続', '3.5mm。電源オフ（ANCなし）でも、電源オン（ANC使用可）でも使用可能'],
        ['ドライバー', '40mmダイナミック型'], ['防水性能', 'なし'], ['重量', '約265g'], ['サイズ（フラット時）', '19.5×16.5×4.5cm／ケース21×18×5cm'],
        ['原産国', 'ベトナム'], ['保証', 'メーカー保証2年'],
        ['付属品', 'ヘッドホン本体、キャリングケース、USB-C to USB-Cケーブル（50cm）、3.5mmオーディオケーブル（1.2m）、航空機用変換プラグ、クイックガイド'],
      ],
    },
    compare: {
      en: ['Over-ear', 'Yes (adaptive)', '40 h (30 h with ANC)', 'None', '265 g', '2 years'],
      ja: ['オーバーイヤー', 'あり（アダプティブ）', '40時間（ANC ON時30時間）', 'なし', '265g', '2年'],
    },
    description: {
      en: [
        'The Seiran Studio NC are full-size headphones for long listening: flights, a whole day at a desk, the long train ride to Moonview Spa. The cups surround the ears rather than pressing on them, and at 265 g they are light for headphones of this size. Noise cancelling adapts automatically, or you can fix it at one level in the Seiran app.',
        'Compatibility: any Bluetooth phone, tablet or computer. On Android phones that support LDAC you can turn on high-resolution playback in the app; iPhones use AAC, the best an iPhone offers over Bluetooth. Multipoint connects two devices at the same time, such as a phone and a laptop, but it switches off while LDAC is in use because LDAC needs the full Bluetooth bandwidth. Some older Windows laptops with Bluetooth 4.x have reported dropouts; firmware 2.1 improves this, so update in the app before you judge the connection.',
        'Fit: the headband is fairly firm so that the cups seal for noise cancelling. People with larger heads or thick glasses frames may find it tight for the first week; it relaxes with use. The protein-leather pads are soft but warm in humid summer weather. Replacement pads cost ¥2,200 a pair from Seiran support and clip on without tools.',
        'The included 3.5 mm cable works even when the battery is flat, without noise cancelling; with the headphones switched on, noise cancelling also works while wired. Seiran covers the headphones for two years from purchase, including the hinges, and the battery if it falls below 70% of its original capacity.',
      ],
      ja: [
        'セイラン Studio NCは、飛行機や一日中のデスクワーク、月見温泉までの長い電車移動など、長時間のリスニングのためのヘッドホンです。耳を押さえつけるのではなく包み込むオーバーイヤー型で、このサイズとしては軽い265g。ノイキャンは自動で調整されるほか、セイランアプリで強さを固定することもできます。',
        '対応機器：Bluetooth対応のスマホ・タブレット・パソコン。LDAC対応のAndroidスマホなら、アプリでハイレゾ相当の再生をオンにできます。iPhoneはBluetoothで最も高音質なAACで接続します。マルチポイントでスマホとノートPCなど2台に同時接続できますが、LDACは通信帯域をすべて使うため、LDAC使用中はマルチポイントがオフになります。Bluetooth 4.x世代の古いWindowsノートPCでは途切れるという報告があり、ファームウェア2.1で改善しています。接続の安定性はアプリで更新してからご確認ください。',
        '装着感：ノイキャン効果を高めるため、ヘッドバンドはやや強めの側圧です。頭の大きい方や太いフレームのメガネをお使いの方は、最初の1週間ほどきつく感じることがありますが、使ううちになじみます。プロテインレザーのイヤーパッドはやわらかい反面、湿度の高い夏は蒸れやすくなります。交換用パッドはセイランのサポートで1組2,200円、工具なしではめ込むだけで交換できます。',
        '付属の3.5mmケーブルはバッテリーが切れていても使えます（ノイキャンなし）。電源を入れていれば、有線接続中もノイキャンが使えます。メーカー保証は購入日から2年間で、ヒンジ部分のほか、バッテリー容量が初期の70%未満になった場合も対象です。',
      ],
    },
    tables: [
      {
        title: { en: 'Connection modes', ja: '接続方法と使える機能' },
        en: [['Connection', 'Noise cancelling', 'Battery', 'Multipoint'], ['Bluetooth (AAC/SBC)', 'Yes', '30 h with ANC, 40 h without', 'Yes'], ['Bluetooth (LDAC)', 'Yes', 'About 24 h with ANC', 'No'], ['3.5 mm cable, power on', 'Yes', 'About 35 h with ANC', '—'], ['3.5 mm cable, power off', 'No', 'Not needed', '—']],
        ja: [['接続方法', 'ノイキャン', 'バッテリー', 'マルチポイント'], ['Bluetooth（AAC/SBC）', '使える', 'ANC ON 30時間／OFF 40時間', '使える'], ['Bluetooth（LDAC）', '使える', 'ANC ON 約24時間', '使えない'], ['3.5mmケーブル（電源オン）', '使える', 'ANC ON 約35時間', '—'], ['3.5mmケーブル（電源オフ）', '使えない', '不要', '—']],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-19', variant: 'grey', helpful: 176, verified: true,
        en: { name: 'Takeshi', title: 'A twelve-hour flight in silence', body: 'Wore them for a 12-hour flight with noise cancelling on the whole time and still had 55% left when we landed. The engine roar becomes a quiet hiss. For the in-flight films I used the cable and the airline adapter, and noise cancelling still works that way.' },
        ja: { name: 'たけし', title: '12時間のフライトが静かに', body: '12時間のフライトでずっとノイキャンONのまま使い、着陸時もまだ55%残っていました。エンジンの轟音がかすかな「サー」という音になります。機内映画は付属のケーブルと航空機用プラグで。有線でもノイキャンが使えます。' } },
      { stars: 2, date: '2026-08-25', variant: 'grey', helpful: 142, verified: true,
        en: { name: 'Mari S.', title: 'Too tight with my glasses', body: 'Sound and noise cancelling are excellent, but the band presses the arms of my glasses into my head. After about 90 minutes I get a headache. It has loosened slightly after a month, but not enough. If you wear glasses all day, try a pair before buying.' },
        ja: { name: '佐藤まり', title: 'メガネだと締め付けがきつい', body: '音もノイキャンも素晴らしいのですが、側圧でメガネのつるが頭に押し付けられ、1時間半ほどで頭が痛くなります。1か月で少しゆるくなったものの、まだ足りません。一日中メガネをかける方は試着してから買うのがおすすめです。' } },
      { stars: 5, date: '2026-09-01', variant: 'navy', helpful: 97, verified: true,
        en: { name: 'Jun', title: 'Comfortable for long sessions, even with glasses', body: 'I disagree with the reviews about tightness. I wear thin metal glasses and edit audio for five or six hours a day with these on, with no pain. Maybe it depends on head size and frames. Navy looks almost black indoors.' },
        ja: { name: 'じゅん', title: 'メガネでも長時間快適', body: '締め付けがきついというレビューには同意できません。細いメタルフレームのメガネで1日5〜6時間音声編集をしていますが、痛くなりません。頭の大きさやフレームによるのかも。ネイビーは室内だとほぼ黒に見えます。' } },
      { stars: 1, date: '2026-07-12', variant: 'grey', helpful: 121, verified: true,
        en: { name: 'R. Nakamura', title: 'Hinge cracked after ten months', body: 'The right hinge, where the cup turns flat, developed a crack and then snapped. I only ever turned it to put the headphones in the case. The 2-year warranty covered it, but the repair took 19 days. For ¥24,800 I expected sturdier plastic.' },
        ja: { name: '中村', title: '10か月でヒンジが割れた', body: 'ハウジングを平らに回転させる右側のヒンジにひびが入り、その後折れました。ケースにしまうときに回していただけです。2年保証で修理してもらえましたが、19日かかりました。24,800円なのでもう少し丈夫な素材であってほしかった。' } },
      { stars: 3, date: '2026-08-09', variant: 'grey', helpful: 84, verified: true,
        en: { name: 'Natsumi', title: 'Hot in summer', body: 'Great in winter. In August in Springvale my ears were sweating after 30 minutes and the pads felt sticky. I now use them only in air-conditioned rooms.' },
        ja: { name: 'なつみ', title: '夏は蒸れます', body: '冬は最高です。8月の春川では30分で耳が汗ばみ、イヤーパッドがべたつきました。今はエアコンの効いた部屋でしか使っていません。' } },
      { stars: 4, date: '2026-06-18', variant: 'navy', helpful: 66, verified: true,
        en: { name: 'Ken', title: 'LDAC is great, but you lose multipoint', body: 'On my Android phone LDAC sounds noticeably more detailed than AAC. But as soon as you turn LDAC on, multipoint goes off and my laptop disconnects. I switch LDAC on for music at home and off on work days. A bit fiddly.' },
        ja: { name: 'ケン', title: 'LDACは良いがマルチポイントが使えない', body: 'AndroidスマホでLDACにすると、AACよりはっきり細かく聞こえます。ただLDACをオンにした瞬間マルチポイントが切れ、ノートPCとの接続が外れます。家で音楽を聴くときはLDACオン、仕事の日はオフと切り替えていますが、少し面倒です。' } },
      { stars: 2, date: '2026-09-23', variant: 'grey', helpful: 109, verified: true,
        en: { name: 'Akiko', title: 'Mic is poor for meetings', body: 'Colleagues say my voice is muffled and that they hear my keyboard. In a quiet room it is acceptable, but from a café they could hardly follow me. I now use the laptop\'s microphone and the headphones only for listening. For indoor calls my Nami Buds 2 are actually clearer.' },
        ja: { name: 'あきこ', title: '会議にはマイクが弱い', body: '同僚から声がこもっていて、キーボードの音が聞こえると言われます。静かな部屋なら許容範囲ですが、カフェからだとほとんど聞き取れなかったそうです。今はマイクはノートPCのものを使い、ヘッドホンは聞くだけ。屋内の通話なら手持ちのナミ Buds 2のほうがクリアでした。' } },
      { stars: 5, date: '2026-05-30', variant: 'grey', helpful: 58, verified: true,
        en: { name: 'Dan', title: 'The cable saved me', body: 'Forgot to charge them before a night bus and the battery died halfway. I plugged in the 3.5 mm cable and kept listening; no noise cancelling, but fine. Not many wireless headphones still do this.' },
        ja: { name: 'ダン', title: '有線モードに救われた', body: '夜行バスの前に充電を忘れ、途中で電池切れ。3.5mmケーブルをつないでそのまま聞けました。ノイキャンは効きませんが十分です。今どき有線で使えるワイヤレスヘッドホンは貴重です。' } },
      { stars: 4, date: '2026-04-14', variant: 'grey', helpful: 41, verified: true,
        en: { name: 'Shiho', title: 'Better noise cancelling than earbuds, but bulky', body: 'I own the Nami Buds 2 too. The Seiran blocks noticeably more of the low rumble on the train, and the battery lasts all week. But even flat, the case is the size of a small book, so on short outings I take the earbuds.' },
        ja: { name: 'しほ', title: 'イヤホンよりノイキャンは強いがかさばる', body: 'ナミ Buds 2も持っています。電車の低い走行音はセイランのほうが明らかによく消え、バッテリーも1週間持ちます。ただ平らにしてもケースは小さめの本くらいあるので、ちょっとした外出はイヤホンにしています。' } },
      { stars: 3, date: '2026-09-06', variant: 'navy', helpful: 52, verified: true,
        en: { name: 'Hiro', title: 'Returned one pair: the restocking fee is real', body: 'My first pair (grey) pressed on my ears, so I returned it after two days. That was allowed, but Marketa deducted the 15% restocking fee (¥3,720) and ¥550 shipping. Later I tried a friend\'s pair with the band adjusted properly, it fit fine, and I bought the navy. An expensive lesson: adjust the band before you give up.' },
        ja: { name: 'ひろ', title: '1台返品：返品手数料は本当にかかります', body: '最初に買ったグレーは耳が圧迫されて、2日で返品しました。返品はできましたが、返品手数料15%（3,720円）と送料550円が引かれました。その後、友人のものでヘッドバンドをきちんと調整して試したら問題なかったので、ネイビーを買い直しました。高い勉強代。あきらめる前にバンドの調整を。' } },
      { stars: 2, date: '2026-03-22', variant: 'grey', helpful: 77, verified: true,
        en: { name: 'Masa', title: 'Drops out with my Windows laptop', body: 'Perfect with my phone. With my four-year-old Windows laptop the sound cut out every few minutes during video calls. Firmware 2.1 helped a lot, from every few minutes to once or twice an hour, but that is still not reliable enough for work.' },
        ja: { name: 'まさ', title: 'Windowsノートだと途切れる', body: 'スマホとは完璧。4年前のWindowsノートだと、ビデオ会議中に数分おきに音が途切れました。ファームウェア2.1でかなり改善し、1時間に1〜2回程度になりましたが、仕事で使うにはまだ不安です。' } },
    ],
    qa: [
      { date: '2026-09-10', votes: 38,
        en: { q: 'Can I use them wired when the battery is flat?', a: 'Yes. With the 3.5 mm cable they work with the power off, without noise cancelling. If the battery has charge and you switch them on, noise cancelling also works while wired.', by: 'Seiran Support' },
        ja: { q: 'バッテリーが切れても有線で使えますか？', a: 'はい。3.5mmケーブルをつなげば電源オフでも使えます（ノイキャンなし）。バッテリーが残っていて電源を入れれば、有線接続中もノイキャンが使えます。', by: 'セイラン サポート' } },
      { date: '2026-07-25', votes: 29,
        en: { q: 'Can I use LDAC and multipoint at the same time?', a: 'No. When I turn on LDAC in the app, multipoint switches off and my second device disconnects. With AAC both work.', by: 'Marketa customer (Ken)' },
        ja: { q: 'LDACとマルチポイントは同時に使えますか？', a: 'いいえ。アプリでLDACをオンにするとマルチポイントがオフになり、2台目の接続が切れます。AACなら両方使えます。', by: 'マルケタ購入者（ケン）' } },
      { date: '2026-08-30', votes: 24,
        en: { q: 'Will they fit a large head?', a: 'My head is 61 cm (XL hat size) and I use the second-to-last notch. Tight for the first week, then fine.', by: 'Marketa customer (Goro)' },
        ja: { q: '頭が大きくても使えますか？', a: '頭囲61cm（帽子XL）ですが、最後から2番目の目盛りで使えています。最初の1週間はきつめでしたが、その後は快適です。', by: 'マルケタ購入者（ごろう）' } },
      { date: '2026-05-16', votes: 19,
        en: { q: 'Can I buy replacement ear pads?', a: 'Yes. Replacement pads are ¥2,200 a pair from Seiran support. They clip on, no tools needed. Replacing pads does not affect the warranty.', by: 'Seiran Support' },
        ja: { q: '交換用のイヤーパッドは買えますか？', a: 'はい。セイランのサポートで1組2,200円でご購入いただけます。はめ込み式で工具は不要です。交換しても保証には影響しません。', by: 'セイラン サポート' } },
      { date: '2026-06-03', votes: 14,
        en: { q: 'Is an airline adapter included?', a: 'Yes, a two-pin airline adapter comes in the case with the 3.5 mm cable.', by: 'Marketa customer (Takeshi)' },
        ja: { q: '飛行機用の変換プラグは付いていますか？', a: 'はい、2ピンの航空機用プラグが3.5mmケーブルと一緒にケースに入っています。', by: 'マルケタ購入者（たけし）' } },
    ],
    similar: ['nami-buds', 'kaze-openear', 'voltx-pods'],
    fbt: ['ampora-go-20k', 'nami-buds'],
    alsoViewed: ['nami-buds', 'kaze-openear', 'voltx-pods', 'kestrel-27k', 'ampora-go-20k', 'ampora-slim-10k'],
  },
  {
    id: 'voltx-pods',
    cat: 'electronics',
    cluster: 'audio',
    brand: { en: 'VoltX', ja: 'ボルトX' },
    seller: 'brightdeal',
    images: ['voltx-pods'],
    title: {
      en: 'VoltX Pods Wireless Earbuds Bluetooth 5.3 Hi-Fi Stereo Bass, IPX5 Waterproof, 25H Playtime with Charging Case, Touch Control, Auto Pairing, ENC Mic for Calls, for iPhone Android',
      ja: 'ワイヤレスイヤホン Bluetooth5.3 ボルトX Pods 高音質 重低音 IPX5防水 最大25時間再生 充電ケース付き タッチ操作 自動ペアリング ENC通話ノイズ低減 iPhone Android対応 ブラック',
    },
    short: { en: 'VoltX Pods Earbuds', ja: 'ボルトX Pods イヤホン' },
    rating: 3.4,
    ratings: 2688,
    hist: [38, 17, 12, 10, 23],
    added: '2025-06-30',
    badges: ['sponsored'],
    coupon: null,
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'black', name: { en: 'Black', ja: 'ブラック' }, price: 2980, list: 5980, stock: 120, ship: 'brightdeal' },
    ],
    returns: {
      en: 'Sold and shipped by BrightDeal Trading, which uses its own policy: change-of-mind returns within 30 days only if unopened, and you pay ¥880 return shipping. If faulty, message the seller first and wait up to 2 business days for a prepaid label; if the seller does not reply or refuses a valid return, Marketa Purchase Protection applies.',
      ja: 'ブライトディール商事が販売・発送する商品のため、同社の返品条件が適用されます。お客様都合の返品は未開封品のみ30日以内で、返送料880円はお客様負担です。不良品の場合はまず出品者にメッセージで連絡し、返送用伝票の発行を最大2営業日お待ちください。返信がない場合や正当な返品を断られた場合は、マルケタ購入保証の対象になります。',
    },
    bullets: {
      en: [
        'AUTO PAIRING, BLUETOOTH 5.3: open the case and the earbuds reconnect to the last device. Works with iPhone, Android, tablets and computers. SBC codec only; one device at a time (no multipoint).',
        '5 H PER CHARGE, 25 H IN TOTAL: each charge lasts up to 5 h at medium volume and the case recharges the earbuds about 4 times. The case charges by USB-C in about 1.5 h.',
        'NO ACTIVE NOISE CANCELLING: ENC reduces background noise for the person you are calling only; it does not make your surroundings quieter.',
        'SPLASH RESISTANT, IPX5 (manufacturer\'s rating): for sweat and light rain. Do not swim, shower or rinse them; water damage is not covered by the seller warranty.',
        'LIGHT STEM DESIGN: 4.1 g per earbud. Medium ear tips fitted, small and large included.',
        '6-MONTH SELLER WARRANTY from BrightDeal Trading. Ships from Kobe; delivery takes 4–8 days and is not eligible for Marketa Fast.',
      ],
      ja: [
        '【Bluetooth5.3 自動ペアリング】ケースを開けるだけで前回の機器に自動接続。iPhone・Android・タブレット・パソコンに対応。コーデックはSBCのみ、1台ずつの接続です（マルチポイント非対応）。',
        '【最大25時間再生】イヤホン単体で最大5時間（音量中程度）、充電ケースで約4回分充電できます。ケースはUSB-Cで約1.5時間で満充電。',
        '【通話ノイズ低減ENC】ENCは通話相手に届く周囲の雑音を減らす機能です。アクティブノイズキャンセリングではないため、周りの音は小さくなりません。',
        '【IPX5防水（メーカー公称）】汗や小雨に対応。水泳・シャワー・水洗いは不可で、水濡れによる故障は販売店保証の対象外です。',
        '【軽量4.1g】片耳約4.1gのスティック型。イヤーピースはM装着済み、S・Lも付属。',
        '【6か月保証】ブライトディール商事による6か月の販売店保証付き。神戸の倉庫から発送し、お届けまで4〜8日。マルケタFastの対象外です。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'VoltX'], ['Model', 'VX-P1'], ['Type', 'True wireless in-ear, stem style'], ['Noise cancelling', 'No (ENC call noise reduction only)'],
        ['Battery', 'Up to 5 h per charge; about 20 h more from the case'], ['Charging', 'USB-C, case full in about 1.5 h'], ['Bluetooth', '5.3 (stated), range about 10 m'],
        ['Codec', 'SBC'], ['Multipoint', 'No'], ['Water resistance', 'IPX5 (manufacturer\'s rating)'], ['Controls', 'Touch'],
        ['Weight', '4.1 g per earbud; case 35 g'], ['Case dimensions', '5.8 × 4.5 × 2.2 cm'], ['Country of origin', 'China'],
        ['Warranty', '6 months (BrightDeal Trading seller warranty)'], ['In the box', 'Earbuds, charging case, ear tips S/M/L (M fitted), USB-A to USB-C cable, manual'],
      ],
      ja: [
        ['ブランド', 'ボルトX'], ['型番', 'VX-P1'], ['タイプ', '完全ワイヤレス（カナル型・スティック）'], ['ノイズキャンセリング', 'なし（通話用ENCのみ）'],
        ['連続再生時間', '最大5時間／ケースで約20時間分追加'], ['充電', 'USB-C、ケース満充電約1.5時間'], ['Bluetooth', '5.3（公称）、通信距離約10m'],
        ['対応コーデック', 'SBC'], ['マルチポイント', '非対応'], ['防水性能', 'IPX5（メーカー公称）'], ['操作', 'タッチ操作'],
        ['重量', '片耳約4.1g／ケース約35g'], ['ケースサイズ', '幅5.8×高さ4.5×厚さ2.2cm'], ['原産国', '中国'],
        ['保証', '6か月（ブライトディール商事による販売店保証）'], ['付属品', 'イヤホン本体、充電ケース、イヤーピースS/M/L（M装着済み）、USB-A to USB-Cケーブル、取扱説明書'],
      ],
    },
    compare: {
      en: ['In-ear (stems)', 'No', '5 h; about 25 h with case', 'IPX5 (stated)', '4.1 g per bud; case 35 g', '6 months (seller)'],
      ja: ['カナル型（スティック）', 'なし', '5時間／ケース併用約25時間', 'IPX5（メーカー公称）', '片耳4.1g／ケース35g', '6か月（販売店保証）'],
    },
    description: {
      en: [
        'VoltX Pods are basic wireless earbuds for podcasts, videos and the gym at a low price. Pair them once with your phone and they reconnect automatically whenever you open the case. The sound is clear in the middle range with light bass; there is no app and no equaliser.',
        'There is no active noise cancelling. The ENC feature cleans up background noise in your voice during calls, but you still hear the train or the street. They connect to one device at a time: to switch from your phone to a tablet, disconnect the phone first. Like most budget earbuds they have a short audio delay, noticeable in games and in some video apps.',
        'Battery: up to 5 hours at medium volume, less at high volume. The case holds about four more charges. If one earbud stops connecting, put both in the case, hold the touch areas on both earbuds for 10 seconds until the lights flash red and white, then pair again.',
        'Sold and shipped by BrightDeal Trading from Kobe: delivery takes 4–8 days and is not eligible for Marketa Fast. BrightDeal gives a 6-month warranty; for any fault, contact the seller by Marketa message (weekdays 10:00–17:00).',
      ],
      ja: [
        'ボルトX Podsは、ポッドキャストや動画、ジムで気軽に使えるお手頃なワイヤレスイヤホンです。一度スマホとペアリングすれば、ケースを開けるたびに自動で接続します。音は中音域がクリアで低音は控えめ。専用アプリやイコライザーはありません。',
        'アクティブノイズキャンセリングは搭載していません。ENCは通話時に自分の声に混じる周囲の雑音を減らす機能で、電車や街の音は聞こえたままです。接続は1台ずつで、スマホからタブレットに切り替えるときは先にスマホとの接続を解除してください。多くの低価格イヤホンと同様にわずかな音の遅延があり、ゲームや一部の動画アプリでは気になることがあります。',
        'バッテリー：音量中程度で最大5時間、大音量ではそれより短くなります。ケースで約4回分充電できます。片耳がつながらなくなったときは、両耳をケースに入れてから取り出し、両方のタッチ部分を赤と白のランプが点滅するまで10秒長押ししてリセットし、もう一度ペアリングしてください。',
        'ブライトディール商事が神戸の倉庫から販売・発送します。お届けまで4〜8日で、マルケタFastの対象外です。販売店保証は6か月。不具合の際はマルケタのメッセージで出品者にご連絡ください（平日10:00〜17:00）。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-17', variant: 'black', helpful: 112, verified: true,
        en: { name: 'Daichi', title: 'Cannot beat it for ¥2,980', body: 'Bought them for the gym and podcasts. They connect as soon as I open the case and the sound is fine for the price. If I lose one I will not cry. Arrived from Kobe in four days.' },
        ja: { name: 'だいち', title: '2,980円なら文句なし', body: 'ジムとポッドキャスト用に購入。ケースを開けるとすぐつながり、音もこの値段なら十分。なくしても泣かずに済みます。神戸から4日で届きました。' } },
      { stars: 1, date: '2026-08-28', variant: 'black', helpful: 164, verified: true,
        en: { name: 'Miho', title: 'Left bud stopped connecting after three weeks', body: 'After three weeks the left earbud would not connect at all, even after a reset. I messaged BrightDeal on a Friday evening and got a reply with a prepaid label on Tuesday. The refund came nine days after I sent them back. Cheap, but you pay in hassle.' },
        ja: { name: 'みほ', title: '3週間で左がつながらなくなった', body: '3週間で左耳がリセットしても一切つながらなくなりました。金曜の夜にブライトディールへメッセージを送り、火曜日に返送用伝票付きの返信。送り返してから返金まで9日かかりました。安いけれど手間がかかります。' } },
      { stars: 1, date: '2026-07-21', variant: 'black', helpful: 139, verified: true,
        en: { name: 'Shota', title: '"IPX5" did not survive a rainy run', body: 'I ran for 30 minutes in steady rain and the right bud started crackling, then died. The seller said water damage is not covered by the warranty, even though the title says IPX5 waterproof. If you run in the rain, get something with a rating you can trust.' },
        ja: { name: 'しょうた', title: '「IPX5」なのに雨のランで故障', body: '小雨の中を30分走ったら右耳からバリバリ音がして、そのまま鳴らなくなりました。出品者からは水濡れは保証対象外との回答。商品名にIPX5防水とあるのに。雨の日に走るなら、信頼できる防水性能のものを選んだほうがいいです。' } },
      { stars: 2, date: '2026-09-09', variant: 'black', helpful: 97, verified: true,
        en: { name: 'Asuka', title: 'Constant dropouts with my iPhone', body: 'With my iPhone in my back pocket the sound cuts out every few seconds when I walk. In my hand it is fine. On a crowded train they are unusable.' },
        ja: { name: 'あすか', title: 'iPhoneだと頻繁に途切れる', body: 'iPhoneをお尻のポケットに入れて歩くと、数秒ごとに音が途切れます。手に持っていれば大丈夫。満員電車では使い物になりません。' } },
      { stars: 4, date: '2026-08-13', variant: 'black', helpful: 52, verified: true,
        en: { name: 'Kota', title: 'No dropouts with my Android', body: 'I read the reviews about dropouts and was worried, but with my Android phone in my pocket they have been steady for two months. Maybe it is an iPhone thing. The bass is light but acceptable.' },
        ja: { name: 'こうた', title: 'Androidでは途切れません', body: '途切れるというレビューを見て心配でしたが、Androidをポケットに入れて2か月、安定しています。iPhoneとの相性なのかも。低音は軽めですが許容範囲です。' } },
      { stars: 3, date: '2026-06-30', variant: 'black', helpful: 68, verified: true,
        en: { name: 'Rie', title: 'Fine for music, terrible for calls', body: 'Music is acceptable. On calls, people say I sound like I am talking from inside a can, and the ENC makes my voice cut in and out. I use them only for listening.' },
        ja: { name: 'りえ', title: '音楽はまあまあ、通話は最悪', body: '音楽は許容範囲です。通話では「缶の中でしゃべっているみたい」と言われ、ENCのせいか声が途切れ途切れになるそうです。聞く専用にしています。' } },
      { stars: 2, date: '2026-05-25', variant: 'black', helpful: 59, verified: true,
        en: { name: 'Gamer_Yu', title: 'Too much delay for games and some videos', body: 'There is a clear delay: in games the sound comes after the action, and in some video apps the lip sync is off. The big video apps seem to correct for it, others do not.' },
        ja: { name: 'ゲーマーゆう', title: 'ゲームや動画には遅延が大きい', body: 'はっきり遅延があります。ゲームでは動きのあとに音が来るし、動画アプリによっては口の動きと声がずれます。大手の動画アプリは補正されるようですが、そうでないものもあります。' } },
      { stars: 5, date: '2026-04-18', variant: 'black', helpful: 31, verified: true,
        en: { name: 'Junko', title: 'Bought three for the kids', body: 'Three pairs for my children\'s online lessons. At this price I do not worry when they get dropped or lost. One case lid is a little loose, but they all work.' },
        ja: { name: 'じゅんこ', title: '子ども3人分購入', body: 'オンライン授業用に子ども3人分買いました。この値段なら落としてもなくしても気になりません。ケースのふたが1つ少しゆるいですが、全部問題なく使えています。' } },
      { stars: 3, date: '2026-09-21', variant: 'black', helpful: 44, verified: true,
        en: { name: 'Hayato', title: 'Then I tried Nami Buds 2', body: 'I used these for half a year and thought they were fine. Then I tried a friend\'s Nami Buds 2 with noise cancelling on the train, and the difference is huge. For the gym the VoltX are still OK, but for commuting, save up.' },
        ja: { name: 'はやと', title: 'ナミ Buds 2を試したら…', body: '半年使って十分だと思っていましたが、友人のナミ Buds 2を電車でノイキャンONにして試したら別物でした。ジム用ならボルトXでもいいですが、通勤用なら少し貯金してでもあちらを。' } },
      { stars: 1, date: '2026-03-15', variant: 'black', helpful: 76, verified: true,
        en: { name: 'Takahashi', title: 'Case stopped charging after five months', body: 'The case hinge got loose and then the case stopped charging the right bud. Five months in, so still under the 6-month warranty, but it took two messages and a week before BrightDeal sent the label.' },
        ja: { name: '高橋', title: 'ケースが5か月で充電できなくなった', body: 'ケースのヒンジがゆるくなり、そのうち右耳が充電されなくなりました。5か月だったので6か月保証の範囲内でしたが、ブライトディールから伝票が届くまでにメッセージ2回、1週間かかりました。' } },
      { stars: 4, date: '2026-07-08', variant: 'black', helpful: 23, verified: false,
        en: { name: 'Nina', title: 'Good, but the manual is hard to read', body: 'Works well for podcasts. The Japanese in the manual is odd and the reset steps were hard to follow; the product page explains it better (hold both earbuds for 10 seconds).' },
        ja: { name: 'にな', title: '使えるけど説明書が読みにくい', body: 'ポッドキャスト用には十分。説明書の日本語が不自然で、リセット方法がわかりにくかったです。商品ページの説明（両耳を10秒長押し）のほうがわかりやすい。' } },
      { stars: 2, date: '2026-09-27', variant: 'black', helpful: 49, verified: true,
        en: { name: 'Noboru', title: '"25H playtime" is misleading', body: 'The title says 25 hours, but that includes the case. At the volume I need on the bus, the earbuds last about 3.5 hours, then they go back in the case for an hour. Fine for short trips only.' },
        ja: { name: 'のぼる', title: '「25時間再生」は紛らわしい', body: 'タイトルは25時間ですが、ケース込みの数字です。バスの中で聞こえる音量だと単体で3.5時間ほどしか持たず、ケースで1時間充電しないといけません。短時間用です。' } },
    ],
    qa: [
      { date: '2026-07-14', votes: 63,
        en: { q: 'Do these have noise cancelling?', a: 'No active noise cancelling. ENC reduces background noise for the other person during calls only.', by: 'BrightDeal Trading' },
        ja: { q: 'ノイズキャンセリングは付いていますか？', a: 'アクティブノイズキャンセリングは搭載しておりません。ENCは通話時に相手側へ届く雑音を減らす機能です。', by: 'ブライトディール商事' } },
      { date: '2026-06-22', votes: 19,
        en: { q: 'Can I swim with them? IPX5 means waterproof, right?', a: 'Yes, IPX5 is waterproof. I use them in the pool.', by: 'Marketa customer (Ryo)' },
        ja: { q: '泳ぐときに使えますか？IPX5なら防水ですよね？', a: 'はい、IPX5は防水です。プールで使っています。', by: 'マルケタ購入者（りょう）' } },
      { date: '2026-08-05', votes: 44,
        en: { q: 'Is it safe to use them in the pool?', a: 'No. IPX5 only covers water jets and splashes, not going under water. Mine stopped working after one swim, and the seller said water damage is not covered.', by: 'Marketa customer (Mai)' },
        ja: { q: 'プールで使っても大丈夫ですか？', a: 'いいえ。IPX5は噴流や水しぶきへの耐性で、水中は対象外です。私のは一度泳いだだけで壊れ、出品者からは水濡れは保証対象外と言われました。', by: 'マルケタ購入者（まい）' } },
      { date: '2026-09-02', votes: 35,
        en: { q: 'Can I return them if I open the box and don\'t like them?', a: 'Change-of-mind returns are accepted within 30 days only if the box is unopened; the customer pays ¥880 return shipping. For faulty items, please message us and we will send a prepaid label within 2 business days.', by: 'BrightDeal Trading' },
        ja: { q: '開封して気に入らなかった場合、返品できますか？', a: 'お客様都合の返品は、未開封の場合のみ30日以内に承ります（返送料880円はお客様負担）。不良品の場合はメッセージでご連絡いただければ、2営業日以内に返送用伝票をお送りします。', by: 'ブライトディール商事' } },
      { date: '2026-05-09', votes: 12,
        en: { q: 'Do they work with iPhone?', a: 'Yes, they work with iPhone and Android over Bluetooth (SBC codec).', by: 'BrightDeal Trading' },
        ja: { q: 'iPhoneで使えますか？', a: 'はい、iPhone・AndroidともにBluetoothで接続できます（SBCコーデック）。', by: 'ブライトディール商事' } },
    ],
    similar: ['nami-buds', 'kaze-openear', 'seiran-headphones'],
    fbt: ['titancell-40k', 'ampora-slim-10k'],
    alsoViewed: ['nami-buds', 'kaze-openear', 'seiran-headphones', 'titancell-40k', 'ampora-slim-10k', 'drizzle-pro'],
  },
  {
    id: 'kaze-openear',
    cat: 'electronics',
    cluster: 'audio',
    brand: { en: 'Kaze', ja: 'カゼ' },
    seller: 'marketa',
    images: ['kaze-openear'],
    title: {
      en: 'Kaze Open-Ear Bone Conduction Headphones, Wireless Bluetooth 5.3, IP67 Waterproof, 29 g Titanium Band, 8 h Battery, Multipoint, for Running, Cycling and Work',
      ja: 'カゼ オープンイヤー 骨伝導ヘッドホン ワイヤレス Bluetooth5.3 IP67防水防塵 29g 軽量チタンフレーム 最大8時間再生 マルチポイント対応 ランニング サイクリング テレワーク KZ-OE1',
    },
    short: { en: 'Kaze Open-Ear Headphones', ja: 'カゼ 骨伝導ヘッドホン' },
    rating: 4.2,
    ratings: 876,
    hist: [60, 19, 8, 5, 8],
    added: '2025-05-22',
    badges: [],
    coupon: { amount: 1000, en: 'Save ¥1,000 with coupon', ja: '1,000円OFFクーポン' },
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'blue', name: { en: 'Blue', ja: 'ブルー' }, price: 9800, list: 12800, stock: 18, ship: 'fast' },
      { id: 'black', name: { en: 'Black', ja: 'ブラック' }, price: 9800, list: 12800, stock: 27, ship: 'fast' },
    ],
    returns: {
      en: 'Open-ear headphones have no hygiene seal, so they can be returned within 30 days of delivery: unused for a full refund, or opened in like-new condition with all accessories, including the magnetic charging cable, minus a 15% restocking fee (¥1,470) and ¥550 return shipping (free for paid Fast members). Defective units are returned free within 30 days; after that the 1-year Kaze warranty applies.',
      ja: 'オープンイヤー型のため衛生シールはなく、お届けから30日以内なら返品できます。未使用品は全額返金、開封済みの場合はマグネット充電ケーブルを含む付属品がすべてそろった新品同様の状態に限り、返品手数料15%（1,470円）と返送料550円（有料のFast会員は無料）を差し引いて返金します。初期不良は30日以内なら送料無料、その後はカゼの1年保証の対象です。',
    },
    bullets: {
      en: [
        'EARS STAY OPEN: sound travels through your cheekbones, so nothing goes in or over your ears and you still hear traffic, bicycle bells and people talking. Good for running, cycling and long days at a desk.',
        'IP67 DUST AND WATERPROOF: rinse off sweat under the tap and run in heavy rain. Not for swimming: Bluetooth does not work under water.',
        '29 G TITANIUM BAND: light, flexible and steady when you run. One size, for head circumferences of about 54–62 cm; works with glasses and most bike helmets.',
        '8 H BATTERY, MULTIPOINT: 8 hours per charge, full in 1.5 h; 10 minutes gives about 1.5 h. Connects to two devices at once (Bluetooth 5.3, SBC).',
        'MAGNETIC CHARGING CABLE: charges with the included magnetic cable (USB-A plug on the other end), not USB-C. This keeps the headphones sealed for IP67. Spare cables ¥1,280.',
        'NOT FOR NOISY PLACES: there is no noise cancelling, and at high volume people next to you can hear your music. 1-year Kaze warranty.',
      ],
      ja: [
        '【耳をふさがない】頬骨から振動で音を伝えるので、耳の穴にも耳の上にも何もかかりません。車の音や自転車のベル、人の声も聞こえたまま。ランニングやサイクリング、長時間のデスクワークに。',
        '【IP67防塵・防水】汗は水道で洗い流せて、大雨のランニングでも安心。ただし水中ではBluetoothが届かないため、水泳には使えません。',
        '【29gのチタンフレーム】軽くてしなやか、走ってもずれにくい設計。頭囲約54〜62cmのワンサイズで、メガネやほとんどの自転車用ヘルメットと併用できます。',
        '【8時間再生・マルチポイント】1回の充電で8時間、満充電1.5時間、10分の充電で約1.5時間使えます。2台同時接続に対応（Bluetooth 5.3、SBC）。',
        '【マグネット充電ケーブル】充電は付属の専用マグネットケーブル（反対側はUSB-A）で行います。USB-Cではありません。端子穴をなくしてIP67の防水性を確保しています。予備ケーブルは1,280円。',
        '【騒がしい場所には不向き】ノイズキャンセリングはなく、大音量では隣の人に音が聞こえることがあります。メーカー保証1年。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Kaze'], ['Model', 'KZ-OE1'], ['Type', 'Open-ear, bone conduction, behind-the-neck band'], ['Noise cancelling', 'No'],
        ['Battery', '8 h'], ['Charging', 'Proprietary magnetic cable (USB-A plug), full in about 1.5 h; 10 min gives about 1.5 h'],
        ['Bluetooth', '5.3, range about 10 m'], ['Codec', 'SBC'], ['Multipoint', 'Yes, 2 devices'],
        ['Water and dust resistance', 'IP67 (1 m for 30 min; not for swimming)'], ['Microphones', '2, with call noise reduction'],
        ['Controls', '3 buttons (volume up/down, multifunction)'], ['Fit', 'Head circumference about 54–62 cm'], ['Weight', '29 g'],
        ['Country of origin', 'China'], ['Warranty', '1 year (manufacturer)'],
        ['In the box', 'Headphones, magnetic charging cable (USB-A, 1 m), silicone pouch, foam earplugs, quick guide'],
      ],
      ja: [
        ['ブランド', 'カゼ'], ['型番', 'KZ-OE1'], ['タイプ', 'オープンイヤー・骨伝導・ネックバンド型'], ['ノイズキャンセリング', 'なし'],
        ['連続再生時間', '8時間'], ['充電', '専用マグネットケーブル（USB-A）、満充電約1.5時間／10分充電で約1.5時間再生'],
        ['Bluetooth', '5.3（通信距離約10m）'], ['対応コーデック', 'SBC'], ['マルチポイント', '対応（2台）'],
        ['防水・防塵性能', 'IP67（水深1mで30分。水泳には非対応）'], ['マイク', '2基、通話ノイズ低減機能付き'],
        ['操作', 'ボタン3つ（音量＋／−、マルチファンクション）'], ['対応頭囲', '約54〜62cm'], ['重量', '約29g'],
        ['原産国', '中国'], ['保証', 'メーカー保証1年'],
        ['付属品', 'ヘッドホン本体、マグネット充電ケーブル（USB-A、1m）、シリコンポーチ、耳栓、クイックガイド'],
      ],
    },
    compare: {
      en: ['Open-ear (bone conduction)', 'No (ears stay open)', '8 h', 'IP67 (dust-tight, waterproof)', '29 g', '1 year'],
      ja: ['オープンイヤー（骨伝導）', 'なし（耳をふさがない）', '8時間', 'IP67（防塵・防水）', '29g', '1年'],
    },
    description: {
      en: [
        'The Kaze Open-Ear sit just in front of your ears, on the cheekbones, and carry sound to the inner ear as vibration. Your ear canals stay open, so you hear cars, bicycles and announcements as usual. That makes them popular with runners and cyclists, with people who find earbuds painful, and with anyone who needs to hear a doorbell or a child while listening.',
        'The trade-offs: bass is lighter than with earbuds or over-ear headphones, and at the top few volume steps you may feel a tickling vibration. In quiet rooms, people sitting next to you can hear the sound at high volume, and on a noisy train you will struggle to hear podcasts because nothing blocks outside noise. Foam earplugs are included for when you want to shut out the world and listen only through the band.',
        'Charging uses a magnetic cable that clicks onto two contacts on the right ear hook, so there is no open port to let water in. The other end is USB-A: plug it into a USB-A charger, a computer, or a power bank such as the Ampora Slim 10K. To charge from a laptop with only USB-C ports, use a USB-C to USB-A adapter. Take the cable with you when you travel, because no other cable fits; spare cables cost ¥1,280 from Kaze support.',
        'Multipoint connects two devices at once, for example your phone and a work laptop. IP67 means the headphones survive 30 minutes under 1 m of fresh water, so rain, sweat and rinsing are fine, but they are not made for swimming. Whether you may cycle with headphones depends on local rules, so check before you ride. Kaze covers the headphones and cable for one year from purchase.',
      ],
      ja: [
        'カゼ オープンイヤーは耳の少し前、頬骨にあてて、振動で内耳に音を伝えるヘッドホンです。耳の穴をふさがないので、車や自転車、アナウンスもいつもどおり聞こえます。ランナーやサイクリストのほか、カナル型イヤホンで耳が痛くなる方、音楽を聴きながらインターホンや子どもの声に気づきたい方にも選ばれています。',
        '注意点：カナル型イヤホンやヘッドホンに比べて低音は軽めで、音量を最大近くまで上げると振動がくすぐったく感じることがあります。静かな部屋では大音量だと隣の人に音が聞こえ、騒がしい電車内では外の音を遮れないためポッドキャストが聞き取りにくくなります。外の音を遮って骨伝導だけで聞きたいときのために、耳栓が付属しています。',
        '充電は、右側の耳かけ部分にある2つの接点にマグネットでくっつく専用ケーブルで行います。端子穴がないので水が入りません。ケーブルの反対側はUSB-Aで、USB-A充電器やパソコン、「アンポラ Slim 10K」などのモバイルバッテリーにつなげます。USB-Cポートしかないノートパソコンから充電する場合は、USB-C→USB-A変換アダプターをご用意ください。他のケーブルでは充電できないので、旅行の際は必ずお持ちください。予備ケーブルはカゼのサポートで1,280円です。',
        'マルチポイントでスマホと仕事用ノートPCなど2台に同時接続できます。IP67は真水の水深1mに30分沈めても耐える性能で、雨・汗・水洗いは問題ありませんが、水泳用ではありません。自転車運転中のヘッドホン使用については地域のルールをご確認ください。メーカー保証は購入日から1年間（本体・ケーブル）です。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-12', variant: 'blue', helpful: 145, verified: true,
        en: { name: 'Ryo', title: 'Finally I can hear the bikes on the river path', body: 'I run along the Mirror River path most mornings. With earbuds I twice nearly got hit by cyclists I did not hear. With these I hear bells and footsteps and still have my podcast. They do not move even on the stone steps up to Springvale Castle. I have rinsed them under the tap after every run for four months with no problems.' },
        ja: { name: 'りょう', title: '川沿いで自転車の音が聞こえる', body: 'ほぼ毎朝、鏡川沿いの遊歩道を走っています。イヤホンだと後ろからの自転車に気づかず、2回ぶつかりそうになりました。これならベルや足音が聞こえて、ポッドキャストも聞けます。春川城の石段ダッシュでもずれません。4か月、毎回走った後に水道で洗っていますが問題なし。' } },
      { stars: 1, date: '2026-08-21', variant: 'black', helpful: 132, verified: true,
        en: { name: 'Satomi', title: 'Lost the cable, could not charge for a week', body: 'I left the magnetic cable at an inn in Moonview Spa, and nothing else charges these: not USB-C, not wireless. The spare cable was out of stock and took eight days to arrive. Please just use USB-C. Now I keep a spare in my bag.' },
        ja: { name: 'さとみ', title: 'ケーブルをなくして1週間充電できず', body: '月見温泉の旅館にマグネットケーブルを忘れてきたら、ほかに充電する方法がありません。USB-Cでもワイヤレスでもないので。予備ケーブルは在庫切れで、届くまで8日。素直にUSB-Cにしてほしいです。今は予備をカバンに入れています。' } },
      { stars: 2, date: '2026-07-30', variant: 'blue', helpful: 98, verified: true,
        en: { name: 'Kenta', title: 'Colleagues can hear my music', body: 'I bought these for the office so that I would notice when someone calls my name. They do that, but at more than half volume the person at the next desk could hear my music. In a quiet office you have to keep the volume low, and then the air conditioning is louder than the music.' },
        ja: { name: 'けんた', title: '隣の席に音が漏れる', body: '名前を呼ばれても気づけるようにと職場用に買いました。その目的は果たせますが、音量を半分以上にすると隣の席の人に音楽が聞こえていました。静かなオフィスでは音量を下げるしかなく、そうするとエアコンの音のほうが大きく聞こえます。' } },
      { stars: 4, date: '2026-06-08', variant: 'black', helpful: 64, verified: true,
        en: { name: 'Masumi', title: 'Great in rain, but not a swimming headset', body: 'Ran a half marathon in heavy rain and they were fine. I also tried them in the pool: they survived, but the sound stops as soon as your head goes under because Bluetooth does not travel through water. As the page says: rain and sweat yes, swimming no.' },
        ja: { name: 'ますみ', title: '雨は平気、でも水泳用ではない', body: '大雨のハーフマラソンでも問題ありませんでした。プールでも試してみましたが、壊れはしないものの頭が水に入るとBluetoothが届かず音が途切れます。説明どおり、雨や汗はOK、水泳はNGです。' } },
      { stars: 3, date: '2026-09-04', variant: 'blue', helpful: 71, verified: true,
        en: { name: 'Chika', title: 'Loose on my small head', body: 'I am 152 cm tall with a small head, and there is a gap between the band and my neck, so when I look up while running the band touches my collar and slides. Fine for walking. I wish there were a smaller size.' },
        ja: { name: 'ちか', title: '頭が小さいとゆるい', body: '身長152cmで頭も小さめです。バンドと首の間にすき間ができ、走りながら上を向くとバンドが襟に当たってずれます。歩くぶんには問題なし。小さいサイズがあればよかったです。' } },
      { stars: 5, date: '2026-08-15', variant: 'black', helpful: 55, verified: true,
        en: { name: 'Yuko', title: 'Fits my small head perfectly', body: 'I have a small head too (54 cm hat size) and they sit snugly, even with my glasses. Interesting how different our experiences are. Maybe it depends on the shape of the back of the head.' },
        ja: { name: 'ゆうこ', title: '小さい頭でもぴったり', body: '私も頭が小さい（帽子54cm）ですが、メガネをかけていてもしっかりフィットします。人によってこんなに違うのは不思議。後頭部の形によるのかもしれません。' } },
      { stars: 2, date: '2026-05-20', variant: 'black', helpful: 47, verified: true,
        en: { name: 'Takumi', title: 'Music sounds thin, and it tickles', body: 'Fine for podcasts and radio. For music the bass is weak, and when I turn it up to get more bass the band vibrates against my cheeks and tickles. If music quality matters to you, these are not the ones.' },
        ja: { name: 'たくみ', title: '音楽は物足りないし、くすぐったい', body: 'ポッドキャストやラジオなら十分。音楽だと低音が弱く、低音を求めて音量を上げるとこめかみ付近の振動がくすぐったくなります。音質重視の方には向きません。' } },
      { stars: 4, date: '2026-07-19', variant: 'blue', helpful: 39, verified: true,
        en: { name: 'Nao', title: 'Works under my bike helmet', body: 'They fit under my helmet without pressure. The other end of the cable is USB-A, so on rides I charge them from my Ampora Slim 10K power bank, which has a USB-A port. My work laptop only has USB-C, so I needed an adapter there.' },
        ja: { name: 'なお', title: '自転車のヘルメットの下でも使える', body: 'ヘルメットの下でも圧迫感なく使えます。ケーブルの反対側はUSB-Aなので、ライド中はUSB-Aポートのあるアンポラ Slim 10Kから充電しています。会社のノートPCはUSB-Cしかないので、変換アダプターが必要でした。' } },
      { stars: 1, date: '2026-09-26', variant: 'blue', helpful: 58, verified: true,
        en: { name: 'K. Mori', title: 'Left side went silent after seven months', body: 'After seven months of daily use, no sound at all from the left side. Kaze replaced the headphones under the 1-year warranty in 10 days. The replacement works, but for nearly ¥10,000 I expected them to last longer.' },
        ja: { name: '森', title: '7か月で左側が鳴らなくなった', body: '毎日使って7か月、左側から音が出なくなりました。1年保証で10日ほどで交換。交換品は問題ありませんが、1万円近くするのでもう少しもってほしかったです。' } },
      { stars: 5, date: '2026-06-27', variant: 'black', helpful: 43, verified: true,
        en: { name: 'Erika', title: 'For anyone whose ears hurt with earbuds', body: 'I bought the Nami Buds 2 first, but anything in my ear canal hurts after an hour. I could not return them because I had broken the hygiene seal, so my son has them now. These do not touch the ear canal at all and I wear them all afternoon.' },
        ja: { name: 'えりか', title: 'カナル型で耳が痛くなる人に', body: '先にナミ Buds 2を買いましたが、耳の穴に入れるものは1時間で痛くなります。衛生シールを開けたので返品できず、今は息子が使っています。こちらは耳の穴に何も入らないので、午後ずっとつけていられます。' } },
      { stars: 3, date: '2026-08-31', variant: 'blue', helpful: 26, verified: false,
        en: { name: 'Taiga', title: 'Calls are fine indoors, not on the bike', body: 'Indoors, callers say I sound clear. On the bike or on windy days they mostly hear wind. Probably the same with any headset.' },
        ja: { name: 'たいが', title: '通話は室内ならOK、自転車ではNG', body: '室内なら相手から声がクリアだと言われます。自転車や風の強い日は風の音ばかりだそうです。どのヘッドセットでも同じかもしれませんが。' } },
    ],
    qa: [
      { date: '2026-08-11', votes: 49,
        en: { q: 'Can I charge them with a USB-C cable?', a: 'No. They charge only with the included magnetic cable, which has a USB-A plug. Spare cables are ¥1,280 from Kaze support. A USB-C to USB-A adapter lets you use a USB-C charger or laptop.', by: 'Kaze Support' },
        ja: { q: 'USB-Cケーブルで充電できますか？', a: 'いいえ。付属の専用マグネットケーブル（USB-Aプラグ）でのみ充電できます。予備ケーブルはカゼのサポートで1,280円です。USB-C→USB-A変換アダプターを使えば、USB-C充電器やノートPCからも充電できます。', by: 'カゼ サポート' } },
      { date: '2026-07-02', votes: 33,
        en: { q: 'Can I swim with them?', a: 'We do not recommend it. They are rated IP67, so they survive 30 minutes at 1 m, but Bluetooth does not reach through water, so the sound cuts out as soon as your head goes under.', by: 'Kaze Support' },
        ja: { q: '水泳で使えますか？', a: 'おすすめしません。IP67なので水深1mで30分は耐えますが、Bluetoothは水中を通らないため、頭が水に入るとすぐに音が途切れます。', by: 'カゼ サポート' } },
      { date: '2026-09-18', votes: 27,
        en: { q: 'Can I return them after trying them? I know earbuds can\'t be returned once opened.', a: 'Yes. Open-ear headphones have no hygiene seal, so opened ones can be returned within 30 days in like-new condition with all accessories, minus a 15% restocking fee. Unused ones are refunded in full.', by: 'Marketa Customer Service' },
        ja: { q: '試したあとでも返品できますか？イヤホンは開封後返品できないと聞きました。', a: 'はい。オープンイヤー型には衛生シールがないため、開封後でも30日以内に付属品がすべてそろった新品同様の状態であれば、返品手数料15%を差し引いて返品を承ります。未使用品は全額返金です。', by: 'マルケタ カスタマーサービス' } },
      { date: '2026-06-14', votes: 21,
        en: { q: 'Do they work with glasses?', a: 'Yes, the band goes behind your ears under the arms of your glasses. With thick frames it presses a little after a few hours.', by: 'Marketa customer (Yoshi)' },
        ja: { q: 'メガネと一緒に使えますか？', a: 'はい、バンドはメガネのつるの下を通って耳の後ろにかかります。太いフレームだと数時間で少し圧迫感があります。', by: 'マルケタ購入者（よし）' } },
      { date: '2026-04-30', votes: 11,
        en: { q: 'Will they fit a child?', a: 'They are made for heads of 54–62 cm. My 10-year-old (about 52 cm) found them loose when running.', by: 'Marketa customer (Chika)' },
        ja: { q: '子どもでも使えますか？', a: '対応頭囲は54〜62cmです。10歳の子ども（約52cm）には走るとゆるいようでした。', by: 'マルケタ購入者（ちか）' } },
    ],
    similar: ['nami-buds', 'seiran-headphones', 'voltx-pods'],
    fbt: ['ampora-slim-10k', 'northpine-packable'],
    alsoViewed: ['nami-buds', 'seiran-headphones', 'voltx-pods', 'ampora-slim-10k', 'northpine-packable', 'yamabiko-storm'],
  },
];
