// Yuzu bath and body (Health & Beauty). Same shape as kettles.mjs.
export const cluster = {
  id: 'bath',
  compareRows: {
    en: ['Type', 'Size / amount', 'Scent', 'Key ingredients', 'Skin notes', 'Made in'],
    ja: ['種類', '内容量', '香り', '主な成分', '肌への注意', '原産国'],
  },
};

export default [
  {
    id: 'minori-bath-salts',
    cat: 'beauty',
    cluster: 'bath',
    brand: { en: 'Minori Yuzu Farm', ja: 'みのり柚子園' },
    seller: 'minori',
    images: ['minori-bath-salts'],
    title: {
      en: 'Minori Yuzu Farm Yuzu Bath Salts with Minori Bay Sea Salt and Real Yuzu Peel, No Colouring or Synthetic Fragrance, Resealable Pouch with Scoop, 500 g (about 16 baths) / 1 kg',
      ja: 'みのり柚子園 ゆずの湯 バスソルト みのり湾の海塩×柚子果皮 無着色 合成香料不使用 チャック付き袋 計量スプーン付き 500g（約16回分）/ 1kg 入浴剤 ギフト',
    },
    short: { en: 'Minori Yuzu Bath Salts', ja: 'みのり柚子園 ゆずバスソルト' },
    rating: 4.6,
    ratings: 1452,
    hist: [75, 15, 5, 2, 3],
    added: '2022-11-01',
    badges: ['choice'],
    coupon: { pct: 10, en: 'Save 10% with coupon', ja: '10%OFFクーポン' },
    variantLabel: { en: 'Size', ja: '内容量' },
    variants: [
      { id: '500g', name: { en: '500 g (about 16 baths)', ja: '500g（約16回分）' }, price: 1980, list: null, stock: 46, ship: 'fast' },
      { id: '1kg', name: { en: '1 kg (about 33 baths)', ja: '1kg（約33回分）' }, price: 3520, list: null, stock: 9, ship: 'fast' },
    ],
    returns: {
      en: 'Sold by Minori Yuzu Farm and shipped by Marketa, so Marketa\'s policy applies (not the farm\'s 14 days): unopened pouches can be returned within 30 days of delivery; opened bath products cannot be returned unless defective, damaged or the wrong item.',
      ja: 'みのり柚子園が販売し、マルケタが発送する商品のため、マルケタの返品規定が適用されます（農園の14日規定ではありません）。未開封品はお届けから30日以内なら返品可能、開封済みの入浴剤は不良・破損・誤配送の場合を除き返品できません。',
    },
    bullets: {
      en: [
        'THREE INGREDIENTS: sea salt from Minori Bay, fine yuzu peel powder and cold-pressed yuzu peel oil from our own orchard near Tsukimi Onsen. No colouring, no synthetic fragrance, no preservatives.',
        'ABOUT 16 BATHS PER 500 g: one level scoop (30 g, scoop included) for a 180–200 L bath. The 1 kg pouch makes about 33 baths, about ¥107 a bath instead of ¥124.',
        'A REAL YUZU SCENT, NOT A PERFUME: strongest as the salt dissolves, then softening after 15–20 minutes as the natural oil evaporates. It varies a little with each harvest.',
        'REHEATING (追い焚き) OK, but the fine peel powder collects in the circulation filter, so rinse the filter after use. NOT FOR 24-HOUR CIRCULATING BATHS, jetted baths or wooden (hinoki) tubs.',
        'SENSITIVE SKIN: yuzu peel oil can sting broken skin and cause redness in some people. Patch test on your inner arm first, and do not use on eczema, cuts or freshly shaved skin.',
        'SOLD BY MINORI YUZU FARM, SHIPPED BY MARKETA for next-day delivery. Opened bath products cannot be returned unless defective.',
      ],
      ja: [
        '【原料は3つだけ】みのり湾の海塩、自家農園（月見温泉近く）の柚子果皮パウダー、柚子果皮を低温圧搾した精油のみ。着色料・合成香料・保存料は使っていません。',
        '【500gで約16回分】180〜200Lのお湯に、付属スプーンすりきり1杯（30g）が目安。1kgは約33回分で、1回あたり約107円（500gは約124円）とお得です。',
        '【香水ではなく、本物の柚子の香り】香りがいちばん立つのは溶けはじめ。天然の精油は揮発するため、15〜20分ほどでやわらぎます。収穫年によって香りが少しずつ異なります。',
        '【追い焚きOK】ただし細かい果皮パウダーが循環口のフィルターにたまるため、ご使用後はフィルターを洗ってください。24時間風呂・ジェットバス・木製（檜）浴槽にはお使いいただけません。',
        '【肌が敏感な方へ】柚子果皮油は傷のある肌にしみたり、赤みが出たりすることがあります。はじめに腕の内側でパッチテストを。湿疹・傷・ムダ毛処理直後の肌にはお使いにならないでください。',
        '【販売：みのり柚子園／発送：マルケタ】翌日お届け対象です。開封済みの入浴剤は、不良品を除き返品できません。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Minori Yuzu Farm'], ['Product type', 'Bath salts (cosmetic)'], ['Contents', '500 g or 1 kg, resealable stand-up pouch'],
        ['Baths per pack', 'About 16 (500 g) / about 33 (1 kg) at 30 g per bath'], ['Amount per bath', '30 g (1 level scoop) for 180–200 L'],
        ['Full ingredients', 'Sea salt, Citrus junos peel powder, Citrus junos peel oil'], ['Scent', 'Yuzu, from the peel oil only (no added fragrance)'],
        ['Water colour', 'Stays clear, with a few fine peel flecks'], ['Free from', 'Colouring, synthetic fragrance, preservatives'],
        ['Reheating (追い焚き)', 'OK; rinse the circulation filter after use'], ['24-hour circulating bath', 'Not suitable'],
        ['Not suitable for', 'Jetted baths, wooden or natural-stone tubs; leftover water for laundry not recommended'],
        ['Shelf life', '2 years unopened; use within 6 months of opening'], ['Storage', 'Close the zip; keep out of the humid bathroom'],
        ['Country of origin', 'Japan (made at the farm, Minori Prefecture)'], ['In the box', 'Pouch of bath salts, 30 g scoop'],
      ],
      ja: [
        ['ブランド', 'みのり柚子園'], ['種類', '浴用化粧品（バスソルト）'], ['内容量', '500gまたは1kg（チャック付きスタンド袋）'],
        ['使用回数', '約16回（500g）／約33回（1kg）※1回30gの場合'], ['1回の使用量', '180〜200Lに30g（スプーンすりきり1杯）'],
        ['全成分', '海塩、ユズ果皮末、ユズ果皮油'], ['香り', '柚子（果皮油のみ、香料無添加）'],
        ['湯の色', '透明（細かい果皮の粒が少し浮きます）'], ['無添加', '着色料、合成香料、保存料'],
        ['追い焚き', '可（使用後に循環口のフィルターを洗浄）'], ['24時間風呂', '使用不可'],
        ['使用できないもの', 'ジェットバス、木製・天然石の浴槽。残り湯の洗濯への利用はおすすめしません'],
        ['使用期限', '未開封で製造から2年、開封後は6か月以内'], ['保管方法', 'チャックを閉め、湿気の多い浴室を避けて保管'],
        ['原産国', '日本（みのり県の自社農園で製造）'], ['付属品', 'バスソルト本体、30g計量スプーン'],
      ],
    },
    compare: {
      en: ['Bath salts (cosmetic)', '500 g (about 16 baths) / 1 kg (about 33)', 'Natural yuzu peel oil', 'Sea salt, yuzu peel powder, yuzu peel oil', 'Citrus oil can sting sensitive or broken skin', 'Japan'],
      ja: ['バスソルト（浴用化粧品）', '500g（約16回分）／1kg（約33回分）', '天然の柚子果皮油', '海塩、ユズ果皮末、ユズ果皮油', '柑橘の精油が敏感肌・傷にしみることあり', '日本'],
    },
    description: {
      en: [
        'The Hirose family has grown yuzu on the hillsides of the Kagami River valley, near Tsukimi Onsen, since 1978. After the juice is pressed for our ponzu and marmalade, the peel is cold-pressed for its oil, and what is left is dried and milled into a fine powder. We mix both with sea salt from Minori Bay at the farm. That is the whole recipe.',
        'How to use: add one level scoop (30 g, scoop included) to a 180–200 L bath and stir. The salt dissolves within a minute; the peel powder floats, then settles, so you may see a few flecks and a little grit at the bottom of the tub. The scent is strongest as the salt dissolves and softens after 15–20 minutes, because real citrus oil evaporates. Rinse the tub and any chrome fittings after draining so the salt does not leave marks.',
        'Reheating and bath equipment: you can reheat (追い焚き) with one-hole and two-hole systems, but the fine peel powder collects in the filter on the circulation port; pull it out and rinse it after the last bath of the day. Do not use it in 24-hour circulating baths, jetted baths, or wooden or natural-stone tubs, and we do not recommend using the leftover water for laundry. See the tables below.',
        'Skin: yuzu peel oil contains natural citrus compounds such as limonene, which can sting broken skin and cause redness in sensitive people. Patch test on your inner arm before the first bath, and do not use it on eczema, cuts, sunburn or freshly shaved skin. Children from 3 years can use half a scoop. Stop if your skin becomes red or itchy.',
        'Storage and returns: close the zip tightly and keep the pouch out of the bathroom. In humid weather the salt can set into a block, which you can break up with a spoon handle; the scent is not affected. Use within 6 months of opening for the best scent. The pouches are stored and shipped by Marketa, so they arrive the next day and follow Marketa\'s return policy: unopened within 30 days; opened only if defective or damaged.',
      ],
      ja: [
        '広瀬家は1978年から、月見温泉に近い鏡川の谷あいの斜面で柚子を育てています。ぽん酢やマーマレード用に果汁を搾ったあとの皮から精油を低温圧搾し、残りを乾燥させて細かい粉末に。それをみのり湾の海塩と農園で合わせました。原料はそれだけです。',
        '使い方：180〜200Lのお湯に付属スプーンすりきり1杯（30g）を入れ、よくかき混ぜてください。塩は1分ほどで溶けます。果皮パウダーは浮いたあと沈むため、浴槽の底に細かい粒やざらつきが少し残ることがあります。香りがいちばん立つのは溶けはじめで、天然の精油は揮発するため15〜20分ほどでやわらぎます。排水後は塩分の跡が残らないよう、浴槽やめっきの金具をすすいでください。',
        '追い焚きと浴槽の設備について：1つ穴・2つ穴とも追い焚きできますが、細かい果皮パウダーが循環口のフィルターにたまります。その日の最後の入浴後にフィルターを外して洗ってください。24時間風呂、ジェットバス、木製・天然石の浴槽ではお使いいただけません。残り湯の洗濯への利用もおすすめしません。詳しくは下の表をご覧ください。',
        '肌について：柚子果皮油にはリモネンなど柑橘の天然成分が含まれ、傷のある肌にしみたり、敏感な方は赤みが出たりすることがあります。初めての入浴の前に腕の内側でパッチテストをし、湿疹・傷・日焼け・ムダ毛処理直後の肌にはお使いにならないでください。3歳以上のお子さまはスプーン半分が目安です。赤みやかゆみが出たら使用を中止してください。',
        '保管と返品：チャックをしっかり閉め、浴室の外で保管してください。湿気の多い時期は塩が固まることがありますが、スプーンの柄などで砕けば問題なく使え、香りも変わりません。香りを楽しむため、開封後は6か月以内にお使いください。在庫はマルケタが保管・発送するため翌日お届けとなり、返品もマルケタの規定に準じます（未開封品は30日以内、開封品は不良・破損の場合のみ）。',
      ],
    },
    tables: [
      {
        title: { en: 'How much to use, and how many baths per pack', ja: '使用量の目安と使用回数' },
        en: [
          ['Bath water', 'Amount', '500 g pack', '1 kg pack'],
          ['150 L (compact tub)', '25 g (a little under 1 scoop)', 'About 20 baths', 'About 40 baths'],
          ['180–200 L (standard tub)', '30 g (1 level scoop)', 'About 16 baths', 'About 33 baths'],
          ['250 L (large tub)', '40 g (about 1⅓ scoops)', 'About 12 baths', 'About 25 baths'],
        ],
        ja: [
          ['お湯の量', '使用量', '500g', '1kg'],
          ['150L（コンパクト浴槽）', '25g（スプーン1杯弱）', '約20回', '約40回'],
          ['180〜200L（一般的な浴槽）', '30g（スプーンすりきり1杯）', '約16回', '約33回'],
          ['250L（大きめの浴槽）', '40g（スプーン約1と1/3杯）', '約12回', '約25回'],
        ],
      },
      {
        title: { en: 'Can I use it with my bath?', ja: 'お風呂の設備別 使用の可否' },
        en: [
          ['Bath or use', 'OK?', 'Notes'],
          ['Reheating (追い焚き), one- or two-hole', 'Yes', 'Rinse the circulation filter after the last bath of the day'],
          ['24-hour circulating bath', 'No', 'Peel clogs the filter; salt can damage the heater'],
          ['Jetted or bubble bath', 'No', 'Peel can block the jets'],
          ['Acrylic, FRP, enamel or stainless tub', 'Yes', 'Rinse after draining'],
          ['Wooden (hinoki) or natural-stone tub', 'No', 'Can stain, and salt soaks into the surface'],
          ['Leftover water for laundry', 'Not recommended', 'Salt and peel specks stay in fabric'],
        ],
        ja: [
          ['お風呂・用途', '可否', '備考'],
          ['追い焚き（1つ穴・2つ穴）', '可', 'その日の最後の入浴後に循環口のフィルターを洗ってください'],
          ['24時間風呂', '不可', '果皮でフィルターが詰まり、塩分でヒーターを傷めるおそれ'],
          ['ジェットバス・気泡浴', '不可', '果皮で噴出口が詰まるおそれ'],
          ['アクリル・FRP・ホーロー・ステンレス浴槽', '可', '排水後に浴槽をすすいでください'],
          ['木製（檜）・天然石の浴槽', '不可', 'しみや、塩分が染み込む原因になります'],
          ['残り湯の洗濯', 'おすすめしません', '塩分や果皮の粒が衣類に残ります'],
        ],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-26', variant: '500g', helpful: 142, verified: true,
        en: { name: 'Yumiko', title: 'Smells like the orchard, not like perfume', body: 'The moment the salt hits the water the bathroom smells like peeling a fresh yuzu. No colour, no candy smell. I come out warm right down to my toes and stay warm until bed.' },
        ja: { name: 'ゆみこ', title: '香水ではなく、柚子畑の香り', body: 'お湯に入れた瞬間、浴室じゅうが柚子の皮をむいたときのような香りに。色も甘ったるい香りもありません。つま先まで温まり、寝るまでぽかぽかが続きます。' } },
      { stars: 2, date: '2026-08-19', variant: '1kg', helpful: 176, verified: true,
        en: { name: 'Osamu', title: 'Peel bits clog the bath filter', body: 'We reheat (追い焚き) every evening. After a week the filter on the circulation port was coated in a brown paste of peel powder and the reheat had become noticeably weaker. Now I clean the filter after every bath, which the pouch does mention in small print. Lovely scent, but a chore if you reheat.' },
        ja: { name: '修', title: '果皮の粉が風呂のフィルターに詰まる', body: '毎晩追い焚きをしています。1週間で循環口のフィルターに茶色い果皮の粉がべったりつき、追い焚きの効きが明らかに弱くなりました。今は毎回フィルターを掃除しています（袋の小さな注意書きにも書いてありました）。香りは良いのですが、追い焚きする家庭には手間です。' } },
      { stars: 1, date: '2026-07-23', variant: '500g', helpful: 98, verified: true,
        en: { name: 'Kana', title: 'Red, itchy legs after the first bath', body: 'I have sensitive skin and had shaved my legs that morning. After 15 minutes my legs were stinging, and that night I had red, itchy patches that took two days to settle. My husband is fine with it. Because the pouch was opened, I could not return it. Patch test first, and do not use it after shaving.' },
        ja: { name: 'かな', title: '初回で脚が赤くかゆくなりました', body: '敏感肌で、その日の朝に脚のムダ毛処理をしていました。15分ほどで脚がピリピリし、夜には赤いかゆみが出て、治まるまで2日かかりました。夫は平気です。開封済みなので返品できませんでした。まずパッチテストを、そして処理した日は使わないことをおすすめします。' } },
      { stars: 2, date: '2026-06-15', variant: '500g', helpful: 87, verified: true,
        en: { name: 'Ayaka', title: 'Scent fades in ten minutes', body: 'Gorgeous for the first five or ten minutes, then I could barely smell it, and whoever bathes second gets almost nothing. The Yumeguri Tsukimi Onsen powder I used before lasted the whole evening. Real yuzu oil seems to evaporate fast.' },
        ja: { name: 'あやか', title: '香りが10分で消える', body: '最初の5〜10分はとても良い香りですが、その後はほとんど分からなくなり、2番目に入る家族はほぼ無香。以前使っていた湯めぐりの月見温泉の入浴剤は一晩中香っていました。天然の柚子油はすぐ揮発するようです。' } },
      { stars: 4, date: '2026-09-01', variant: '1kg', helpful: 64, verified: true,
        en: { name: 'Shigeru', title: 'Scent is gentle; the warmth is the point', body: 'Some say the scent fades. It does get softer, but I can still smell it at the end of a 20-minute soak, and what matters to me is that I stay warm afterwards. It is real yuzu, not an air freshener, so it does not shout. The 1 kg is the better buy.' },
        ja: { name: '茂', title: '香りは控えめ。温まるのが本題', body: '香りがすぐ消えるという声もありますが、やわらぐだけで、20分浸かっていても最後までほんのり香ります。大事なのは湯冷めしないこと。芳香剤ではなく本物の柚子なので主張しすぎないのが良い。1kgのほうがお得です。' } },
      { stars: 5, date: '2026-03-08', variant: '500g', helpful: 51, verified: true,
        en: { name: 'Noriko', title: 'I alternate it with the Yumeguri powder', body: 'Yuzu salts on weekdays, Yumeguri Tsukimi Onsen packets at the weekend for the milky green onsen feel. Both are fine with our reheat as long as I rinse the filter on salt days.' },
        ja: { name: 'のりこ', title: '湯めぐりの入浴剤と交互に', body: '平日は柚子のバスソルト、週末はにごり湯気分を楽しみたいので湯めぐりの月見温泉。塩の日にフィルターを洗えば、どちらも追い焚きで問題なく使えています。' } },
      { stars: 3, date: '2026-07-02', variant: '1kg', helpful: 46, verified: true,
        en: { name: 'Taro', title: 'Turned into a block in the humid bathroom', body: 'I kept the pouch on the bathroom shelf with the zip half closed. In the rainy season it set into one hard lump and I had to break it up with a spoon handle. The scent is still fine. Keep it outside the bathroom and close the zip properly.' },
        ja: { name: '太郎', title: '湿気の多い浴室で固まった', body: 'チャックを半分開けたまま浴室の棚に置いていたら、梅雨時にひとつの硬い塊になり、スプーンの柄で砕きました。香りは問題なし。浴室の外に置いて、チャックはきちんと閉めましょう。' } },
      { stars: 5, date: '2026-02-11', variant: '500g', helpful: 38, verified: true,
        en: { name: 'Megumi', title: 'A gift with the hand cream', body: 'I sent the 500 g with a Minori Yuzu Farm hand cream to my mother in Sapporo, with free noshi paper. She loved both and asked where to buy more. Well packed.' },
        ja: { name: 'めぐみ', title: 'ハンドクリームと一緒に贈り物に', body: '500gをみのり柚子園のハンドクリームと一緒に、札幌の母へ贈りました（のしは無料）。どちらもとても気に入って、どこで買えるのか聞かれました。梱包も丁寧でした。' } },
      { stars: 3, date: '2026-05-18', variant: '500g', helpful: 57, verified: true,
        en: { name: 'Kazuhiko', title: '16 baths? About 12 in our big tub', body: 'Our tub takes about 250 L, so I use a heaped scoop, and the 500 g lasted 12 baths. Not misleading exactly (it says 30 g for 200 L), but work out your own cost per bath. The scent and warmth are great.' },
        ja: { name: 'かずひこ', title: '16回分？うちの大きな浴槽では約12回', body: 'うちの浴槽は約250Lなので山盛り1杯入れていて、500gで12回でした。「200Lに30g」と書いてあるので誤解を招くとまでは言いませんが、1回あたりの値段は自分で計算したほうがいいです。香りと温まり方は最高。' } },
      { stars: 4, date: '2026-08-29', variant: '1kg', helpful: 34, verified: true,
        en: { name: 'Emi', title: 'Fine with our reheat if you rinse the filter', body: 'I disagree a little with the filter complaints. We reheat every night too, and I just pull out the filter and rinse it under the shower after the last person gets out. Thirty seconds. No problems in four months.' },
        ja: { name: 'えみ', title: 'フィルターを流せば追い焚きも問題なし', body: 'フィルターの件、少し反論です。うちも毎晩追い焚きしますが、最後の人が出たあとにフィルターを外してシャワーで流すだけ、30秒です。4か月使って問題ありません。' } },
      { stars: 2, date: '2026-09-14', variant: '1kg', helpful: 29, verified: true,
        en: { name: 'Hiroshi', title: 'Peel leaves a ring in the tub', body: 'The fine peel powder sinks and leaves a yellow-brown ring at the water line and grit at the bottom of the tub. It wipes off, but I want a bath additive I do not have to clean up after. It also left salt marks on the chrome tap.' },
        ja: { name: '浩', title: '浴槽に果皮の輪じみ', body: '細かい果皮の粉が沈んで、水面の位置に黄茶色の輪ができ、浴槽の底もざらつきます。拭けば落ちますが、後片付けの要らない入浴剤がいいです。めっきの蛇口に塩の跡も残りました。' } },
      { stars: 5, date: '2025-12-22', variant: '500g', helpful: 66, verified: true,
        en: { name: 'Sachiko', title: 'Yuzu bath all winter, not just on the solstice', body: 'We have always had a yuzu bath on the winter solstice. This year we have had one every night in December. I tried the farm\'s ponzu as well, and it is excellent too.' },
        ja: { name: '幸子', title: '冬至だけでなく冬じゅう柚子湯', body: '冬至には毎年柚子湯にしていましたが、今年は12月中ずっと楽しんでいます。同じ農園のぽん酢も買いましたが、こちらも絶品。' } },
    ],
    qa: [
      { date: '2026-04-20', votes: 58,
        en: { q: 'Can I use it with reheating (追い焚き)? What about a 24-hour bath?', a: 'Reheating: yes, with one-hole and two-hole systems. At the normal amount the salt will not harm the boiler, but the fine peel powder collects in the filter on the circulation port, so please rinse it after the last bath of the day. 24-hour circulating baths: no. The peel clogs their filtration and the salt can damage the heater.', by: 'Minori Yuzu Farm' },
        ja: { q: '追い焚きはできますか？24時間風呂ではどうですか？', a: '追い焚きは1つ穴・2つ穴とも可能です。通常の使用量なら塩分で風呂釜を傷めることはありませんが、細かい果皮パウダーが循環口のフィルターにたまるため、その日の最後の入浴後に洗ってください。24時間風呂ではお使いいただけません。果皮でろ過装置が詰まり、塩分でヒーターを傷めるおそれがあります。', by: 'みのり柚子園' } },
      { date: '2026-06-03', votes: 33,
        en: { q: 'Can I use the leftover bath water for laundry?', a: 'We do not recommend it. Salt can stay in the fabric and the peel powder can leave small specks on clothes. Use fresh water for washing.', by: 'Minori Yuzu Farm' },
        ja: { q: '残り湯を洗濯に使えますか？', a: 'おすすめしません。塩分が衣類に残ったり、果皮の細かい粒がついたりすることがあります。洗濯には水道水をお使いください。', by: 'みのり柚子園' } },
      { date: '2026-08-07', votes: 26,
        en: { q: 'Is it OK for children?', a: 'Our two (4 and 7) have used it all winter with no problems. We use half a scoop when they bathe first.', by: 'Marketa customer (Ayumi)' },
        ja: { q: '子どもも使えますか？', a: 'うちの子（4歳と7歳）は冬の間ずっと使っていて問題ありません。子どもが先に入るときはスプーン半分にしています。', by: 'マルケタ購入者（あゆみ）' } },
      { date: '2026-09-09', votes: 21,
        en: { q: 'If I open the 1 kg and do not like the scent, can I return it?', a: 'This item is shipped from Marketa, so Marketa\'s policy applies: unopened pouches can be returned within 30 days of delivery, but once opened, bath products can be returned only if defective or damaged. If you are unsure about the scent, we suggest trying the 500 g first.', by: 'Minori Yuzu Farm' },
        ja: { q: '1kgを開封して香りが好みでなかった場合、返品できますか？', a: 'こちらはマルケタから発送される商品のため、マルケタの返品規定が適用されます。未開封ならお届けから30日以内に返品できますが、開封後の入浴剤は不良・破損の場合のみとなります。香りが心配な方は、まず500gでお試しください。', by: 'みのり柚子園' } },
      { date: '2026-01-15', votes: 17,
        en: { q: 'Does it change the colour of the water?', a: 'No. The water stays clear, with a few tiny flecks of peel floating at first.', by: 'Marketa customer (Noriko)' },
        ja: { q: 'お湯の色は変わりますか？', a: '変わりません。透明なままで、最初に細かい果皮の粒が少し浮く程度です。', by: 'マルケタ購入者（のりこ）' } },
    ],
    similar: ['minori-hand-cream', 'yumeguri-onsen-powder', 'citrine-body-wash'],
    fbt: ['minori-hand-cream', 'minori-marmalade-set'],
    alsoViewed: ['yumeguri-onsen-powder', 'minori-hand-cream', 'citrine-body-wash', 'minori-marmalade-set', 'minori-ponzu-set', 'shiroshita-senbei'],
  },
  {
    id: 'minori-hand-cream',
    cat: 'beauty',
    cluster: 'bath',
    brand: { en: 'Minori Yuzu Farm', ja: 'みのり柚子園' },
    seller: 'minori',
    images: ['minori-hand-cream'],
    title: {
      en: 'Minori Yuzu Farm Yuzu Hand Cream with Shea Butter, Squalane and Yuzu Seed Oil, Scented Only with Yuzu Peel Oil, No Synthetic Fragrance, Made in Japan, 40 g / 80 g Tube',
      ja: 'みのり柚子園 ゆず ハンドクリーム シアバター スクワラン 柚子種子油 天然柚子の香り 合成香料不使用 日本製 40g / 80g 保湿 手荒れ ギフト',
    },
    short: { en: 'Minori Yuzu Hand Cream', ja: 'みのり柚子園 ゆずハンドクリーム' },
    rating: 4.4,
    ratings: 987,
    hist: [65, 19, 8, 4, 4],
    added: '2023-10-16',
    badges: [],
    coupon: null,
    variantLabel: { en: 'Size', ja: '内容量' },
    variants: [
      { id: '40g', name: { en: '40 g tube', ja: '40g チューブ' }, price: 1320, list: null, stock: 38, ship: 'fast' },
      { id: '80g', name: { en: '80 g tube', ja: '80g チューブ' }, price: 2200, list: null, stock: 7, ship: 'fast' },
    ],
    returns: {
      en: 'Sold by Minori Yuzu Farm and shipped by Marketa, so Marketa\'s policy applies: unopened tubes can be returned within 30 days of delivery; opened cosmetics cannot be returned unless defective, damaged or the wrong item.',
      ja: 'みのり柚子園が販売し、マルケタが発送する商品のため、マルケタの返品規定が適用されます。未開封品はお届けから30日以内なら返品可能、開封済みの化粧品は不良・破損・誤配送の場合を除き返品できません。',
    },
    bullets: {
      en: [
        'RICH, LONG-LASTING MOISTURE: shea butter, squalane, rice bran oil and oil pressed from the seeds of our own yuzu, for hands that dry and crack in winter or after frequent washing.',
        'SCENTED ONLY WITH YUZU PEEL OIL: no synthetic fragrance. Fresh and slightly bitter when you apply it, fading to a faint trace in 20–30 minutes.',
        'A LITTLE GOES A LONG WAY: a pea-sized amount (about 0.5 g) covers both hands. It feels slightly oily for the first few minutes, so use less during the day and more at night.',
        'NOT FOR BROKEN SKIN: citrus peel oil can sting cuts and cracks and may cause redness on sensitive skin. Patch test first.',
        'TWO SIZES: 40 g (about 80 uses) fits a coat pocket; 80 g (about 160 uses) works out at ¥27.50 a gram instead of ¥33. Both are under 100 mL for carry-on bags on international flights.',
        'SOLD BY MINORI YUZU FARM, SHIPPED BY MARKETA for next-day delivery. Opened cosmetics cannot be returned unless defective.',
      ],
      ja: [
        '【しっとり長続きする保湿】シアバター、スクワラン、コメヌカ油に、自家農園の柚子の種から搾った油を配合。冬の乾燥や、手洗いの多い毎日で荒れた手に。',
        '【香りは柚子果皮油だけ】合成香料は使っていません。塗った瞬間はみずみずしくほろ苦い柚子の香り。20〜30分でほのかな香りに変わります。',
        '【少量でしっかり】小豆粒大（約0.5g）で両手に十分。塗ってから数分はややしっとり感が残るため、日中は少なめ、夜はたっぷりがおすすめです。',
        '【傷のある肌には使わないでください】柑橘の精油は切り傷やひび割れにしみたり、敏感肌に赤みが出たりすることがあります。はじめにパッチテストを。',
        '【2つのサイズ】40g（約80回分）はポケットに入るサイズ。80g（約160回分）は1gあたり27.5円と、40g（33円）よりお得です。どちらも100mL未満で、国際線の機内持ち込みも可能です。',
        '【販売：みのり柚子園／発送：マルケタ】翌日お届け対象です。開封済みの化粧品は、不良品を除き返品できません。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Minori Yuzu Farm'], ['Product type', 'Hand cream (cosmetic)'], ['Contents', '40 g or 80 g aluminium tube with flip cap'],
        ['Uses per tube', 'About 80 (40 g) / about 160 (80 g) at 0.5 g each'], ['Texture', 'Rich cream; slightly oily for a few minutes'],
        ['Scent', 'Yuzu peel oil (no synthetic fragrance)'], ['Key ingredients', 'Shea butter, squalane, yuzu seed oil, rice bran oil'],
        ['Full ingredients', 'Water, Glycerin, Shea butter, Squalane, Butylene glycol, Cetearyl alcohol, Citrus junos seed oil, Glyceryl stearate, Behenyl alcohol, Rice bran oil, Citrus junos peel oil, Tocopherol, Xanthan gum, Phenoxyethanol'],
        ['Free from', 'Synthetic fragrance, colouring, parabens, mineral oil, silicones'], ['Animal-derived ingredients', 'None; not tested on animals'],
        ['Skin notes', 'Patch test first; may sting cuts and cracks'], ['Shelf life', '3 years unopened; use within 6 months of opening'],
        ['Tube size', '40 g: 12.5 × 3.5 cm; 80 g: 15 × 4.5 cm'], ['Country of origin', 'Japan (made in Minori Prefecture)'], ['In the box', 'Tube in a paper carton'],
      ],
      ja: [
        ['ブランド', 'みのり柚子園'], ['種類', 'ハンドクリーム（化粧品）'], ['内容量', '40gまたは80g（アルミチューブ、ワンタッチキャップ）'],
        ['使用回数', '約80回（40g）／約160回（80g）※1回0.5gの場合'], ['テクスチャー', '濃厚なクリーム。塗布後数分はしっとり感が残ります'],
        ['香り', '柚子果皮油（合成香料不使用）'], ['主な成分', 'シア脂、スクワラン、ユズ種子油、コメヌカ油'],
        ['全成分', '水、グリセリン、シア脂、スクワラン、BG、セテアリルアルコール、ユズ種子油、ステアリン酸グリセリル、ベヘニルアルコール、コメヌカ油、ユズ果皮油、トコフェロール、キサンタンガム、フェノキシエタノール'],
        ['無添加', '合成香料、着色料、パラベン、鉱物油、シリコーン'], ['動物由来成分', '不使用（動物実験なし）'],
        ['肌への注意', '使用前にパッチテストを。傷やひび割れにしみることがあります'], ['使用期限', '未開封で3年、開封後は6か月以内'],
        ['チューブサイズ', '40g：12.5×3.5cm／80g：15×4.5cm'], ['原産国', '日本（みのり県で製造）'], ['付属品', 'チューブ本体（紙箱入り）'],
      ],
    },
    compare: {
      en: ['Hand cream', '40 g / 80 g tube', 'Natural yuzu peel oil', 'Shea butter, squalane, yuzu seed oil', 'Rich texture; may sting cracked skin', 'Japan'],
      ja: ['ハンドクリーム', '40g／80g チューブ', '天然の柚子果皮油', 'シア脂、スクワラン、ユズ種子油', '濃厚なテクスチャー。ひび割れにしみることあり', '日本'],
    },
    description: {
      en: [
        'A rich hand cream made with oil pressed from the seeds of the yuzu we grow above the Kagami River, together with shea butter, squalane and rice bran oil. It is made for hands that dry out and crack in winter, from washing up, frequent hand washing or cold wind.',
        'Scent: the only scent is yuzu peel oil from our own fruit. It smells fresh and slightly bitter, like the peel itself rather than sweets, and fades to a faint trace in 20–30 minutes. It varies a little from one harvest to the next. If you want a scent that lasts for hours, this is not that kind of cream.',
        'How to use: squeeze out a pea-sized amount (about 0.5 g) and rub it in well, including between the fingers and over the knuckles. It feels slightly oily for the first few minutes, so during the day use a little less and wait a moment before touching your phone or paper. At night, a thicker layer under cotton gloves works well for cracked knuckles.',
        'Skin: citrus peel oil can sting cuts and open cracks and may cause redness on sensitive skin. Before the first use, patch test on the inside of your arm and wait 24 hours, and do not apply it to broken skin. If you have eczema, ask a dermatologist first.',
        'Sizes and returns: both tubes contain the same cream. The 40 g fits a coat pocket; the 80 g is better value and lasts about three months with daily use. Use within 6 months of opening. Sold by Minori Yuzu Farm and shipped by Marketa: unopened tubes can be returned within 30 days; opened cosmetics only if defective or damaged.',
      ],
      ja: [
        '鏡川を見下ろす自家農園の柚子の種から搾った油に、シアバター、スクワラン、コメヌカ油を合わせた濃厚なハンドクリームです。冬の水仕事やこまめな手洗い、冷たい風で乾燥し、ひび割れがちな手のために作りました。',
        '香り：香りづけは自家農園の柚子果皮油のみ。お菓子のような甘さではなく、皮そのもののみずみずしくほろ苦い香りで、20〜30分ほどでほのかな残り香になります。収穫年によって香りが少し異なります。何時間も香りが続くタイプのクリームではありません。',
        '使い方：小豆粒大（約0.5g）を取り、指の間や関節まで丁寧になじませてください。塗ってから数分はしっとり感が残るため、日中は少なめにし、スマートフォンや書類に触れる前に少し時間を置くのがおすすめです。夜はたっぷり塗って綿の手袋をすると、関節のひび割れのケアに効果的です。',
        '肌について：柑橘の精油は切り傷やひび割れにしみたり、敏感な肌に赤みが出たりすることがあります。初めて使う前に腕の内側でパッチテストをして24時間様子を見て、傷のある部分には塗らないでください。湿疹のある方は、皮膚科医にご相談のうえお使いください。',
        'サイズと返品：40g・80gとも中身は同じです。40gはコートのポケットに入るサイズ、80gはお得で、毎日使って約3か月もちます。開封後は6か月以内にお使いください。みのり柚子園が販売し、マルケタが発送します。未開封品は30日以内なら返品可能、開封済みの化粧品は不良・破損の場合のみ返品できます。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-23', variant: '40g', helpful: 121, verified: true,
        en: { name: 'Ritsuko', title: 'Real yuzu, not sweets', body: 'It smells like the inside of a yuzu peel, slightly bitter and fresh, not like sweets. It fits in my coat pocket. My hands crack every winter from washing up, and this has kept them smooth so far this autumn.' },
        ja: { name: '律子', title: 'お菓子ではなく、本物の柚子', body: '柚子の皮の内側のような、ほろ苦くてさわやかな香りで、甘ったるさはありません。コートのポケットに入る大きさ。毎年冬は水仕事で手がひび割れますが、この秋はこれのおかげで今のところすべすべです。' } },
      { stars: 2, date: '2026-09-05', variant: '80g', helpful: 109, verified: true,
        en: { name: 'Jiro', title: 'Too greasy for work', body: 'I use it at my desk, and for 15 minutes afterwards I leave greasy fingerprints on my phone screen, keyboard and paperwork. When I use less, my hands feel dry again an hour later. Fine at night, not at the office.' },
        ja: { name: '次郎', title: '仕事中には油っぽすぎる', body: 'デスクで使うと、そのあと15分はスマホの画面やキーボード、書類に指の跡がべったり。量を減らすと1時間後にはまた乾燥します。夜用ならいいですが、仕事中は無理です。' } },
      { stars: 4, date: '2026-08-28', variant: '40g', helpful: 87, verified: true,
        en: { name: 'Misaki', title: 'Not greasy if you use a pea-sized amount', body: 'I think the "greasy" reviewers use too much. A pea-sized dab rubbed in well is absorbed in a couple of minutes and I can type straight after. One star off because the scent is gone within half an hour.' },
        ja: { name: 'みさき', title: '小豆粒くらいならべたつかない', body: '油っぽいという方は量が多いのでは。小豆粒くらいをよくなじませれば2〜3分で浸透し、すぐにキーボードも打てます。香りが30分ももたないので星ひとつ減。' } },
      { stars: 1, date: '2026-07-11', variant: '40g', helpful: 93, verified: true,
        en: { name: 'Takako', title: 'Stung my cracked fingers badly', body: 'I work in a restaurant kitchen and my fingertips crack in winter. The first time I used this it stung the cracks so badly that I had to wash it off, and the skin around them went red. Probably the citrus oil. It was opened, so I could not return it. Do not buy it for cracked hands, which is exactly what I bought it for.' },
        ja: { name: '貴子', title: 'ひび割れにひどくしみた', body: '飲食店の厨房で働いていて、冬は指先がひび割れます。初めて塗ったとき割れたところがひどくしみて洗い流すほどで、まわりも赤くなりました。柑橘の精油のせいだと思います。開封済みなので返品不可。まさにひび割れ用に買ったのに、ひび割れには向きませんでした。' } },
      { stars: 2, date: '2026-06-22', variant: '80g', helpful: 58, verified: true,
        en: { name: 'Noa', title: 'Lovely scent that lasts 20 minutes', body: 'I bought it for the scent, and it is gone in 20 minutes. It is a fine moisturiser, but at this price I wanted the yuzu to last. The Citrine Lab body wash smells stronger and for longer, although that one is clearly perfume.' },
        ja: { name: 'のあ', title: '香りが20分しかもたない', body: '香りが目当てで買いましたが、20分で消えてしまいます。保湿クリームとしては普通に良いけれど、この値段なら柚子の香りがもっと続いてほしい。シトリンラボのボディソープのほうが強く長く香りますが、あちらは明らかに香料の香りです。' } },
      { stars: 5, date: '2026-01-29', variant: '80g', helpful: 66, verified: true,
        en: { name: 'Fumi', title: 'A winter essential', body: 'My third tube. I put on a thick layer at night with cotton gloves and my knuckles no longer crack. The 80 g lasts me about three months.' },
        ja: { name: 'ふみ', title: '冬の必需品', body: '3本目です。夜にたっぷり塗って綿の手袋をして寝ると、指の関節のひび割れがなくなりました。80gで約3か月もちます。' } },
      { stars: 3, date: '2026-05-09', variant: '40g', helpful: 31, verified: true,
        en: { name: 'Sho', title: 'Good cream, flimsy cap', body: 'The hinge of the flip cap cracked after a month in my pocket, and now it pops open in my bag. The cream itself is nice.' },
        ja: { name: '翔', title: 'クリームは良いがキャップがもろい', body: 'ポケットに入れて1か月でキャップのヒンジが割れ、カバンの中で開いてしまいます。クリーム自体は良いです。' } },
      { stars: 5, date: '2026-02-18', variant: '40g', helpful: 27, verified: true,
        en: { name: 'Yoshie', title: 'A little yuzu set for myself', body: 'I bought the 40 g with the Minori Yuzu Bath Salts. A bath, then this cream, and I go to bed smelling of yuzu. Although it is the farm\'s product, both arrived the next day in one box from Marketa.' },
        ja: { name: 'よしえ', title: '自分用の小さな柚子セット', body: 'みのり柚子園のバスソルトと一緒に40gを購入。お風呂のあとにこのクリームを塗ると、柚子の香りに包まれて眠れます。農園の商品ですが、マルケタから翌日に1つの箱でまとめて届きました。' } },
      { stars: 4, date: '2026-08-10', variant: '80g', helpful: 22, verified: true,
        en: { name: 'Gen', title: 'The 80 g is better value', body: 'It works out at ¥27.50 a gram against ¥33 for the 40 g. I keep the big tube by the sink. Four stars because the aluminium tube dents and is hard to squeeze out at the end.' },
        ja: { name: 'げん', title: '80gのほうがお得', body: '1gあたり27.5円で、40gの33円よりお得。大きいチューブは洗面台に置いています。アルミチューブがへこんで最後のほうは絞り出しにくいので星4つ。' } },
      { stars: 1, date: '2026-09-30', variant: '80g', helpful: 15, verified: true,
        en: { name: 'Kyoko', title: 'Came out runny and separated', body: 'The first squeeze was clear oil followed by thin, runny cream. Maybe it got hot in transit. Marketa refunded it as defective without any trouble, but I have not reordered.' },
        ja: { name: '京子', title: '分離してゆるくなっていた', body: '最初に絞ると透明な油が出て、そのあとゆるいクリームが出てきました。配送中に高温になったのかもしれません。マルケタが不良品としてすぐ返金してくれましたが、再注文はしていません。' } },
    ],
    qa: [
      { date: '2026-03-14', votes: 44,
        en: { q: 'Does it contain synthetic fragrance?', a: 'No. The scent comes only from the oil pressed from our own yuzu peel, so it is lighter and fades sooner than perfumed creams, and it varies slightly between harvests.', by: 'Minori Yuzu Farm' },
        ja: { q: '合成香料は入っていますか？', a: '入っていません。香りは自家農園の柚子の皮から搾った精油のみのため、香料入りのクリームより軽く、早く消えます。収穫年によって香りが少し異なります。', by: 'みのり柚子園' } },
      { date: '2026-07-19', votes: 31,
        en: { q: 'Is it OK for eczema or badly cracked hands?', a: 'Shea butter and squalane protect dry skin, but citrus peel oil can sting open cracks and irritate eczema. Please patch test on the inside of your arm for 24 hours and avoid broken skin. If you have eczema, please ask a dermatologist first.', by: 'Minori Yuzu Farm' },
        ja: { q: '湿疹やひどいひび割れにも使えますか？', a: 'シアバターとスクワランが乾燥した肌を守りますが、柑橘の精油はひび割れにしみたり、湿疹を刺激したりすることがあります。腕の内側で24時間パッチテストをし、傷のある部分には塗らないでください。湿疹のある方は、まず皮膚科医にご相談ください。', by: 'みのり柚子園' } },
      { date: '2026-05-26', votes: 23,
        en: { q: 'Can I take it on a plane?', a: 'Yes. Both sizes are under 100 mL, so they are fine in carry-on bags even on international flights (put it in the clear plastic bag at security).', by: 'Marketa customer (Ritsuko)' },
        ja: { q: '飛行機に持ち込めますか？', a: 'はい。どちらのサイズも100mL未満なので、国際線でも機内に持ち込めます（保安検査では透明の袋に入れてください）。', by: 'マルケタ購入者（律子）' } },
      { date: '2026-09-03', votes: 12,
        en: { q: 'Is it vegan? Is it tested on animals?', a: 'It contains no animal-derived ingredients and we do not test on animals. It is not certified vegan.', by: 'Minori Yuzu Farm' },
        ja: { q: 'ヴィーガン対応ですか？動物実験はしていますか？', a: '動物由来の成分は使用しておらず、動物実験も行っていません。ただし、ヴィーガン認証は取得していません。', by: 'みのり柚子園' } },
      { date: '2026-08-15', votes: 9,
        en: { q: 'Is the cream in the 40 g and 80 g tubes the same?', a: 'Yes, only the tube size is different.', by: 'Marketa customer (Gen)' },
        ja: { q: '40gと80gで中身は同じですか？', a: 'はい、チューブの大きさが違うだけです。', by: 'マルケタ購入者（げん）' } },
    ],
    similar: ['minori-bath-salts', 'yumeguri-onsen-powder', 'citrine-body-wash'],
    fbt: ['minori-bath-salts', 'citrine-body-wash'],
    alsoViewed: ['minori-bath-salts', 'citrine-body-wash', 'yumeguri-onsen-powder', 'minori-marmalade-set', 'minori-ponzu-set', 'kagami-mug-pair'],
  },
  {
    id: 'yumeguri-onsen-powder',
    cat: 'beauty',
    cluster: 'bath',
    brand: { en: 'Yumeguri', ja: '湯めぐり' },
    seller: 'marketa',
    images: ['yumeguri-onsen-powder'],
    title: {
      en: 'Yumeguri Tsukimi Onsen Medicated Bath Powder (Quasi-Drug), Milky Green, Sodium Bicarbonate Spring Type, Forest Scent, 25 g Single-Use Packets, Box of 12 / 24',
      ja: '湯めぐり 月見温泉 薬用入浴剤 医薬部外品 にごり湯 若草色 炭酸水素塩泉タイプ 森の香り 25g 分包 12包 / 24包 疲労回復 冷え症 肩こり',
    },
    short: { en: 'Yumeguri Tsukimi Onsen Bath Powder', ja: '湯めぐり 月見温泉 入浴剤' },
    rating: 4.3,
    ratings: 2880,
    hist: [58, 24, 9, 4, 5],
    added: '2021-09-01',
    badges: ['bestseller'],
    coupon: null,
    variantLabel: { en: 'Pack', ja: '入数' },
    variants: [
      { id: '12', name: { en: '12 packets', ja: '12包' }, price: 1100, list: null, stock: 64, ship: 'fast' },
      { id: '24', name: { en: '24 packets', ja: '24包' }, price: 1980, list: null, stock: 31, ship: 'fast' },
    ],
    returns: {
      en: 'Unopened boxes can be returned within 30 days of delivery. Opened bath products cannot be returned unless defective, damaged in delivery or the wrong item.',
      ja: '未開封品はお届けから30日以内なら返品できます。開封済みの入浴剤は、不良・配送中の破損・誤配送の場合を除き返品できません。',
    },
    bullets: {
      en: [
        'TSUKIMI ONSEN-STYLE BATH AT HOME: recreates the main components of Tsukimi Onsen\'s soft sodium bicarbonate spring with sodium bicarbonate and sodium sulfate. It does not contain real spring water.',
        'MEDICATED (QUASI-DRUG): approved effects include relief of fatigue, stiff shoulders, lower-back pain, feeling cold, rough skin, heat rash and chilblains (full list in the specifications).',
        'MILKY GREEN, FOREST SCENT: turns the water an opaque soft green with a hinoki-and-green-leaf fragrance. The colour is for atmosphere; the real Tsukimi Onsen spring is clear.',
        'ONE PACKET PER BATH: 25 g single-use packets for 150–200 L. 12 packets is about ¥92 a bath, 24 packets about ¥83.',
        'REHEATING (追い焚き) OK; NOT FOR 24-HOUR CIRCULATING BATHS. Contains no sulfur, so it does not corrode boilers. Do not use in wooden or natural-marble tubs.',
        'SOLD BY MARKETA. Unopened boxes can be returned within 30 days; opened bath products are not returnable unless defective.',
      ],
      ja: [
        '【おうちで月見温泉気分】やわらかな湯ざわりで知られる月見温泉の炭酸水素塩泉の主成分を、炭酸水素ナトリウムと硫酸ナトリウムで再現しました。温泉水は含まれていません。',
        '【薬用入浴剤（医薬部外品）】疲労回復、肩のこり、腰痛、冷え症、荒れ性、あせも、しもやけなどに（効能・効果の全文は仕様欄をご覧ください）。',
        '【若草色のにごり湯・森の香り】お湯がやわらかな乳白緑色になり、檜と若葉をイメージした森の香りが広がります。色は雰囲気を楽しむためのもので、実際の月見温泉は無色透明です。',
        '【1回1包】25gの分包で、150〜200Lのお湯に1包。12包なら1回約92円、24包なら約83円です。',
        '【追い焚きOK・24時間風呂は不可】硫黄を含まないため、風呂釜を傷めません。木製（檜）や天然大理石の浴槽にはお使いいただけません。',
        '【マルケタ販売】未開封品は30日以内なら返品可能です。開封済みの入浴剤は、不良品を除き返品できません。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Yumeguri'], ['Product type', 'Medicated bath powder (quasi-drug, 医薬部外品)'], ['Contents', '25 g × 12 or 24 packets'],
        ['Amount per bath', '1 packet for 150–200 L at 38–41 °C'], ['Active ingredients', 'Sodium bicarbonate, dried sodium sulfate'],
        ['Other ingredients', 'Dextrin, titanium dioxide, silica, fragrance, Yellow 202(1), Blue 1'],
        ['Effects', 'Fatigue, stiff shoulders, lower-back pain, feeling cold, neuralgia, rheumatism, haemorrhoids, bruises, sprains, heat rash, eczema, rough skin, chapped and cracked skin, chilblains, acne, coldness before and after childbirth'],
        ['Water colour', 'Milky green (opaque)'], ['Scent', 'Forest (hinoki and green leaves), synthetic fragrance'],
        ['Reheating (追い焚き)', 'OK (one-hole and two-hole types)'], ['24-hour circulating bath', 'Not suitable'],
        ['Not suitable for', 'Wooden tubs, natural marble, jetted baths'], ['Leftover water', 'OK for the laundry wash cycle; rinse with fresh water'],
        ['Shelf life', '3 years unopened; use an opened packet the same day'], ['Country of origin', 'Japan'], ['In the box', '12 or 24 packets in a paper box'],
      ],
      ja: [
        ['ブランド', '湯めぐり'], ['種類', '薬用入浴剤（医薬部外品）'], ['内容量', '25g×12包または24包'],
        ['1回の使用量', '150〜200L（38〜41℃）に1包'], ['有効成分', '炭酸水素ナトリウム、乾燥硫酸ナトリウム'],
        ['その他の成分', 'デキストリン、酸化チタン、無水ケイ酸、香料、黄202(1)、青1'],
        ['効能・効果', '疲労回復、肩のこり、腰痛、冷え症、神経痛、リウマチ、痔、うちみ、くじき、あせも、湿しん、荒れ性、ひび、あかぎれ、しもやけ、にきび、産前産後の冷え症'],
        ['湯の色', '若草色のにごり湯'], ['香り', '森の香り（檜と若葉）、香料使用'],
        ['追い焚き', '可（1つ穴・2つ穴とも）'], ['24時間風呂', '使用不可'],
        ['使用できないもの', '木製浴槽、天然大理石、ジェットバス'], ['残り湯', '洗濯の「洗い」に使用可（すすぎは水道水で）'],
        ['使用期限', '未開封で3年、開封した分包はその日のうちに使用'], ['原産国', '日本'], ['付属品', '分包12包または24包（紙箱入り）'],
      ],
    },
    compare: {
      en: ['Bath powder (quasi-drug)', '25 g × 12 or 24 packets', 'Forest (synthetic fragrance)', 'Sodium bicarbonate, sodium sulfate', 'Contains dye and fragrance; not for wooden tubs', 'Japan'],
      ja: ['薬用入浴剤（医薬部外品）', '25g×12包／24包', '森の香り（香料）', '炭酸水素ナトリウム、硫酸ナトリウム', '色素・香料を含む。木製浴槽不可', '日本'],
    },
    description: {
      en: [
        'Tsukimi Onsen, at the end of the HaruTetsu Kagami Line, is known for its soft, slightly slippery water, a sodium bicarbonate spring often called a "bath for beautiful skin". Yumeguri\'s bath powder recreates its main components at home with sodium bicarbonate and sodium sulfate. It does not contain any spring water from Tsukimi Onsen.',
        'The water turns an opaque milky green, with a forest scent of hinoki and green leaves. Both are added for atmosphere; the real spring is clear and almost odourless. As a medicated bath powder (quasi-drug), its effects on fatigue, stiff shoulders, lower-back pain, feeling cold and rough skin are approved by Japan\'s health ministry; the full list is in the specifications.',
        'How to use: tear open one packet, add it to 150–200 L of water at 38–41 °C and stir. Soak for 10–15 minutes. The tear notch is small; with wet hands, scissors are easier. Rinse the tub soon after draining, as the milky ingredients can leave a faint white film.',
        'Bath equipment: it contains no sulfur, so you can reheat (追い焚き) with one-hole and two-hole systems. Do not use it in 24-hour circulating baths or jetted baths, or in wooden or natural-marble tubs, which it can stain. Leftover water can be used for the laundry wash cycle, but rinse with fresh water and do not use it for wool, silk or white clothes.',
        'Cautions: stop using it if your skin becomes red or itchy, and consult a doctor. Babies and small children should bathe only with an adult; for babies under 1 year, ask your doctor first. Do not drink it. Unopened boxes can be returned within 30 days of delivery; opened boxes only if defective or damaged.',
      ],
      ja: [
        '春川鉄道 鏡線の終点にある月見温泉は、少しとろみのあるやわらかなお湯で知られる炭酸水素塩泉で、「美肌の湯」とも呼ばれています。湯めぐりの入浴剤は、その主成分を炭酸水素ナトリウムと硫酸ナトリウムでご家庭向けに再現しました。月見温泉の温泉水は含まれていません。',
        'お湯は若草色のにごり湯になり、檜と若葉をイメージした森の香りが広がります。色と香りは雰囲気を楽しむためのもので、実際の源泉は無色透明でほとんど香りはありません。薬用入浴剤（医薬部外品）として、疲労回復、肩のこり、腰痛、冷え症、荒れ性などの効能・効果が認められています。全文は仕様欄をご覧ください。',
        '使い方：分包を1包開け、38〜41℃・150〜200Lのお湯に入れてよくかき混ぜてください。10〜15分ほどの入浴がおすすめです。切り口が小さいため、手が濡れているときははさみを使うと簡単です。にごり成分がうっすら白く残ることがあるので、排水後は早めに浴槽をすすいでください。',
        '浴槽の設備について：硫黄を含まないため、1つ穴・2つ穴とも追い焚きできます。24時間風呂、ジェットバス、木製（檜）や天然大理石の浴槽では、しみの原因になるためお使いいただけません。残り湯は洗濯の「洗い」には使えますが、すすぎは水道水で。ウール・シルク・白い衣類には使わないでください。',
        '使用上の注意：肌に赤みやかゆみが出た場合は使用を中止し、医師にご相談ください。乳幼児は必ず大人と一緒に入浴し、1歳未満の赤ちゃんは事前に医師にご相談ください。飲用はできません。未開封品はお届けから30日以内なら返品できますが、開封済みのものは不良・破損の場合のみとなります。',
      ],
    },
    tables: [
      {
        title: { en: 'Cost per bath (bath additives on Marketa)', ja: '1回あたりの価格（マルケタ取り扱いの入浴剤）' },
        en: [
          ['Product', 'Price', 'Baths', 'Per bath'],
          ['Yumeguri, 12 packets', '¥1,100', '12', 'About ¥92'],
          ['Yumeguri, 24 packets', '¥1,980', '24', 'About ¥83'],
          ['Minori Yuzu Bath Salts, 500 g', '¥1,980', 'About 16', 'About ¥124'],
          ['Minori Yuzu Bath Salts, 1 kg', '¥3,520', 'About 33', 'About ¥107'],
        ],
        ja: [
          ['商品', '価格', '回数', '1回あたり'],
          ['湯めぐり 12包', '1,100円', '12回', '約92円'],
          ['湯めぐり 24包', '1,980円', '24回', '約83円'],
          ['みのり柚子園 ゆずバスソルト 500g', '1,980円', '約16回', '約124円'],
          ['みのり柚子園 ゆずバスソルト 1kg', '3,520円', '約33回', '約107円'],
        ],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-28', variant: '24', helpful: 205, verified: true,
        en: { name: 'Masako', title: 'The closest thing to Tsukimi Onsen at home', body: 'I grew up near Tsukimi Onsen, and this brings back the soft, slightly slippery feel of the water. My skin feels smooth afterwards and my shoulders loosen up. The 24-packet box works out at ¥83 a bath.' },
        ja: { name: '雅子', title: '家で味わう月見温泉', body: '月見温泉の近くで育ちましたが、あのとろっとやわらかいお湯の感じを思い出します。上がったあとは肌がすべすべで、肩のこりもほぐれます。24包なら1回83円ほどです。' } },
      { stars: 2, date: '2026-08-12', variant: '12', helpful: 133, verified: true,
        en: { name: 'Kenji', title: 'It is not real onsen water', body: 'From the name I assumed it contained water or minerals from Tsukimi Onsen. Read the box: it "recreates" the components with baking soda and sodium sulfate, plus dye and perfume. And the real spring is clear, not green. A pleasant enough bath powder, but the name oversells it.' },
        ja: { name: '健二', title: '本物の温泉ではありません', body: '名前から月見温泉のお湯か成分が入っていると思っていました。箱をよく読むと、重曹と硫酸ナトリウムで成分を「再現」したもので、色素と香料入り。そもそも本物の月見温泉は透明で、緑色ではありません。入浴剤としては悪くないけれど、名前が大げさです。' } },
      { stars: 4, date: '2026-07-27', variant: '24', helpful: 71, verified: true,
        en: { name: 'Asuka', title: 'Not the real thing, and it never claims to be', body: 'The box clearly says it recreates the spring\'s components; nowhere does it say spring water. As a bath powder it is good value, it warms me up, and the colour is fun. Just do not expect Tsukimi Onsen itself.' },
        ja: { name: 'あすか', title: '本物とは言っていないし、それで十分', body: '箱には「成分を再現」とはっきり書いてあって、温泉水とはどこにも書いていません。入浴剤としてはお得で、よく温まるし色も楽しい。月見温泉そのものを期待しなければ満足です。' } },
      { stars: 1, date: '2026-06-08', variant: '24', helpful: 88, verified: true,
        en: { name: 'Isao', title: 'Stained our hinoki tub', body: 'We used it in our wooden tub. After a month the wood had a grey-green tinge along the water line that will not come out. The back of the box does say "not for wooden tubs" in small print, but it should be on the front.' },
        ja: { name: '勲', title: '檜の浴槽にしみが', body: '木の浴槽で使っていたら、1か月で水面の位置に灰緑色のしみがつき、取れなくなりました。箱の裏に小さく「木製浴槽には使用しないでください」と書いてありますが、表に書いてほしかった。' } },
      { stars: 2, date: '2026-05-16', variant: '12', helpful: 76, verified: true,
        en: { name: 'Rina', title: 'Smells like air freshener', body: 'The "forest" scent is strong and artificial, like a car air freshener, and it hangs around the bathroom until the next morning. If you like natural scents, this is not for you.' },
        ja: { name: 'りな', title: '芳香剤のようなにおい', body: '「森の香り」は強くて人工的で、車の芳香剤のよう。翌朝まで浴室に残ります。自然な香りが好きな方には向きません。' } },
      { stars: 5, date: '2026-04-02', variant: '24', helpful: 39, verified: true,
        en: { name: 'Takumi', title: 'Gentle scent, not overpowering', body: 'I am sensitive to perfume and was worried after reading about the smell, but to me it is soft and woody, and it is gone once the bath is drained. Everyone\'s nose is different, I suppose.' },
        ja: { name: 'たくみ', title: '香りはやさしく、強すぎない', body: '香料に敏感なので「におう」というレビューで心配しましたが、私にはやわらかい木の香りで、お湯を抜けば残りません。感じ方は人それぞれですね。' } },
      { stars: 3, date: '2026-03-22', variant: '12', helpful: 44, verified: true,
        en: { name: 'Sanae', title: 'Packets are hard to tear with wet hands', body: 'The notch is tiny, and with wet hands I end up fetching scissors. Once or twice the powder sprayed across the floor. Fine product otherwise.' },
        ja: { name: '早苗', title: '濡れた手では袋が開けにくい', body: '切り口が小さく、手が濡れているとはさみを取りに行くことに。1〜2回、粉が床に飛び散りました。それ以外は良い商品です。' } },
      { stars: 5, date: '2026-01-18', variant: '24', helpful: 52, verified: true,
        en: { name: 'Hideo', title: 'My feet stay warm until morning', body: 'My feet are always cold in winter. After a 15-minute soak with this I fall asleep with warm feet. It works fine with our reheat.' },
        ja: { name: '秀夫', title: '朝まで足がぽかぽか', body: '冬はいつも足が冷えます。これを入れて15分浸かると、足が温かいまま眠れます。追い焚きでも問題なく使えています。' } },
      { stars: 4, date: '2026-08-30', variant: '24', helpful: 47, verified: true,
        en: { name: 'Kumiko', title: 'Cheaper per bath than the yuzu salts', body: 'I also like the Minori Yuzu Bath Salts, but they come to about ¥124 a bath in the 500 g size against ¥83 for these, and these do not leave peel in the reheat filter. Salts for a treat, these for every day.' },
        ja: { name: '久美子', title: '柚子のバスソルトより1回あたりが安い', body: 'みのり柚子園のバスソルトも好きですが、500gだと1回約124円、こちらは83円。しかも追い焚きのフィルターに果皮がたまりません。ご褒美の日はバスソルト、普段はこちらにしています。' } },
      { stars: 1, date: '2026-07-04', variant: '12', helpful: 61, verified: true,
        en: { name: 'Ken', title: 'Made my skin itchy', body: 'The box lists eczema among its effects, but my arms and back became itchy after the second bath, so I stopped. Maybe it is the fragrance or the dye. Check the ingredients if you have sensitive skin.' },
        ja: { name: 'けん', title: '肌がかゆくなった', body: '箱には効能に「湿しん」とありますが、2回目の入浴後に腕と背中がかゆくなり、使うのをやめました。香料か色素のせいかもしれません。敏感肌の方は成分を確認してください。' } },
      { stars: 4, date: '2026-09-10', variant: '24', helpful: 21, verified: true,
        en: { name: 'Yasu', title: 'Fine with our reheat; leaves a slight film', body: 'Used it with the reheat for half a year without problems. The milky colour leaves a faint white film in the tub if you do not rinse it straight after draining. I wash with the Citrine Lab yuzu and hinoki body wash first, and the two scents clash a little.' },
        ja: { name: 'やす', title: '追い焚きOK。うっすら白い膜が残る', body: '追い焚きで半年使って問題なし。排水後すぐにすすがないと、浴槽にうっすら白い膜が残ります。先にシトリンラボのゆず＆ひのきのボディソープで洗っていますが、香りが少しぶつかります。' } },
      { stars: 5, date: '2025-11-20', variant: '12', helpful: 18, verified: true,
        en: { name: 'Mum of two', title: 'The kids love the green', body: 'My kids (5 and 8) call it the "matcha bath" and get in without arguing. We bought the 12 to see if they liked it; ordering the 24 next.' },
        ja: { name: 'ふたりのママ', title: '子どもたちが緑色のお湯に大喜び', body: '5歳と8歳の子どもたちが「抹茶風呂」と呼んで、文句を言わずに入ってくれます。気に入るか試しに12包を買いましたが、次は24包にします。' } },
    ],
    qa: [
      { date: '2026-02-20', votes: 71,
        en: { q: 'Does it contain real Tsukimi Onsen water?', a: 'No. It contains no spring water. It recreates the main components of Tsukimi Onsen\'s sodium bicarbonate spring (sodium bicarbonate and sodium sulfate) so the water feels soft and smooth. The milky green colour and forest scent are added for atmosphere; the real spring is clear.', by: 'Yumeguri Customer Support' },
        ja: { q: '本物の月見温泉のお湯が入っていますか？', a: 'いいえ、温泉水は含まれていません。月見温泉の炭酸水素塩泉の主成分（炭酸水素ナトリウム・硫酸ナトリウム）を再現し、やわらかくなめらかな湯ざわりにしています。若草色と森の香りは雰囲気づくりのためで、実際の源泉は無色透明です。', by: '湯めぐり お客様相談室' } },
      { date: '2026-05-05', votes: 48,
        en: { q: 'Can I use it with reheating (追い焚き)? With a 24-hour bath?', a: 'Reheating: yes, with one-hole and two-hole systems. It contains no sulfur or other ingredients that corrode the boiler. 24-hour circulating baths: no, because the powder can clog their filters. Please also follow your bathtub maker\'s instructions.', by: 'Yumeguri Customer Support' },
        ja: { q: '追い焚きはできますか？24時間風呂は？', a: '追い焚きは1つ穴・2つ穴ともご使用いただけます。硫黄など風呂釜を傷める成分は含まれていません。24時間風呂は、粉末でフィルターが詰まるおそれがあるためご使用いただけません。浴槽・給湯器メーカーの取扱説明書もあわせてご確認ください。', by: '湯めぐり お客様相談室' } },
      { date: '2026-07-14', votes: 29,
        en: { q: 'Can I use the leftover water for laundry?', a: 'Yes, for the wash cycle; please use fresh water for the final rinse. Do not use it for wool, silk or white clothes, as the dye can tint them.', by: 'Yumeguri Customer Support' },
        ja: { q: '残り湯を洗濯に使えますか？', a: '「洗い」にはお使いいただけます。すすぎは水道水で行ってください。色素で色がつくことがあるため、ウール・シルク・白い衣類には使わないでください。', by: '湯めぐり お客様相談室' } },
      { date: '2026-08-25', votes: 22,
        en: { q: 'Can my 4-month-old baby bathe in it?', a: 'Yes, it is a quasi-drug, so it is safe for everyone from birth. We use it for our baby.', by: 'Marketa customer (Yuta)' },
        ja: { q: '生後4か月の赤ちゃんも入れますか？', a: '大丈夫です。医薬部外品なので、生まれたときから誰でも安全です。うちも赤ちゃんと一緒に使っています。', by: 'マルケタ購入者（ゆうた）' } },
      { date: '2026-09-02', votes: 35,
        en: { q: 'From what age can children use it?', a: 'From about 1 year, always with an adult in the bath. For babies under 1 year, please ask your doctor first. Being a quasi-drug means its effects are approved, not that it suits every skin, so please correct the earlier answer: stop if your child\'s skin becomes red or itchy.', by: 'Yumeguri Customer Support' },
        ja: { q: '何歳から使えますか？', a: '1歳ごろから、必ず大人と一緒にご入浴ください。1歳未満の赤ちゃんは、事前に医師にご相談ください。医薬部外品とは効能・効果が認められているという意味で、どなたの肌にも合うという意味ではありません（上の回答は誤りです）。肌に赤みやかゆみが出たら使用を中止してください。', by: '湯めぐり お客様相談室' } },
    ],
    similar: ['minori-bath-salts', 'minori-hand-cream', 'citrine-body-wash'],
    fbt: ['minori-bath-salts', 'citrine-body-wash'],
    alsoViewed: ['minori-bath-salts', 'citrine-body-wash', 'minori-hand-cream', 'shiroshita-senbei', 'minori-marmalade-set', 'tsukimi-trail-women'],
  },
  {
    id: 'citrine-body-wash',
    cat: 'beauty',
    cluster: 'bath',
    brand: { en: 'Citrine Lab', ja: 'シトリンラボ' },
    seller: 'marketa',
    images: ['citrine-body-wash'],
    title: {
      en: 'Citrine Lab Yuzu & Hinoki Body Wash, Amino-Acid Cleanser, Sulfate-Free, Weakly Acidic, Moisturising, 480 mL Pump Bottle / 400 mL Refill / Pump + 2 Refills',
      ja: 'シトリンラボ ボディソープ ゆず＆ひのきの香り アミノ酸系 サルフェートフリー 弱酸性 保湿 本体480mL / 詰め替え400mL / 本体＋詰め替え2個セット',
    },
    short: { en: 'Citrine Lab Yuzu & Hinoki Body Wash', ja: 'シトリンラボ ボディソープ ゆず＆ひのき' },
    rating: 4.2,
    ratings: 1640,
    hist: [57, 22, 10, 5, 6],
    added: '2024-06-10',
    badges: [],
    coupon: { amount: 200, en: 'Save ¥200 with coupon', ja: '200円OFFクーポン' },
    variantLabel: { en: 'Size', ja: 'タイプ' },
    variants: [
      { id: 'pump', name: { en: '480 mL pump bottle', ja: '本体 480mL' }, price: 1480, list: null, stock: 52, ship: 'fast' },
      { id: 'refill', name: { en: '400 mL refill pouch', ja: '詰め替え用 400mL' }, price: 980, list: null, stock: 73, ship: 'fast' },
      { id: 'set', name: { en: 'Pump + 2 refills', ja: '本体＋詰め替え2個' }, price: 3180, list: null, stock: 8, ship: 'fast' },
    ],
    returns: {
      en: 'Unopened items can be returned within 30 days of delivery. Opened toiletries cannot be returned unless defective, damaged in delivery or the wrong item; in the set, each bottle and pouch counts separately.',
      ja: '未開封品はお届けから30日以内なら返品できます。開封済みのトイレタリー用品は、不良・配送中の破損・誤配送の場合を除き返品できません。セットの場合は、本体・詰め替えをそれぞれ1点として扱います。',
    },
    bullets: {
      en: [
        'GENTLE AMINO-ACID CLEANSERS: washes with mild amino-acid surfactants instead of sulfates (no SLS or SLES) and is weakly acidic, close to skin, so it leaves skin less tight than ordinary body soap.',
        'YUZU & HINOKI SCENT: a fresh citrus top note over a soft cypress-wood base. The scent is synthetic fragrance; yuzu fruit extract and hinoki water are included for skin conditioning, not for scent.',
        'LESS FOAM, BY DESIGN: amino-acid washes lather less than sulfate soaps. Two pumps on a body towel or foaming net give a soft, fine lather.',
        'THREE WAYS TO BUY: 480 mL pump bottle (about 2 months for one person), 400 mL refill pouch (¥245 per 100 mL), or the pump with 2 refills (1,280 mL, ¥260 less than buying them separately).',
        'FREE FROM sulfates, silicones, parabens and colouring. Contains fragrance; if you react to perfumes, patch test first. For adults and children from 3 years.',
        'MADE IN JAPAN, sold and shipped by Marketa. Opened toiletries cannot be returned unless defective; unopened ones within 30 days.',
      ],
      ja: [
        '【やさしいアミノ酸系洗浄成分】硫酸系洗浄成分（ラウリル硫酸Na・ラウレス硫酸Na）を使わず、マイルドなアミノ酸系洗浄成分で洗います。肌と同じ弱酸性で、一般的なボディソープより洗い上がりのつっぱり感が少なめです。',
        '【ゆず＆ひのきの香り】みずみずしい柑橘のトップノートから、やわらかな檜の香りへ。香りは香料によるものです。ユズ果実エキスとヒノキ水は肌を整える目的で配合しており、香りづけのためではありません。',
        '【泡立ちはひかえめ】アミノ酸系は硫酸系の石けんより泡立ちが控えめです。ボディタオルや泡立てネットに2プッシュで、きめ細かくやわらかな泡になります。',
        '【3つの買い方】本体480mL（1人で約2か月）、詰め替え400mL（100mLあたり245円）、本体＋詰め替え2個（計1,280mL、別々に買うより260円お得）。',
        '【無添加】サルフェート・シリコーン・パラベン・着色料不使用。香料を含むため、香料で肌が荒れやすい方はパッチテストを。大人と3歳以上のお子さまに。',
        '【日本製・マルケタ販売】開封済みのトイレタリー用品は、不良品を除き返品できません（未開封品は30日以内なら返品可）。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Citrine Lab'], ['Product type', 'Body wash (cosmetic)'], ['Contents', '480 mL pump bottle / 400 mL refill pouch / 480 mL pump + 2 × 400 mL refills'],
        ['Cleansing base', 'Amino-acid surfactants (sulfate-free)'], ['pH', 'Weakly acidic (about 6)'], ['Scent', 'Yuzu & hinoki (synthetic fragrance)'],
        ['Full ingredients', 'Water, Sodium lauroyl methylaminopropionate, Cocamidopropyl betaine, Sodium cocoyl glutamate, Glycerin, Polyglyceryl-10 laurate, Citrus junos fruit extract, Chamaecyparis obtusa water, Butylene glycol, Polyquaternium-10, Citric acid, Sodium chloride, Disodium EDTA, Sodium benzoate, Phenoxyethanol, Fragrance'],
        ['Free from', 'Sulfates, silicones, parabens, colouring'], ['Lasts', 'About 2 months (480 mL, one person, 2 pumps a day)'],
        ['Refill', 'The 400 mL pouch fills the 480 mL bottle to about four-fifths'], ['Skin notes', 'Contains fragrance; for adults and children from 3 years'],
        ['Shelf life', '3 years unopened; use within 1 year of opening'], ['Bottle size', '7 × 7 × 21 cm'], ['Country of origin', 'Japan'],
        ['In the box', 'Bottle with pump and/or refill pouches, depending on the option'],
      ],
      ja: [
        ['ブランド', 'シトリンラボ'], ['種類', 'ボディソープ（化粧品）'], ['内容量', '本体480mL／詰め替え400mL／本体480mL＋詰め替え400mL×2'],
        ['洗浄成分', 'アミノ酸系（サルフェートフリー）'], ['pH', '弱酸性（約6）'], ['香り', 'ゆず＆ひのき（香料）'],
        ['全成分', '水、ラウロイルメチルアラニンNa、コカミドプロピルベタイン、ココイルグルタミン酸Na、グリセリン、ラウリン酸ポリグリセリル-10、ユズ果実エキス、ヒノキ水、BG、ポリクオタニウム-10、クエン酸、塩化Na、EDTA-2Na、安息香酸Na、フェノキシエタノール、香料'],
        ['無添加', 'サルフェート、シリコーン、パラベン、着色料'], ['使用期間の目安', '約2か月（480mL、1人・1日2プッシュの場合）'],
        ['詰め替え', '400mLで本体480mLボトルの約8割まで'], ['肌への注意', '香料を含みます。大人と3歳以上のお子さまに'],
        ['使用期限', '未開封で3年、開封後は1年以内'], ['ボトルサイズ', '7×7×21cm'], ['原産国', '日本'],
        ['付属品', 'ご選択に応じてポンプ付きボトル、詰め替えパウチ'],
      ],
    },
    compare: {
      en: ['Body wash', '480 mL pump / 400 mL refill', 'Yuzu & hinoki (synthetic fragrance)', 'Amino-acid cleansers; sulfate-free', 'Contains fragrance', 'Japan'],
      ja: ['ボディソープ', '本体480mL／詰め替え400mL', 'ゆず＆ひのき（香料）', 'アミノ酸系洗浄成分、サルフェートフリー', '香料を含む', '日本'],
    },
    description: {
      en: [
        'Citrine Lab\'s Yuzu & Hinoki Body Wash is an everyday body wash for people whose skin feels tight or itchy after ordinary soap, especially in the dry winter months. Instead of sulfate cleansers (SLS, SLES), it uses mild amino-acid surfactants and is weakly acidic, close to the skin\'s own pH.',
        'About the scent: the fresh citrus top note and soft cypress-wood base come from fragrance (香料). Yuzu fruit extract and hinoki water are included in small amounts for skin conditioning and do not give the scent. If you want a natural yuzu scent, look at products scented with yuzu peel oil instead; this one smells more like a hotel shower than a yuzu orchard.',
        'How to use: amino-acid washes lather less than sulfate soaps. Two pumps on a wet body towel or foaming net make a soft, fine lather; on bare hands you will need more. Rinse well. Polyquaternium-10 leaves skin feeling lightly conditioned rather than squeaky clean.',
        'Sizes: the 480 mL pump bottle lasts one person about two months at two pumps a day. The 400 mL refill pouch has a tear-off corner and fills the bottle to about four-fifths; rinse and dry the bottle before refilling. The pump with two refills (1,280 mL) costs ¥3,180, ¥260 less than ¥3,440 for the three bought separately. See the table below.',
        'Free from sulfates, silicones, parabens and colouring; contains fragrance and the preservatives sodium benzoate and phenoxyethanol. Suitable for adults and children from 3 years. Stop using it if your skin becomes red or itchy. Unopened items can be returned within 30 days; opened toiletries only if defective or damaged.',
      ],
      ja: [
        'シトリンラボのゆず＆ひのきボディソープは、一般的なボディソープで洗うと肌がつっぱったり、かゆくなったりする方のための毎日のボディソープです。特に乾燥する冬に。硫酸系洗浄成分（ラウリル硫酸Na・ラウレス硫酸Na）の代わりにマイルドなアミノ酸系洗浄成分を使い、肌と同じ弱酸性に仕上げています。',
        '香りについて：みずみずしい柑橘のトップノートとやわらかな檜のベースノートは、香料によるものです。ユズ果実エキスとヒノキ水は肌を整えるために少量配合しており、香りのもとではありません。天然の柚子の香りをお求めの方は、柚子果皮油で香りづけした商品をお選びください。こちらは柚子畑というより、ホテルのシャワールームのような香りです。',
        '使い方：アミノ酸系は硫酸系の石けんより泡立ちが控えめです。濡らしたボディタオルや泡立てネットに2プッシュで、やわらかくきめ細かい泡になります。手で泡立てる場合はもう少し多めに。よくすすいでください。ポリクオタニウム-10の働きで、キュッとした洗い上がりではなく、しっとりした洗い上がりになります。',
        'サイズ：本体480mLは、1人で1日2プッシュ使って約2か月もちます。詰め替え400mLは角を切って注ぐタイプで、ボトルの約8割まで入ります。詰め替えの前にボトルを洗い、よく乾かしてください。本体＋詰め替え2個（計1,280mL）は3,180円で、別々に買う（計3,440円）より260円お得です。下の表をご覧ください。',
        'サルフェート・シリコーン・パラベン・着色料は不使用。香料と、防腐剤として安息香酸Na・フェノキシエタノールを含みます。大人と3歳以上のお子さまにお使いいただけます。肌に赤みやかゆみが出たら使用を中止してください。未開封品は30日以内なら返品可能、開封済みのトイレタリー用品は不良・破損の場合のみ返品できます。',
      ],
    },
    tables: [
      {
        title: { en: 'Which option to buy', ja: 'どれを買う？ 価格と使用期間の目安' },
        en: [
          ['Option', 'Contents', 'Price', 'Per 100 mL', 'Lasts one person'],
          ['480 mL pump bottle', '480 mL', '¥1,480', '¥308', 'About 2 months'],
          ['400 mL refill pouch', '400 mL', '¥980', '¥245', 'About 7 weeks'],
          ['Pump + 2 refills', '1,280 mL', '¥3,180', '¥248', 'About 5 months'],
        ],
        ja: [
          ['タイプ', '内容量', '価格', '100mLあたり', '1人で使った場合の目安'],
          ['本体', '480mL', '1,480円', '308円', '約2か月'],
          ['詰め替え用', '400mL', '980円', '245円', '約7週間'],
          ['本体＋詰め替え2個', '1,280mL', '3,180円', '248円', '約5か月'],
        ],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-20', variant: 'pump', helpful: 98, verified: true,
        en: { name: 'Erina', title: 'My skin no longer feels tight after a shower', body: 'I switched from a regular body soap, and the tight, itchy feeling on my shins in winter has gone. The lather is softer but plenty with a nylon towel.' },
        ja: { name: 'えりな', title: 'シャワー後のつっぱり感がなくなった', body: '普通のボディソープから替えたら、冬のすねのつっぱりやかゆみがなくなりました。泡はやわらかめですが、ナイロンタオルを使えば十分です。' } },
      { stars: 1, date: '2026-08-04', variant: 'pump', helpful: 143, verified: true,
        en: { name: 'Kotaro', title: 'Artificial yuzu smell, like a toilet freshener', body: 'I bought it for the words "yuzu" and "hinoki", and it smells like a cheap lemon toilet freshener. The ingredients say "fragrance" at the end, and the yuzu is just an extract. After the Minori Yuzu Farm bath salts, which smell of real peel, this was a big disappointment. And you cannot return an opened bottle.' },
        ja: { name: '虎太郎', title: '人工的な柚子の香り。トイレの芳香剤みたい', body: '「ゆず」「ひのき」に惹かれて買いましたが、安いレモンのトイレ用芳香剤のようなにおい。成分表を見ると最後に「香料」とあり、柚子はエキスだけでした。本物の皮の香りがするみのり柚子園のバスソルトを使ったあとだと、がっかりです。しかも開封済みは返品できません。' } },
      { stars: 4, date: '2026-07-16', variant: 'refill', helpful: 72, verified: true,
        en: { name: 'Mayumi', title: 'Pleasant, and the scent lasts', body: 'I know it is fragrance, but I like it: citrus first, then a woody note I can still smell on my skin an hour later. My partner calls it the "hotel shower" smell, and he means it nicely.' },
        ja: { name: 'まゆみ', title: '心地よく、香りが長続き', body: '香料なのは分かっていますが、好きな香りです。最初に柑橘、そのあと木の香りがして、1時間後もまだ肌から香ります。夫は「ホテルのシャワーの香り」と言っています（ほめ言葉です）。' } },
      { stars: 2, date: '2026-06-24', variant: 'set', helpful: 81, verified: true,
        en: { name: 'Daichi', title: 'Barely foams, so it runs out fast', body: 'Two pumps in my hands make almost no foam, so I use four or five, and the 480 mL bottle was empty in five weeks. I understand amino-acid washes foam less, but it makes the "2 months" estimate optimistic.' },
        ja: { name: '大地', title: '泡立たないので減りが早い', body: '手に2プッシュではほとんど泡立たず、4〜5プッシュ使うので、480mLが5週間でなくなりました。アミノ酸系は泡立ちにくいと分かっていますが、「約2か月」の目安は楽観的だと思います。' } },
      { stars: 1, date: '2026-05-30', variant: 'pump', helpful: 66, verified: true,
        en: { name: 'Sae', title: 'Rash on my back', body: 'Two days after switching I had small red bumps across my back and chest. They cleared when I went back to my unscented soap. I suspect the fragrance. If your skin reacts to perfume, avoid it.' },
        ja: { name: '紗英', title: '背中に湿疹', body: '替えて2日後、背中と胸に小さな赤いぶつぶつが出ました。無香料の石けんに戻したら治まりました。香料が原因だと思います。香料で肌荒れしやすい方は避けたほうがいいです。' } },
      { stars: 3, date: '2026-04-17', variant: 'refill', helpful: 47, verified: true,
        en: { name: 'Toru', title: 'Refill pouch is hard to pour', body: 'The pouch has no spout, just a tear-off corner, and pouring it into the narrow bottle neck makes a mess. Also, 400 mL only fills the bottle about four-fifths.' },
        ja: { name: '徹', title: '詰め替えパウチが注ぎにくい', body: '注ぎ口がなく角を切るだけなので、細いボトルの口に注ぐとこぼれます。それに400mLではボトルの8割ほどしか入りません。' } },
      { stars: 5, date: '2026-09-12', variant: 'set', helpful: 35, verified: true,
        en: { name: 'Yui', title: 'The set is the best value', body: 'The pump and two refills for ¥3,180 is ¥260 less than buying them separately, and it lasts the two of us about three months. I clipped the ¥200 coupon too.' },
        ja: { name: 'ゆい', title: 'セットがいちばんお得', body: '本体＋詰め替え2個で3,180円、別々に買うより260円安く、2人で約3か月もちます。200円クーポンも使いました。' } },
      { stars: 4, date: '2026-02-26', variant: 'pump', helpful: 29, verified: true,
        en: { name: 'Shun', title: 'I wish there were more hinoki', body: 'The yuzu dominates and the hinoki is faint. A good wash otherwise.' },
        ja: { name: 'しゅん', title: 'もっとひのきが香ってほしい', body: '柚子が強く、ひのきはかすかです。それ以外は良いボディソープ。' } },
      { stars: 5, date: '2026-08-18', variant: 'refill', helpful: 24, verified: true,
        en: { name: 'Kiyomi', title: 'My fourth refill', body: 'Gentle, no dryness, and the refill is only ¥980. It has arrived the next day every time.' },
        ja: { name: '清美', title: '詰め替え4回目', body: 'やさしい洗い上がりで乾燥せず、詰め替えは980円。毎回翌日に届きます。' } },
      { stars: 3, date: '2026-07-07', variant: 'pump', helpful: 33, verified: true,
        en: { name: 'Wataru', title: 'Leaves a slippery film', body: 'Even after rinsing well my skin feels a little slick, not squeaky clean. Some people like that; I do not.' },
        ja: { name: '渉', title: 'ぬるっとした膜が残る', body: 'よくすすいでも肌が少しぬるっとして、さっぱりしません。好きな人もいると思いますが、私は苦手でした。' } },
      { stars: 2, date: '2026-09-29', variant: 'pump', helpful: 18, verified: true,
        en: { name: 'Ryo', title: 'The pump stopped working after six weeks', body: 'The pump started sticking down, then stopped coming back up at all. Citrine Lab sent me a new pump free after I emailed a photo, but it took ten days, and in the meantime I was unscrewing the top and pouring.' },
        ja: { name: 'りょう', title: '6週間でポンプが壊れた', body: 'ポンプが押したまま戻りにくくなり、そのうちまったく戻らなくなりました。写真をメールしたらシトリンラボが新しいポンプを無料で送ってくれましたが、10日かかり、その間はキャップを外して注いでいました。' } },
      { stars: 5, date: '2026-06-01', variant: 'pump', helpful: 21, verified: true,
        en: { name: 'Tamaki', title: 'Lovely with an onsen powder bath', body: 'I wash with this, then soak in a Yumeguri Tsukimi Onsen bath. The yuzu and forest scents go together surprisingly well.' },
        ja: { name: 'たまき', title: '温泉の入浴剤と相性ぴったり', body: 'これで洗ってから、湯めぐりの月見温泉の入浴剤を入れたお風呂へ。柚子と森の香りが意外なほど合います。' } },
    ],
    qa: [
      { date: '2026-04-08', votes: 53,
        en: { q: 'Is the yuzu scent natural?', a: 'No. The scent comes from fragrance, listed as 香料 at the end of the ingredients. Yuzu fruit extract and hinoki water are included in small amounts for skin conditioning and do not provide the scent.', by: 'Citrine Lab Customer Support' },
        ja: { q: '柚子の香りは天然ですか？', a: 'いいえ。香りは成分表の最後にある「香料」によるものです。ユズ果実エキスとヒノキ水は肌を整える目的で少量配合しており、香りのもとではありません。', by: 'シトリンラボ お客様窓口' } },
      { date: '2026-05-22', votes: 31,
        en: { q: 'Is it free of sulfates and silicones?', a: 'Yes. It is also free of parabens and colouring. The preservatives are sodium benzoate and phenoxyethanol.', by: 'Citrine Lab Customer Support' },
        ja: { q: 'サルフェートフリー、シリコーンフリーですか？', a: 'はい。パラベン・着色料も使用していません。防腐剤として安息香酸Naとフェノキシエタノールを配合しています。', by: 'シトリンラボ お客様窓口' } },
      { date: '2026-06-11', votes: 27,
        en: { q: 'Can children use it?', a: 'Yes, from 3 years old. For babies we recommend a fragrance-free baby wash.', by: 'Citrine Lab Customer Support' },
        ja: { q: '子どもにも使えますか？', a: 'はい、3歳以上のお子さまにお使いいただけます。赤ちゃんには無香料のベビー用ボディソープをおすすめします。', by: 'シトリンラボ お客様窓口' } },
      { date: '2026-07-02', votes: 22,
        en: { q: 'Does the 400 mL refill fit the 480 mL bottle?', a: 'Yes, it fills it about four-fifths. Rinse the bottle and let it dry completely first, so water does not dilute the wash.', by: 'Marketa customer (Kiyomi)' },
        ja: { q: '詰め替え400mLは本体480mLのボトルに入りますか？', a: '入ります。ボトルの8割くらいまでです。水で薄まらないよう、先にボトルを洗ってしっかり乾かしてから詰め替えてください。', by: 'マルケタ購入者（清美）' } },
      { date: '2026-09-15', votes: 14,
        en: { q: 'Can I use it on my face?', a: 'It is formulated for the body. Some customers use it on the face, but keep it out of your eyes, and note that the fragrance may irritate sensitive facial skin.', by: 'Citrine Lab Customer Support' },
        ja: { q: '顔にも使えますか？', a: 'ボディ用に設計しています。顔に使われるお客様もいらっしゃいますが、目に入らないようご注意ください。また、香料が顔の敏感な肌を刺激することがあります。', by: 'シトリンラボ お客様窓口' } },
    ],
    similar: ['minori-bath-salts', 'minori-hand-cream', 'yumeguri-onsen-powder'],
    fbt: ['yumeguri-onsen-powder', 'minori-hand-cream'],
    alsoViewed: ['yumeguri-onsen-powder', 'minori-bath-salts', 'minori-hand-cream', 'nami-buds', 'shiroshita-senbei', 'hearth-kettle'],
  },
];
