// Local food and gifts (Food & Gifts). Same shape as kettles.mjs.
export const cluster = {
  id: 'gifts',
  compareRows: {
    en: ['Contents', 'Best before', 'Allergens', 'Gift box / noshi', 'Made in', 'Storage'],
    ja: ['内容', '賞味期限', 'アレルギー物質', 'ギフト箱・のし', '製造地', '保存方法'],
  },
};

export default [
  {
    id: 'minori-ponzu-set',
    cat: 'gifts',
    cluster: 'gifts',
    brand: { en: 'Minori Yuzu Farm', ja: 'みのり柚子園' },
    seller: 'minori',
    images: ['minori-ponzu-set'],
    title: {
      en: 'Minori Yuzu Farm Yuzu Ponzu (2 × 300 mL) and Green Yuzu Kosho (50 g) Gift Set, Made with Yuzu Grown in the Kagami River Valley, Harukawa Souvenir, Free Noshi and Message Card',
      ja: 'みのり柚子園 ゆずぽん酢 300ml×2本 青柚子こしょう 50g ギフトセット 鏡川流域産 柚子使用 春川 お土産 贈答 内祝い 御礼 のし・メッセージカード無料',
    },
    short: { en: 'Minori Yuzu Ponzu & Kosho Set', ja: 'みのり柚子園 ぽん酢＆柚子こしょう' },
    rating: 4.7,
    ratings: 803,
    hist: [80, 12, 4, 2, 2],
    added: '2022-11-01',
    badges: ['choice'],
    coupon: { pct: 5, member: true, en: '5% off for Marketa Fast members', ja: 'Fast会員限定 5%OFFクーポン' },
    variantLabel: { en: 'Packaging', ja: '包装' },
    variants: [
      { id: 'gift-box', name: { en: 'Gift box', ja: 'ギフト箱入り' }, price: 4320, list: null, stock: 60, ship: 'minori' },
      { id: 'home-pack', name: { en: 'Home pack (no box)', ja: 'ご家庭用（箱なし）' }, price: 3780, list: null, stock: 38, ship: 'minori' },
    ],
    returns: {
      en: 'Sold and shipped by Minori Yuzu Farm. Food cannot be returned unless it arrives damaged or faulty: send photos to the farm within 7 days of delivery for a replacement or refund.',
      ja: 'みのり柚子園が販売・発送する商品です。食品のため返品はお受けできません。破損・不良品が届いた場合は、到着後7日以内に写真を添えて当園までご連絡ください。交換または返金いたします。',
    },
    bullets: {
      en: [
        'TWO HARUKAWA FLAVOURS: two 300 mL bottles of yuzu ponzu and a 50 g jar of green yuzu kosho, made by the Hirose family in the kitchen at their orchard near Tsukimi Onsen.',
        'REAL YUZU JUICE: the ponzu contains 20% hand-squeezed juice from our own trees, blended with soy sauce, rice vinegar, mirin, bonito and kombu stock. Tangy first, with a salty finish: 1.1 g salt per tablespoon.',
        'FRESH GREEN YUZU KOSHO: green yuzu peel picked in August, green chillies and salt, ground in small batches. Very hot and aromatic; a little goes a long way on hot pot, grilled chicken, sashimi or pasta.',
        'ALLERGENS: the ponzu contains soy and wheat, plus bonito (fish) extract, so it is not suitable for fish allergies or a gluten-free diet. The yuzu kosho contains none of these.',
        'BEST BEFORE: ponzu 8 months unopened (at least 5 months left on delivery); refrigerate after opening and use within 1 month. Yuzu kosho: keep refrigerated; 6 months unopened, use within 3 months of opening.',
        'GIFT BOX OR HOME PACK: the gift box (¥4,320) ships free with free noshi and a gift message card. The home pack (¥3,780) has the same contents in a plain carton with no noshi, and pays ¥600 shipping unless your farm order reaches ¥4,000.',
        'ARRIVES WED 7 – THU 8 OCT from the farm, in time for the Lantern Festival (10–11 Oct). Not Marketa Fast-eligible.',
      ],
      ja: [
        '【春川の味を2種類】ゆずぽん酢300mL×2本と青柚子こしょう50g。月見温泉近くの柚子園で、広瀬家が園内の加工場で手作りしています。',
        '【柚子果汁たっぷり】自家栽培の柚子を手搾りした果汁を20%使用。醤油、米酢、みりん、かつお節と昆布のだしを合わせました。爽やかな酸味のあとに塩味がきます（食塩相当量 大さじ1あたり1.1g）。',
        '【できたての青柚子こしょう】8月に摘んだ青柚子の皮と青唐辛子、塩を少量ずつすりつぶしています。辛さと香りはしっかり。鍋、焼き鳥、お刺身、パスタに少しで十分です。',
        '【アレルギー物質】ぽん酢には小麦・大豆のほか、かつお（魚）エキスが含まれます。魚アレルギーの方、グルテンを控えている方には向きません。柚子こしょうにはいずれも含まれません。',
        '【賞味期限】ぽん酢は未開封で8か月（お届け時に5か月以上）。開封後は冷蔵し1か月以内に。柚子こしょうは要冷蔵、未開封で6か月、開封後3か月以内にお召し上がりください。',
        '【ギフト箱とご家庭用】ギフト箱（4,320円）は送料無料、のし・メッセージカードも無料。ご家庭用（3,780円）は中身は同じで無地の段ボール入り、のしは付けられません。当園でのご注文が4,000円未満の場合、送料600円がかかります。',
        '【10月7日（水）〜8日（木）お届け】当園から直送。灯籠まつり（10月10日・11日）に間に合います。マルケタFastの対象外です。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Minori Yuzu Farm'], ['Contents', '2 × 300 mL yuzu ponzu, 1 × 50 g green yuzu kosho'],
        ['Ponzu ingredients', 'Soy sauce (soybeans, wheat, salt), yuzu juice (20%, Minori Prefecture), rice vinegar, mirin, bonito flake extract, kombu extract'],
        ['Yuzu kosho ingredients', 'Green yuzu peel (Minori Prefecture), green chilli, salt'],
        ['Allergens', 'Soy, wheat (ponzu). Also contains bonito (fish).'], ['Salt', 'Ponzu 1.1 g per 15 mL; yuzu kosho about 15%'],
        ['Additives', 'No preservatives, colourings or MSG'], ['Best before (unopened)', 'Ponzu 8 months from bottling; yuzu kosho 6 months'],
        ['After opening', 'Ponzu: refrigerate, use within 1 month. Yuzu kosho: refrigerate, use within 3 months'],
        ['Storage', 'Ponzu: cool, dark place until opened. Yuzu kosho: always refrigerate'],
        ['Gift box', '26 × 18 × 8 cm, 1.3 kg, kraft box with yuzu illustration'], ['Home pack', 'Same contents in a plain carton'],
        ['Noshi / message card', 'Free (gift box only)'], ['Producer', 'Minori Yuzu Farm (Hirose family), Tsukimi Onsen area, Minori Prefecture'],
        ['Country of origin', 'Japan'], ['Guarantee', 'Damaged or faulty on arrival: replacement or refund (report within 7 days)'],
      ],
      ja: [
        ['ブランド', 'みのり柚子園'], ['内容', 'ゆずぽん酢300mL×2本、青柚子こしょう50g×1個'],
        ['ぽん酢 原材料', 'しょうゆ（大豆・小麦・食塩）、ゆず果汁（20%、みのり県産）、米酢、みりん、かつお節エキス、昆布エキス'],
        ['柚子こしょう 原材料', '青ゆず皮（みのり県産）、青唐辛子、食塩'],
        ['アレルギー物質', '小麦・大豆（ぽん酢）。かつお（魚）を含みます'], ['食塩相当量', 'ぽん酢 15mLあたり1.1g、柚子こしょう 約15%'],
        ['添加物', '保存料・着色料・化学調味料不使用'], ['賞味期限（未開封）', 'ぽん酢 製造から8か月、柚子こしょう 6か月'],
        ['開封後', 'ぽん酢は冷蔵で1か月以内、柚子こしょうは冷蔵で3か月以内'],
        ['保存方法', 'ぽん酢は開封まで冷暗所、柚子こしょうは常に要冷蔵'],
        ['ギフト箱', '26×18×8cm、約1.3kg、柚子のイラスト入りクラフト箱'], ['ご家庭用', '同じ内容を無地の段ボールでお届け'],
        ['のし・メッセージカード', '無料（ギフト箱のみ）'], ['製造者', 'みのり柚子園（広瀬家）、みのり県 月見温泉近郊'],
        ['原産国', '日本'], ['品質保証', '破損・不良品は到着後7日以内のご連絡で交換または返金'],
      ],
    },
    compare: {
      en: ['2 × 300 mL ponzu + 50 g yuzu kosho', 'Ponzu 8 months, kosho 6 months (unopened)', 'Soy, wheat; also bonito (fish)', 'Gift box: free noshi and card; home pack: none', 'Minori Yuzu Farm, near Tsukimi Onsen', 'Ponzu: cool and dark; kosho: refrigerate'],
      ja: ['ぽん酢300mL×2＋柚子こしょう50g', 'ぽん酢8か月・柚子こしょう6か月（未開封）', '小麦・大豆、かつお（魚）', 'ギフト箱：のし・カード無料／ご家庭用：なし', 'みのり柚子園（月見温泉近郊）', 'ぽん酢は冷暗所、柚子こしょうは要冷蔵'],
    },
    tables: [
      {
        title: { en: 'Gift box or home pack?', ja: 'ギフト箱とご家庭用の違い' },
        en: [
          ['', 'Gift box', 'Home pack'],
          ['Price', '¥4,320', '¥3,780'],
          ['Shipping', 'Free', '¥600 (free if your farm order is ¥4,000 or more)'],
          ['Total delivered, ordered alone', '¥4,320', '¥4,380'],
          ['Noshi and message card', 'Free', 'Not available'],
          ['Packing', 'Kraft gift box, bottles in pulp dividers', 'Plain carton, bubble wrap'],
        ],
        ja: [
          ['', 'ギフト箱', 'ご家庭用'],
          ['価格', '4,320円', '3,780円'],
          ['送料', '無料', '600円（当園でのご注文4,000円以上で無料）'],
          ['単品注文時のお支払い合計', '4,320円', '4,380円'],
          ['のし・メッセージカード', '無料', '対応不可'],
          ['梱包', 'クラフトのギフト箱、瓶はパルプの仕切り入り', '無地の段ボール、プチプチ包装'],
        ],
      },
      {
        title: { en: 'Best before and storage', ja: '賞味期限と保存方法' },
        en: [
          ['Item', 'Unopened', 'After opening', 'Storage'],
          ['Yuzu ponzu 300 mL', '8 months from bottling (at least 5 months left on delivery)', 'Within 1 month', 'Cool, dark place; refrigerate after opening'],
          ['Green yuzu kosho 50 g', '6 months', 'Within 3 months', 'Refrigerate at all times'],
        ],
        ja: [
          ['商品', '未開封', '開封後', '保存方法'],
          ['ゆずぽん酢 300mL', '製造から8か月（お届け時に5か月以上）', '1か月以内', '冷暗所。開封後は冷蔵'],
          ['青柚子こしょう 50g', '6か月', '3か月以内', '常に冷蔵'],
        ],
      },
    ],
    description: {
      en: [
        'Minori Yuzu Farm is a family orchard on the terraced hillsides of the Kagami River valley, a short drive from Tsukimi Onsen. The Hirose family has grown yuzu here since 1978; cool nights and morning fog off the river give the fruit thick, fragrant peel. Everything in this box is made in the farm’s own small kitchen from fruit picked on the hillside.',
        'The ponzu is made from ripe yellow yuzu harvested in November and December and squeezed by hand. At 20% yuzu juice it is much fruitier than most supermarket ponzu, and it is brewed with real bonito flakes and kombu rather than stock powder. It is a dipping and dressing sauce: use it on hot pot, tofu, gyoza, grilled fish or salad. It is tangy first with a noticeably salty finish; if you are watching your salt, mix it half and half with dashi or water.',
        'The green yuzu kosho is made once a year, in August, from unripe green yuzu and green chillies grown on the farm. It is bright green when made and slowly turns olive green in the fridge; this is natural and does not affect the taste. It is very hot: start with an amount the size of a grain of rice. There are no preservatives, so keep it refrigerated even before opening.',
        'Allergens: the ponzu contains soy and wheat (from the soy sauce), and bonito, which is a fish. Bonito is not one of the allergens Japanese labels must highlight, so on the bottle it appears only in the ingredients list. The yuzu kosho contains no soy, wheat or fish and is made on separate equipment.',
        'For gifts, choose the gift box: noshi paper (御祝, 御礼, 内祝, 御歳暮 and more) and a message card are free; write the inscription and your name in the order notes. The farm ships Monday to Saturday and the set arrives Wed 7 – Thu 8 Oct in Harukawa city, before the Lantern Festival. Food cannot be returned, but if a bottle arrives broken or leaking, send photos within 7 days and the farm replaces it or refunds you.',
      ],
      ja: [
        'みのり柚子園は、月見温泉から車ですぐ、鏡川流域の段々畑にある家族経営の柚子園です。広瀬家が1978年から柚子を育てています。夜の冷え込みと川から上がる朝霧のおかげで、皮が厚く香りの強い柚子が実ります。この箱の中身はすべて、斜面の畑で収穫した柚子を使い、園内の小さな加工場で作ったものです。',
        'ぽん酢には、11月から12月に収穫した完熟の黄柚子を手で搾った果汁を使っています。果汁は20%と、一般的な市販品よりずっと柚子の風味が豊か。だしの素ではなく、かつお節と昆布からとっただしを合わせています。つけだれやドレッシングとして、鍋、豆腐、餃子、焼き魚、サラダにどうぞ。最初に酸味、あとからしっかりした塩味がきます。塩分が気になる方はだしや水で半々に割ってお使いください。',
        '青柚子こしょうは、園で育てた青い未熟の柚子と青唐辛子で、毎年8月に一度だけ仕込みます。できたては鮮やかな緑色で、冷蔵庫の中で少しずつオリーブ色に変わりますが、自然な変化で味には影響ありません。辛さはかなり強めなので、米粒くらいの量から試してください。保存料を使っていないため、開封前から冷蔵庫で保存してください。',
        'アレルギー物質について：ぽん酢には、しょうゆ由来の小麦・大豆のほか、魚であるかつおが含まれます。かつおは表示が義務付けられた品目ではないため、瓶のラベルでは原材料名欄にのみ記載しています。柚子こしょうには小麦・大豆・魚は含まれず、別の設備で製造しています。',
        '贈り物にはギフト箱をお選びください。のし（御祝・御礼・内祝・御歳暮など）とメッセージカードは無料です。表書きとお名前はご注文時の備考欄にご記入ください。当園は月曜〜土曜に発送し、春川市内には10月7日（水）〜8日（木）、灯籠まつりの前にお届けします。食品のため返品はお受けできませんが、瓶の破損や液漏れがあった場合は7日以内に写真をお送りいただければ、交換または返金いたします。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-22', variant: 'gift-box', helpful: 120, verified: true,
        en: { name: 'Fumiko', title: 'The best ponzu I have tasted', body: 'You can smell the yuzu as soon as you open the bottle, not the vinegar. We had it with chicken hot pot and my husband, who usually drowns everything in shop ponzu, used half as much. The kosho is hot but wonderful on grilled fish.' },
        ja: { name: 'ふみこ', title: '今まででいちばんのぽん酢', body: '瓶を開けた瞬間、お酢ではなく柚子の香りがします。鶏の水炊きでいただきましたが、いつも市販のぽん酢をどばどばかける夫が半分の量で満足していました。柚子こしょうは辛いですが、焼き魚に最高です。' } },
      { stars: 2, date: '2026-08-17', variant: 'gift-box', helpful: 74, verified: true,
        en: { name: 'Hideo', title: 'Far too salty for us', body: 'The yuzu smell is lovely when you open it, but the taste is mostly soy and salt. On cold tofu it overpowers everything. We now dilute it half and half with dashi. For ¥4,320 I expected more yuzu.' },
        ja: { name: '英夫', title: 'うちには塩辛すぎました', body: '開けたときの柚子の香りはいいのですが、味はほとんど醤油と塩。冷ややっこにかけるとほかの味が消えてしまいます。今はだしで半分に割って使っています。4,320円ならもっと柚子を感じたかったです。' } },
      { stars: 5, date: '2026-07-05', variant: 'home-pack', helpful: 31, verified: true,
        en: { name: 'Kai', title: 'Not salty at all if you use it as ponzu', body: 'Some reviews say it is salty. Ponzu is a dipping sauce, not a soup. Tangy and fresh, and the home pack is all we need for ourselves.' },
        ja: { name: 'かい', title: 'ぽん酢として使えば塩辛くない', body: '塩辛いというレビューもありますが、ぽん酢はつけだれでスープではありません。酸味がさわやかで、自宅用ならご家庭用で十分です。' } },
      { stars: 2, date: '2026-09-28', variant: 'gift-box', helpful: 66, verified: true,
        en: { name: 'Erika', title: 'Bottle leaked in transit and ruined the box', body: 'One bottle’s cap had loosened and ponzu soaked the gift box, so I could not give it to my boss as planned. The farm replied the next morning and sent a new set, which arrived two days later, after I sent photos. Good service, but it was meant for a specific day.' },
        ja: { name: 'えりか', title: '配送中に液漏れして箱がだめに', body: '1本のキャップがゆるんでいて、ぽん酢がギフト箱に染みていました。予定していた上司へのお渡しには使えず。写真を送ると翌朝には返事があり、新しいセットが2日後に届きました。対応は良かったのですが、渡す日が決まっていたので残念です。' } },
      { stars: 1, date: '2026-06-10', variant: 'gift-box', helpful: 92, verified: true,
        en: { name: 'Laura', title: 'Contains fish: read the full ingredients', body: 'My husband has a fish allergy. The allergen line on the bottle lists only wheat and soy, and the bonito extract is only in the ingredients list. He reacted after one dish. The listing does mention bonito, but please read the full ingredients, not just the allergen line.' },
        ja: { name: 'ローラ', title: '魚が入っています。原材料まで確認を', body: '夫に魚アレルギーがあります。瓶のアレルギー表示は小麦・大豆だけで、かつおエキスは原材料欄にしか書かれていませんでした。一品食べて症状が出ました。商品ページにはかつおの記載がありますが、アレルギー表示欄だけでなく原材料まで必ず見てください。' } },
      { stars: 4, date: '2026-09-03', variant: 'home-pack', helpful: 58, verified: true,
        en: { name: 'Shin', title: 'The home pack cost me more than the gift box', body: 'I chose the home pack to save ¥540, then paid ¥600 shipping because my farm order was under ¥4,000. The gift box would have been ¥60 cheaper delivered. Tastes great, though.' },
        ja: { name: 'しん', title: 'ご家庭用のほうが高くついた', body: '540円安いご家庭用を選んだら、園での注文が4,000円未満で送料600円。届くまでの合計はギフト箱のほうが60円安かったです。味は最高です。' } },
      { stars: 5, date: '2026-09-30', variant: 'gift-box', helpful: 15, verified: true,
        en: { name: 'Megumi', title: 'Noshi done beautifully', body: 'A 御礼 noshi with our family name, written by hand. It arrived in two days. I ordered it with the yuzu marmalade set as a gift for our Lantern Festival hosts; the marmalade came from Marketa the next day and the ponzu separately from the farm.' },
        ja: { name: 'めぐみ', title: 'のしがとてもていねい', body: '「御礼」ののしに名字を手書きで入れてくれました。2日で到着。灯籠まつりでお世話になるお宅への手土産に、ゆずマーマレードのセットと一緒に注文。マーマレードはマルケタから翌日、ぽん酢は園から別便で届きました。' } },
      { stars: 2, date: '2026-08-25', variant: 'gift-box', helpful: 27, verified: true,
        en: { name: 'Taichi', title: 'The yuzu kosho is extremely hot', body: 'I expected a gentle citrus paste; it is fiery. The tip of a chopstick is enough. My elderly parents, who I bought it for, could not eat it at all. The ponzu is good.' },
        ja: { name: '太一', title: '柚子こしょうが激辛', body: 'やさしい柑橘のペーストを想像していたら、かなりの辛さ。箸の先にちょっとで十分です。贈った高齢の両親はまったく食べられませんでした。ぽん酢はおいしいです。' } },
      { stars: 5, date: '2026-08-08', variant: 'home-pack', helpful: 19, verified: true,
        en: { name: 'Grace', title: 'The best yuzu kosho I have had', body: 'Hot, sharp and fresh green, exactly what yuzu kosho should be. A tiny bit in miso soup is wonderful.' },
        ja: { name: 'グレース', title: '今まででいちばんの柚子こしょう', body: '辛くて鋭くて、青々とした香り。柚子こしょうはこうでなくては。お味噌汁にほんの少し入れるのもおすすめです。' } },
      { stars: 3, date: '2026-07-21', variant: 'gift-box', helpful: 22, verified: true,
        en: { name: 'Satoru', title: 'Kosho turned olive in the fridge', body: 'After a month it went from bright green to olive green. The farm said the colour changes naturally and the taste is unaffected. They are right, but it looks less appetising.' },
        ja: { name: '悟', title: '冷蔵庫で柚子こしょうが変色', body: '1か月で鮮やかな緑からオリーブ色に。園に聞いたら自然な変化で味は変わらないとのこと。確かにそうですが、見た目はおいしそうではなくなります。' } },
      { stars: 4, date: '2025-12-14', variant: 'gift-box', helpful: 13, verified: true,
        en: { name: 'Atsuko', title: 'Good year-end gift', body: 'Sent as an oseibo. The ponzu had six months left before its best-before date, plenty for a gift. One star off because the kosho needs the fridge, which I had to tell the recipient.' },
        ja: { name: '敦子', title: 'お歳暮にちょうどいい', body: 'お歳暮に贈りました。ぽん酢は賞味期限まで半年あり、贈り物には十分。柚子こしょうが要冷蔵なので、先方にひとこと伝える必要があり星4つ。' } },
      { stars: 5, date: '2026-09-11', variant: 'gift-box', helpful: 11, verified: true,
        en: { name: 'Yuko', title: 'Our standard Harukawa souvenir', body: 'We send this and the Shiroshita senbei to relatives every autumn. Note that the ponzu contains wheat and soy; the senbei box also has shrimp, so check allergies for both.' },
        ja: { name: '優子', title: 'わが家の春川みやげの定番', body: '毎年秋、これと城下製菓のおせんべいを親戚に送っています。ぽん酢には小麦・大豆が、おせんべいには海老も入っているので、どちらもアレルギーの確認をお忘れなく。' } },
    ],
    qa: [
      { date: '2026-06-12', votes: 48,
        en: { q: 'Does the ponzu contain fish?', a: 'Yes, bonito flake extract. Bonito is not one of the allergens Japanese labels must highlight, so it appears only in the ingredients list on the bottle. The ponzu is not suitable for anyone with a fish allergy. The yuzu kosho contains no fish.', by: 'Minori Yuzu Farm' },
        ja: { q: 'ぽん酢に魚は入っていますか？', a: 'はい、かつお節エキスを使用しています。かつおは表示義務のある品目ではないため、瓶では原材料名欄にのみ記載しております。魚アレルギーの方はお控えください。柚子こしょうには魚は含まれていません。', by: 'みのり柚子園' } },
      { date: '2026-10-04', votes: 9,
        en: { q: 'If I order the gift box tomorrow, will it arrive before 10 October?', a: 'Yes. We ship Monday to Saturday, and orders placed by Monday 5 Oct arrive in Harukawa city on Wed 7 – Thu 8 Oct.', by: 'Minori Yuzu Farm' },
        ja: { q: '明日ギフト箱を注文したら、10月10日までに届きますか？', a: 'はい。当園は月曜〜土曜に発送しております。10月5日（月）までのご注文は、春川市内に10月7日（水）〜8日（木）にお届けします。', by: 'みのり柚子園' } },
      { date: '2026-08-30', votes: 14,
        en: { q: 'Can I add noshi to the home pack?', a: 'No, the home pack ships in a plain carton, so noshi and the message card are available with the gift box only.', by: 'Minori Yuzu Farm' },
        ja: { q: 'ご家庭用にものしを付けられますか？', a: 'ご家庭用は無地の段ボールでお届けするため、のし・メッセージカードはギフト箱のみの対応となります。', by: 'みのり柚子園' } },
      { date: '2026-07-01', votes: 6,
        en: { q: 'Does the yuzu kosho need to go in the fridge before opening?', a: 'No, I kept mine in the cupboard until I opened it and it was fine.', by: 'Marketa customer (Kenta)' },
        ja: { q: '柚子こしょうは開封前も冷蔵が必要ですか？', a: '私は開けるまで戸棚に置いていましたが、問題ありませんでした。', by: 'マルケタ購入者（けんた）' } },
      { date: '2026-07-03', votes: 22,
        en: { q: 'How should I store the yuzu kosho?', a: 'Please refrigerate it at all times, including before opening. It contains no preservatives, so at room temperature the colour and aroma fade quickly. Unopened it keeps 6 months in the fridge; once opened, use it within 3 months.', by: 'Minori Yuzu Farm' },
        ja: { q: '柚子こしょうの保存方法を教えてください。', a: '開封前も含めて、常に冷蔵庫で保存してください。保存料を使っていないため、常温では色と香りがすぐに落ちてしまいます。未開封なら冷蔵で6か月、開封後は3か月以内にお召し上がりください。', by: 'みのり柚子園' } },
      { date: '2026-05-19', votes: 11,
        en: { q: 'Is it gluten-free?', a: 'The ponzu is not: the soy sauce contains wheat. The yuzu kosho is gluten-free.', by: 'Minori Yuzu Farm' },
        ja: { q: 'グルテンフリーですか？', a: 'ぽん酢はしょうゆに小麦を含むため、グルテンフリーではありません。柚子こしょうはグルテンフリーです。', by: 'みのり柚子園' } },
    ],
    similar: ['minori-marmalade-set', 'shiroshita-senbei', 'kagami-sake-set'],
    fbt: ['minori-marmalade-set', 'shiroshita-senbei'],
    alsoViewed: ['minori-marmalade-set', 'shiroshita-senbei', 'kagami-sake-set', 'minori-bath-salts', 'kagami-plate-set', 'minori-hand-cream'],
  },
  {
    id: 'minori-marmalade-set',
    cat: 'gifts',
    cluster: 'gifts',
    brand: { en: 'Minori Yuzu Farm', ja: 'みのり柚子園' },
    seller: 'minori',
    images: ['minori-marmalade-set'],
    title: {
      en: 'Minori Yuzu Farm Yuzu Marmalade (2 × 200 g) and Yuzu-cha Citron Tea (430 g) Gift Set, Made with Kagami Valley Yuzu, No Added Pectin, Gift Box, Free Noshi',
      ja: 'みのり柚子園 ゆずマーマレード 200g×2 ゆず茶 430g ギフトセット 鏡川流域産柚子 ペクチン無添加 化粧箱入り のし対応 春川みやげ 贈り物',
    },
    short: { en: 'Minori Yuzu Marmalade & Yuzu-cha Set', ja: 'みのり柚子園 マーマレード＆ゆず茶' },
    rating: 4.5,
    ratings: 1290,
    hist: [71, 16, 6, 3, 4],
    added: '2023-01-12',
    badges: [],
    coupon: null,
    variantLabel: { en: 'Set', ja: 'セット' },
    variants: [
      { id: 'set', name: { en: '2 marmalade + 1 yuzu-cha', ja: 'マーマレード2個＋ゆず茶1個' }, price: 3240, list: null, stock: 54, ship: 'fast' },
    ],
    returns: {
      en: 'Sold by Minori Yuzu Farm and shipped by Marketa, so Marketa’s return policy applies: food and drink cannot be returned unless defective, damaged in delivery or wrong. Report damage within 7 days of delivery for a free replacement or full refund.',
      ja: 'みのり柚子園が販売し、マルケタが発送する商品のため、マルケタの返品規定が適用されます。食品・飲料は、不良品・配送中の破損・誤配送の場合を除き返品できません。破損は到着後7日以内にご連絡いただければ、無料で交換または全額返金いたします。',
    },
    bullets: {
      en: [
        'TWO WAYS TO ENJOY YUZU: two 200 g jars of yuzu marmalade and a 430 g jar of yuzu-cha (citron tea concentrate) in a gift box.',
        'THICK-CUT, GENTLY BITTER MARMALADE: whole Kagami-valley yuzu peel, sugar and yuzu juice, set with the fruit’s own pectin. At 45 Brix it is less sweet than ordinary jam, so it must be refrigerated after opening.',
        'YUZU-CHA: fine strips of peel in a honey-yuzu syrup. Stir 2 tablespoons into a cup (about 150 mL) of hot water for a warming drink, or use it with soda water, yogurt or as a glaze for meat. Contains honey: not for babies under 1 year.',
        'ALLERGENS: none of the 28 allergens labelled in Japan. Made in a kitchen that also handles soy and wheat (for the farm’s ponzu).',
        'BEST BEFORE 12 months unopened at room temperature (at least 6 months left on delivery). After opening refrigerate; marmalade within 3 weeks, yuzu-cha within 1 month.',
        'SHIPS FROM MARKETA: next day (Tue 6 Oct) for Marketa Fast members. Gift box included; free noshi paper, and gift wrap ¥330 at checkout.',
      ],
      ja: [
        '【柚子を2つの楽しみ方で】ゆずマーマレード200g×2個と、ゆず茶430g×1個をギフト箱に詰め合わせました。',
        '【厚切り皮のほろ苦いマーマレード】鏡川流域の柚子の皮、砂糖、柚子果汁だけで、果実のペクチンで仕上げています。糖度45度と一般的なジャムより甘さ控えめのため、開封後は要冷蔵です。',
        '【ゆず茶】細切りの皮をはちみつ入りの柚子シロップに漬けました。カップ1杯（約150mL）のお湯に大さじ2を溶かすと体の温まる一杯に。炭酸割り、ヨーグルト、お肉の照り焼きのたれにも。はちみつを使用しているため、1歳未満の乳児には与えないでください。',
        '【アレルギー物質】特定原材料等28品目は使用していません。同じ加工場で大豆・小麦（当園のぽん酢）を扱っています。',
        '【賞味期限】未開封・常温で12か月（お届け時に6か月以上）。開封後は冷蔵し、マーマレードは3週間、ゆず茶は1か月以内にお召し上がりください。',
        '【マルケタから発送】マルケタFast会員なら翌日、10月6日（火）にお届け。ギフト箱入り。のし紙は無料、ギフトラッピングはご注文時に330円で承ります。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Minori Yuzu Farm'], ['Contents', '2 × 200 g yuzu marmalade, 1 × 430 g yuzu-cha'],
        ['Marmalade ingredients', 'Yuzu (Minori Prefecture), sugar, yuzu juice'], ['Yuzu-cha ingredients', 'Sugar, yuzu peel (Minori Prefecture), honey, yuzu juice'],
        ['Sugar content', 'Marmalade about 45 Brix; yuzu-cha about 55 Brix'], ['Allergens', 'None of the 28 labelled allergens (yuzu-cha contains honey)'],
        ['Additives', 'No added pectin, preservatives or colourings'], ['Best before (unopened)', '12 months from production; at least 6 months left on delivery'],
        ['After opening', 'Refrigerate; marmalade within 3 weeks, yuzu-cha within 1 month'], ['Storage', 'Room temperature, away from direct sunlight, until opened'],
        ['Energy', 'Marmalade about 38 kcal per tablespoon (20 g); yuzu-cha about 95 kcal per 2 tablespoons (40 g)'],
        ['Packaging', 'Glass jars with metal lids in a printed gift box (22 × 16 × 9 cm, 1.4 kg)'], ['Producer', 'Minori Yuzu Farm (Hirose family), Tsukimi Onsen area, Minori Prefecture'],
        ['Seller / shipping', 'Sold by Minori Yuzu Farm, ships from Marketa'], ['Country of origin', 'Japan'],
        ['Guarantee', 'Damaged, faulty or wrong: replacement or refund (report within 7 days)'],
      ],
      ja: [
        ['ブランド', 'みのり柚子園'], ['内容', 'ゆずマーマレード200g×2個、ゆず茶430g×1個'],
        ['マーマレード 原材料', 'ゆず（みのり県産）、砂糖、ゆず果汁'], ['ゆず茶 原材料', '砂糖、ゆず皮（みのり県産）、はちみつ、ゆず果汁'],
        ['糖度', 'マーマレード 約45度、ゆず茶 約55度'], ['アレルギー物質', '特定原材料等28品目不使用（ゆず茶にはちみつ使用）'],
        ['添加物', 'ペクチン・保存料・着色料無添加'], ['賞味期限（未開封）', '製造から12か月（お届け時に6か月以上）'],
        ['開封後', '要冷蔵。マーマレードは3週間、ゆず茶は1か月以内'], ['保存方法', '開封前は直射日光を避けて常温'],
        ['エネルギー', 'マーマレード 大さじ1（20g）約38kcal、ゆず茶 大さじ2（40g）約95kcal'],
        ['包装', 'ガラス瓶（金属キャップ）、印刷入りギフト箱（22×16×9cm、約1.4kg）'], ['製造者', 'みのり柚子園（広瀬家）、みのり県 月見温泉近郊'],
        ['販売・発送', '販売：みのり柚子園／発送：マルケタ'], ['原産国', '日本'],
        ['品質保証', '破損・不良・誤配送は到着後7日以内のご連絡で交換または返金'],
      ],
    },
    compare: {
      en: ['2 × 200 g marmalade + 430 g yuzu-cha', '12 months (unopened)', 'None of the 28 labelled (yuzu-cha contains honey)', 'Gift box; free noshi, wrap ¥330 (Marketa)', 'Minori Yuzu Farm, near Tsukimi Onsen', 'Room temperature; refrigerate after opening'],
      ja: ['マーマレード200g×2＋ゆず茶430g', '12か月（未開封）', '28品目不使用（ゆず茶にはちみつ）', 'ギフト箱入り、のし無料・ラッピング330円（マルケタ）', 'みのり柚子園（月見温泉近郊）', '常温。開封後は冷蔵'],
    },
    description: {
      en: [
        'This set comes from the same hillside orchard as the farm’s ponzu: Minori Yuzu Farm, run by the Hirose family in the Kagami River valley near Tsukimi Onsen since 1978. The yuzu are harvested ripe in November and December, and the peel, which holds most of the fruit’s fragrance, goes into both jars.',
        'The marmalade is made the old way in small copper pans: thick-cut peel simmered with sugar and juice and set only by the fruit’s own pectin. It has a pleasant bitterness from the pith and is less sweet than ordinary jam (about 45 Brix), which is why it must go in the fridge once opened and be finished within three weeks. Children who are used to sweet jam sometimes find it too bitter.',
        'Yuzu-cha is a Korean-style citron tea concentrate: fine strips of peel in a syrup of sugar, honey and yuzu juice. Stir two tablespoons into about 150 mL of water at 80 °C or hotter and eat the peel at the end. It is sweet, so start with less if you prefer it lighter. Because it contains honey, do not give it to babies under one year old.',
        'Neither jar contains any of the 28 allergens labelled in Japan, but they are made in the farm’s kitchen, which also handles soy and wheat for the ponzu. Unopened, both keep for 12 months at room temperature; Marketa ships stock with at least 6 months left.',
        'This item is sold by Minori Yuzu Farm and shipped from Marketa’s Harukawa warehouse: Marketa Fast members get free next-day delivery on Tue 6 Oct if they order by 14:00. Without membership, standard delivery is ¥450 because the set is under ¥3,500 (free if your Marketa-shipped order reaches ¥3,500). It arrives separately from anything shipped by the farm itself, such as the ponzu set. Free noshi paper and ¥330 gift wrap can be chosen at checkout.',
      ],
      ja: [
        'ぽん酢と同じ、月見温泉近くの鏡川流域の斜面の柚子園「みのり柚子園」のセットです。1978年から広瀬家が営んでいます。11月から12月に完熟の柚子を収穫し、香りのもとである皮を両方の瓶にたっぷり使いました。',
        'マーマレードは昔ながらの小さな銅鍋で炊いています。厚切りの皮を砂糖と果汁で煮詰め、柚子そのもののペクチンだけで固めました。わたのほろ苦さがあり、一般的なジャムより甘さ控えめ（糖度約45度）。そのため開封後は冷蔵庫で保存し、3週間以内にお召し上がりください。甘いジャムに慣れたお子さまには苦く感じることがあります。',
        'ゆず茶は韓国風の柚子茶のもとで、細切りの皮を砂糖・はちみつ・柚子果汁のシロップに漬けています。80℃以上のお湯約150mLに大さじ2を溶かし、最後に皮も召し上がってください。甘めなので、すっきり飲みたい方は少なめから。はちみつを使用しているため、1歳未満の乳児には与えないでください。',
        'どちらも特定原材料等28品目は使用していませんが、ぽん酢用に大豆・小麦を扱う同じ加工場で製造しています。未開封なら常温で12か月保存でき、マルケタからは賞味期限まで6か月以上あるものを発送します。',
        '本商品はみのり柚子園が販売し、マルケタの春川倉庫から発送します。マルケタFast会員なら14時までのご注文で10月6日（火）に無料でお届け。会員でない場合、3,500円未満のため通常配送料450円がかかります（マルケタ発送の商品と合わせて3,500円以上で無料）。ぽん酢セットなど柚子園からの直送品とは別にお届けします。のし紙（無料）とギフトラッピング（330円）はご注文時にお選びいただけます。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-19', variant: 'set', helpful: 77, verified: true,
        en: { name: 'Harumi', title: 'Bitter in the best way', body: 'Proper thick-cut peel and a real bitterness, like the marmalade my grandmother made. On buttered toast it is perfect. The yuzu-cha is sweeter, but lovely on a cold morning.' },
        ja: { name: 'はるみ', title: 'ほろ苦さがたまらない', body: '厚切りの皮でしっかりほろ苦く、祖母の手作りマーマレードのようです。バタートーストに最高。ゆず茶は甘めですが、寒い朝にぴったりです。' } },
      { stars: 2, date: '2026-08-26', variant: 'set', helpful: 41, verified: true,
        en: { name: 'Kotaro', title: 'The yuzu-cha is far too sweet', body: 'The marmalade is good, but the yuzu-cha tastes like syrup with a bit of peel. Even with half the recommended amount it is too sweet for me. I would buy two marmalades instead if they sold them.' },
        ja: { name: '光太郎', title: 'ゆず茶が甘すぎる', body: 'マーマレードはおいしいですが、ゆず茶は皮の入ったシロップという感じ。表示の半分の量でも私には甘すぎます。マーマレード2個だけのセットがあればそちらを買いたいです。' } },
      { stars: 2, date: '2026-09-08', variant: 'set', helpful: 63, verified: true,
        en: { name: 'Nana', title: 'Jar smashed in delivery, the day before the birthday', body: 'The yuzu-cha jar broke and the syrup soaked everything, including the gift box. I reported it in the app with photos and Marketa sent a replacement the next day at no charge, but I had to give my mother an empty-handed promise on her birthday. Pack the jars better.' },
        ja: { name: 'なな', title: '誕生日前日に瓶が割れて届いた', body: 'ゆず茶の瓶が割れて、シロップがギフト箱までびしょびしょ。アプリから写真付きで連絡すると、マルケタが翌日に無料で代わりを送ってくれましたが、母の誕生日当日は手ぶらで「届くからね」と言うしかありませんでした。瓶の梱包をもっとしっかりしてほしいです。' } },
      { stars: 1, date: '2026-07-12', variant: 'set', helpful: 55, verified: true,
        en: { name: 'Oliver', title: 'Mould after two weeks: keep it in the fridge', body: 'I kept the opened marmalade in the cupboard as I would ordinary jam, and it grew mould within two weeks. The jar does say to refrigerate, but only in small Japanese print. Low sugar means it does not keep.' },
        ja: { name: 'オリバー', title: '2週間でかびが。冷蔵庫へ', body: '普通のジャムと同じように開封後も戸棚に置いていたら、2週間でかびが生えました。瓶には要冷蔵と書いてありますが、小さな日本語だけ。甘さ控えめなぶん日持ちしません。' } },
      { stars: 3, date: '2026-06-03', variant: 'set', helpful: 24, verified: true,
        en: { name: 'Satomi', title: 'Too bitter for my kids', body: 'I like it, but my children took one bite and refused. If you want something sweet for the family, this is not it.' },
        ja: { name: 'さとみ', title: '子どもには苦すぎた', body: '私は好きですが、子どもたちは一口でギブアップ。家族みんなで食べる甘いジャムを探しているなら、これではないと思います。' } },
      { stars: 5, date: '2026-09-29', variant: 'set', helpful: 18, verified: true,
        en: { name: 'Kenta', title: 'Yuzu-cha with the Hearth kettle', body: 'I set the Hearth kettle to 80 °C and keep it warm, so a cup of yuzu-cha is ready in seconds. Two tablespoons is just right for me. The jar is big; it lasted about three weeks of daily cups.' },
        ja: { name: '健太', title: 'ハースのケトルでゆず茶', body: 'ハースのケトルを80℃にして保温しておけば、ゆず茶がすぐに飲めます。大さじ2がちょうどいい濃さ。瓶は大きめで、毎日1杯飲んで3週間ほどもちました。' } },
      { stars: 2, date: '2026-08-14', variant: 'set', helpful: 33, verified: true,
        en: { name: 'Rie', title: 'Only 6 months left on the best-before date', body: 'The listing says 12 months, but that is from production. Mine arrived with exactly six months left, which is fine for us but short if you are buying ahead for New Year gifts.' },
        ja: { name: '理恵', title: '賞味期限まで6か月しかなかった', body: '12か月と書いてありますが、それは製造日から。届いたものは期限までちょうど6か月でした。自宅用なら問題ありませんが、お正月の贈り物用に買いだめするには短いです。' } },
      { stars: 4, date: '2026-09-25', variant: 'set', helpful: 9, verified: true,
        en: { name: 'Tom', title: 'Next day, well packed this time', body: 'With Fast it came the next afternoon, jars wrapped in paper inside the gift box. The free noshi was printed, not handwritten, which is fine. Four stars because the yuzu-cha is a bit sweet.' },
        ja: { name: 'トム', title: '翌日到着、梱包もしっかり', body: 'Fastで翌日の午後に届きました。ギフト箱の中で瓶が紙に包まれていました。無料ののしは手書きではなく印刷ですが十分。ゆず茶が少し甘いので星4つ。' } },
      { stars: 5, date: '2026-07-30', variant: 'set', helpful: 16, verified: true,
        en: { name: 'Sayaka', title: 'Ordered with the ponzu set: two deliveries', body: 'I bought this with the farm’s ponzu gift box. They come separately: the marmalade from Marketa the next day, and the ponzu from the farm two days later. Both excellent.' },
        ja: { name: 'さやか', title: 'ぽん酢セットと一緒に。届くのは別々', body: '柚子園のぽん酢ギフト箱と一緒に購入。届くのは別々で、マーマレードはマルケタから翌日、ぽん酢は園から2日後でした。どちらもとてもおいしいです。' } },
      { stars: 4, date: '2025-10-08', variant: 'set', helpful: 12, verified: true,
        en: { name: 'Akira', title: 'A good hostess gift', body: 'Took it to friends in Kamagaoka for last year’s Lantern Festival. A safe choice: nobody I know dislikes yuzu, and it keeps.' },
        ja: { name: '晃', title: '手土産に無難', body: '去年の灯籠まつりで、窯ヶ丘の友人宅への手土産にしました。柚子が嫌いな人はまわりにいないし、日持ちもするので無難な選択です。' } },
      { stars: 5, date: '2026-02-11', variant: 'set', helpful: 7, verified: false,
        en: { name: 'Momo', title: 'Got me through the winter', body: 'A cup of yuzu-cha every evening all winter. Also great stirred into plain yogurt.' },
        ja: { name: 'もも', title: '冬のお供に', body: '冬の間、毎晩ゆず茶を1杯。プレーンヨーグルトに混ぜてもおいしいです。' } },
    ],
    qa: [
      { date: '2026-04-22', votes: 29,
        en: { q: 'Can I give the yuzu-cha to my 8-month-old?', a: 'No. The yuzu-cha contains honey, which must not be given to babies under one year old. The marmalade contains no honey, but it is quite bitter for small children.', by: 'Minori Yuzu Farm' },
        ja: { q: '生後8か月の子にゆず茶を飲ませてもいいですか？', a: 'いいえ。ゆず茶にははちみつを使用しているため、1歳未満の乳児には与えないでください。マーマレードにははちみつは入っていませんが、小さなお子さまにはかなり苦く感じられると思います。', by: 'みのり柚子園' } },
      { date: '2026-07-14', votes: 21,
        en: { q: 'How long does it keep after opening?', a: 'Refrigerate after opening. Eat the marmalade within 3 weeks and the yuzu-cha within 1 month, and always use a clean, dry spoon.', by: 'Minori Yuzu Farm' },
        ja: { q: '開封後はどのくらいもちますか？', a: '開封後は冷蔵庫で保存し、マーマレードは3週間、ゆず茶は1か月以内にお召し上がりください。乾いた清潔なスプーンをお使いください。', by: 'みのり柚子園' } },
      { date: '2026-08-02', votes: 10,
        en: { q: 'Does this ship from the farm or from Marketa?', a: 'From Marketa. Mine came the next day with Fast, while the ponzu I ordered at the same time came from the farm two days later.', by: 'Marketa customer (Sayaka)' },
        ja: { q: '柚子園からの発送ですか、マルケタからですか？', a: 'マルケタからです。Fastで翌日に届きました。同時に注文したぽん酢は柚子園からで、2日後に届きました。', by: 'マルケタ購入者（さやか）' } },
      { date: '2026-05-06', votes: 4,
        en: { q: 'Is the set vegan?', a: 'Yes, it is just fruit and sugar.', by: 'Marketa customer (Jo)' },
        ja: { q: 'このセットはヴィーガン対応ですか？', a: 'はい、果物と砂糖だけなので大丈夫です。', by: 'マルケタ購入者（じょー）' } },
      { date: '2026-05-08', votes: 17,
        en: { q: 'Is the yuzu-cha vegan?', a: 'No, the yuzu-cha contains honey. The marmalade is vegan: yuzu, sugar and yuzu juice only.', by: 'Minori Yuzu Farm' },
        ja: { q: 'ゆず茶はヴィーガン対応ですか？', a: 'いいえ、ゆず茶にははちみつが入っています。マーマレードは柚子・砂糖・柚子果汁のみで、ヴィーガン対応です。', by: 'みのり柚子園' } },
    ],
    similar: ['minori-ponzu-set', 'shiroshita-senbei', 'kagami-sake-set'],
    fbt: ['minori-ponzu-set', 'kagami-mug-pair'],
    alsoViewed: ['minori-ponzu-set', 'shiroshita-senbei', 'minori-bath-salts', 'minori-hand-cream', 'kagami-mug-pair', 'hearth-kettle'],
  },
  {
    id: 'kagami-sake-set',
    cat: 'gifts',
    cluster: 'gifts',
    brand: { en: 'Kagami Kiln', ja: '鏡窯' },
    seller: 'kagami',
    images: ['kagami-sake-set'],
    title: {
      en: 'Kagami Kiln Harukawa Ware Sake Set, Tokkuri Flask 300 mL and 2 Guinomi Cups, White Ash Glaze with Indigo Drips, Signed Paulownia Box, Handmade in Harukawa, Japan, Retirement or 60th Birthday Gift',
      ja: '鏡窯 春川焼 酒器セット 徳利 300ml ぐい呑み 2客 白灰釉 藍流し 桐箱入り 共箱 手作り 日本製 還暦祝い 退職祝い 父の日 贈り物',
    },
    short: { en: 'Kagami Kiln Sake Set', ja: '鏡窯 酒器セット（桐箱入り）' },
    rating: 4.8,
    ratings: 73,
    hist: [86, 9, 2, 1, 2],
    added: '2025-03-03',
    badges: [],
    coupon: null,
    variantLabel: { en: 'Set', ja: 'セット' },
    variants: [
      { id: 'white-ash', name: { en: 'Tokkuri + 2 guinomi, white ash with indigo drips', ja: '徳利＋ぐい呑み2客（白灰釉・藍流し）' }, price: 9900, list: null, stock: 12, ship: 'kagami' },
    ],
    returns: {
      en: 'Sold and shipped by Kagami Kiln: unused items in their box can be returned within 14 days of delivery, with return shipping paid by you for a change of mind. Breakage in delivery: send photos within 48 hours for a replacement or refund without returning it. Variation in the glaze drips and natural marks in the paulownia wood are not defects.',
      ja: '鏡窯が販売・発送する商品です。箱を含め未使用の場合に限り、到着後14日以内なら返品できます（お客様都合の返送料はご負担ください）。配送中の破損は48時間以内に写真をお送りいただければ、返送不要で交換または返金いたします。釉薬の流れ方の違いや桐の木目・節は不良ではありません。',
    },
    bullets: {
      en: [
        'A SAKE SET FOR TWO: a 300 mL tokkuri flask (about 1.7 gō) and two guinomi cups of about 60 mL each, so the flask fills both cups two or three times.',
        'WHITE ASH WITH INDIGO DRIPS: indigo glaze is poured over a milky white ash glaze so it runs down from the rim during firing. Every set’s drips fall differently, from a few thin lines to wide streaks.',
        'SIGNED PAULOWNIA BOX (tomobako): the kiri wood box lid is brush-inscribed with the work’s name and signed and sealed by fourth-generation potter Kagami Sōichi, with a yellow cotton wrapping cloth.',
        'WARM OR CHILLED: warm sake by standing the tokkuri in a pan of just-boiled water (about 3 minutes for nurukan, 40 °C). Not for the microwave, a direct flame or the dishwasher; wash by hand.',
        'NOSHI FREE, GIFT WRAP ¥330: choose 御祝, 御礼, 還暦御祝, 退職御祝, 寿 and more, with inner or outer noshi. Ideal for retirement, a 60th birthday or a thank-you.',
        'ARRIVES THU 8 – FRI 9 OCT, before the Lantern Festival, with free shipping (Kagami Kiln orders of ¥5,000 or more).',
      ],
      ja: [
        '【2人で楽しむ酒器セット】徳利300mL（約1.7合）と、約60mLのぐい呑み2客。徳利1本でぐい呑み2客に2〜3回ずつ注げます。',
        '【白灰釉に藍流し】乳白色の白灰釉の上から藍釉を流し掛け、焼成中に口縁から流れ落ちる景色をつくっています。細い筋が数本のものから太く流れるものまで、一つとして同じものはありません。',
        '【作家の共箱（桐箱）】桐箱のふたには、4代目 鏡 宗一が作品名を筆で書き、署名・落款を入れています。黄色の木綿の布包み付き。',
        '【燗でも冷やでも】沸かしたてのお湯を張った鍋に徳利を立てて温めます（ぬる燗40℃なら約3分）。電子レンジ・直火・食洗機は不可。手洗いしてください。',
        '【のし無料・ラッピング330円】御祝・御礼・還暦御祝・退職御祝・寿など、内のし・外のしをお選びいただけます。退職祝い、還暦祝い、お礼の品に。',
        '【10月8日（木）〜9日（金）お届け】灯籠まつりの前に届きます。鏡窯でのご注文5,000円以上で送料無料。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Kagami Kiln (Harukawa, Minori Prefecture)'], ['Ware', 'Harukawa ware (春川焼), stoneware'], ['Contents', 'Tokkuri ×1, guinomi ×2'],
        ['Tokkuri capacity', '300 mL to the shoulder (about 1.7 gō)'], ['Tokkuri size', 'Ø8 × H14 cm, about 380 g'],
        ['Guinomi capacity', 'About 60 mL each'], ['Guinomi size', 'Ø6.5 × H5 cm, about 90 g each'], ['Glaze', 'White ash glaze with indigo drips (lead-free)'],
        ['Box', 'Paulownia (kiri) wood, lid signed and sealed by Kagami Sōichi, yellow cotton cloth'], ['Boxed size and weight', '24 × 16 × 16 cm, about 1.1 kg'],
        ['Warming', 'Hot-water bath only'], ['Microwave', 'No'], ['Dishwasher', 'No (hand wash)'],
        ['Country of origin', 'Japan (Harukawa)'], ['Warranty', 'No manufacturer warranty; breakage in delivery handled by the seller (report within 48 hours)'],
        ['In the box', 'Tokkuri, 2 guinomi, paulownia box, cotton cloth, care leaflet (English/Japanese)'],
      ],
      ja: [
        ['ブランド', '鏡窯（みのり県春川市）'], ['種類', '春川焼（陶器）'], ['内容', '徳利×1、ぐい呑み×2'],
        ['徳利容量', '300mL（肩まで）、約1.7合'], ['徳利サイズ', '直径8×高さ14cm、約380g'],
        ['ぐい呑み容量', '各約60mL'], ['ぐい呑みサイズ', '直径6.5×高さ5cm、1客約90g'], ['釉薬', '白灰釉・藍流し（無鉛）'],
        ['箱', '桐箱（共箱）、ふたに鏡 宗一の署名・落款、黄色の木綿布包み'], ['箱込みサイズ・重量', '24×16×16cm、約1.1kg'],
        ['燗のつけ方', '湯煎のみ'], ['電子レンジ', '使用不可'], ['食洗機', '使用不可（手洗い）'],
        ['原産国', '日本（春川市）'], ['保証', 'メーカー保証なし（配送中の破損は到着後48時間以内のご連絡で出品者が対応）'],
        ['付属品', '徳利、ぐい呑み2客、桐箱、布包み、お手入れのしおり（日英）'],
      ],
    },
    compare: {
      en: ['Tokkuri 300 mL + 2 guinomi', 'Not applicable (tableware)', 'Not applicable', 'Signed paulownia box; noshi free, wrap ¥330', 'Kagami Kiln, Harukawa (handmade)', 'Dry fully before boxing; keep the box dry'],
      ja: ['徳利300mL＋ぐい呑み2客', '該当なし（器）', '該当なし', '桐の共箱入り、のし無料・ラッピング330円', '鏡窯（春川・手作り）', 'よく乾かしてから箱へ。箱は湿気を避けて'],
    },
    tables: [
      {
        title: { en: 'Warming sake in the tokkuri', ja: '徳利での燗のつけ方' },
        en: [
          ['Style', 'Temperature', 'Time in a pan of just-boiled water (300 mL)'],
          ['Hinata-kan (sun-warm)', 'About 30 °C', '1–2 min'],
          ['Nuru-kan (lukewarm)', 'About 40 °C', 'About 3 min'],
          ['Jō-kan (warm)', 'About 45 °C', 'About 4 min'],
          ['Atsu-kan (hot)', 'About 50 °C', 'About 5 min'],
        ],
        ja: [
          ['燗', '温度', '沸かしたてのお湯での目安（300mL）'],
          ['日向燗', '約30℃', '1〜2分'],
          ['ぬる燗', '約40℃', '約3分'],
          ['上燗', '約45℃', '約4分'],
          ['熱燗', '約50℃', '約5分'],
        ],
      },
    ],
    description: {
      en: [
        'This set pairs two of the oldest Harukawa ware glazes. The milky white ash glaze is made at Kagami Kiln from wood ash and feldspar, and the indigo is poured over it from the rim, so that in the 1,250 °C firing it runs down the sides in streaks. Kagami Kiln has made sake ware in Kamagaoka, above the Kagami River, since it was founded in 1891; today the work is led by fourth-generation potter Kagami Sōichi.',
        'Each tokkuri is thrown on the wheel and its neck is narrowed by hand, so the flask pours in a thin, steady stream. Capacities vary by a few millilitres, and the drips on the flask and the two cups will not match each other exactly: they are made and glazed as a set but run in their own way in the kiln. The photos show a typical set; yours may have fewer or wider drips.',
        'For warm sake, stand the filled tokkuri in a pan of water just off the boil (see the table: about 3 minutes for nuru-kan). The narrow neck stays cool enough to hold. Do not heat it in a microwave or on a flame: the narrow neck heats unevenly and can crack. Wash by hand, rinse well so no sake smell remains, and dry the inside upside down for a day before storing.',
        'The set comes in a paulownia (kiri) tomobako, a box whose lid is brush-inscribed and signed by the potter, the traditional way to present Japanese ceramics as a gift. Paulownia breathes and keeps out damp, but it dents easily, so the box is shipped inside a padded outer carton. Noshi paper is free: write the inscription (御祝, 還暦御祝, 退職御祝, 御礼, 寿 and so on), the name, and inner or outer noshi in the order notes. Gift wrapping is ¥330.',
        'Kagami Kiln ships within 2 business days, so the set arrives Thu 8 – Fri 9 Oct in Harukawa city, before the Lantern Festival, with free shipping. Unused items can be returned within 14 days (you pay return shipping for a change of mind). Please open the outer carton the day it arrives: breakage must be reported within 48 hours.',
      ],
      ja: [
        '春川焼でも古くから使われてきた2つの釉薬を組み合わせた酒器セットです。鏡窯で木の灰と長石から調合する乳白色の白灰釉の上に、口縁から藍釉を流し掛けると、約1,250℃の焼成で側面を筋になって流れ落ちます。鏡窯は1891年の創業以来、鏡川を見下ろす窯ヶ丘で酒器を作り続けてきました。現在は4代目の鏡 宗一が中心となって制作しています。',
        '徳利は一つずつろくろで挽き、首を手で絞っているため、細く安定した線で注げます。容量には数ミリリットルの差があります。徳利とぐい呑みの藍の流れ方はそろいません。セットとして作り、同じように釉掛けしても、窯の中でそれぞれに流れるためです。写真は一例で、お届けするものは流れが少なかったり太かったりします。',
        '燗をつけるときは、お酒を入れた徳利を沸騰直後のお湯を張った鍋に立ててください（ぬる燗なら約3分。表を参照）。首の部分は持てる程度の熱さにとどまります。電子レンジや直火は、細い首が不均一に熱されて割れるおそれがあるため不可です。手洗いし、お酒のにおいが残らないようよくすすいで、逆さにして丸1日中まで乾かしてからしまってください。',
        '作家がふたに作品名を書き、署名した桐の共箱入り。和の器を贈るときの正式なかたちです。桐は湿気を通しにくく器を守りますが、へこみやすいため、緩衝材入りの外箱に入れて発送します。のしは無料です。表書き（御祝・還暦御祝・退職御祝・御礼・寿など）、お名前、内のし・外のしの別をご注文時の備考欄にご記入ください。ギフトラッピングは330円です。',
        '鏡窯から2営業日以内に発送し、春川市内には10月8日（木）〜9日（金）、灯籠まつりの前にお届けします。送料無料。未使用品は到着後14日以内なら返品できます（お客様都合の返送料はご負担ください）。破損のご連絡は48時間以内に限られるため、届いた日に外箱を開けてご確認ください。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-17', variant: 'white-ash', helpful: 38, verified: true,
        en: { name: 'Takashi', title: 'Retirement gift for my father', body: 'My father retired after 38 years at the city office and this was our family’s gift, with a 退職御祝 noshi. When he saw the signed paulownia box he went quiet, then opened his best bottle that evening. The indigo runs down the flask like rain on a window.' },
        ja: { name: '隆', title: '父の退職祝いに', body: '市役所に38年勤めた父の退職祝いに、家族から「退職御祝」ののしを付けて贈りました。署名入りの桐箱を見て父はしばらく黙り込み、その晩いちばんいいお酒を開けていました。徳利を流れる藍が窓をつたう雨のようです。' } },
      { stars: 5, date: '2026-07-26', variant: 'white-ash', helpful: 21, verified: true,
        en: { name: 'Mr. Nishida', title: 'Pours without a drip', body: 'The neck is shaped well; it pours a thin stream and stops cleanly. I warm sake in it most evenings in a pan of hot water, about three minutes, exactly as the leaflet says.' },
        ja: { name: '西田', title: '切れが良い徳利', body: '首の形が良く、細く注げて最後もきれいに切れます。ほぼ毎晩、しおりのとおり湯煎で3分ほど燗をつけています。' } },
      { stars: 2, date: '2026-09-26', variant: 'white-ash', helpful: 29, verified: true,
        en: { name: 'Noriko', title: 'Paulownia box arrived dented', body: 'The ceramics were fine, but one corner of the paulownia box was dented and the lid scratched, even inside the padded carton. Since nothing was broken it was not “breakage”, but the kiln kindly sent a new box free of charge. It took a week, though, so I had to hand over the gift in the dented one.' },
        ja: { name: '典子', title: '桐箱がへこんで届いた', body: '器は無事でしたが、緩衝材入りの外箱の中でも桐箱の角がへこみ、ふたに擦り傷がありました。割れていないので「破損」にはあたりませんが、窯元のご厚意で新しい箱を無料で送ってもらえました。ただ1週間かかったので、贈り物はへこんだ箱のまま渡すことに。' } },
      { stars: 1, date: '2026-08-03', variant: 'white-ash', helpful: 33, verified: true,
        en: { name: 'Jiro', title: 'Tokkuri chipped in delivery; replacement doesn’t match', body: 'There was a chip on the tokkuri’s lip when I unpacked it. I sent photos within the 48 hours and the kiln replaced it without asking for it back, but the new tokkuri’s blue drips look quite different from the cups, so it no longer feels like a set.' },
        ja: { name: '次郎', title: '配送で徳利が欠け、交換品は柄がそろわず', body: '開けたら徳利の口が欠けていました。48時間以内に写真を送ると返送不要で交換してもらえましたが、新しい徳利は藍の流れ方がぐい呑みとまるで違い、セットという感じがしなくなりました。' } },
      { stars: 1, date: '2026-07-14', variant: 'white-ash', helpful: 21, verified: true,
        en: { name: 'Bob', title: 'The cups are tiny', body: 'Sixty millilitres each: two sips. For ¥9,900 I expected bigger cups. If you want something to actually drink from, buy the Kagami Kiln mug pair instead.' },
        ja: { name: 'ボブ', title: 'ぐい呑みが小さすぎる', body: '1客60mLで、ふた口で終わり。9,900円ならもっと大きいと思っていました。たっぷり飲みたいなら、鏡窯のペアマグを買ったほうがいいです。' } },
      { stars: 5, date: '2026-08-19', variant: 'white-ash', helpful: 26, verified: true,
        en: { name: 'Kazuo', title: 'Small cups are the point', body: 'Guinomi are meant to be small: you pour for each other, a little at a time. Sixty millilitres is a generous guinomi. Beautiful work.' },
        ja: { name: '和夫', title: '小さいのがいい', body: 'ぐい呑みは小さいもの。少しずつ注ぎ合うのが楽しいのです。60mLはぐい呑みとしてはむしろたっぷり。見事な仕事です。' } },
      { stars: 3, date: '2026-06-29', variant: 'white-ash', helpful: 17, verified: true,
        en: { name: 'Yui', title: 'Much less indigo than the photo', body: 'Mine has only three thin blue lines on the flask and almost none on the cups. The photo shows wide drips. The kiln says it is variation. It is still pretty, but not what I chose it for.' },
        ja: { name: 'ゆい', title: '写真より藍がかなり少ない', body: '届いたものは徳利に細い藍の筋が3本だけで、ぐい呑みにはほとんどありません。写真では太く流れていたのに。窯元は個体差とのこと。きれいではありますが、選んだ理由はそこだったので。' } },
      { stars: 4, date: '2026-01-21', variant: 'white-ash', helpful: 11, verified: true,
        en: { name: 'Hiroshi', title: 'Good for warm sake in winter', body: 'The hot-water method works well and the neck stays cool. One star off because the narrow inside is hard to dry; I stand it upside down in a glass overnight.' },
        ja: { name: '博', title: '冬の燗酒に', body: '湯煎でうまく燗がつき、首も熱くなりません。中が細くて乾きにくいので星ひとつ減。ひと晩コップに逆さに立てて乾かしています。' } },
      { stars: 5, date: '2025-10-14', variant: 'white-ash', helpful: 14, verified: true,
        en: { name: 'Ellen', title: 'Toasting at the Lantern Festival', body: 'Ordered on the Monday of festival week and it arrived on Thursday. We took it to the riverbank on Saturday night and drank cold sake while the lanterns floated past. A very Harukawa memory.' },
        ja: { name: 'エレン', title: '灯籠まつりで乾杯', body: 'まつりの週の月曜に注文して木曜に届きました。土曜の夜に河原へ持っていき、流れていく灯籠を眺めながら冷酒を。春川らしい思い出になりました。' } },
      { stars: 2, date: '2026-05-02', variant: 'white-ash', helpful: 12, verified: true,
        en: { name: 'Masaki', title: 'Mine dribbles', body: 'Unlike other reviewers, mine dribbles down the neck unless I pour quickly. Handmade, so I suppose it depends on the piece. Lovely to look at.' },
        ja: { name: 'まさき', title: 'うちのは垂れます', body: 'ほかの方と違い、うちの徳利は勢いよく注がないと首をつたって垂れます。手作りなので個体差でしょう。見た目はすてきです。' } },
    ],
    qa: [
      { date: '2026-09-10', votes: 19,
        en: { q: 'Can the noshi go inside the gift wrapping?', a: 'Yes. Write 内のし (inside the wrapping) or 外のし (outside) in the order notes. Without gift wrapping, the noshi goes directly on the paulownia box.', by: 'Kagami Kiln' },
        ja: { q: 'のしを包装紙の内側に付けられますか？', a: 'はい。ご注文時の備考欄に「内のし」または「外のし」とご記入ください。ラッピングなしの場合は、桐箱に直接のしをお掛けします。', by: '鏡窯' } },
      { date: '2026-02-04', votes: 15,
        en: { q: 'Can I warm sake in the microwave?', a: 'Please do not. The narrow neck heats unevenly in a microwave and can crack. Stand the tokkuri in a pan of just-boiled water instead; about 3 minutes gives nuru-kan.', by: 'Kagami Kiln' },
        ja: { q: '電子レンジで燗をつけてもいいですか？', a: 'お控えください。細い首の部分が不均一に加熱されて割れるおそれがあります。沸騰直後のお湯に徳利を立てて温めてください。約3分でぬる燗になります。', by: '鏡窯' } },
      { date: '2026-06-18', votes: 12,
        en: { q: 'Is the writing on the box lid done by hand?', a: 'Yes. Each lid is brush-inscribed with the work’s name and signed and sealed by Kagami Sōichi himself.', by: 'Kagami Kiln' },
        ja: { q: '箱のふたの字は手書きですか？', a: 'はい。一つずつ鏡 宗一本人が筆で作品名を書き、署名・落款を入れております。', by: '鏡窯' } },
      { date: '2026-10-02', votes: 5,
        en: { q: 'Will it arrive before the Lantern Festival if I order this weekend?', a: 'Mine arrived three days after ordering, so it should. Order by Monday to be safe.', by: 'Marketa customer (Ellen)' },
        ja: { q: '今週末に注文したら灯籠まつりに間に合いますか？', a: '私のときは注文から3日で届いたので、間に合うと思います。念のため月曜までに注文するのがおすすめです。', by: 'マルケタ購入者（エレン）' } },
    ],
    similar: ['minori-ponzu-set', 'minori-marmalade-set', 'shiroshita-senbei'],
    fbt: ['kagami-mug-pair', 'shiroshita-senbei'],
    alsoViewed: ['kagami-mug-pair', 'kagami-tea-set', 'kagami-plate-set', 'minori-ponzu-set', 'shiroshita-senbei', 'kagami-donabe'],
  },
  {
    id: 'shiroshita-senbei',
    cat: 'gifts',
    cluster: 'gifts',
    brand: { en: 'Shiroshita Seika', ja: '城下製菓' },
    seller: 'marketa',
    images: ['shiroshita-senbei'],
    title: {
      en: 'Shiroshita Seika Harukawa Castle Senbei Assortment, 6 Flavours, Individually Wrapped Rice Crackers in a Castle Gift Box, Harukawa Souvenir (24 or 36 Pieces)',
      ja: '城下製菓 春川城せんべい 詰め合わせ 6種 個包装 化粧箱入り 春川みやげ 手土産 お菓子 ギフト 24枚入／36枚入',
    },
    short: { en: 'Shiroshita Castle Senbei Assortment', ja: '城下製菓 春川城せんべい詰め合わせ' },
    rating: 4.4,
    ratings: 2115,
    hist: [65, 19, 8, 3, 5],
    added: '2021-10-01',
    badges: ['bestseller'],
    coupon: { amount: 150, en: 'Save ¥150 with coupon', ja: '150円OFFクーポン' },
    variantLabel: { en: 'Size', ja: '内容量' },
    variants: [
      { id: 'p24', name: { en: '24 pieces (6 flavours × 4)', ja: '24枚入（6種×4枚）' }, price: 2160, list: null, stock: 120, ship: 'fast' },
      { id: 'p36', name: { en: '36 pieces (6 flavours × 6)', ja: '36枚入（6種×6枚）' }, price: 3240, list: null, stock: 26, ship: 'fast2' },
    ],
    returns: {
      en: 'Sold and shipped by Marketa. Food cannot be returned unless it is defective, damaged in delivery or the wrong item; report damage, such as a crushed box with many broken crackers, within 7 days of delivery for a free replacement or full refund.',
      ja: 'マルケタが販売・発送する商品です。食品のため、不良品・配送中の破損・誤配送の場合を除き返品できません。箱がつぶれて多くのおせんべいが割れていたなどの破損は、到着後7日以内にご連絡いただければ、無料で交換または全額返金いたします。',
    },
    bullets: {
      en: [
        'HARUKAWA’S CLASSIC SOUVENIR: baked by Shiroshita Seika, a confectioner beside the Harukawa Castle moat since 1921. Each cracker is stamped with the castle’s crest.',
        'SIX FLAVOURS: soy sauce, nori seaweed, black sesame, shrimp (ebi), yuzu sugar made with Minori yuzu, and sea salt, in equal numbers in both sizes.',
        'ALLERGENS: wheat, soy, sesame and shrimp. Shrimp is in the ebi senbei only, but all six flavours are baked on the same line, so the box is not suitable for anyone with a shrimp allergy, even with the shrimp crackers removed.',
        'BEST BEFORE 90 DAYS from baking, with at least 60 days left on delivery. Each cracker is individually wrapped, so they stay crisp; store at room temperature away from heat and damp.',
        'TWO SIZES: 24 pieces (21 × 28 cm box) for a family visit, 36 pieces (28 × 32 cm box) for an office or a large family. Each cracker is about 7 cm across and fairly hard.',
        'GIFT-READY: free noshi paper and gift wrap ¥330 at checkout. The 24-piece box arrives tomorrow for Fast members; the 36-piece box ships from outside Minori Prefecture (Fast: Thu 8 Oct; standard: Sat 10 Oct).',
      ],
      ja: [
        '【春川みやげの定番】1921年創業、春川城のお堀端の菓子店「城下製菓」が焼き上げます。一枚一枚に春川城の家紋入り。',
        '【6種の味】醤油、青のり、黒ごま、海老、みのり産柚子の柚子ざらめ、塩。どちらのサイズも6種同じ枚数ずつ入っています。',
        '【アレルギー物質】小麦・大豆・ごま・えび。えびは海老せんべいのみに使用していますが、6種すべてを同じ製造ラインで焼いているため、海老せんべいを除いてもえびアレルギーの方には適しません。',
        '【賞味期限は製造から90日】お届け時に60日以上あるものを発送します。個包装で湿気にくく、直射日光・高温多湿を避けて常温で保存してください。',
        '【2つのサイズ】24枚入（箱21×28cm）はご家族への手土産に、36枚入（箱28×32cm）は職場や大家族に。1枚は直径約7cmで、やや硬めの歯ごたえです。',
        '【贈り物に】のし紙は無料、ギフトラッピングはご注文時に330円。24枚入はFast会員なら明日お届け。36枚入は県外の倉庫から発送のため、Fast会員は10月8日（木）、通常配送は10月10日（土）のお届けです。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Shiroshita Seika'], ['Maker', 'Shiroshita Seika Co., Ltd., Harukawa (founded 1921)'],
        ['Contents', '24 pieces (6 flavours × 4) or 36 pieces (6 flavours × 6)'], ['Flavours', 'Soy sauce, nori, black sesame, shrimp, yuzu sugar, sea salt'],
        ['Main ingredients', 'Non-glutinous rice (Minori Prefecture), soy sauce (soybeans, wheat), sugar, black sesame, shrimp, green nori, yuzu peel, sea salt (Minori Bay)'],
        ['Allergens', 'Wheat, soy, sesame, shrimp (all flavours made on a shared line)'], ['Best before', '90 days from baking (at least 60 days left on delivery)'],
        ['Storage', 'Room temperature, away from direct sunlight, heat and humidity'], ['Piece size', 'About 7 cm across, 6 mm thick'],
        ['Energy', 'About 38 kcal per piece'], ['Packaging', 'Each piece individually wrapped; castle-print gift box'],
        ['Box size and weight', '24 pieces: 21 × 28 × 5 cm, 520 g. 36 pieces: 28 × 32 × 5 cm, 760 g'],
        ['Country of origin', 'Japan (Harukawa)'], ['Sold by', 'Marketa'],
        ['Guarantee', 'Damaged, defective or wrong: replacement or refund (report within 7 days)'],
      ],
      ja: [
        ['ブランド', '城下製菓'], ['製造者', '株式会社城下製菓（春川市、1921年創業）'],
        ['内容', '24枚（6種×4枚）または36枚（6種×6枚）'], ['味', '醤油、青のり、黒ごま、海老、柚子ざらめ、塩'],
        ['主な原材料', 'うるち米（みのり県産）、しょうゆ（大豆・小麦を含む）、砂糖、黒ごま、えび、青のり、ゆず皮、食塩（みのり湾産）'],
        ['アレルギー物質', '小麦・大豆・ごま・えび（全種を同じラインで製造）'], ['賞味期限', '製造から90日（お届け時に60日以上）'],
        ['保存方法', '直射日光・高温多湿を避けて常温で保存'], ['1枚のサイズ', '直径約7cm、厚さ約6mm'],
        ['エネルギー', '1枚あたり約38kcal'], ['包装', '1枚ずつ個包装、春川城の絵柄入り化粧箱'],
        ['箱サイズ・重量', '24枚入：21×28×5cm・約520g／36枚入：28×32×5cm・約760g'],
        ['原産国', '日本（春川市）'], ['販売', 'マルケタ'],
        ['品質保証', '破損・不良・誤配送は到着後7日以内のご連絡で交換または返金'],
      ],
    },
    compare: {
      en: ['24 or 36 pieces, 6 flavours', '90 days from baking (60+ days on delivery)', 'Wheat, soy, sesame, shrimp', 'Castle-print box; free noshi, wrap ¥330 (Marketa)', 'Shiroshita Seika, Harukawa', 'Room temperature, away from damp'],
      ja: ['24枚または36枚、6種', '製造から90日（お届け時60日以上）', '小麦・大豆・ごま・えび', '春川城柄の化粧箱、のし無料・ラッピング330円（マルケタ）', '城下製菓（春川）', '常温、湿気を避けて'],
    },
    tables: [
      {
        title: { en: 'What’s in the box', ja: '詰め合わせの内容' },
        en: [
          ['Flavour', '24 pieces', '36 pieces', 'Contains'],
          ['Soy sauce', '4', '6', 'Wheat, soy'],
          ['Nori seaweed', '4', '6', 'Wheat, soy'],
          ['Black sesame', '4', '6', 'Wheat, soy, sesame'],
          ['Shrimp (ebi)', '4', '6', 'Shrimp, wheat, soy'],
          ['Yuzu sugar', '4', '6', 'None of the 28 listed (shared line)'],
          ['Sea salt', '4', '6', 'None of the 28 listed (shared line)'],
          ['All flavours', '', '', 'May contain shrimp, sesame, wheat and soy (shared baking line)'],
        ],
        ja: [
          ['味', '24枚入', '36枚入', 'アレルギー物質'],
          ['醤油', '4', '6', '小麦・大豆'],
          ['青のり', '4', '6', '小麦・大豆'],
          ['黒ごま', '4', '6', '小麦・大豆・ごま'],
          ['海老', '4', '6', 'えび・小麦・大豆'],
          ['柚子ざらめ', '4', '6', '28品目不使用（同一ラインで製造）'],
          ['塩', '4', '6', '28品目不使用（同一ラインで製造）'],
          ['全種共通', '', '', 'えび・ごま・小麦・大豆が混入する可能性があります（同一ラインで焼成）'],
        ],
      },
    ],
    description: {
      en: [
        'Shiroshita Seika has baked rice crackers beside the outer moat of Harukawa Castle since 1921, and this assortment has been the city’s standard souvenir for decades. The name means “below the castle”, and every cracker is stamped with the castle’s crest. They are made from Minori Prefecture rice, pressed into discs, dried for two days and baked twice on iron plates, which gives them their firm, crunchy bite.',
        'There are six flavours in equal numbers: soy sauce, brushed with the shop’s own blend and baked again; nori; black sesame; shrimp, with whole small shrimp pressed into the dough; yuzu sugar, glazed with sugar and Minori Yuzu Farm peel; and sea salt from Minori Bay. They are on the hard side. Most people find them pleasantly crunchy, but they may be difficult for very young children or anyone with weak teeth.',
        'Allergens: wheat and soy (soy sauce), sesame and shrimp. All six flavours are baked on the same line, so even the yuzu sugar and salt crackers may contain traces of shrimp and sesame. If anyone you are giving them to has a shrimp or crab allergy, choose a different gift; taking out the shrimp crackers is not enough.',
        'Best before is 90 days from baking, printed on the side of the box, and Marketa ships stock with at least 60 days left. Each piece is individually wrapped, so an opened box stays crisp for weeks; once a wrapper is opened, eat that cracker the same day. Keep the box at room temperature away from the stove and humidity.',
        'Both sizes are sold and shipped by Marketa. The 24-piece box is in stock in Harukawa: Fast members get it free tomorrow, Tue 6 Oct, if they order by 14:00. The 36-piece box ships from a warehouse outside Minori Prefecture: Thu 8 Oct for Fast members, Sat 10 Oct, the first day of the Lantern Festival, by standard delivery. Free noshi paper and gift wrap (¥330) can be added at checkout. Food cannot be returned, but a crushed box with broken crackers counts as damage in delivery: report it within 7 days.',
      ],
      ja: [
        '城下製菓は1921年から春川城の外堀のほとりでおせんべいを焼き続けている菓子店で、この詰め合わせは長年、春川みやげの定番です。店名は「城の下」の意味で、一枚一枚に春川城の家紋を押しています。みのり県産のうるち米を円形に打ち抜き、2日間乾燥させてから鉄板で二度焼きすることで、しっかりした歯ごたえに仕上げています。',
        '6種類を同じ枚数ずつ詰め合わせています。店の自家製だれを塗って焼き直した醤油、青のり、黒ごま、小えびを丸ごと生地に押し込んだ海老、みのり柚子園の柚子皮と砂糖をからめた柚子ざらめ、みのり湾の塩。やや硬めで、多くの方には心地よい歯ごたえですが、小さなお子さまや歯の弱い方には食べにくい場合があります。',
        'アレルギー物質は、しょうゆ由来の小麦・大豆、ごま、えびです。6種すべてを同じラインで焼いているため、柚子ざらめや塩にも、えびやごまが混入する可能性があります。贈る相手にえび・かにのアレルギーがある方がいる場合は、海老せんべいを抜くだけでは不十分ですので、別の品をお選びください。',
        '賞味期限は製造から90日で、箱の側面に記載しています。マルケタからは期限まで60日以上あるものを発送します。個包装なので、箱を開けても数週間はぱりっとしたまま。袋を開けたものはその日のうちにお召し上がりください。コンロのそばや湿気の多い場所を避け、常温で保存してください。',
        'どちらのサイズもマルケタが販売・発送します。24枚入は春川の倉庫に在庫があり、Fast会員なら14時までのご注文で明日10月6日（火）に無料でお届け。36枚入はみのり県外の倉庫からの発送で、Fast会員は10月8日（木）、通常配送では灯籠まつり初日の10月10日（土）のお届けです。のし紙（無料）とギフトラッピング（330円）はご注文時に追加できます。食品のため返品はできませんが、箱がつぶれておせんべいが割れていた場合は配送中の破損として、7日以内にご連絡ください。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-20', variant: 'p24', helpful: 140, verified: true,
        en: { name: 'Sumiko', title: 'Our family’s favourite souvenir', body: 'We have taken these to relatives every time we visit for thirty years. Same taste as always, and the castle crest on each one makes them feel special. The yuzu sugar ones disappear first.' },
        ja: { name: '澄子', title: 'わが家の定番のおみやげ', body: '30年来、親戚を訪ねるときはいつもこれ。昔と変わらない味で、一枚ずつお城の家紋があるのが特別感があります。柚子ざらめから先になくなります。' } },
      { stars: 1, date: '2026-08-31', variant: 'p24', helpful: 112, verified: true,
        en: { name: 'Ryo', title: 'We removed the shrimp ones; it was not enough', body: 'My son is allergic to shrimp, so we took out the ebi crackers and let him have a salt one. He came out in hives within twenty minutes. Only then did I read the back of the box: all flavours are made on the same line. The page does say this, but I missed it. If there is a shrimp allergy in the family, do not buy this at all.' },
        ja: { name: '亮', title: '海老せんべいを抜いても駄目でした', body: '息子にえびアレルギーがあるので、海老せんべいだけ除いて塩味を食べさせたところ、20分ほどでじんましんが出ました。そこで初めて箱の裏を読み、全種が同じラインで作られていると知りました。商品ページにも書いてあるのに見落としていました。家族にえびアレルギーの人がいるなら、そもそも買わないでください。' } },
      { stars: 2, date: '2026-09-16', variant: 'p36', helpful: 66, verified: true,
        en: { name: 'Mio', title: 'Box crushed, a third of them broken', body: 'The box arrived crushed at one corner and 12 of the 36 crackers were broken into pieces inside their wrappers. Marketa refunded me after I sent photos, no problem, but I needed it for a visit that afternoon and had nothing to bring.' },
        ja: { name: 'みお', title: '箱がつぶれ、3分の1が割れていた', body: '箱の角がつぶれて届き、36枚中12枚が袋の中で粉々に。写真を送るとマルケタはすぐ返金してくれましたが、その日の午後の訪問に持っていく予定だったので、手ぶらで行くことになりました。' } },
      { stars: 2, date: '2026-07-22', variant: 'p24', helpful: 38, verified: true,
        en: { name: 'Isamu', title: 'Too hard for my parents', body: 'These are the thick, hard kind. My father is 80 and could not bite them at all; my mother broke them into pieces and soaked them in tea. Choose something softer for elderly relatives.' },
        ja: { name: '勇', title: '親には硬すぎました', body: '厚くて硬いタイプです。80歳の父はまったく噛めず、母は割ってお茶に浸して食べていました。高齢の方への手土産なら、もっとやわらかいものを。' } },
      { stars: 5, date: '2026-08-12', variant: 'p24', helpful: 27, verified: true,
        en: { name: 'Natsuki', title: 'Crunchy, not rock-hard', body: 'I was worried by the reviews about hardness, but they are crisp and light, not tooth-breaking at all. My grandmother, who is 85, eats the salt ones happily.' },
        ja: { name: 'なつき', title: 'ぱりっと軽い、硬すぎない', body: '硬いというレビューが気になっていましたが、ぱりっと軽い食感で歯が折れるようなことはありません。85歳の祖母も塩味をおいしそうに食べています。' } },
      { stars: 3, date: '2026-06-25', variant: 'p24', helpful: 22, verified: true,
        en: { name: 'Wataru', title: 'The soy sauce ones are very salty', body: 'The yuzu sugar ones are wonderful and the sesame ones good, but the soy sauce crackers are so salty I need a glass of water after one. Uneven assortment.' },
        ja: { name: '渉', title: '醤油味がかなりしょっぱい', body: '柚子ざらめは絶品、黒ごまもおいしいのですが、醤油は1枚で水が欲しくなるほどしょっぱいです。味によって当たり外れがあります。' } },
      { stars: 3, date: '2026-09-04', variant: 'p36', helpful: 31, verified: true,
        en: { name: 'Kana', title: 'Best-before date shorter than I expected', body: 'I read “90 days” and planned to keep a box for New Year, but that is from baking. Mine arrived with 64 days left, so it will not last until January.' },
        ja: { name: 'かな', title: '思ったより賞味期限が短い', body: '「90日」とあったのでお正月用にとっておくつもりでしたが、製造日からの日数でした。届いた時点で残り64日、1月まではもちません。' } },
      { stars: 5, date: '2026-09-02', variant: 'p36', helpful: 17, verified: true,
        en: { name: 'Steve', title: 'Perfect office gift', body: 'Bought the 36-piece box for my team. Individually wrapped, so easy to share. It took five days without Fast because it ships from outside the prefecture; fine for us.' },
        ja: { name: 'スティーブ', title: '職場へのおみやげに最適', body: 'チーム用に36枚入を購入。個包装なので配りやすいです。県外からの発送でFastなしだと5日かかりましたが、うちは問題ありませんでした。' } },
      { stars: 5, date: '2026-09-27', variant: 'p24', helpful: 12, verified: true,
        en: { name: 'Akiko', title: 'With green tea from the Kagami Kiln set', body: 'Sencha from my Kagami Kiln kyusu and a black sesame senbei is my afternoon treat now. The castle crest is a nice touch.' },
        ja: { name: '明子', title: '鏡窯の急須で淹れた煎茶と', body: '鏡窯の急須で淹れた煎茶と黒ごませんべいが、最近の午後の楽しみです。家紋入りなのもうれしい。' } },
      { stars: 2, date: '2026-05-15', variant: 'p24', helpful: 29, verified: true,
        en: { name: 'Keisuke', title: 'Two wrappers unsealed, crackers soft', body: 'Two of the wrappers were not sealed and those crackers had gone soft and tasted stale. Marketa sent a replacement box after I reported it, but this is a gift item and quality control should catch that.' },
        ja: { name: '圭介', title: '個包装が2枚開いていて湿気っていた', body: '2枚の袋がきちんと閉じておらず、そのおせんべいはしけて古い味がしました。連絡するとマルケタが代わりの箱を送ってくれましたが、贈答品なので検品でしっかり防いでほしいです。' } },
      { stars: 5, date: '2025-10-15', variant: 'p24', helpful: 15, verified: true,
        en: { name: 'Lena', title: 'Brought to last year’s Lantern Festival', body: 'Shared these with friends on the riverbank during last year’s festival. Every flavour was gone in half an hour; the yuzu sugar was the favourite.' },
        ja: { name: 'レナ', title: '去年の灯籠まつりに持参', body: '去年のまつりで、河原で友だちと分けて食べました。30分で全種類なくなり、いちばん人気は柚子ざらめでした。' } },
      { stars: 4, date: '2026-09-30', variant: 'p24', helpful: 5, verified: true,
        en: { name: 'Hideki', title: 'Yuzu sugar ones go first', body: 'If you like the yuzu sugar crackers, you will probably like the Minori Yuzu Farm marmalade too: same bittersweet peel. I wish there were a yuzu-only box.' },
        ja: { name: 'ひでき', title: '柚子ざらめが一番人気', body: '柚子ざらめが好きなら、みのり柚子園のマーマレードもきっと気に入ると思います。同じほろ苦い柚子の皮の味。柚子ざらめだけの箱があればいいのに。' } },
    ],
    qa: [
      { date: '2026-09-01', votes: 74,
        en: { q: 'Is it safe for someone with a shrimp allergy if I take out the shrimp crackers?', a: 'No. All six flavours are baked on the same line, so every cracker may contain traces of shrimp. We cannot recommend this assortment for anyone with a shrimp or crab allergy.', by: 'Shiroshita Seika' },
        ja: { q: '海老せんべいを抜けば、えびアレルギーの人でも食べられますか？', a: 'いいえ。6種すべてを同じラインで焼いているため、どのおせんべいにもえびが混入する可能性があります。えび・かにアレルギーの方にはおすすめできません。', by: '城下製菓' } },
      { date: '2026-06-30', votes: 23,
        en: { q: 'Are they gluten-free? They are rice crackers.', a: 'No. The soy sauce used in several flavours contains wheat, and all flavours are made on a line that handles wheat.', by: 'Shiroshita Seika' },
        ja: { q: 'お米のおせんべいなので、グルテンフリーですか？', a: 'いいえ。複数の味に使っているしょうゆに小麦が含まれ、全種とも小麦を扱うラインで製造しています。', by: '城下製菓' } },
      { date: '2026-08-08', votes: 8,
        en: { q: 'How long do they keep?', a: 'Ninety days from when you receive them.', by: 'Marketa customer (Yoshiko)' },
        ja: { q: '日持ちはどのくらいですか？', a: '届いてから90日です。', by: 'マルケタ購入者（よしこ）' } },
      { date: '2026-08-10', votes: 27,
        en: { q: 'Is the 90-day best-before from delivery or from baking?', a: 'From baking. Marketa ships stock with at least 60 days left, and the exact date is printed on the side of the box.', by: 'Shiroshita Seika' },
        ja: { q: '賞味期限90日は、届いてからですか？製造日からですか？', a: '製造日からです。マルケタからは期限まで60日以上あるものを発送しており、正確な日付は箱の側面に記載しています。', by: '城下製菓' } },
      { date: '2026-10-03', votes: 6,
        en: { q: 'Will the 36-piece box arrive before the festival?', a: 'It ships from outside Minori Prefecture. Mine took five days without Fast; Fast members get it in about three. If you need it before the festival weekend, the 24-piece box is safer.', by: 'Marketa customer (Steve)' },
        ja: { q: '36枚入はまつりまでに届きますか？', a: '36枚入はみのり県外からの発送です。私はFastなしで5日かかりました。Fast会員なら3日ほどだそうです。まつりの週末より前に必要なら、24枚入のほうが確実です。', by: 'マルケタ購入者（スティーブ）' } },
    ],
    similar: ['minori-ponzu-set', 'minori-marmalade-set', 'kagami-sake-set'],
    fbt: ['minori-marmalade-set', 'kagami-tea-set'],
    alsoViewed: ['minori-marmalade-set', 'minori-ponzu-set', 'kagami-sake-set', 'kagami-tea-set', 'yumeguri-onsen-powder', 'kagami-mug-pair'],
  },
];
