// Rain jackets (Outdoor). Same shape as kettles.mjs.
export const cluster = {
  id: 'jackets',
  compareRows: {
    en: ['Construction', 'Waterproof rating', 'Breathability', 'Weight', 'Sizes / fit', 'Warranty'],
    ja: ['素材構造', '耐水圧', '透湿性', '重量', 'サイズ・フィット', '保証'],
  },
};

const marketaJacketReturns = {
  en: 'Returnable within 30 days of delivery if unworn outdoors, with tags attached and in its bag (trying it on indoors is fine); for a change of mind ¥550 return shipping is deducted, free for paid Fast members. To change size, return it and order the other size.',
  ja: 'お届けから30日以内、屋外で未着用・タグ付き・購入時の袋入りであれば返品できます（室内での試着は可）。お客様都合の場合は返送料550円を返金額から差し引きます（有料のFast会員は無料）。サイズ交換は、返品のうえ別サイズをご注文ください。',
};

export default [
  {
    id: 'northpine-packable',
    cat: 'outdoor',
    cluster: 'jackets',
    brand: { en: 'Northpine', ja: 'ノースパイン' },
    seller: 'marketa',
    images: ['northpine-packable', 'northpine-packable-2'],
    title: {
      en: 'Northpine Packable Rain Jacket, Unisex, 2.5-Layer Waterproof 10,000 mm, Breathable 8,000 g/m²/24 h, 210 g, Packs into Its Chest Pocket, Fully Taped Seams, Adjustable Hood',
      ja: 'ノースパイン パッカブル レインジャケット ユニセックス メンズ レディース 防水 耐水圧10,000mm 透湿性8,000g 2.5レイヤー 軽量210g 胸ポケット収納 全面シームテープ NP-RJ25',
    },
    short: { en: 'Northpine Packable Rain Jacket', ja: 'ノースパイン パッカブル レインジャケット' },
    rating: 4.3,
    ratings: 2140,
    hist: [61, 21, 8, 4, 6],
    added: '2023-03-14',
    badges: ['bestseller', 'deal'],
    coupon: null,
    variantLabel: { en: 'Colour · Size', ja: 'カラー・サイズ' },
    variants: [
      { id: 'navy-xs', name: { en: 'Navy · XS', ja: 'ネイビー・XS' }, price: 6980, list: 8800, stock: 7, ship: 'fast' },
      { id: 'navy-s', name: { en: 'Navy · S', ja: 'ネイビー・S' }, price: 6980, list: 8800, stock: 22, ship: 'fast' },
      { id: 'navy-m', name: { en: 'Navy · M', ja: 'ネイビー・M' }, price: 6980, list: 8800, stock: 35, ship: 'fast' },
      { id: 'navy-l', name: { en: 'Navy · L', ja: 'ネイビー・L' }, price: 6980, list: 8800, stock: 4, ship: 'fast' },
      { id: 'navy-xl', name: { en: 'Navy · XL', ja: 'ネイビー・XL' }, price: 6980, list: 8800, stock: 12, ship: 'fast' },
      { id: 'navy-xxl', name: { en: 'Navy · XXL', ja: 'ネイビー・XXL' }, price: 7480, list: 8800, stock: 9, ship: 'fast2' },
      { id: 'yellow-s', name: { en: 'Yellow · S', ja: 'イエロー・S' }, price: 6980, list: 8800, stock: 6, ship: 'fast2' },
      { id: 'yellow-m', name: { en: 'Yellow · M', ja: 'イエロー・M' }, price: 6980, list: 8800, stock: 14, ship: 'fast2' },
      { id: 'yellow-l', name: { en: 'Yellow · L', ja: 'イエロー・L' }, price: 6980, list: 8800, stock: 3, ship: 'fast2' },
      { id: 'olive-m', name: { en: 'Olive · M', ja: 'オリーブ・M' }, price: 6980, list: 8800, stock: 0, ship: 'oos' },
    ],
    returns: marketaJacketReturns,
    bullets: {
      en: [
        'WATERPROOF FOR A CITY DOWNPOUR: 2.5-layer nylon with a PU membrane, rated 10,000 mm, with every seam taped. It keeps you dry walking or commuting through heavy rain for an hour or two; for all-day rain in the mountains, see the 20,000 mm Yamabiko Storm.',
        'BREATHABLE ENOUGH FOR WALKING: 8,000 g/m²/24 h lets sweat out on flat ground at an easy pace. On a long, steep climb you will get damp inside; there are no pit zips.',
        'PACKS INTO ITS OWN CHEST POCKET: turn the pocket inside out and zip it into a 17 × 11 × 6 cm pouch with a hang loop. 210 g in size M, lighter than most folding umbrellas.',
        'HOOD AND CUFFS: hood with a stiffened peak and two adjusters (back and face). It fits over hair or a thin beanie, but not over a stiff-brimmed cap or a helmet. Hook-and-loop cuffs, elastic hem drawcord.',
        'CUT SMALL: the fit is close to the body. If you will wear a fleece or a thick sweater underneath, choose one size up. Check the size chart below; Navy comes in XS–XXL, Yellow in S–L.',
        '1-YEAR WARRANTY from Northpine against defects in materials and sewing (seams, zips, delamination). Wear and tear, tears and loss of water repellency are not covered.',
      ],
      ja: [
        '【街の大雨に十分な防水性】2.5レイヤーナイロン＋PU防水透湿膜、耐水圧10,000mm、縫い目はすべてシームテープ処理。通勤・通学や街歩きの大雨なら1〜2時間しっかり防ぎます。山で一日中雨に打たれる場合は、耐水圧20,000mmの「ヤマビコ ストーム」をご覧ください。',
        '【歩く程度なら蒸れにくい】透湿性8,000g/m²/24h。平地をゆっくり歩くぶんには汗を逃がしますが、急な登りが長く続くと内側が湿ってきます。脇下のベンチレーション（ピットジップ）はありません。',
        '【胸ポケットにそのまま収納】ポケットを裏返してファスナーを閉じれば約17×11×6cmのポーチに。吊り下げループ付き。Mサイズで約210gと、たいていの折りたたみ傘より軽量です。',
        '【フードと袖口】芯入りのひさしと2か所（後頭部・顔まわり）のアジャスター付き。髪や薄手のニット帽の上からはかぶれますが、つばの硬いキャップやヘルメットの上からはかぶれません。袖口は面ファスナー、裾はドローコードで調整できます。',
        '【小さめの作りです】体に沿うすっきりしたシルエットです。フリースや厚手のセーターの上に着る場合はワンサイズ上をおすすめします。下のサイズ表をご確認ください。ネイビーはXS〜XXL、イエローはS〜Lです。',
        '【メーカー保証1年】素材や縫製の不良（シーム、ファスナー、膜のはがれ）が対象です。通常の摩耗、破れ、撥水性の低下は対象外です。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Northpine'], ['Model', 'NP-RJ25'], ['Fit', 'Unisex, close-fitting (runs small)'],
        ['Sizes', 'Navy XS–XXL; Yellow S–L; Olive M (sold out)'], ['Outer fabric', '20-denier nylon ripstop, 2.5-layer with PU membrane'],
        ['Waterproof rating', '10,000 mm'], ['Breathability', '8,000 g/m²/24 h'], ['Seams', 'Fully taped'], ['Water repellency', 'PFC-free DWR finish'],
        ['Hood', 'Fixed, stiffened peak, 2 adjusters; not helmet-compatible'], ['Pockets', '2 zipped hand pockets, 1 chest pocket (doubles as stuff pouch)'],
        ['Ventilation', 'None (no pit zips)'], ['Packed size', '17 × 11 × 6 cm'], ['Weight', '210 g (size M)'],
        ['Care', 'Machine wash at 30 °C or below, gentle cycle, in a net; no softener or bleach; tumble dry low'],
        ['Country of origin', 'Vietnam'], ['Warranty', '1 year (manufacturer)'], ['In the box', 'Jacket (with hang tag and care card)'],
      ],
      ja: [
        ['ブランド', 'ノースパイン'], ['型番', 'NP-RJ25'], ['フィット', 'ユニセックス、細身（小さめ）'],
        ['サイズ', 'ネイビーXS〜XXL／イエローS〜L／オリーブM（品切れ）'], ['表地', '20デニール ナイロンリップストップ、2.5レイヤー（PU防水透湿膜）'],
        ['耐水圧', '10,000mm'], ['透湿性', '8,000g/m²/24h'], ['シーム', '全面シームテープ'], ['撥水加工', 'PFCフリー撥水加工'],
        ['フード', '取り外し不可、芯入りひさし、アジャスター2か所（ヘルメット非対応）'], ['ポケット', 'ファスナー付きハンドポケット×2、胸ポケット×1（収納袋兼用）'],
        ['ベンチレーション', 'なし（ピットジップなし）'], ['収納サイズ', '約17×11×6cm'], ['重量', '約210g（Mサイズ）'],
        ['お手入れ', '洗濯機可（30℃以下・弱水流・ネット使用）、柔軟剤・漂白剤不可、乾燥機は低温'],
        ['原産国', 'ベトナム'], ['保証', 'メーカー保証1年'], ['付属品', '本体（下げ札・洗濯表示カード付き）'],
      ],
    },
    compare: {
      en: ['2.5-layer', '10,000 mm', '8,000 g/m²/24 h', '210 g (M)', 'Unisex XS–XXL; runs small', '1 year'],
      ja: ['2.5レイヤー', '10,000mm', '8,000g/m²/24h', '約210g（M）', 'ユニセックスXS〜XXL、小さめ', '1年'],
    },
    description: {
      en: [
        'The Northpine Packable is a light, everyday rain jacket for town: the walk to the station, a bike ride to campus, or an evening at the Lantern Festival when the forecast is uncertain. It folds into its own chest pocket, so it can live in a bag all year and come out only when the rain does.',
        'What 10,000 mm means: in a lab test the fabric holds back the pressure of a 10-metre column of water before it leaks. It is not an amount of rain. In practice it keeps you dry in heavy rain for an hour or two of walking. Water can still get through where the pressure is higher, for example under backpack straps over several hours, or where wind drives rain into the hood opening. The 8,000 g/m²/24 h breathability lets sweat escape at a walking pace, but on a steep climb such as the trail up Mount Tsukimi you sweat faster than it can escape and the inside feels clammy.',
        'Fit: Northpine cuts the jacket close to the body to save weight. Most people who wear it over a T-shirt or shirt take their usual size; if you will wear a fleece, a thick sweater or a suit jacket underneath, take one size up. The sleeves are on the short side for people with long arms. Measure a jacket you like lying flat and compare it with the chart below.',
        'Care: the outer fabric has a water-repellent finish that makes rain bead up and roll off. Dirt, sweat and skin oils wear it down; when rain starts to soak into the outer fabric (it looks darker in patches), the jacket feels cold even though it is not leaking. Wash it in a net on a gentle cycle at 30 °C or below with a little liquid detergent, no fabric softener or bleach, and rinse twice. Then tumble dry on low for 20 minutes, or iron on low through a cloth, to reactivate the finish. If water still does not bead, use a spray-on re-proofer for outdoor clothing. Do not dry-clean.',
        'Navy XS–XL is in stock at Marketa Harukawa (HRK1) for next-day delivery. Navy XXL (¥500 more, with longer sleeves and back) and every Yellow size ship from another Marketa warehouse and take two to three days. Olive is sold out with no restock date. The 1-year Northpine warranty covers defects; keep your Marketa order confirmation as proof of purchase.',
      ],
      ja: [
        'ノースパインのパッカブル レインジャケットは、駅までの道や自転車通学、天気が読めない日の灯籠まつりなど、街で使うための軽い日常用レインジャケットです。胸ポケットにそのまま収納できるので、一年中カバンに入れておき、雨のときだけ取り出せます。',
        '耐水圧10,000mmとは、生地の上に高さ10mの水柱を立てた試験で水がしみ出さないという意味で、雨の量ではありません。実際には、大雨の中を1〜2時間歩いても濡れない程度が目安です。ただし、ザックのベルトで何時間も押さえられる部分や、風で雨がフードの中に吹き込む場合は水が入ることがあります。透湿性8,000g/m²/24hは歩くペースなら汗を逃がしますが、月見山の登山道のような急な登りでは汗の量に追いつかず、内側がじっとりします。',
        'サイズ感：軽量化のため体に沿った細身のつくりです。Tシャツやシャツの上に着る方の多くは普段どおりのサイズ、フリース・厚手のセーター・スーツの上に着る場合はワンサイズ上をおすすめします。腕の長い方には袖がやや短めです。お手持ちの上着を平置きで測り、下のサイズ表と比べてお選びください。',
        'お手入れ：表地には雨を玉にして弾く撥水加工がされています。汚れや汗、皮脂で撥水性が落ちると、表地が雨を吸って部分的に色が濃くなり、浸水していなくても冷たく感じます。洗濯ネットに入れて弱水流・30℃以下で、少量の液体洗剤で洗い、柔軟剤や漂白剤は使わずに2回すすいでください。その後、乾燥機の低温で20分、または当て布をして低温でアイロンをかけると撥水性が回復します。それでも水を弾かない場合は、アウトドアウェア用の撥水スプレーをお使いください。ドライクリーニングは不可です。',
        'ネイビーのXS〜XLはマルケタ春川センター（HRK1）に在庫があり、翌日お届けが可能です。ネイビーのXXL（500円高く、袖丈・着丈が長め）とイエロー全サイズは県外のマルケタ倉庫から発送のため、お届けまで2〜3日かかります。オリーブは品切れ中で、再入荷は未定です。メーカー保証は1年間。マルケタの注文確認メールが購入証明になります。',
      ],
    },
    tables: [
      {
        title: { en: 'Size chart (garment measurements, cm)', ja: 'サイズ表（仕上がり寸法・cm）' },
        en: [
          ['Size', 'Chest (garment)', 'Back length', 'Sleeve (shoulder to cuff)', 'Suggested height'],
          ['XS', '100', '66', '58', '150–160'], ['S', '104', '68', '60', '158–166'], ['M', '108', '70', '61.5', '165–173'],
          ['L', '112', '72', '63', '172–180'], ['XL', '117', '74', '64.5', '178–186'], ['XXL', '122', '76', '66', '184–192'],
        ],
        ja: [
          ['サイズ', '胸囲（仕上がり）', '着丈（後ろ中心）', '袖丈（肩先から袖口）', '目安身長'],
          ['XS', '100', '66', '58', '150〜160'], ['S', '104', '68', '60', '158〜166'], ['M', '108', '70', '61.5', '165〜173'],
          ['L', '112', '72', '63', '172〜180'], ['XL', '117', '74', '64.5', '178〜186'], ['XXL', '122', '76', '66', '184〜192'],
        ],
      },
      {
        title: { en: 'What waterproof ratings mean (jackets on Marketa)', ja: '耐水圧の目安（マルケタ取り扱いのジャケット）' },
        en: [
          ['Rating', 'Jacket', 'Good for'],
          ['3,000 mm', 'Drizzle Pro', 'Light rain and short trips; soaks through in heavy rain'],
          ['10,000 mm', 'Northpine Packable', 'Heavy rain for 1–2 hours: commuting, town, festivals'],
          ['15,000 mm', 'Tsukimi Trail Women\'s', 'Day hikes in steady rain with a light pack'],
          ['20,000 mm', 'Yamabiko Storm 3L', 'All-day rain and wind in the mountains, heavy pack'],
        ],
        ja: [
          ['耐水圧', 'ジャケット', '向いている使い方'],
          ['3,000mm', 'ドリズルプロ', '小雨・短時間の外出。大雨ではしみてくる'],
          ['10,000mm', 'ノースパイン パッカブル', '1〜2時間の大雨：通勤・街歩き・お祭り'],
          ['15,000mm', '月見トレイル レディース', '降り続く雨の中の日帰り登山（軽めの荷物）'],
          ['20,000mm', 'ヤマビコ ストーム 3L', '山での一日中の風雨、重い荷物'],
        ],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-24', variant: 'navy-m', helpful: 163, verified: true,
        en: { name: 'Kenta', title: 'Lives in my bag, saved me twice this month', body: 'I keep it packed in my work bag; it is about the size of a can of coffee. I got caught in the downpour on the 18th walking 15 minutes from Harukawa Central to my office and stayed completely dry from the waist up (my trousers were soaked). The back adjuster keeps the hood from slipping. For town use I cannot see why you would pay more.' },
        ja: { name: 'けんた', title: 'いつもカバンに。今月2回助けられました', body: '缶コーヒーくらいの大きさにたたんで通勤カバンに入れっぱなしです。18日の土砂降りの日、春川中央駅から会社まで15分歩きましたが、上半身はまったく濡れませんでした（ズボンはびしょびしょ）。後ろのアジャスターでフードもずれません。街で使うなら、これ以上高いものは要らないと思います。' } },
      { stars: 2, date: '2026-09-10', variant: 'navy-l', helpful: 241, verified: true,
        en: { name: 'Takeshi O.', title: 'Runs small: order one size up', body: 'I am 176 cm, 74 kg and wear L in every brand. This L is tight across the chest over a shirt, and with a thin fleece I cannot raise my arms without the hem riding up to my belt. The sleeves stop above my wrists when I hold a bike handlebar. I returned it (¥550 taken off the refund) and the XL fits like a normal L.' },
        ja: { name: '岡田', title: '小さめです。ワンサイズ上を', body: '176cm・74kgで、どのメーカーでもLを着ています。このLはシャツの上でも胸まわりがきつく、薄手のフリースを着ると腕を上げたときに裾がベルトの位置まで上がってきます。自転車のハンドルを握ると袖が手首より上に。返品して（返金から550円差し引き）XLにしたら、普通のLくらいの感覚です。' } },
      { stars: 4, date: '2026-09-15', variant: 'navy-m', helpful: 132, verified: true,
        en: { name: 'Sakura', title: 'True to size for me, not small', body: 'After reading all the "runs small" reviews I nearly ordered L. I am 168 cm, 60 kg, usually M, and the M fits normally over a T-shirt or a light knit, with room to move. I think it only feels small if you want a thick fleece underneath. I wanted the yellow, but it would have taken two more days, so I went with navy.' },
        ja: { name: 'さくら', title: '私には普通のサイズ感でした', body: '「小さめ」というレビューを読んでLにしかけましたが、168cm・60kgでいつもMの私には、Mでちょうど良いサイズでした。Tシャツや薄手のニットの上なら動きやすさも十分。厚手のフリースを中に着たい人には小さく感じるのかもしれません。本当はイエローが欲しかったのですが、届くのが2日ほど遅くなるのでネイビーにしました。' } },
      { stars: 1, date: '2026-08-23', variant: 'yellow-s', helpful: 118, verified: true,
        en: { name: 'Mai', title: 'Wet from the inside on Mount Tsukimi', body: 'I wore it for the climb from Tsukimi Onsen to the summit in light rain. Forty minutes into the steep section I was as wet inside from sweat as I would have been without a jacket, and the lining felt like a plastic bag. It is fine for walking in town, but it is not a hiking jacket. My husband\'s Yamabiko Storm, with pit zips, stayed dry inside on the same climb.' },
        ja: { name: 'まい', title: '月見山では内側からびしょ濡れ', body: '小雨の中、月見温泉から山頂まで登るときに着ました。急登に入って40分ほどで、汗のせいでジャケットを着ていないのと同じくらい内側が濡れ、裏地はビニール袋のような肌ざわりに。街歩きなら問題ありませんが、登山用ではありません。同じ道を登った夫のヤマビコ ストーム（ピットジップ付き）は中まで乾いていました。' } },
      { stars: 2, date: '2026-07-30', variant: 'navy-l', helpful: 87, verified: true,
        en: { name: 'Jun', title: 'Hood is too small to go over a cap', body: 'I wear a baseball cap almost every day and the hood will not go over it: the brim pushes the hood back, and when I tighten the face cord the whole hood slides off behind the cap. Without a cap it fits fine. If you wear a cap in the rain, think twice.' },
        ja: { name: 'じゅん', title: 'キャップの上からフードがかぶれない', body: 'ほぼ毎日野球帽をかぶっていますが、その上からフードがかぶれません。つばがフードを後ろに押してしまい、顔まわりのコードを締めるとフードごと後ろへずり落ちます。帽子なしならちょうど良いです。雨の日にキャップをかぶる方は要注意。' } },
      { stars: 3, date: '2025-10-14', variant: 'navy-s', helpful: 64, verified: true,
        en: { name: 'Rie', title: 'Good for town, but cold and clammy after three hours', body: 'I wore it all evening at the Lantern Festival at the weekend in steady rain. It never actually leaked, but after about three hours the shoulders under my backpack straps had soaked through the outer fabric and felt cold and damp against my skin. Fine for an hour, not for a whole evening outdoors.' },
        ja: { name: 'りえ', title: '街なら十分。ただ3時間で肩が冷たく', body: '週末の灯籠まつりで、雨が降り続く中ひと晩着ていました。浸水こそしませんでしたが、3時間ほどでリュックのベルトが当たる肩の部分の表地が水を吸い、肌に冷たく湿った感じが伝わってきました。1時間程度なら十分、ひと晩外にいるには物足りないです。' } },
      { stars: 5, date: '2026-06-19', variant: 'yellow-m', helpful: 41, verified: true,
        en: { name: 'Hiro', title: 'Yellow is easy to see on the bike', body: 'I ride to Harukawa University every day. The yellow is very visible to drivers in the rain at dusk, and the hem cord stops it flapping. The hood does not fit over a helmet, so I wear it underneath. It took two extra days to arrive.' },
        ja: { name: 'ひろ', title: 'イエローは自転車で目立つ', body: '毎日自転車で春川大学に通っています。夕方の雨でもイエローは車からよく見えるようで安心。裾のドローコードを絞ればバタつきません。フードはヘルメットの上からかぶれないので、ヘルメットの下に入れています。届くまで2日ほど余分にかかりました。' } },
      { stars: 2, date: '2026-03-02', variant: 'olive-m', helpful: 96, verified: true,
        en: { name: 'Naoko', title: 'Stopped beading after a few washes', body: 'After about ten washes with my usual powder detergent and fabric softener, rain soaked straight into the fabric and I felt damp after a 30-minute walk. Northpine support told me softener ruins the water-repellent finish and that this is not covered by the warranty. Annoying that it is only mentioned on the care label.' },
        ja: { name: 'なおこ', title: '何度か洗ったら水をはじかなくなった', body: 'いつもの粉洗剤と柔軟剤で10回ほど洗ったら、雨がそのまま生地にしみ込み、30分歩いただけで湿っぽくなりました。ノースパインのサポートに問い合わせると、柔軟剤で撥水加工が落ちるので保証の対象外とのこと。注意書きが洗濯表示のタグにしかないのは不親切だと思います。' } },
      { stars: 4, date: '2026-04-11', variant: 'navy-m', helpful: 58, verified: true,
        en: { name: 'Tomo', title: 'Re-proofing brings it back', body: 'For anyone whose jacket stopped beading: mine did too after a year. I washed it with liquid detergent and no softener, put it in the dryer on low for 20 minutes, and it beads like new again. When that stopped working I used a spray-on re-proofer (about ¥1,500) and it is still fine. Ten minutes, twice a year.' },
        ja: { name: 'とも', title: '撥水は復活します', body: '水をはじかなくなったという方へ。私のも1年で同じ状態になりました。液体洗剤（柔軟剤なし）で洗い、乾燥機の低温で20分かけたら新品のように水玉になりました。それでも効かなくなってきたら1,500円ほどの撥水スプレーを。年2回、10分の手間で今も問題なく使えています。' } },
      { stars: 4, date: '2026-08-05', variant: 'navy-xxl', helpful: 23, verified: true,
        en: { name: 'Big Dave', title: 'XXL fits a big frame, but costs more', body: 'I am 188 cm and broad. The XXL fits well over a hoodie and the sleeves are long enough. It costs ¥500 more than the other sizes and came from outside the prefecture, so it took three days instead of one.' },
        ja: { name: '大山', title: 'XXLは大柄でも着られるが少し高い', body: '188cmでがっしり体型です。XXLはパーカーの上からでも着られ、袖の長さも十分。ほかのサイズより500円高く、県外の倉庫からの発送で、翌日ではなく3日かかりました。' } },
      { stars: 5, date: '2026-05-27', variant: 'navy-m', helpful: 77, verified: true,
        en: { name: 'Shiho', title: 'Worth twice the price of the Drizzle Pro', body: 'I first bought the Drizzle Pro from BrightDeal for ¥3,480. It leaked at the shoulders the first time I wore it in proper rain and smelled of chemicals, and sending it back was a hassle. This one is ¥6,980, but it is actually waterproof, packs smaller and does not smell. Buy once.' },
        ja: { name: 'しほ', title: 'ドリズルプロの倍の値段の価値あり', body: '最初にブライトディールのドリズルプロ（3,480円）を買いましたが、本降りの雨の中で初めて着た日に肩から浸水し、薬品のにおいもきつく、返品も手間でした。こちらは6,980円ですが、ちゃんと防水で、小さくたためて、においもありません。最初からこれを買えばよかった。' } },
      { stars: 3, date: '2026-02-08', variant: 'navy-l', helpful: 29, verified: true,
        en: { name: 'Kaz', title: 'Rustles, and sticks to bare arms', body: 'Does the job in the rain, but it rustles like a shopping bag and the inside sticks to bare arms in summer. I am told all 2.5-layer jackets are like that. Wear it over long sleeves.' },
        ja: { name: 'かず', title: 'シャカシャカ音と、素肌へのはりつき', body: '雨はしっかり防ぎますが、レジ袋のようなシャカシャカ音がして、夏に半袖で着ると内側が腕にはりつきます。2.5レイヤーはこういうものだそうです。長袖の上に着るのがおすすめ。' } },
    ],
    qa: [
      { date: '2026-07-03', votes: 22,
        en: { q: 'Is it OK in a typhoon?', a: 'Yes. 10,000 mm means it can take 10 metres of rain, which is more than any typhoon.', by: 'Marketa customer (Yusuke)' },
        ja: { q: '台風でも大丈夫ですか？', a: '大丈夫です。耐水圧10,000mmは10メートル分の雨に耐えられるという意味なので、どんな台風よりも上です。', by: 'マルケタ購入者（ゆうすけ）' } },
      { date: '2026-07-21', votes: 64,
        en: { q: 'What does 10,000 mm actually mean? Is it enough for heavy rain?', a: 'It is a lab test: the fabric holds back the pressure of a 10-metre column of water before it leaks. It is not an amount of rain, so the earlier answer here is not correct. In practice 10,000 mm keeps you dry in heavy rain for an hour or two of walking. In a typhoon, wind drives rain into the hood and cuffs and pack straps press water through, so for long exposure we recommend a 20,000 mm jacket. Please stay indoors during a typhoon.', by: 'Northpine Customer Support' },
        ja: { q: '耐水圧10,000mmとは具体的にどういう意味ですか？大雨でも大丈夫？', a: '生地の上に高さ10メートルの水柱を立てたときの水圧に耐えられることを示す試験値で、雨の量ではありません（上の回答は誤りです）。目安として、大雨の中を1〜2時間歩く程度なら濡れません。台風では風で雨がフードや袖口から吹き込み、ザックのベルトの圧で水がしみることもあるため、長時間なら耐水圧20,000mmクラスをおすすめします。なお、台風の際は外出をお控えください。', by: 'ノースパイン カスタマーサポート' } },
      { date: '2026-06-09', votes: 38,
        en: { q: 'Will the hood go over a baseball cap?', a: 'It fits over a thin beanie or a soft cap with a short brim. Most baseball caps with a stiff brim push the hood back so it will not close around your face. It is not designed to go over a bicycle or climbing helmet.', by: 'Northpine Customer Support' },
        ja: { q: '野球帽の上からフードをかぶれますか？', a: '薄手のニット帽や、つばの短い柔らかいキャップの上ならかぶれます。つばの硬い一般的な野球帽ではフードが後ろに押され、顔まわりを閉じられません。自転車用・登山用ヘルメットの上からかぶる設計ではありません。', by: 'ノースパイン カスタマーサポート' } },
      { date: '2026-05-14', votes: 29,
        en: { q: 'Can I put it in the washing machine?', a: 'Yes. Use a net, a gentle cycle at 30 °C or below and a little liquid detergent. Do not use fabric softener or bleach, and rinse twice. Tumble dry on low for about 20 minutes to restore the water repellency, or iron on low through a cloth. When water no longer beads, apply a spray-on re-proofer.', by: 'Northpine Customer Support' },
        ja: { q: '洗濯機で洗えますか？', a: 'はい。洗濯ネットに入れ、弱水流・30℃以下で、少量の液体洗剤をお使いください。柔軟剤・漂白剤は使わず、すすぎは2回に。乾燥機の低温で約20分、または当て布をして低温アイロンをかけると撥水性が戻ります。それでも水を弾かなくなったら撥水スプレーをお使いください。', by: 'ノースパイン カスタマーサポート' } },
      { date: '2026-08-28', votes: 17,
        en: { q: 'I am 175 cm and 70 kg. M or L?', a: 'I am 174 cm and 71 kg. The M is fine over a T-shirt but tight over a fleece, so I kept the L for winter.', by: 'Marketa customer (Ryo)' },
        ja: { q: '175cm・70kgです。MとLどちらがいいですか？', a: '174cm・71kgです。MはTシャツの上なら問題ありませんが、フリースの上だときついので、冬用にLを残しました。', by: 'マルケタ購入者（りょう）' } },
    ],
    similar: ['yamabiko-storm', 'tsukimi-trail-women', 'drizzle-pro'],
    fbt: ['ampora-slim-10k', 'kaze-openear'],
    alsoViewed: ['yamabiko-storm', 'tsukimi-trail-women', 'drizzle-pro', 'ampora-slim-10k', 'kaze-openear', 'nami-buds'],
  },
  {
    id: 'yamabiko-storm',
    cat: 'outdoor',
    cluster: 'jackets',
    brand: { en: 'Yamabiko', ja: 'ヤマビコ' },
    seller: 'marketa',
    images: ['yamabiko-storm'],
    title: {
      en: 'Yamabiko Storm 3L Shell Men\'s Waterproof Jacket, 3-Layer 20,000 mm / 25,000 g/m²/24 h, Helmet-Compatible Hood, Pit Zips, 390 g, for Hiking and Mountaineering',
      ja: 'ヤマビコ ストーム 3Lシェル メンズ 防水透湿 3レイヤー 耐水圧20,000mm 透湿性25,000g ヘルメット対応フード ピットジップ 登山 トレッキング 雨具 390g YB-3LS',
    },
    short: { en: 'Yamabiko Storm 3L Shell', ja: 'ヤマビコ ストーム 3Lシェル' },
    rating: 4.7,
    ratings: 412,
    hist: [80, 13, 4, 1, 2],
    added: '2024-02-20',
    badges: ['choice'],
    coupon: { amount: 1000, member: true, en: 'Fast members: save ¥1,000 with coupon', ja: 'Fast会員限定 1,000円OFFクーポン' },
    variantLabel: { en: 'Colour · Size', ja: 'カラー・サイズ' },
    variants: [
      { id: 'red-s', name: { en: 'Red · S', ja: 'レッド・S' }, price: 22000, list: 27500, stock: 5, ship: 'fast' },
      { id: 'red-m', name: { en: 'Red · M', ja: 'レッド・M' }, price: 22000, list: 27500, stock: 11, ship: 'fast' },
      { id: 'red-l', name: { en: 'Red · L', ja: 'レッド・L' }, price: 22000, list: 27500, stock: 8, ship: 'fast' },
      { id: 'red-xl', name: { en: 'Red · XL', ja: 'レッド・XL' }, price: 22000, list: 27500, stock: 3, ship: 'fast' },
      { id: 'black-s', name: { en: 'Black · S', ja: 'ブラック・S' }, price: 22000, list: 27500, stock: 6, ship: 'fast' },
      { id: 'black-m', name: { en: 'Black · M', ja: 'ブラック・M' }, price: 22000, list: 27500, stock: 14, ship: 'fast' },
      { id: 'black-l', name: { en: 'Black · L', ja: 'ブラック・L' }, price: 22000, list: 27500, stock: 9, ship: 'fast' },
      { id: 'black-xl', name: { en: 'Black · XL', ja: 'ブラック・XL' }, price: 22000, list: 27500, stock: 4, ship: 'fast2' },
    ],
    returns: marketaJacketReturns,
    bullets: {
      en: [
        'BUILT FOR MOUNTAIN STORMS: 3-layer shell with Yamabiko\'s own Kodama membrane, rated 20,000 mm. It stays dry under backpack straps and in wind-driven rain over a full day, not just a shower.',
        'BREATHES ON THE CLIMB: 25,000 g/m²/24 h breathability plus 30 cm two-way pit zips under both arms, so you can let heat out on a steep ascent without taking the jacket off.',
        'HELMET-COMPATIBLE HOOD: three-way adjustable hood with a wired peak fits over a climbing or cycling helmet, and cinches down to turn with your head when you are not wearing one.',
        'PACK-FRIENDLY POCKETS: two hand pockets set high, above a hip belt, plus a chest pocket for a phone or map. The water-resistant zips keep out rain but are not fully waterproof.',
        'RUNS SLIGHTLY LARGE: cut with room for a fleece and a light down layer. If you will wear only a base layer underneath, or are between sizes, take the smaller size. Men\'s S–XL; see the size chart.',
        '2-YEAR WARRANTY from Yamabiko covering seam tape, membrane delamination, zips and sewing. Tears and wear can be repaired at cost after the warranty.',
      ],
      ja: [
        '【山の嵐に耐える防水性】独自の防水透湿膜「コダマ」を使った3レイヤーシェル。耐水圧20,000mmで、ザックのショルダーベルトで圧がかかる部分や横殴りの雨でも、一日を通して浸水を防ぎます。',
        '【登りでも蒸れにくい】透湿性25,000g/m²/24hに加え、両脇に約30cmのダブルジップ式ピットジップ。急な登りでもジャケットを脱がずに熱を逃がせます。',
        '【ヘルメット対応フード】ワイヤー入りのひさしと3方向のアジャスター付き。登山用・自転車用ヘルメットの上からかぶれ、ヘルメットなしでも絞れば頭の動きにしっかり追従します。',
        '【ザックを背負ったまま使えるポケット】ハンドポケットはヒップベルトに干渉しない高めの位置。スマートフォンや地図が入る胸ポケット付き。止水ファスナーは雨を防ぎますが、完全防水ではありません。',
        '【やや大きめの作り】フリースや薄手のダウンを中に着られるゆとりのある設計です。ベースレイヤーの上に着るだけの方や、サイズで迷う方は小さいほうをおすすめします。メンズS〜XL。サイズ表をご確認ください。',
        '【メーカー保証2年】シームテープ、膜のはがれ、ファスナー、縫製の不良が対象。破れや摩耗は保証期間後も有償で修理を承ります。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Yamabiko'], ['Model', 'YB-3LS'], ['Fit', 'Men\'s regular fit with room for layers (runs slightly large)'], ['Sizes', 'S, M, L, XL'],
        ['Construction', '3-layer: 40-denier nylon face, Kodama membrane, tricot backer'], ['Waterproof rating', '20,000 mm'],
        ['Breathability', '25,000 g/m²/24 h'], ['Seams', 'Fully taped (13 mm tape)'], ['Hood', '3-way adjustable, wired peak, helmet-compatible'],
        ['Ventilation', '30 cm two-way pit zips'], ['Pockets', '2 hand pockets (above hip belt), 1 chest pocket'],
        ['Front zip', 'Two-way water-resistant zip with inner storm flap'], ['Hem and cuffs', 'Dropped back hem with drawcord; hook-and-loop cuffs'],
        ['Weight', '390 g (size M)'], ['Care', 'Machine wash at 30 °C, gentle cycle; no softener; tumble dry low to reactivate the DWR'],
        ['Country of origin', 'Vietnam (designed in Japan)'], ['Warranty', '2 years (manufacturer)'], ['In the box', 'Jacket, stuff sack (20 × 12 cm)'],
      ],
      ja: [
        ['ブランド', 'ヤマビコ'], ['型番', 'YB-3LS'], ['フィット', 'メンズ、重ね着できるレギュラーフィット（やや大きめ）'], ['サイズ', 'S、M、L、XL'],
        ['素材構造', '3レイヤー：40デニール ナイロン表地、防水透湿膜「コダマ」、トリコット裏地'], ['耐水圧', '20,000mm'],
        ['透湿性', '25,000g/m²/24h'], ['シーム', '全面シームテープ（13mm幅）'], ['フード', '3方向調整、ワイヤー入りひさし、ヘルメット対応'],
        ['ベンチレーション', '約30cmのダブルジップ式ピットジップ'], ['ポケット', 'ハンドポケット×2（ヒップベルトより上）、胸ポケット×1'],
        ['前ファスナー', 'ダブルジップ止水ファスナー、内側にストームフラップ'], ['裾・袖口', '後ろ裾長め（ドローコード付き）、袖口は面ファスナー'],
        ['重量', '約390g（Mサイズ）'], ['お手入れ', '洗濯機可（30℃・弱水流）、柔軟剤不可、乾燥機の低温で撥水回復'],
        ['原産国', 'ベトナム（日本で企画・設計）'], ['保証', 'メーカー保証2年'], ['付属品', '本体、収納袋（約20×12cm）'],
      ],
    },
    compare: {
      en: ['3-layer', '20,000 mm', '25,000 g/m²/24 h', '390 g (M)', 'Men\'s S–XL; runs slightly large', '2 years'],
      ja: ['3レイヤー', '20,000mm', '25,000g/m²/24h', '約390g（M）', 'メンズS〜XL、やや大きめ', '2年'],
    },
    description: {
      en: [
        'The Yamabiko Storm is a full mountain shell: the jacket you want when rain is forecast all day above the tree line, the wind is up and you are carrying a pack. If you mostly need a jacket for town, the train and the occasional shower, it is more than you need; the 210 g Northpine Packable costs about a third as much.',
        'The 3-layer construction bonds the membrane between the outer fabric and a thin inner backer, so nothing rubs the membrane and there is no loose lining to cling when you sweat. At 20,000 mm it holds up to the pressure of pack straps and kneeling on wet ground, and at 25,000 g/m²/24 h it is among the most breathable shells at this price. On a climb such as the three-hour trail from Tsukimi Onsen to the summit of Mount Tsukimi, open the pit zips before you start to sweat, not after.',
        'Fit: the cut leaves room for a fleece and a light down jacket, so most buyers who wear it over a base layer only find it slightly large and take one size down. If you are between sizes and hike in cold weather, keep your usual size. The back hem is 4 cm longer than the front to cover your lower back when you lean forward, and the sleeves still reach the base of your thumbs with your arms raised.',
        'Care: wash it whenever it gets dirty; sweat and sunscreen clog the membrane and wear down the water-repellent finish. Use a little liquid detergent or a technical wash at 30 °C, no softener or bleach, and tumble dry on low for 20–30 minutes, which revives the finish. When water no longer beads after drying, use a wash-in or spray-on re-proofer.',
        'Red and Black are both in stock at Marketa Harukawa in S–L, and Red also in XL; Black XL ships from another Marketa warehouse. Yamabiko\'s 2-year warranty covers seam tape that lifts, delamination and faulty zips; keep your Marketa order confirmation. Tears and worn cuffs are repaired at cost.',
      ],
      ja: [
        'ヤマビコ ストームは本格的な山岳用シェルです。森林限界を超える稜線で一日中雨の予報、風も強く、ザックを背負って歩く。そんな日に頼れる一着です。街や電車での移動、たまのにわか雨が中心なら性能を持て余します。約210gのノースパイン パッカブルなら3分の1ほどの価格です。',
        '3レイヤー構造は防水透湿膜を表地と薄い裏地で挟んで貼り合わせているため、膜がこすれて傷まず、汗をかいても裏地がまとわりつきません。耐水圧20,000mmはザックのベルトの圧や濡れた地面にひざをついたときの圧にも耐え、透湿性25,000g/m²/24hはこの価格帯のシェルではトップクラスです。月見温泉から月見山の山頂まで約3時間の登りのような場面では、汗をかく前にピットジップを開けておくのがコツです。',
        'サイズ感：フリースと薄手のダウンを中に着られるゆとりがあるため、ベースレイヤーの上に着るだけの方の多くは「やや大きい」と感じ、ワンサイズ下を選んでいます。サイズで迷い、寒い時期にも登る方は普段のサイズのままがおすすめです。後ろ裾は前より4cm長く、前かがみになっても腰が出ません。腕を上げても袖は親指の付け根まで届きます。',
        'お手入れ：汚れたらこまめに洗ってください。汗や日焼け止めは膜の目詰まりや撥水低下の原因になります。少量の液体洗剤またはアウトドアウェア用洗剤で30℃で洗い、柔軟剤・漂白剤は使わず、乾燥機の低温で20〜30分乾かすと撥水性が回復します。乾燥後も水を弾かなくなったら、浸け込み式またはスプレー式の撥水剤をお使いください。',
        'レッド・ブラックともS〜Lはマルケタ春川センターに在庫があり、レッドはXLも在庫あり。ブラックのXLは県外のマルケタ倉庫から発送します。メーカー保証は2年間で、シームテープのはがれ、膜のはがれ、ファスナーの不良が対象です。マルケタの注文確認メールを保管しておいてください。破れや袖口の摩耗は有償で修理できます。',
      ],
    },
    tables: [
      {
        title: { en: 'Size chart (garment measurements, cm)', ja: 'サイズ表（仕上がり寸法・cm）' },
        en: [
          ['Size', 'Chest (garment)', 'Back length', 'Sleeve (shoulder to cuff)', 'Suggested height'],
          ['S', '106', '72', '62', '160–168'], ['M', '112', '74', '64', '167–175'],
          ['L', '118', '76', '66', '174–182'], ['XL', '124', '78', '68', '181–189'],
        ],
        ja: [
          ['サイズ', '胸囲（仕上がり）', '着丈（後ろ中心）', '袖丈（肩先から袖口）', '目安身長'],
          ['S', '106', '72', '62', '160〜168'], ['M', '112', '74', '64', '167〜175'],
          ['L', '118', '76', '66', '174〜182'], ['XL', '124', '78', '68', '181〜189'],
        ],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-22', variant: 'red-m', helpful: 88, verified: true,
        en: { name: 'Shinji', title: 'Dry after six hours of rain on the ridge', body: 'I walked the ridge from the summit of Mount Tsukimi down to Tsukimi Onsen in the tail end of a typhoon: six hours of wind and rain with a 30 L pack. Completely dry underneath, including the shoulders, which always soaked through on my old jacket. The hood turns with my head and the peak keeps rain off my glasses.' },
        ja: { name: '真司', title: '尾根で6時間の雨でも中はドライ', body: '台風崩れの雨の中、月見山の山頂から尾根づたいに月見温泉まで下りました。風雨の中6時間、30Lのザックを背負っていましたが、前のジャケットでは必ずしみてきた肩も含めて中はまったく濡れず。フードは頭の動きについてきて、ひさしのおかげでメガネに雨がかかりません。' } },
      { stars: 5, date: '2026-08-31', variant: 'black-l', helpful: 64, verified: true,
        en: { name: 'Ayumu', title: 'The pit zips are the reason to buy it', body: 'I climbed Mount Tsukimi from the onsen side in drizzle, about three hours up. I opened both pit zips before the steep part and was only slightly damp under the arms at the top. My Northpine Packable, which I wore on the same route last year, was soaked inside from sweat. A different class of jacket.' },
        ja: { name: 'あゆむ', title: '買う理由はピットジップ', body: '霧雨の中、温泉側から月見山に登りました（登り約3時間）。急登の手前で両脇のピットジップを開けておいたら、山頂でも脇の下が少し湿る程度。去年同じルートで着たノースパインのパッカブルは汗で中がびしょびしょでした。別物です。' } },
      { stars: 2, date: '2026-07-12', variant: 'black-l', helpful: 97, verified: true,
        en: { name: 'Masa', title: 'Runs large: sleeves past my fingertips', body: 'I am 175 cm and always take L. In this L the sleeves cover my hands completely and the chest has room for a down jacket with plenty left over. Over just a base layer it flapped in the wind. I returned it and ordered M, which fits well, but it cost me ¥550 in return shipping and a week.' },
        ja: { name: 'まさ', title: '大きめ。袖が指先まで', body: '175cmで普段はL。このLは袖で手が完全に隠れ、胸まわりはダウンを着込んでもまだ余るほど。ベースレイヤーの上だけだと風でバタつきました。返品してMを注文し直したらちょうど良いのですが、返送料550円と1週間の手間がかかりました。' } },
      { stars: 4, date: '2026-08-14', variant: 'red-m', helpful: 71, verified: true,
        en: { name: 'Kohei', title: 'True to size if you layer, as intended', body: 'I do not agree that it runs large. I am 171 cm, 66 kg, and the M fits perfectly over a fleece, which is how a mountain shell should fit. If you only ever wear a T-shirt under it, then yes, size down. One star off because it is noisy.' },
        ja: { name: 'こうへい', title: '重ね着前提ならジャストサイズ', body: '大きめという意見には反対です。171cm・66kgでMを、フリースの上に着てちょうど良い。山用のシェルは本来そういうサイズ感だと思います。Tシャツの上にしか着ないならワンサイズ下でしょう。ガサガサ音がするので星ひとつ減らしました。' } },
      { stars: 1, date: '2026-06-28', variant: 'red-s', helpful: 54, verified: true,
        en: { name: 'Ichiro', title: 'Phone got wet in the hand pocket', body: 'For ¥22,000 I expected the pockets to be waterproof. After two hours of heavy rain the phone in my hand pocket was wet and a paper receipt had turned to pulp. Yamabiko says the zips are water-resistant, not waterproof. The jacket kept me dry, but now my phone goes in a plastic bag.' },
        ja: { name: '一郎', title: 'ハンドポケットのスマホが濡れた', body: '22,000円ならポケットも防水だと思っていました。大雨の中を2時間歩いたら、ハンドポケットのスマホが濡れ、レシートはふやけてボロボロに。メーカーによると止水ファスナーは「防水」ではなく「防滴」だそうです。体は濡れませんでしたが、今はスマホをビニール袋に入れています。' } },
      { stars: 2, date: '2026-05-03', variant: 'black-m', helpful: 48, verified: true,
        en: { name: 'Yuka', title: 'Too stiff and heavy for everyday', body: 'I bought it for commuting and regret it. It is stiff, crackles every time I move, and at 390 g it does not fold small enough for my bag. It is clearly a great mountain jacket, but for the walk to the station the Northpine Packable would have been enough at a third of the price.' },
        ja: { name: 'ゆか', title: '普段使いには硬くて重い', body: '通勤用に買いましたが後悔しています。生地が硬く、動くたびにガサガサ鳴り、390gあるのでカバンに入るほど小さくなりません。山では良いジャケットなのは分かりますが、駅までの道ならノースパインのパッカブルで十分で、値段も3分の1でした。' } },
      { stars: 3, date: '2026-03-19', variant: 'red-l', helpful: 39, verified: true,
        en: { name: 'Goro', title: 'Stopped beading after one season', body: 'After a season of weekend hikes the shoulders and forearms soaked up water and felt cold, although nothing leaked. Washing it and tumble-drying on low fixed it for a while; then I needed a wash-in re-proofer. Normal for any shell, I know, but at this price I hoped it would last longer between treatments.' },
        ja: { name: '五郎', title: '1シーズンで撥水が落ちた', body: '週末登山で1シーズン使ったら、肩と前腕の表地が水を吸って冷たく感じるようになりました（浸水はなし）。洗って乾燥機の低温にかけたらしばらく戻りましたが、その後は浸け込み式の撥水剤が必要に。どのシェルもそうだとは思いますが、この値段ならもう少し長持ちしてほしかったです。' } },
      { stars: 5, date: '2026-09-06', variant: 'black-m', helpful: 33, verified: true,
        en: { name: 'Riku', title: 'Hood works over my climbing helmet', body: 'Used it on a scrambling route with a helmet. The hood goes over it easily and the rear adjuster pulls it snug so it turns with my head. Without the helmet it cinches down small. Black M arrived the next day.' },
        ja: { name: 'りく', title: 'ヘルメットの上からかぶれる', body: '岩場のあるルートでヘルメットをかぶって使いました。フードは楽にかぶれ、後ろのアジャスターで締めれば頭と一緒に向きが変わります。ヘルメットなしでも小さく絞れます。ブラックのMは翌日届きました。' } },
      { stars: 4, date: '2026-04-22', variant: 'red-xl', helpful: 18, verified: true,
        en: { name: 'Hank', title: 'Red is brighter than the photo', body: 'I expected a darker red; it is closer to a bright tomato red. Easy to spot on the trail, which is the point. The XL fits me at 185 cm over a fleece with room to spare.' },
        ja: { name: 'ハンク', title: 'レッドは写真より明るい', body: 'もう少し深い赤を想像していましたが、明るいトマトのような赤です。山で目立つのでむしろ良し。185cmでXLをフリースの上に着て、まだ余裕があります。' } },
      { stars: 5, date: '2026-02-14', variant: 'red-m', helpful: 45, verified: true,
        en: { name: 'Toshi', title: 'Warranty repair was painless', body: 'At 14 months the seam tape at one cuff started to lift. I sent photos to Yamabiko, posted the jacket with their prepaid label and got it back repaired in 10 days, free under the 2-year warranty.' },
        ja: { name: 'とし', title: '保証修理がスムーズ', body: '14か月目に片方の袖口のシームテープがはがれてきました。写真を送り、メーカーの着払い伝票で発送したところ、2年保証で無料修理され10日で戻ってきました。' } },
      { stars: 4, date: '2026-07-25', variant: 'black-m', helpful: 26, verified: true,
        en: { name: 'Makoto', title: 'My wife chose the Tsukimi Trail instead', body: 'There is no women\'s version, so my wife tried on a friend\'s S and found it wide in the shoulders and short over the hips. She bought the Tsukimi Trail Women\'s, which is lighter at 280 g. Mine is the better jacket in a storm; hers is more comfortable for a walk around the onsen town.' },
        ja: { name: '誠', title: '妻は月見トレイルを選びました', body: 'レディースがないので、妻が友人のSを試着しましたが、肩幅が広く、お尻が隠れないとのこと。結局、280gと軽い月見トレイルのレディースを買いました。嵐の中ならこちらが上、温泉街を歩くなら妻のほうが快適そうです。' } },
      { stars: 2, date: '2026-09-28', variant: 'black-xl', helpful: 12, verified: true,
        en: { name: 'Leo', title: 'Hem toggle cracked on the second outing', body: 'The plastic toggle on the hem drawcord cracked in the cold on my second hike, so the hem now hangs loose. Small thing, but it feels flimsy for ¥22,000. Black XL also took three days to arrive while the other sizes were next-day.' },
        ja: { name: 'レオ', title: '2回目の山行で裾のコードストッパーが割れた', body: '2回目の山行で、寒さのせいか裾のドローコードのプラスチック製ストッパーが割れ、裾が締まらなくなりました。小さなことですが、22,000円にしては作りが安っぽいです。ブラックのXLは、ほかのサイズが翌日なのに届くまで3日かかりました。' } },
    ],
    qa: [
      { date: '2026-05-10', votes: 31,
        en: { q: 'Will the hood fit over a climbing helmet?', a: 'Yes. The hood fits over most climbing and cycling helmets up to about 62 cm head circumference. Loosen the rear adjuster first. Without a helmet, tighten the rear and both face adjusters so the hood turns with your head.', by: 'Yamabiko Customer Support' },
        ja: { q: '登山用ヘルメットの上からフードをかぶれますか？', a: 'はい。頭囲約62cmまでの一般的な登山用・自転車用ヘルメットの上からかぶれます。先に後頭部のアジャスターをゆるめてください。ヘルメットなしの場合は、後頭部と顔まわり両側のアジャスターを締めると、頭の動きにフードが追従します。', by: 'ヤマビコ カスタマーサポート' } },
      { date: '2026-08-02', votes: 40,
        en: { q: 'I am 168 cm and 60 kg. S or M?', a: 'I am 167 cm and 62 kg. The S fits over a fleece with room to move; the M was baggy on me.', by: 'Marketa customer (Daiki)' },
        ja: { q: '168cm・60kgです。SとMどちらがいいですか？', a: '167cm・62kgです。Sでフリースの上から着ても動きやすく、Mはだぶだぶでした。', by: 'マルケタ購入者（だいき）' } },
      { date: '2026-06-18', votes: 24,
        en: { q: 'Is there a women\'s version?', a: 'Not at the moment. Some smaller women wear the S, but it is wide at the shoulders and short at the hips. My wife bought the Tsukimi Trail Women\'s instead.', by: 'Marketa customer (Makoto)' },
        ja: { q: 'レディースモデルはありますか？', a: '今のところありません。小柄な女性がSを着ることもありますが、肩幅が広く丈もヒップまで届きません。妻は月見トレイルのレディースを買いました。', by: 'マルケタ購入者（誠）' } },
      { date: '2026-03-27', votes: 19,
        en: { q: 'How often should I wash it, and how do I re-proof it?', a: 'Wash it whenever it is dirty, and after every few hikes in summer. Use a little liquid detergent at 30 °C with no softener, then tumble dry on low for 20–30 minutes; the heat reactivates the water-repellent finish. When water no longer beads after drying, apply a wash-in re-proofer, or a spray-on one to the shoulders and forearms, and tumble dry again.', by: 'Yamabiko Customer Support' },
        ja: { q: 'どのくらいの頻度で洗い、撥水はどう回復させればいいですか？', a: '汚れたらその都度、夏は数回の山行ごとに洗ってください。少量の液体洗剤で30℃、柔軟剤は使わず、乾燥機の低温で20〜30分。熱で撥水加工が回復します。乾燥後も水を弾かない場合は、浸け込み式の撥水剤か、肩と前腕にスプレー式の撥水剤を使い、もう一度乾燥機にかけてください。', by: 'ヤマビコ カスタマーサポート' } },
      { date: '2026-09-12', votes: 15,
        en: { q: 'Can I reach the hand pockets while wearing a hip belt?', a: 'Yes. The hand pockets start about 8 cm above the hem line, so they sit above the hip belt of most 30–50 L packs.', by: 'Yamabiko Customer Support' },
        ja: { q: 'ザックのヒップベルトを締めたままハンドポケットを使えますか？', a: 'はい。ハンドポケットは裾から約8cm上に配置しているため、30〜50Lクラスのザックの多くでヒップベルトより上に位置します。', by: 'ヤマビコ カスタマーサポート' } },
    ],
    similar: ['northpine-packable', 'tsukimi-trail-women', 'drizzle-pro'],
    fbt: ['ampora-go-20k', 'kaze-openear'],
    alsoViewed: ['northpine-packable', 'tsukimi-trail-women', 'drizzle-pro', 'ampora-go-20k', 'kestrel-27k', 'kaze-openear'],
  },
  {
    id: 'tsukimi-trail-women',
    cat: 'outdoor',
    cluster: 'jackets',
    brand: { en: 'Tsukimi Trail', ja: '月見トレイル' },
    seller: 'marketa',
    images: ['tsukimi-trail-women'],
    title: {
      en: 'Tsukimi Trail Women\'s Rain Jacket, 2.5-Layer Waterproof 15,000 mm, Breathable 10,000 g/m²/24 h, Hip-Length Cut, Ponytail-Friendly Hood, 280 g, Packable, for Hiking and Everyday Rain',
      ja: '月見トレイル レインジャケット レディース 防水透湿 2.5レイヤー 耐水圧15,000mm 透湿性10,000g ヒップが隠れるロング丈 ポニーテール対応フード 軽量280g 登山 通勤 TT-WR3',
    },
    short: { en: 'Tsukimi Trail Women\'s Rain Jacket', ja: '月見トレイル レディース レインジャケット' },
    rating: 4.5,
    ratings: 268,
    hist: [70, 17, 7, 3, 3],
    added: '2025-04-08',
    badges: [],
    coupon: null,
    variantLabel: { en: 'Colour · Size', ja: 'カラー・サイズ' },
    variants: [
      { id: 'teal-xs', name: { en: 'Teal · XS', ja: 'ティール・XS' }, price: 12800, list: null, stock: 6, ship: 'fast' },
      { id: 'teal-s', name: { en: 'Teal · S', ja: 'ティール・S' }, price: 12800, list: null, stock: 14, ship: 'fast' },
      { id: 'teal-m', name: { en: 'Teal · M', ja: 'ティール・M' }, price: 12800, list: null, stock: 11, ship: 'fast' },
      { id: 'teal-l', name: { en: 'Teal · L', ja: 'ティール・L' }, price: 12800, list: null, stock: 5, ship: 'fast' },
      { id: 'plum-xs', name: { en: 'Plum · XS', ja: 'プラム・XS' }, price: 12800, list: null, stock: 3, ship: 'fast2' },
      { id: 'plum-s', name: { en: 'Plum · S', ja: 'プラム・S' }, price: 12800, list: null, stock: 8, ship: 'fast2' },
      { id: 'plum-m', name: { en: 'Plum · M', ja: 'プラム・M' }, price: 12800, list: null, stock: 9, ship: 'fast2' },
      { id: 'plum-l', name: { en: 'Plum · L', ja: 'プラム・L' }, price: 12800, list: null, stock: 2, ship: 'fast2' },
    ],
    returns: marketaJacketReturns,
    bullets: {
      en: [
        'MADE IN TSUKIMI ONSEN: designed by a small outdoor brand at the foot of Mount Tsukimi and tested on its trails through the June rainy season and autumn typhoons; sewn in Minori Prefecture.',
        'COVERS YOUR HIPS: a longer, women\'s-specific cut (78 cm back length in M) keeps rain off the top of your trousers and off your seat when you sit on a wet rock. The two-way front zip opens from the bottom for sitting and high steps.',
        'WATERPROOF 15,000 mm, BREATHABLE 10,000 g/m²/24 h: 2.5-layer fabric with fully taped seams, enough for a day hike in steady rain. There are no pit zips; a mesh-backed back vent lets some heat out.',
        'PONYTAIL-FRIENDLY HOOD: a vertical adjuster at the back leaves room for a low ponytail, and the soft peak keeps rain off glasses. A high bun or a stiff-brimmed cap will not fit under it.',
        'LIGHT AND PACKABLE: 280 g in size M; packs into the included stuff sack (18 × 12 cm).',
        'WOMEN\'S XS–L ON JAPANESE SIZING (XS = 5, S = 7, M = 9, L = 11). The hips are fitted: if you will wear a fleece and are between sizes, size up. 2-year warranty, plus paid repairs at the brand\'s workshop.',
      ],
      ja: [
        '【月見温泉生まれ】月見山のふもとの小さなアウトドアブランドが企画し、梅雨や秋の台風の季節に地元の登山道で試験を重ねたレインジャケットです。縫製はみのり県内の工場です。',
        '【お尻まで隠れるロング丈】女性の体型に合わせた長めの丈（Mサイズで着丈78cm）。パンツのウエストまわりや、濡れた岩に腰かけたときのお尻を雨から守ります。前ファスナーはダブルジップで、下から開けて座ったり大きな段差を上ったりできます。',
        '【耐水圧15,000mm・透湿性10,000g】全面シームテープ処理の2.5レイヤー素材。しとしと降り続く雨の日帰り登山にも対応します。ピットジップはありませんが、背中のメッシュ裏地付きベンチレーションから熱を逃がします。',
        '【ポニーテール対応フード】後頭部の縦方向アジャスターで低めのポニーテールが収まり、柔らかいひさしがメガネを雨から守ります。高い位置のお団子ヘアや、つばの硬いキャップの上からはかぶれません。',
        '【軽量・コンパクト】Mサイズで約280g。付属の収納袋（約18×12cm）に収まります。',
        '【レディースXS〜L（日本サイズ）】XS＝5号、S＝7号、M＝9号、L＝11号が目安。ヒップまわりはすっきりした作りのため、フリースを中に着る方でサイズに迷う場合は大きいほうを。メーカー保証2年、保証外の破れなども工房で有償修理できます。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Tsukimi Trail'], ['Model', 'TT-WR3'], ['Fit', 'Women\'s, hip length, fitted at the hips'], ['Sizes', 'XS, S, M, L (Japanese 5, 7, 9, 11)'],
        ['Construction', '2.5-layer, 20-denier recycled nylon with PU membrane'], ['Waterproof rating', '15,000 mm'], ['Breathability', '10,000 g/m²/24 h'],
        ['Seams', 'Fully taped'], ['Hood', 'Ponytail adjuster, soft peak; not helmet-compatible'], ['Ventilation', 'Mesh-backed back vent (no pit zips)'],
        ['Pockets', '2 zipped hand pockets, 1 inner mesh pocket'], ['Front zip', 'Two-way water-resistant zip'], ['Back length', '78 cm (size M)'],
        ['Weight', '280 g (size M)'], ['Care', 'Machine wash at 30 °C or below in a net; no softener; tumble dry low or iron low through a cloth'],
        ['Country of origin', 'Japan (sewn in Minori Prefecture)'], ['Warranty', '2 years (manufacturer)'], ['In the box', 'Jacket, stuff sack'],
      ],
      ja: [
        ['ブランド', '月見トレイル'], ['型番', 'TT-WR3'], ['フィット', 'レディース、ヒップ丈、ヒップまわりはすっきり'], ['サイズ', 'XS、S、M、L（5号・7号・9号・11号）'],
        ['素材構造', '2.5レイヤー、20デニール 再生ナイロン（PU防水透湿膜）'], ['耐水圧', '15,000mm'], ['透湿性', '10,000g/m²/24h'],
        ['シーム', '全面シームテープ'], ['フード', 'ポニーテール用アジャスター、柔らかいひさし（ヘルメット非対応）'], ['ベンチレーション', '背中のメッシュ裏地付きベンチレーション（ピットジップなし）'],
        ['ポケット', 'ファスナー付きハンドポケット×2、内側メッシュポケット×1'], ['前ファスナー', 'ダブルジップ止水ファスナー'], ['着丈', '78cm（Mサイズ）'],
        ['重量', '約280g（Mサイズ）'], ['お手入れ', '洗濯機可（30℃以下・ネット使用）、柔軟剤不可、乾燥機の低温または当て布で低温アイロン'],
        ['原産国', '日本（みのり県で縫製）'], ['保証', 'メーカー保証2年'], ['付属品', '本体、収納袋'],
      ],
    },
    compare: {
      en: ['2.5-layer', '15,000 mm', '10,000 g/m²/24 h', '280 g (M)', 'Women\'s XS–L; hip length', '2 years'],
      ja: ['2.5レイヤー', '15,000mm', '10,000g/m²/24h', '約280g（M）', 'レディースXS〜L、ヒップ丈', '2年'],
    },
    description: {
      en: [
        'Tsukimi Trail is a small outdoor brand with a workshop in Tsukimi Onsen, at the end of the HaruTetsu Kagami Line. Its founders guide on Mount Tsukimi and kept hearing the same complaint from women in their groups: unisex rain jackets are wide in the shoulders and stop at the waist, so the top of your trousers is wet by lunchtime. This jacket is their answer.',
        'Between a city jacket and a mountain shell: 15,000 mm keeps out steady rain for a full day hike and holds up to the straps of a light day pack. For all-day storms with a heavy pack, a 20,000 mm 3-layer shell is the safer choice. Breathability is 10,000 g/m²/24 h, but there are no pit zips, and a backpack covers the back vent, so on a steep, warm climb open the front zip from the top and slow your pace to avoid getting damp inside.',
        'Fit: sizes follow Japanese women\'s sizing (XS = 5, S = 7, M = 9, L = 11). The shoulders are narrower than a unisex jacket and the hips are fitted, so if you have fuller hips or will wear a fleece or thick trousers, choose the larger size. The sleeves are long; petite buyers under 150 cm find even the XS sleeves cover their hands, though the hook-and-loop cuffs can be tightened.',
        'Care: wash it in a net at 30 °C or below with a little liquid detergent, no softener or bleach, rinse well and tumble dry on low, or iron on low through a cloth, to revive the water repellency. Use a spray-on re-proofer when water stops beading.',
        'Teal is in stock at Marketa Harukawa for next-day delivery; Plum ships from another Marketa warehouse and takes two to three days. Tsukimi Trail\'s 2-year warranty covers defects in seams, zips and fabric. Tears, snags and worn cuffs are repaired at their workshop at cost, from ¥1,500 plus postage, in about two weeks.',
      ],
      ja: [
        '月見トレイルは、春川鉄道 鏡線の終点・月見温泉に工房を構える小さなアウトドアブランドです。月見山でガイドをしている創業者たちは、参加する女性たちから同じ悩みを何度も聞いてきました。「ユニセックスのレインジャケットは肩幅が広く、丈がウエストまでしかないので、お昼にはパンツの上のほうが濡れてしまう」。その答えとして作ったのがこのジャケットです。',
        '街用と山岳用シェルの中間：耐水圧15,000mmは、一日中降り続く雨の日帰り登山や、軽めのデイパックのベルトの圧にも耐えます。重い荷物を背負って一日中嵐の中を歩くなら、耐水圧20,000mmの3レイヤーシェルのほうが安心です。透湿性は10,000g/m²/24hですが、ピットジップはなく、背中のベンチレーションはザックで塞がれます。蒸し暑い日の急な登りでは、前ファスナーを上から開け、ペースを落として内側の蒸れを防いでください。',
        'サイズ感：日本のレディースサイズ基準です（XS＝5号、S＝7号、M＝9号、L＝11号）。ユニセックスより肩幅が狭く、ヒップまわりはすっきりしているため、ヒップがしっかりした方や、フリース・厚手のパンツと合わせる方は大きいほうをお選びください。袖は長めで、150cm未満の小柄な方はXSでも袖が手にかかるという声があります（袖口は面ファスナーで絞れます）。',
        'お手入れ：洗濯ネットに入れて30℃以下で、少量の液体洗剤で洗い、柔軟剤・漂白剤は使わずに十分すすいでください。乾燥機の低温、または当て布をして低温でアイロンをかけると撥水性が回復します。水を弾かなくなったら撥水スプレーをお使いください。',
        'ティールはマルケタ春川センターに在庫があり翌日お届け、プラムは県外のマルケタ倉庫から発送のため2〜3日かかります。メーカー保証は2年間で、シーム・ファスナー・生地の不良が対象です。破れ、かぎ裂き、袖口のすり切れなどは月見温泉の工房で有償修理（1,500円〜＋送料、約2週間）を承ります。',
      ],
    },
    tables: [
      {
        title: { en: 'Size chart (garment measurements, cm)', ja: 'サイズ表（仕上がり寸法・cm）' },
        en: [
          ['Size', 'Japanese size', 'Bust (garment)', 'Back length', 'Sleeve (shoulder to cuff)', 'Suggested height'],
          ['XS', '5', '94', '74', '56', '145–153'], ['S', '7', '98', '76', '57.5', '152–158'],
          ['M', '9', '102', '78', '59', '157–163'], ['L', '11', '107', '80', '60.5', '162–168'],
        ],
        ja: [
          ['サイズ', '号数', 'バスト（仕上がり）', '着丈（後ろ中心）', '袖丈（肩先から袖口）', '目安身長'],
          ['XS', '5号', '94', '74', '56', '145〜153'], ['S', '7号', '98', '76', '57.5', '152〜158'],
          ['M', '9号', '102', '78', '59', '157〜163'], ['L', '11号', '107', '80', '60.5', '162〜168'],
        ],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-19', variant: 'teal-s', helpful: 74, verified: true,
        en: { name: 'Natsuki', title: 'Finally covers my hips', body: 'Every unisex jacket I have tried is wide in the shoulders and stops at my waist, so the top of my trousers gets wet. This one is long enough that I can sit on a wet bench and stay dry. I am 158 cm and wear the S over a thin fleece; there is plenty of room at the hips for me.' },
        ja: { name: 'なつき', title: 'やっとお尻まで隠れる', body: 'ユニセックスのジャケットはどれも肩幅が広く、丈がウエストまでしかないので、パンツの上のほうが濡れていました。これは濡れたベンチに座っても大丈夫な長さ。158cmで薄手のフリースの上にSを着ていますが、ヒップまわりも私には余裕があります。' } },
      { stars: 3, date: '2026-08-27', variant: 'teal-m', helpful: 52, verified: true,
        en: { name: 'Yoko', title: 'Tight at the hips over a fleece', body: 'The length is great, but I wear size 11 skirts, and over a fleece the M pulls across the hips; I cannot sit without unzipping the bottom. Going up to L made the sleeves far too long. Try it on over your thickest layer before you take the tags off.' },
        ja: { name: '陽子', title: 'フリースを着るとヒップがきつい', body: '丈は最高ですが、スカートは11号の私がフリースの上にMを着ると、ヒップまわりが突っ張って、裾のファスナーを開けないと座れません。Lにすると今度は袖が長すぎ。タグを切る前に、いちばん厚い服の上から試着することをおすすめします。' } },
      { stars: 2, date: '2026-07-08', variant: 'teal-m', helpful: 44, verified: true,
        en: { name: 'Erika', title: 'Hood does not fit over a bun or a cap', body: 'The ponytail adjuster works for a low ponytail, but I wear my hair in a high bun for hiking and the hood presses it down painfully. Over my cap it will not close at all. A small hood on an otherwise good jacket.' },
        ja: { name: 'えりか', title: 'お団子ヘアやキャップの上からは無理', body: '低いポニーテールならアジャスターで収まりますが、山では高めのお団子にしているのでフードに押されて痛いです。キャップの上からはまったく閉まりません。ジャケット自体は良いのに、フードが小さいのが残念。' } },
      { stars: 1, date: '2026-08-16', variant: 'teal-l', helpful: 61, verified: true,
        en: { name: 'Michi', title: 'Sweaty on the Mount Tsukimi climb', body: 'I wore it on the Mount Tsukimi trail in warm drizzle. With no pit zips, by the steep section I was wetter inside from sweat than the rain would have made me. The back vent does almost nothing with a backpack on, because the pack covers it. Fine for walking around Tsukimi Onsen, not for a summer climb.' },
        ja: { name: 'みち', title: '月見山の登りで汗だく', body: '蒸し暑い霧雨の日に月見山の登山道で着ました。ピットジップがないので、急登に差しかかるころには雨より汗で内側がびしょびしょ。背中のベンチレーションはザックで塞がれるのでほとんど効きません。月見温泉の街歩きなら良いですが、夏の登山には向きません。' } },
      { stars: 2, date: '2026-06-05', variant: 'teal-xs', helpful: 37, verified: true,
        en: { name: 'Chii', title: 'Sleeves far too long on the XS', body: 'I am 147 cm. The body length of the XS is fine, but the sleeves cover my hands by about 5 cm even with the cuffs tightened. It is sold as a women\'s jacket, but petite women do not seem to have been considered.' },
        ja: { name: 'ちぃ', title: 'XSでも袖が長すぎる', body: '147cmです。XSの着丈はちょうど良いのですが、袖口を締めても袖が手を5cmほど覆ってしまいます。レディースなのに、小柄な人は想定されていないようです。' } },
      { stars: 5, date: '2026-09-02', variant: 'plum-l', helpful: 29, verified: true,
        en: { name: 'Hana', title: 'Sleeves long enough, for once', body: 'I am 168 cm with long arms, and most women\'s jackets end above my wrists. The L sleeves reach my thumbs. The plum is a lovely colour, deeper than on screen. It took three days to arrive, which was fine.' },
        ja: { name: 'はな', title: '袖の長さが足りる貴重な一着', body: '168cmで腕が長く、レディースのジャケットはたいてい手首が出てしまいます。Lは袖が親指の付け根まで届きます。プラムは画面より深みのあるきれいな色。届くまで3日かかりましたが問題なし。' } },
      { stars: 4, date: '2026-05-21', variant: 'teal-s', helpful: 33, verified: true,
        en: { name: 'Asami', title: 'Fits me better than the Northpine', body: 'I had the Northpine Packable in XS. It was cheaper and packs smaller, but the shoulders were wide and it stopped at my waist. This one fits as if it were made for me. It is ¥5,820 more, worth it if you walk a lot in the rain. One star off because the stuff sack is fiddly.' },
        ja: { name: 'あさみ', title: 'ノースパインより体に合う', body: 'ノースパインのパッカブル（XS）を持っていました。安くて小さくたためますが、肩幅が広く丈もウエストまで。こちらは自分のために作られたかのようなフィット感です。差額は5,820円ですが、雨の中をよく歩く人なら価値あり。収納袋に入れるのが少し面倒なので星ひとつ減。' } },
      { stars: 5, date: '2025-11-03', variant: 'teal-m', helpful: 22, verified: false,
        en: { name: 'Sumire', title: 'I bought mine at their workshop in Tsukimi Onsen', body: 'Their small workshop near the station sells these too, and the owner checked the fit on me in person. They also repaired a snag on my old one for ¥1,500. Lovely people, sturdy jacket.' },
        ja: { name: 'すみれ', title: '月見温泉の工房で購入しました', body: '駅近くの小さな工房でも販売していて、店主さんが直接サイズを見てくれました。前のジャケットのかぎ裂きも1,500円で直してもらいました。感じの良いお店で、丈夫なジャケットです。' } },
      { stars: 2, date: '2026-04-09', variant: 'plum-s', helpful: 19, verified: true,
        en: { name: 'K. Mori', title: 'Front zip is stiff and hard to start', body: 'The water-resistant zip is stiff, and engaging it at the bottom takes both hands and several tries, especially with cold fingers. It has eased a little after a month, but on a cold, rainy morning it is frustrating.' },
        ja: { name: '森', title: '前ファスナーが硬く、かみ合わせにくい', body: '止水ファスナーが硬く、下でかみ合わせるのに両手で何度かやり直す必要があります。指がかじかんでいるとなおさら。1か月でいくらか滑らかになりましたが、寒い雨の朝はイライラします。' } },
      { stars: 5, date: '2026-07-21', variant: 'teal-s', helpful: 15, verified: true,
        en: { name: 'Ami', title: 'Dry through the whole rainy season', body: 'I wore it every day in the rainy season for the walk to work, and on two day hikes. It never leaked, and it is light enough that I forget I am carrying it.' },
        ja: { name: 'あみ', title: '梅雨の間ずっと活躍', body: '梅雨の間、毎日の通勤と2回の日帰り登山で使いました。一度も浸水せず、持っているのを忘れるくらい軽いです。' } },
      { stars: 4, date: '2026-09-27', variant: 'plum-m', helpful: 8, verified: true,
        en: { name: 'Kumi', title: 'Lighter than my husband\'s Yamabiko', body: 'We hiked together in steady rain. His Yamabiko Storm is stiffer and he could open the pit zips, but mine is 110 g lighter, softer and covers my hips. We both stayed dry. The Plum M fits me at 160 cm.' },
        ja: { name: 'くみ', title: '夫のヤマビコより軽い', body: '夫婦でしとしと雨の中を歩きました。夫のヤマビコ ストームは生地が硬めでピットジップを開けられますが、私のは110g軽く、しなやかで、お尻まで隠れます。二人とも濡れずに済みました。160cmでプラムのMがちょうど良いです。' } },
    ],
    qa: [
      { date: '2026-06-14', votes: 27,
        en: { q: 'I am 158 cm and usually wear size 9 tops. Which size should I choose?', a: 'Our sizes follow Japanese women\'s sizing: S is 7, M is 9 and L is 11, so M should suit you. The hips are fitted, so if you will wear a fleece and your hips are fuller than your tops size suggests, choose L. The sleeves are on the long side, which also favours M over L if you are unsure.', by: 'Tsukimi Trail' },
        ja: { q: '158cmで、トップスは普段9号です。どのサイズがいいですか？', a: '当ブランドは日本のレディースサイズ基準で、S＝7号、M＝9号、L＝11号です。Mがおすすめです。ヒップまわりはすっきりした作りのため、フリースを中に着る予定で、トップスのサイズよりヒップがしっかりしている方はLを。袖は長めなので、迷う場合はMのほうが合いやすいです。', by: '月見トレイル' } },
      { date: '2026-05-02', votes: 21,
        en: { q: 'Is it long enough to sit on a wet bench?', a: 'Yes. On me (160 cm, size M) the back covers my seat completely, and I sit on wet benches at bus stops without getting wet.', by: 'Marketa customer (Kumi)' },
        ja: { q: '濡れたベンチに座れるくらいの丈がありますか？', a: 'はい。160cmでMを着ていますが、後ろはお尻まですっぽり隠れ、バス停の濡れたベンチに座っても濡れません。', by: 'マルケタ購入者（くみ）' } },
      { date: '2026-07-30', votes: 18,
        en: { q: 'Is there a men\'s version?', a: 'Not yet. We are a small workshop and started with women\'s jackets because that was where our guiding groups needed one most. A men\'s version is planned for spring 2027.', by: 'Tsukimi Trail' },
        ja: { q: 'メンズモデルはありますか？', a: 'まだございません。小さな工房のため、ガイドの現場でいちばん求められていたレディースから作り始めました。メンズは2027年春の発売を予定しています。', by: '月見トレイル' } },
      { date: '2026-08-20', votes: 25,
        en: { q: 'Do you repair jackets?', a: 'Yes. Defects in seams, zips and fabric are repaired or replaced free within the 2-year warranty. Tears, snags and worn cuffs are repaired at cost at our workshop in Tsukimi Onsen, from ¥1,500 plus postage, and take about two weeks. Please contact us with a photo first.', by: 'Tsukimi Trail' },
        ja: { q: '修理はしてもらえますか？', a: 'はい。シーム・ファスナー・生地の不良は2年保証の期間内なら無料で修理または交換します。破れ、かぎ裂き、袖口のすり切れは月見温泉の工房で有償修理（1,500円〜＋送料、約2週間）を承ります。まずは写真を添えてお問い合わせください。', by: '月見トレイル' } },
      { date: '2026-09-08', votes: 12,
        en: { q: 'Does the hood go over a cap?', a: 'Over a soft cap with a short brim, just about. Over a baseball cap with a stiff brim, no; it will not close around your face. A low ponytail is fine.', by: 'Marketa customer (Erika)' },
        ja: { q: 'キャップの上からフードをかぶれますか？', a: 'つばの短い柔らかいキャップならなんとか。つばの硬い野球帽だと顔まわりが閉まりません。低めのポニーテールなら問題ありません。', by: 'マルケタ購入者（えりか）' } },
    ],
    similar: ['northpine-packable', 'yamabiko-storm', 'drizzle-pro'],
    fbt: ['yumeguri-onsen-powder', 'ampora-slim-10k'],
    alsoViewed: ['northpine-packable', 'yamabiko-storm', 'drizzle-pro', 'yumeguri-onsen-powder', 'minori-bath-salts', 'ampora-slim-10k'],
  },
  {
    id: 'drizzle-pro',
    cat: 'outdoor',
    cluster: 'jackets',
    brand: { en: 'Drizzle Pro', ja: 'ドリズルプロ' },
    seller: 'brightdeal',
    images: ['drizzle-pro'],
    title: {
      en: 'Drizzle Pro Rain Jacket Men\'s Women\'s Waterproof Windproof Lightweight Hooded Raincoat with Storage Bag for Cycling, Commuting, Hiking, Camping, Festivals, Grey M L XL XXL',
      ja: 'ドリズルプロ レインジャケット メンズ レディース 防水 防風 軽量 撥水 フード付き レインコート 収納袋付き 自転車 通勤 通学 登山 アウトドア フェス グレー M L XL XXL',
    },
    short: { en: 'Drizzle Pro Rain Jacket', ja: 'ドリズルプロ レインジャケット' },
    rating: 3.2,
    ratings: 1077,
    hist: [30, 18, 17, 13, 22],
    added: '2025-05-22',
    badges: ['sponsored'],
    coupon: null,
    variantLabel: { en: 'Colour · Size', ja: 'カラー・サイズ' },
    variants: [
      { id: 'grey-m', name: { en: 'Grey · M', ja: 'グレー・M' }, price: 3480, list: 6980, stock: 64, ship: 'brightdeal' },
      { id: 'grey-l', name: { en: 'Grey · L', ja: 'グレー・L' }, price: 3480, list: 6980, stock: 88, ship: 'brightdeal' },
      { id: 'grey-xl', name: { en: 'Grey · XL', ja: 'グレー・XL' }, price: 3480, list: 6980, stock: 51, ship: 'brightdeal' },
      { id: 'grey-xxl', name: { en: 'Grey · XXL', ja: 'グレー・XXL' }, price: 3480, list: 6980, stock: 27, ship: 'brightdeal' },
    ],
    returns: {
      en: 'Sold and shipped by BrightDeal Trading, so their policy applies: returns within 30 days, but a change of mind (including the wrong size) is accepted only if the bag is unopened, and you pay ¥880 return shipping. For a defect, message the seller first and wait up to 2 business days for a prepaid label; Marketa Purchase Protection applies if they do not reply.',
      ja: 'ブライトディール商事が販売・発送するため、同社の返品条件が適用されます。返品はお届けから30日以内ですが、お客様都合（サイズ違いを含む）は未開封の場合のみで、返送料880円はお客様負担です。不良品の場合はまず出品者にメッセージで連絡し、着払いラベルの送付を最大2営業日お待ちください。返信がない場合はマルケタ購入者保護の対象です。',
    },
    bullets: {
      en: [
        'WATERPROOF COATING: polyester with a PU coating on the inside, rated 3,000 mm. Suitable for light to moderate rain and short trips; not designed for long periods of heavy rain.',
        'LIGHTWEIGHT AND COMPACT: about 320 g, folds into the included drawstring bag (22 × 18 cm) for your bag, bike basket or car.',
        'HOOD WITH DRAWCORD, elastic cuffs and a front zip under a hook-and-loop storm flap to keep out wind.',
        'SIZES M–XXL, ASIAN SIZING, CUT SMALL: please compare the size chart with a jacket you own before opening the bag. Many buyers choose one or two sizes up.',
        'PLEASE NOTE: the PU coating does not breathe, so the inside can become damp when cycling or walking fast. A new coating has a smell when unpacked; air it for a few days.',
        'SHIPS FROM BRIGHTDEAL TRADING in Kobe with free shipping; delivery takes 4–8 days. Change-of-mind returns are accepted only if the bag is unopened.',
      ],
      ja: [
        '【防水コーティング】ポリエステル生地の裏にPUコーティング、耐水圧3,000mm。小雨〜普通の雨、短時間の外出に適しています。長時間の大雨での使用は想定していません。',
        '【軽量・コンパクト】約320g。付属の巾着袋（約22×18cm）にたためて、カバンや自転車のかご、車に常備できます。',
        '【フード・袖口・前立て】ドローコード付きフード、ゴム入り袖口、面ファスナー付きの前立てでファスナー部分からの風を防ぎます。',
        '【サイズM〜XXL（アジアサイズ・小さめ）】開封前に、お手持ちの上着とサイズ表を比べてください。1〜2サイズ上を選ぶ方が多いです。',
        '【ご注意】PUコーティングは透湿性がないため、自転車や早歩きでは内側が蒸れることがあります。新品はコーティング特有のにおいがあります。数日陰干ししてからお使いください。',
        '【ブライトディール商事（神戸）から発送】送料無料、お届けまで4〜8日。お客様都合の返品は未開封の場合のみ承ります。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Drizzle Pro'], ['Model', 'DP-2088'], ['Sizes', 'M, L, XL, XXL (Asian sizing)'], ['Material', '100% polyester, PU coating inside'],
        ['Waterproof rating', '3,000 mm (seller\'s figure)'], ['Breathability', 'Not stated'], ['Seams', 'Taped (main seams)'], ['Hood', 'Drawcord, no peak'],
        ['Pockets', '2 open hand pockets (no zips)'], ['Front closure', 'Plastic zip with hook-and-loop storm flap'], ['Cuffs', 'Elastic'],
        ['Weight', 'About 320 g (size L)'], ['Care', 'Hand wash in cold water; do not tumble dry, iron or dry-clean'],
        ['Country of origin', 'China'], ['Warranty', 'None from the manufacturer; 30-day seller returns'], ['In the box', 'Jacket, drawstring storage bag'],
      ],
      ja: [
        ['ブランド', 'ドリズルプロ'], ['型番', 'DP-2088'], ['サイズ', 'M、L、XL、XXL（アジアサイズ）'], ['素材', 'ポリエステル100％（裏面PUコーティング）'],
        ['耐水圧', '3,000mm（出品者表記）'], ['透湿性', '表記なし'], ['シーム', 'シームテープ（主要部分）'], ['フード', 'ドローコード付き、ひさしなし'],
        ['ポケット', 'ハンドポケット×2（ファスナーなし）'], ['前開き', '樹脂ファスナー＋面ファスナー付き前立て'], ['袖口', 'ゴム入り'],
        ['重量', '約320g（Lサイズ）'], ['お手入れ', '手洗い（水）、乾燥機・アイロン・ドライクリーニング不可'],
        ['原産国', '中国'], ['保証', 'メーカー保証なし（出品者の30日返品対応のみ）'], ['付属品', '本体、巾着型収納袋'],
      ],
    },
    compare: {
      en: ['PU-coated single layer', '3,000 mm', 'Not stated', 'About 320 g (L)', 'M–XXL; runs small', 'None (seller returns only)'],
      ja: ['PUコーティング（一層）', '3,000mm', '表記なし', '約320g（L）', 'M〜XXL、小さめ', 'なし（出品者の返品対応のみ）'],
    },
    description: {
      en: [
        'A low-cost rain jacket to keep in the car, a bike basket or a desk drawer for sudden showers. The polyester shell has a PU coating on the inside that stops light and moderate rain, and the jacket folds into a drawstring bag.',
        'About the 3,000 mm rating: this is enough for light rain and for moderate rain for a short time, such as a 10–20 minute walk or ride. In heavy rain, or where bag straps press on the fabric, water can be forced through, especially along seams. For long walks in heavy rain, or for hiking, choose a jacket rated 10,000 mm or higher.',
        'Sizing: this is Asian sizing and the cut is small. Measure the chest of a jacket you own lying flat and compare it with the chart below; if you usually wear M in Japanese sizes, L or XL is likely to fit. Please check the size before opening the bag, because change-of-mind returns (including the wrong size) are accepted only unopened.',
        'Care: a new PU coating has a smell when you open the bag; hang it in a well-ventilated place for a few days. Hand wash in cold water with a mild detergent and dry in the shade. Heat from a tumble dryer or iron, and dry-cleaning solvents, can make the coating peel or stick together. Do not store it folded while damp.',
        'Ships from BrightDeal Trading\'s warehouse in Kobe with free shipping, separately from items shipped by Marketa, and is not eligible for Marketa Fast delivery. There is no manufacturer warranty; defects are handled by the seller within 30 days of delivery.',
      ],
      ja: [
        '車やかご、デスクの引き出しに常備して、急な雨に備えるための低価格レインジャケットです。ポリエステル生地の裏面にPUコーティングを施し、小雨〜普通の雨を防ぎます。巾着袋にたためて持ち運べます。',
        '耐水圧3,000mmについて：小雨や、10〜20分程度の徒歩・自転車での普通の雨なら十分な目安です。大雨や、カバンのベルトで生地が押される部分では、特に縫い目から水がしみることがあります。大雨の中を長く歩く場合や登山には、耐水圧10,000mm以上のジャケットをおすすめします。',
        'サイズについて：アジアサイズで、小さめの作りです。お手持ちの上着を平置きにして胸まわりを測り、下のサイズ表と比べてください。国内ブランドで普段Mの方は、LまたはXLが目安です。お客様都合の返品（サイズ違いを含む）は未開封の場合のみのため、必ず開封前にご確認ください。',
        'お手入れ：開封直後はPUコーティング特有のにおいがあります。風通しの良い場所で数日陰干ししてください。水で中性洗剤を使って手洗いし、日陰で干してください。乾燥機やアイロンの熱、ドライクリーニングの溶剤でコーティングがはがれたり貼りついたりすることがあります。濡れたままたたんで保管しないでください。',
        'ブライトディール商事の神戸倉庫から送料無料で発送します。マルケタ発送の商品とは別にお届けとなり、マルケタFastのお届け対象外です。メーカー保証はなく、不良はお届けから30日以内に出品者が対応します。',
      ],
    },
    tables: [
      {
        title: { en: 'Seller\'s size chart (garment measurements, cm)', ja: '出品者によるサイズ表（仕上がり寸法・cm）' },
        en: [
          ['Size', 'Chest (garment)', 'Back length', 'Sleeve (shoulder to cuff)', 'Suggested height'],
          ['M', '100', '68', '58', '160–168'], ['L', '104', '70', '59', '166–174'],
          ['XL', '108', '72', '60', '172–180'], ['XXL', '112', '74', '61', '178–186'],
        ],
        ja: [
          ['サイズ', '胸囲（仕上がり）', '着丈（後ろ中心）', '袖丈（肩先から袖口）', '目安身長'],
          ['M', '100', '68', '58', '160〜168'], ['L', '104', '70', '59', '166〜174'],
          ['XL', '108', '72', '60', '172〜180'], ['XXL', '112', '74', '61', '178〜186'],
        ],
      },
    ],
    reviews: [
      { stars: 1, date: '2026-09-18', variant: 'grey-l', helpful: 211, verified: true,
        en: { name: 'Yusuke', title: 'Seams leak at the shoulders', body: 'I wore it for a 20-minute walk from Minori Port Station in heavy rain. The shoulders of my shirt were soaked in two neat lines along the shoulder seams. Inside out, you can see the back and side seams are taped but the shoulder seams are not. The fabric held up; the seams did not.' },
        ja: { name: 'ゆうすけ', title: '肩の縫い目から浸水', body: '大雨の中、みのり港駅から20分歩きました。シャツの両肩が、縫い目に沿って2本の線のようにびっしょり。裏返して見ると、背中と脇の縫い目にはシームテープがあるのに、肩の縫い目にはありません。生地は持ちこたえましたが、縫い目がダメでした。' } },
      { stars: 1, date: '2026-08-09', variant: 'grey-m', helpful: 154, verified: true,
        en: { name: 'Mariko', title: 'Strong chemical smell', body: 'When I opened the bag the smell filled the room, like a new inflatable pool. I hung it on the balcony for a week and it still smells when it gets warm. I wear it with the car window open. I could not return it because the bag had been opened.' },
        ja: { name: 'まりこ', title: '薬品のにおいがきつい', body: '袋を開けた瞬間、部屋中に新品のビニールプールのようなにおいが広がりました。1週間ベランダに干しても、温まるとまだにおいます。車では窓を開けて着ています。開封済みなので返品できませんでした。' } },
      { stars: 2, date: '2026-07-17', variant: 'grey-xl', helpful: 98, verified: true,
        en: { name: 'Shota', title: 'Zip sticks on the storm flap', body: 'The zip catches the fabric of the inner flap every time, and on the fourth day the slider came off at the bottom. I messaged BrightDeal and waited two business days for a return label. The refund came a week after it reached their warehouse in Kobe.' },
        ja: { name: 'しょうた', title: 'ファスナーが前立てを噛む', body: 'ファスナーを上げるたびに内側の前立ての生地を噛み、4日目にスライダーが下から外れました。ブライトディールにメッセージを送り、返送ラベルが届くまで2営業日待ちました。神戸の倉庫に届いてから1週間で返金されました。' } },
      { stars: 2, date: '2026-06-30', variant: 'grey-l', helpful: 87, verified: true,
        en: { name: 'Akira', title: 'Runs two sizes small', body: 'I am 170 cm and wear M in Japanese brands. I ordered L to be safe and still could not zip it over a sweater. Measured flat, the chest was 100 cm, not the 104 cm on the chart. Go two sizes up.' },
        ja: { name: 'あきら', title: '2サイズ小さい', body: '170cmで、国内ブランドならMです。念のためLを買いましたが、セーターの上だとファスナーが閉まりません。平置きで測ると胸囲は100cmで、サイズ表の104cmより小さかったです。2サイズ上を選ぶのがおすすめ。' } },
      { stars: 4, date: '2026-08-21', variant: 'grey-m', helpful: 41, verified: true,
        en: { name: 'Nori', title: 'Fits fine, and does what it says for the price', body: 'I am 163 cm, 55 kg, and the M fits normally over a T-shirt, so I do not understand the "two sizes small" reviews; maybe it depends on your build. It kept me dry cycling 10 minutes to the station in moderate rain. For ¥3,480 I did not expect a mountain jacket.' },
        ja: { name: 'のり', title: 'サイズは普通。値段なりに十分', body: '163cm・55kgで、Tシャツの上にMを着てちょうど良いサイズ感です。「2サイズ小さい」というレビューは体型次第なのかも。普通の雨の中、駅まで自転車で10分走って濡れませんでした。3,480円で登山用並みは期待していません。' } },
      { stars: 5, date: '2026-05-12', variant: 'grey-xl', helpful: 25, verified: true,
        en: { name: 'Kei', title: 'Fine as a car emergency jacket', body: 'Lives in the boot of the car for when it starts raining at the supermarket. Folds into its bag. That is all I need.' },
        ja: { name: 'けい', title: '車の非常用にちょうどいい', body: 'スーパーで急に降られたとき用に、車のトランクに入れています。袋に収まるし、これで十分です。' } },
      { stars: 3, date: '2026-04-25', variant: 'grey-l', helpful: 33, verified: true,
        en: { name: 'Hiroko', title: 'Keeps rain out, keeps sweat in', body: 'On my 25-minute bike commute I arrive as damp inside as out. The coating does not breathe at all. OK for short trips.' },
        ja: { name: 'ひろこ', title: '雨は防ぐけど汗もこもる', body: '自転車通勤25分で、着くころには内側も外と同じくらい湿っています。生地がまったく呼吸しません。短距離ならOK。' } },
      { stars: 1, date: '2026-09-25', variant: 'grey-m', helpful: 57, verified: true,
        en: { name: 'Tetsuya', title: 'Opened it to try it on, so no return', body: 'The M was too small, but because I had opened the bag to try it on, BrightDeal refused a change-of-mind return. The listing does say "unopened only", but how are you supposed to check the size of a jacket without opening it? Check the chart, then go up two sizes.' },
        ja: { name: '哲也', title: '試着のために開封したら返品不可', body: 'Mが小さかったのですが、試着のために袋を開けたので、ブライトディールにお客様都合の返品を断られました。確かに「未開封のみ」と書いてありますが、開けずにどうやってサイズを確かめろと？サイズ表を見て、2サイズ上を買ってください。' } },
      { stars: 5, date: '2026-03-03', variant: 'grey-xxl', helpful: 3, verified: false,
        en: { name: 'happyshopper88', title: 'Very good!!!', body: 'Very good quality and waterproof. Fast delivery. Recommend!!' },
        ja: { name: 'ハッピー', title: 'とても良い！！', body: '品質がとても良く、防水です。配送も早い。おすすめです！！' } },
      { stars: 2, date: '2026-07-29', variant: 'grey-l', helpful: 76, verified: true,
        en: { name: 'Chika', title: 'Returned it and bought the Northpine', body: 'It leaked at the shoulders the first time it rained properly, like others say. I sent it back as defective (free) and bought the Northpine Packable for ¥6,980, which has fully taped seams and has not leaked in two months. Spend the extra.' },
        ja: { name: 'ちか', title: '返品してノースパインに', body: '皆さんと同じく、本降りの雨で初日に肩から浸水。不良品として返品し（送料無料）、全面シームテープのノースパインのパッカブル（6,980円）を買い直しました。2か月使って一度も浸水していません。差額を払う価値あり。' } },
      { stars: 3, date: '2025-10-12', variant: 'grey-xl', helpful: 48, verified: true,
        en: { name: 'Ryota', title: 'OK at the Lantern Festival, but no peak on the hood', body: 'Wore it at the Lantern Festival yesterday in light rain and stayed dry for two hours. The hood has no peak, so rain ran straight into my eyes every time I looked up at the lanterns. Fine for light rain only.' },
        ja: { name: 'りょうた', title: '灯籠まつりでは使えた。フードにひさしなし', body: '昨日の灯籠まつりで小雨の中2時間着て、濡れずに済みました。ただフードにひさしがないので、灯籠を見上げるたびに雨が目に入ります。小雨専用ですね。' } },
      { stars: 4, date: '2026-06-11', variant: 'grey-l', helpful: 14, verified: true,
        en: { name: 'Miki', title: 'Smell went after two hand washes', body: 'Yes, it smells when new. I hand washed it twice with mild detergent, dried it in the shade, and the smell is gone. I hike in a Yamabiko Storm; this is the cheap one I keep at work for drizzle, and it is fine for that.' },
        ja: { name: 'みき', title: '2回手洗いしたらにおいは消えた', body: '新品のにおいは確かにあります。中性洗剤で2回手洗いして日陰干ししたら消えました。登山ではヤマビコ ストームを着ていて、これは職場に置いておく小雨用の安いもの。その用途なら十分です。' } },
    ],
    qa: [
      { date: '2026-05-20', votes: 34,
        en: { q: 'Are the seams taped?', a: 'Yes, fully taped. I checked.', by: 'Marketa customer (Haruto)' },
        ja: { q: '縫い目にシームテープはありますか？', a: 'はい、全部テープ処理されています。確認しました。', by: 'マルケタ購入者（はると）' } },
      { date: '2026-09-19', votes: 52,
        en: { q: 'Which seams exactly are taped? My shoulders got wet.', a: 'Only the back and side seams. The shoulder seams and the seams where the sleeves join are not taped, which is why so many of us got wet shoulders. The answer above saying "fully taped" is wrong.', by: 'Marketa customer (Yusuke)' },
        ja: { q: '具体的にどの縫い目がテープ処理されていますか？肩が濡れました。', a: '背中と脇の縫い目だけです。肩の縫い目と袖付けの縫い目にはテープがなく、だから多くの人の肩が濡れています。上の「全部テープ処理」という回答は誤りです。', by: 'マルケタ購入者（ゆうすけ）' } },
      { date: '2026-06-02', votes: 28,
        en: { q: 'Can I return it if the size is wrong?', a: 'Change-of-mind returns, including the wrong size, are accepted within 30 days only if the bag is unopened, and the buyer pays ¥880 return shipping. Please compare the size chart with a jacket you own before opening. For a defective item, message us and we will send a prepaid label within 2 business days.', by: 'BrightDeal Trading' },
        ja: { q: 'サイズが合わなかった場合、返品できますか？', a: 'サイズ違いを含むお客様都合の返品は、お届けから30日以内・未開封の場合のみ承ります（返送料880円はお客様負担）。開封前に、お手持ちの上着とサイズ表をお比べください。不良品の場合はメッセージでご連絡いただければ、2営業日以内に着払いラベルをお送りします。', by: 'ブライトディール商事' } },
      { date: '2026-07-05', votes: 19,
        en: { q: 'Can I wash it in a machine or use a dryer?', a: 'Please hand wash it in cold water with a mild detergent and dry it in the shade. Do not use a tumble dryer, an iron or dry-cleaning; heat can make the PU coating peel or stick together.', by: 'BrightDeal Trading' },
        ja: { q: '洗濯機や乾燥機は使えますか？', a: '水で中性洗剤を使って手洗いし、日陰で干してください。乾燥機・アイロン・ドライクリーニングは使用できません。熱でPUコーティングがはがれたり貼りついたりすることがあります。', by: 'ブライトディール商事' } },
      { date: '2026-08-12', votes: 11,
        en: { q: 'Does the smell go away?', a: 'Mostly. After a week of airing and two hand washes I only notice it when the jacket is warm from the sun.', by: 'Marketa customer (Miki)' },
        ja: { q: 'においは消えますか？', a: 'ほぼ消えます。1週間干して2回手洗いしたら、日に当たって温まったときに少し感じる程度になりました。', by: 'マルケタ購入者（みき）' } },
    ],
    similar: ['northpine-packable', 'yamabiko-storm', 'tsukimi-trail-women'],
    fbt: ['voltx-pods', 'titancell-40k'],
    alsoViewed: ['northpine-packable', 'yamabiko-storm', 'tsukimi-trail-women', 'voltx-pods', 'titancell-40k', 'tokiya-mug-pair'],
  },
];
