// Electric kettles (Kitchen). See content/README-schema in build.mjs header for the shape.
export const cluster = {
  id: 'kettles',
  compareRows: {
    en: ['Capacity', 'Power', 'Body', 'Temperature settings', 'Keep warm', 'Warranty'],
    ja: ['容量', '消費電力', '本体素材', '温度設定', '保温', '保証'],
  },
};

export default [
  {
    id: 'corvo-kettle',
    cat: 'kitchen',
    cluster: 'kettles',
    brand: { en: 'Corvo', ja: 'コルヴォ' },
    seller: 'marketa',
    images: ['corvo-kettle'],
    title: {
      en: 'Corvo Quick-Boil Electric Kettle 1.0 L, Brushed Stainless Steel, 1,250 W, Auto Shut-Off and Boil-Dry Protection, 360° Base',
      ja: 'コルヴォ 電気ケトル 1.0L ステンレス 1250W 空焚き防止 自動電源オフ 360度回転ベース CV-K100',
    },
    short: { en: 'Corvo Quick-Boil Kettle 1.0 L', ja: 'コルヴォ 電気ケトル 1.0L' },
    rating: 4.2,
    ratings: 2316,
    hist: [58, 20, 9, 5, 8],
    added: '2024-11-20',
    badges: ['bestseller'],
    coupon: { amount: 300, en: 'Save ¥300 with coupon', ja: '300円OFFクーポン' },
    returns: {
      en: 'Returnable within 30 days of delivery. Opened but not faulty: refunded minus a 15% restocking fee. Faulty: free return; after 30 days the 1-year Corvo warranty applies.',
      ja: 'お届けから30日以内なら返品可能。開封済みで不良がない場合は15%の返品手数料を差し引いて返金します。不良品は返送料無料。30日を過ぎた後はコルヴォのメーカー保証（1年）の対象です。',
    },
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'silver', name: { en: 'Silver', ja: 'シルバー' }, price: 3980, list: 4980, stock: 40, ship: 'fast' },
      { id: 'black', name: { en: 'Matte Black', ja: 'マットブラック' }, price: 4280, list: 4980, stock: 6, ship: 'fast2' },
    ],
    bullets: {
      en: [
        'BOILS ONE CUP IN ABOUT 70 SECONDS: 1,250 W heating boils 140 mL in about 1 min 10 s and a full 1.0 L in about 3 min 20 s (tap water at 20 °C).',
        'SAFE TO LEAVE: switches itself off when the water boils, when the kettle is lifted, and if it is switched on empty (boil-dry protection).',
        'STAINLESS INSIDE: the water touches only SUS304 stainless steel and the silicone lid seal; the inner lid is polypropylene but does not touch the water when the kettle is upright.',
        'SINGLE-WALL BODY: the outside gets hot during and after boiling. If you want a body that stays cool to the touch, see the Hearth Double-Wall Kettle.',
        'COMPACT: 21.5 × 14.5 × 20.5 cm and 0.68 kg empty. The 0.9 m cord winds under the 360° base.',
        '1-YEAR WARRANTY from Corvo. No water window: the 0.25 L and 1.0 L marks are inside the kettle.',
      ],
      ja: [
        '【カップ1杯約70秒】1250Wのパワーで140mLを約1分10秒、満水1.0Lを約3分20秒で沸かします（水温20℃の場合）。',
        '【安心の3つの安全機能】沸騰すると自動で電源オフ。本体を持ち上げたときもオフ。空のままスイッチを入れても空焚き防止機能が働きます。',
        '【内側はステンレス】水が触れるのはステンレス（SUS304）とシリコンパッキンのみ。内ぶたはポリプロピレン製ですが、通常の使用では水に触れません。',
        '【シングル構造】沸騰中・沸騰後は本体の外側が熱くなります。外側が熱くなりにくいケトルをお探しの方は「ハース 二重構造ケトル」もご覧ください。',
        '【コンパクト】幅21.5×奥行14.5×高さ20.5cm、本体約0.68kg。0.9mのコードは360度回転ベースの底に巻き取れます。',
        '【メーカー保証1年】水量窓はありません。0.25Lと1.0Lの目盛りは本体内側にあります。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Corvo'], ['Model', 'CV-K100'], ['Capacity', '1.0 L (minimum 0.25 L)'], ['Power', '1,250 W, 100 V, 50/60 Hz'],
        ['Boil time', '1.0 L about 3 min 20 s; 140 mL about 1 min 10 s'], ['Body material', 'Stainless steel (SUS304), single wall'],
        ['Lid', 'Stainless outer, polypropylene inner, silicone seal'], ['Water window', 'No (marks inside)'],
        ['Safety', 'Auto shut-off, boil-dry protection, lift-off shut-off'], ['Temperature settings', 'None (boil only)'], ['Keep warm', 'No'],
        ['Cord length', '0.9 m'], ['Dimensions', '21.5 × 14.5 × 20.5 cm'], ['Weight', '0.68 kg (0.85 kg with base)'],
        ['Country of origin', 'China'], ['Warranty', '1 year (manufacturer)'], ['In the box', 'Kettle, power base, quick guide'],
      ],
      ja: [
        ['ブランド', 'コルヴォ'], ['型番', 'CV-K100'], ['容量', '1.0L（最小0.25L）'], ['消費電力', '1250W（100V 50/60Hz）'],
        ['沸騰時間', '1.0L 約3分20秒／140mL 約1分10秒'], ['本体素材', 'ステンレス（SUS304）シングル構造'],
        ['ふた', '外側ステンレス、内側ポリプロピレン、シリコンパッキン'], ['水量窓', 'なし（内側に目盛り）'],
        ['安全機能', '自動電源オフ、空焚き防止、持ち上げ時オフ'], ['温度設定', 'なし（沸騰のみ）'], ['保温', 'なし'],
        ['コード長', '0.9m'], ['サイズ', '幅21.5×奥行14.5×高さ20.5cm'], ['重量', '約0.68kg（ベース込み約0.85kg）'],
        ['原産国', '中国'], ['保証', 'メーカー保証1年'], ['付属品', '本体、電源プレート、クイックガイド'],
      ],
    },
    compare: {
      en: ['1.0 L', '1,250 W', 'Stainless, single wall', 'None', 'No', '1 year'],
      ja: ['1.0L', '1250W', 'ステンレス（シングル）', 'なし', 'なし', '1年'],
    },
    description: {
      en: [
        'The Corvo Quick-Boil is a plain, compact kettle for people who mostly boil water for one or two cups at a time: tea, instant coffee, cup noodles, a baby bottle. It holds 1.0 L, enough for about five mugs, and its 1,250 W element is the most powerful a standard 100 V wall socket supports comfortably.',
        'Inside, the water touches stainless steel only, with no plastic water gauge. The trade-off is that you cannot see the water level from outside: the fill marks are inside, so you look in through the lid. The lid opens with a button on the handle and stops upright at 75°.',
        'The body is a single layer of steel, so the outside gets hot when the water boils and stays warm for several minutes. Keep it out of reach of small children. Wipe the outside with a soft cloth; to remove limescale, boil 0.8 L of water with 1 tablespoon of citric acid, leave for an hour and rinse.',
        'Corvo covers the kettle and base for one year from purchase. Keep your Marketa order confirmation as proof of purchase; you do not need to register the product.',
      ],
      ja: [
        'コルヴォ 電気ケトルは、お茶やインスタントコーヒー、カップ麺、ミルク作りなど、1〜2杯分のお湯をさっと沸かしたい方のためのシンプルでコンパクトなケトルです。容量は1.0L（マグカップ約5杯分）。家庭用100Vコンセントで無理なく使える1250Wのヒーターを搭載しています。',
        '水が触れる部分はステンレスのみで、樹脂製の水量計はありません。そのぶん外から水量は見えず、目盛りはふたを開けて内側で確認します。ふたは取っ手のボタンで開き、75度の位置で止まります。',
        '本体はステンレス一枚のシングル構造のため、沸騰中と沸騰後しばらくは外側が熱くなります。小さなお子さまの手の届かない場所でお使いください。お手入れは柔らかい布で拭くだけ。水あかが気になるときは、水0.8Lにクエン酸大さじ1を入れて沸かし、1時間置いてからすすいでください。',
        'メーカー保証は購入日から1年間（本体・電源プレート）。マルケタの注文確認メールが購入証明になります。製品登録は不要です。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-21', variant: 'silver', helpful: 214, verified: true,
        en: { name: 'Keiko T.', title: 'Fast, quiet enough, nothing to break', body: 'I make tea four or five times a day and this boils a mug in just over a minute. No screen, no buttons except the switch, which is exactly what I wanted after my last kettle\'s display died. The click when it turns off is quite loud, which I actually like because I can hear it from the next room.' },
        ja: { name: 'けいこ', title: '速くてシンプル、壊れる所がない', body: '1日に4〜5回お茶を入れますが、マグ1杯分が1分ちょっとで沸きます。画面もボタンもスイッチだけ。前のケトルは表示部分が壊れたので、これくらいシンプルなのが良いです。切れるときのカチッという音は大きめですが、隣の部屋でも聞こえるので私にはむしろ便利。' } },
      { stars: 2, date: '2026-08-30', variant: 'silver', helpful: 187, verified: true,
        en: { name: 'Daisuke M.', title: 'The outside gets dangerously hot', body: 'It boils fast, but the whole body is too hot to touch for about five minutes afterwards. I brushed it with my wrist and got a red mark. The description does say single wall, but the photos make it look like the double-wall kind. With kids in the house I returned it and bought the Hearth double-wall one, which costs ¥1,000 more and stays warm, not hot.' },
        ja: { name: 'だいすけ', title: '外側がかなり熱くなります', body: '沸くのは速いですが、沸騰後5分くらいは本体全体が触れないほど熱いです。手首が当たって赤くなりました。説明にはシングル構造と書いてありますが、写真だと二重構造に見えます。子どもがいるので返品し、1,000円ほど高いハースの二重構造タイプに買い替えました。そちらは温かい程度で済みます。' } },
      { stars: 4, date: '2026-09-02', variant: 'black', helpful: 96, verified: true,
        en: { name: 'Mina', title: 'Black finish shows water spots', body: 'Good kettle, and the matte black looks great on the counter for the first day. After that every drip and fingerprint shows. I wipe it daily. Took three days to arrive because black was not in the Harukawa warehouse; silver would have come the next day.' },
        ja: { name: 'みな', title: 'ブラックは水滴の跡が目立ちます', body: 'ケトルとしては満足。マットブラックは置いた初日はとても素敵ですが、その後は水滴や指紋がすべて目立ちます。毎日拭いています。ブラックは春川の倉庫に在庫がなかったようで届くまで3日かかりました。シルバーなら翌日だったそうです。' } },
      { stars: 1, date: '2026-07-14', variant: 'silver', helpful: 152, verified: true,
        en: { name: 'H. Ono', title: 'Lid hinge snapped after five months', body: 'The plastic inner part of the lid hinge cracked and now the lid will not stay closed, so it never switches off by itself because the steam does not reach the sensor. Corvo replaced it under the 1-year warranty, but it took 12 days and I had to send photos twice.' },
        ja: { name: '小野', title: '5か月でふたのヒンジが割れた', body: 'ふたのヒンジ部分の樹脂が割れ、ふたが閉まらなくなりました。蒸気がセンサーに届かないので自動で電源が切れません。1年保証でメーカーが交換してくれましたが、写真を2回送る必要があり、12日かかりました。' } },
      { stars: 5, date: '2026-06-28', variant: 'silver', helpful: 61, verified: true,
        en: { name: 'Ren', title: 'Perfect for a one-room apartment', body: 'Small enough for my tiny counter and the cord winds underneath. I only ever boil 300 to 500 mL, so 1.0 L is plenty. For the price you cannot go wrong.' },
        ja: { name: 'れん', title: 'ワンルームにぴったり', body: '狭いキッチンにも置ける大きさで、コードは底に巻き取れます。一度に沸かすのは300〜500mLくらいなので1.0Lで十分。この値段なら間違いないと思います。' } },
      { stars: 3, date: '2026-09-11', variant: 'silver', helpful: 74, verified: true,
        en: { name: 'Tomoko S.', title: 'Plastic smell for the first week', body: 'There was a plastic smell from the lid for about a week, even after boiling and throwing away the water five times as the guide says. It is gone now. Also, 1.0 L is smaller than it sounds: a pot of tea and two cups of instant soup and it is empty.' },
        ja: { name: 'ともこ', title: '最初の1週間は樹脂のにおい', body: '説明書どおり5回沸かして捨てても、1週間ほどふたから樹脂のにおいがしました。今は気になりません。あと、1.0Lは思ったより少なく、急須1杯とスープ2杯で空になります。' } },
      { stars: 4, date: '2026-05-19', variant: 'silver', helpful: 33, verified: false,
        en: { name: 'coffee_ojisan', title: 'Fine for coffee, but no temperature control', body: 'I do pour-over coffee and need about 92 °C. This only boils, so I wait a minute after it clicks. The spout is wide, so pouring slowly is hard. If coffee is your main use, the Tetsuyu gooseneck is better but more than twice the price.' },
        ja: { name: 'コーヒーおじさん', title: 'コーヒーには温度設定がほしい', body: 'ハンドドリップで92℃くらいが理想ですが、沸騰しかできないのでカチッと切れてから1分待っています。注ぎ口が広く、細く注ぐのは難しいです。コーヒー中心ならテツユのグースネックが良いですが、値段は倍以上です。' } },
      { stars: 5, date: '2026-09-27', variant: 'black', helpful: 12, verified: true,
        en: { name: 'Aya K.', title: 'Bought with the coupon, great deal', body: 'Clipped the ¥300 coupon, so it was under ¥4,000 for the black one. Quick to boil, easy to clean, no complaints so far after three weeks.' },
        ja: { name: 'あや', title: 'クーポンでお得に購入', body: '300円クーポンを使ってブラックが4,000円以下でした。沸くのが速く、手入れも簡単。3週間使って不満はありません。' } },
      { stars: 2, date: '2026-04-03', variant: 'silver', helpful: 88, verified: true,
        en: { name: 'Shun', title: 'Limescale in two weeks with hard water', body: 'Our water at Tsukimi Onsen is very hard and the bottom turned white in two weeks. Citric acid cleans it, but the plate is not flat so the white collects around the edge. Not the kettle\'s fault exactly, but a concealed element would help.' },
        ja: { name: 'しゅん', title: '硬水だと2週間で水あか', body: '月見温泉の水はかなり硬く、2週間で底が白くなりました。クエン酸で落ちますが、底が平らでないので縁に白い汚れがたまります。ケトルのせいとは言い切れませんが、ヒーター隠蔽型なら良かったです。' } },
      { stars: 4, date: '2026-08-08', variant: 'silver', helpful: 19, verified: true,
        en: { name: 'Yuki', title: 'Arrived next day as promised', body: 'Ordered at 13:30 on a Sunday with Marketa Fast and it came the next evening. Works well. Minus one star because there is no water window.' },
        ja: { name: 'ゆき', title: '翌日きちんと届きました', body: '日曜の13時半にマルケタFastで注文し、翌日の夕方に届きました。問題なく使えています。水量窓がないので星ひとつ減らしました。' } },
    ],
    qa: [
      { date: '2026-08-12', votes: 41,
        en: { q: 'Does the water touch any plastic?', a: 'No. Inside it is stainless steel with a silicone seal on the lid. The inner lid is polypropylene but it only touches steam, not the water, unless you tip the kettle over.', by: 'Corvo Customer Support' },
        ja: { q: 'お湯がプラスチックに触れる部分はありますか？', a: 'いいえ。内側はステンレスで、ふたにシリコンパッキンがあります。内ぶたはポリプロピレンですが、本体を倒さない限り触れるのは蒸気だけです。', by: 'コルヴォ カスタマーサポート' } },
      { date: '2026-06-02', votes: 27,
        en: { q: 'Can I use it abroad on 220 V?', a: 'No. It is made for 100 V only. Using it on 220–240 V, even with a plug adapter, will damage it and is not covered by the warranty.', by: 'Corvo Customer Support' },
        ja: { q: '海外（220V）でも使えますか？', a: 'いいえ。100V専用です。変換プラグを使っても220〜240Vでは故障の原因となり、保証の対象外になります。', by: 'コルヴォ カスタマーサポート' } },
      { date: '2026-09-05', votes: 18,
        en: { q: 'Does it keep the water warm?', a: 'No, there is no keep-warm function. The water cools to about 70 °C in 20 minutes. The Hearth kettle has a 30-minute keep-warm mode.', by: 'Marketa customer (Hiroshi)' },
        ja: { q: '保温はできますか？', a: '保温機能はありません。20分ほどで約70℃まで下がります。ハースのケトルには30分保温モードがあります。', by: 'マルケタ購入者（ひろし）' } },
      { date: '2026-07-20', votes: 9,
        en: { q: 'Is the matte black version the same size?', a: 'Yes, only the finish is different. Both colours are 1.0 L.', by: 'Marketa customer (Aya)' },
        ja: { q: 'マットブラックも同じサイズですか？', a: 'はい、仕上げが違うだけで、どちらも1.0Lです。', by: 'マルケタ購入者（あや）' } },
    ],
    similar: ['hearth-kettle', 'vetrina-kettle', 'tetsuyu-gooseneck'],
    fbt: ['kagami-mug-pair', 'minori-marmalade-set'],
    alsoViewed: ['hearth-kettle', 'vetrina-kettle', 'tetsuyu-gooseneck', 'aoba-mini', 'komekko-ih', 'kagami-tea-set'],
  },
  {
    id: 'vetrina-kettle',
    cat: 'kitchen',
    cluster: 'kettles',
    brand: { en: 'Vetrina', ja: 'ヴェトリーナ' },
    seller: 'brightdeal',
    images: ['vetrina-kettle'],
    title: {
      en: 'Vetrina Glass Electric Kettle 1.7 L, Borosilicate Glass with Blue LED, 1,250 W, Auto Shut-Off and Boil-Dry Protection, Stainless Spout Filter, Optional Tea Infuser',
      ja: 'ヴェトリーナ 電気ケトル ガラス 1.7L 大容量 耐熱ガラス 青色LED 1250W 自動電源オフ 空焚き防止 茶こし付きモデルあり VT-G17',
    },
    short: { en: 'Vetrina Glass Kettle 1.7 L', ja: 'ヴェトリーナ ガラスケトル 1.7L' },
    rating: 3.8,
    ratings: 941,
    hist: [45, 22, 12, 7, 14],
    added: '2025-03-14',
    badges: ['sponsored'],
    coupon: null,
    variantLabel: { en: 'Style', ja: 'タイプ' },
    variants: [
      { id: 'standard', name: { en: '1.7 L', ja: '1.7L' }, price: 4480, list: 6980, stock: 34, ship: 'brightdeal' },
      { id: 'infuser', name: { en: '1.7 L with tea infuser', ja: '1.7L 茶こし付き' }, price: 4980, list: 6980, stock: 21, ship: 'brightdeal' },
    ],
    returns: {
      en: 'Sold and shipped by BrightDeal Trading, so the seller\'s policy applies: returns within 30 days, but change-of-mind returns only if unopened, and you pay ¥880 return shipping. If it is faulty, message the seller first and wait up to 2 business days for a prepaid label; if they do not reply or refuse a valid return, Marketa Purchase Protection covers you.',
      ja: 'ブライトディール商事が販売・発送する商品のため、販売者の返品条件が適用されます。返品はお届けから30日以内ですが、お客様都合の返品は未開封品のみで、返送料880円はお客様のご負担です。初期不良の場合はまず販売者にメッセージでご連絡のうえ、着払い伝票の案内を最大2営業日お待ちください。返信がない場合や正当な返品を断られた場合は、マルケタ購入者保護の対象になります。',
    },
    bullets: {
      en: [
        'BIG 1.7 L GLASS BODY: enough for about eight mugs, or breakfast tea and a 1.5 L jug of barley tea in one boil. Boils 1.7 L in about 6 min and 500 mL in about 2 min (tap water at 20 °C).',
        'SEE THE WATER: the borosilicate glass body has 0.5–1.7 L marks on the side, and a blue LED lights the water while it heats and goes out when the kettle switches off.',
        'BOIL ONLY: 1,250 W; switches off at the boil, when lifted from the base and if switched on empty. No temperature settings and no keep-warm.',
        'THE GLASS GETS HOT: it is a single layer, so the body is too hot to touch after boiling; hold it by the handle only. For a body that stays cool, see the Hearth Double-Wall Kettle.',
        'TEA INFUSER VERSION (+¥500): adds a 70 mm stainless mesh basket that hangs in the opening for loose-leaf tea. Boil first, then lower the basket in. The kettle itself is the same.',
        'SOLD AND SHIPPED BY BRIGHTDEAL TRADING from Kobe: free shipping, arrives in 4–8 days, not eligible for Marketa Fast. 6-month seller warranty.',
      ],
      ja: [
        '【1.7Lの大容量】マグカップ約8杯分。朝のお茶と麦茶ポット1.5L分を一度に沸かせます。1.7Lを約6分、500mLを約2分で沸騰（水温20℃の場合）。',
        '【お湯が見えるガラスボディ】耐熱性の高いホウケイ酸ガラス製で、側面に0.5〜1.7Lの目盛り付き。加熱中は青色LEDが水を照らし、電源が切れると消灯します。',
        '【沸騰のみのシンプル設計】1250W。沸騰時・本体を持ち上げたとき・空焚き時に自動で電源オフ。温度設定と保温機能はありません。',
        '【ガラスは熱くなります】一重構造のため、沸騰後は本体に触れず取っ手だけを持ってください。外側が熱くなりにくいケトルをお探しなら「ハース 二重構造ケトル」もご覧ください。',
        '【茶こし付きモデル（+500円）】直径70mmのステンレス製メッシュ茶こしが付属。口に掛けてリーフティーを蒸らせます。沸騰させてから茶こしを入れてください。ケトル本体は通常モデルと同じです。',
        '【ブライトディール商事が販売・発送】神戸の倉庫から送料無料、4〜8日でお届け。マルケタFastの対象外です。販売者保証6か月。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Vetrina'], ['Model', 'VT-G17'], ['Capacity', '1.7 L (minimum 0.5 L)'], ['Power', '1,250 W, 100 V, 50/60 Hz'],
        ['Boil time', '1.7 L about 6 min; 500 mL about 2 min'], ['Body material', 'Borosilicate glass, single layer; stainless steel base plate'],
        ['Lid and spout', 'Polypropylene lid with silicone seal; removable stainless filter in the spout'], ['Water window', 'Whole body is glass, marks 0.5–1.7 L'],
        ['Light', 'Blue LED while heating'], ['Safety', 'Auto shut-off, boil-dry protection, lift-off shut-off'], ['Temperature settings', 'None (boil only)'], ['Keep warm', 'No'],
        ['Cord length', '0.75 m'], ['Dimensions', '23 × 16 × 25 cm'], ['Weight', '1.15 kg (1.35 kg with base)'],
        ['Country of origin', 'China'], ['Warranty', '6 months (seller warranty from BrightDeal Trading)'], ['In the box', 'Kettle, power base, manual (Japanese and English); tea infuser with the infuser version'],
      ],
      ja: [
        ['ブランド', 'ヴェトリーナ'], ['型番', 'VT-G17'], ['容量', '1.7L（最小0.5L）'], ['消費電力', '1250W（100V 50/60Hz）'],
        ['沸騰時間', '1.7L 約6分／500mL 約2分'], ['本体素材', 'ホウケイ酸ガラス（一重構造）、底面ステンレス'],
        ['ふた・注ぎ口', 'ポリプロピレン製ふた、シリコンパッキン、注ぎ口に取り外せるステンレスフィルター'], ['水量窓', '本体全体がガラス（0.5〜1.7Lの目盛り）'],
        ['ライト', '加熱中に青色LEDが点灯'], ['安全機能', '自動電源オフ、空焚き防止、持ち上げ時オフ'], ['温度設定', 'なし（沸騰のみ）'], ['保温', 'なし'],
        ['コード長', '0.75m'], ['サイズ', '幅23×奥行16×高さ25cm'], ['重量', '約1.15kg（ベース込み約1.35kg）'],
        ['原産国', '中国'], ['保証', '販売者保証6か月（ブライトディール商事）'], ['付属品', '本体、電源プレート、取扱説明書（日本語・英語）、茶こし（茶こし付きモデルのみ）'],
      ],
    },
    compare: {
      en: ['1.7 L', '1,250 W', 'Borosilicate glass, single layer', 'None', 'No', '6 months (seller)'],
      ja: ['1.7L', '1250W', '耐熱ガラス（一重）', 'なし', 'なし', '6か月（販売者保証）'],
    },
    description: {
      en: [
        'The Vetrina is the largest kettle in this range: 1.7 L, enough for a family\'s morning tea and a jug of barley tea in one go. The body is borosilicate glass, the heat-resistant glass used for coffee servers and laboratory flasks, so you can see exactly how much water is inside and watch it come to the boil under a blue LED.',
        'It does one thing: it boils. There are no temperature settings and no keep-warm, and because it holds so much, a full kettle takes about 6 minutes, nearly twice as long as a 1.0 L kettle. Fill only what you need for faster boiling. Do not fill above the 1.7 L mark: boiling water can be pushed out past the lid seal, and when pouring a full kettle make sure the lid is pressed down until it clicks at the front and the back.',
        'The tea infuser version comes with a stainless mesh basket that hangs from the rim. Boil the water first, open the lid, lower the basket in and close the lid to steep. Never switch the kettle on with the basket or tea leaves inside: tannin stains the glass and clogs the spout filter. Glass also shows limescale as a white film, especially with hard water; boil 1.0 L of water with 2 tablespoons of citric acid, leave it for an hour and rinse.',
        'This item is sold and shipped by BrightDeal Trading from its warehouse in Kobe. Shipping is free and it arrives 4–8 days after ordering; it is not covered by Marketa Fast, so it cannot come next day. BrightDeal gives a 6-month warranty. Contact the seller from your Marketa order page (weekdays 10:00–17:00, by message only).',
      ],
      ja: [
        'ヴェトリーナは、このシリーズでいちばん大きい1.7Lのガラスケトルです。家族の朝のお茶と麦茶ポット1本分を一度に沸かせます。本体にはコーヒーサーバーや理化学用のフラスコにも使われる耐熱性の高いホウケイ酸ガラスを使用。水の量がひと目でわかり、青色LEDに照らされてお湯が沸いていく様子を楽しめます。',
        '機能は「沸かす」だけ。温度設定と保温機能はありません。容量が大きいぶん、満水では約6分と1.0Lクラスのケトルの倍近くかかります。早く沸かしたいときは必要な分だけ入れてください。1.7Lの目盛りより上まで入れると、沸騰時にふたのパッキンからお湯があふれることがあります。満水で注ぐときは、ふたが前後どちらもカチッと鳴るまで押し込んでください。',
        '茶こし付きモデルには、口の縁に掛けて使うステンレス製メッシュの茶こしが付属します。先にお湯を沸かし、ふたを開けて茶こしを入れ、ふたを閉めて蒸らしてください。茶こしや茶葉を入れたままスイッチを入れないでください。ガラスに茶渋が付き、注ぎ口のフィルターが目詰まりする原因になります。またガラスは水あかが白く曇って見えやすく、硬水の地域では特に目立ちます。水1.0Lにクエン酸大さじ2を入れて沸かし、1時間置いてからすすいでください。',
        '本商品はブライトディール商事が販売し、神戸の倉庫から発送します。送料無料で、ご注文から4〜8日でお届けします。マルケタFastの対象外のため、翌日配送はできません。販売者保証は6か月です。お問い合わせはマルケタの注文履歴から販売者へメッセージでどうぞ（平日10:00〜17:00、メッセージのみ対応）。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-14', variant: 'standard', helpful: 132, verified: true,
        en: { name: 'Natsuki', title: 'Gorgeous and holds a lot', body: 'We are a family of five and this is the first kettle that does breakfast tea and the barley tea jug in one go. Watching it boil under the blue light is oddly relaxing and the kids love it. It took six days to come from Kobe, which the listing said.' },
        ja: { name: 'なつき', title: '見た目がきれいで大容量', body: '5人家族で、朝のお茶と麦茶ポット1本分を一度に沸かせたのはこのケトルが初めてです。青いライトの中で沸いていくのを見ているとなぜか落ち着きます。子どもたちにも大人気。神戸からの発送なので届くまで6日かかりましたが、商品ページに書いてあったので想定内でした。' } },
      { stars: 1, date: '2026-08-22', variant: 'standard', helpful: 241, verified: true,
        en: { name: 'T. Kimura', title: 'LED died after three months, and the return was a chore', body: 'The blue light stopped working after about three months. It still boils, but now I can only tell it is on by the sound. BrightDeal only answers messages on weekdays, it took two business days to get a return label and another week for the replacement. The replacement\'s LED flickers. It was within the 6-month warranty, but it took a lot of messages.' },
        ja: { name: '木村', title: '3か月でLEDが故障、交換も手間', body: '3か月ほどで青いライトが点かなくなりました。お湯は沸きますが、電源が入っているかは音でしか分かりません。ブライトディール商事は平日しか返信がなく、返送用の伝票が届くまで2営業日、交換品が届くまでさらに1週間。しかも交換品のLEDはちらつきます。6か月保証の範囲内でしたが、何度もメッセージのやり取りが必要でした。' } },
      { stars: 2, date: '2026-09-03', variant: 'standard', helpful: 176, verified: true,
        en: { name: 'Hiro', title: 'Drips from the lid when pouring', body: 'If it is more than about two-thirds full, water runs out between the lid and the glass when I pour, onto my hand and the counter. The silicone seal does not sit flat. I now fill it to 1.2 L at most, which defeats the point of a 1.7 L kettle.' },
        ja: { name: 'ひろ', title: '注ぐとふたから水が垂れる', body: '3分の2以上入れて注ぐと、ふたとガラスのすき間からお湯が伝って手や台に垂れます。シリコンパッキンがきちんと収まっていない感じです。今は1.2Lまでしか入れていないので、1.7Lの意味がありません。' } },
      { stars: 5, date: '2026-09-25', variant: 'standard', helpful: 38, verified: true,
        en: { name: 'Kenji', title: 'No drips at all on mine', body: 'I read the reviews about dripping and was worried, but mine pours cleanly even when full. Press the lid down until it clicks at both the front and the back; if it only clicks at the front, it leaks. Big, cheap, works.' },
        ja: { name: 'けんじ', title: 'うちのは全く垂れません', body: '水漏れのレビューを読んで心配でしたが、満水でもきれいに注げます。ふたは前と後ろの両方でカチッと鳴るまで押し込むこと。前だけだと漏れます。大きくて安くて、ちゃんと使えます。' } },
      { stars: 2, date: '2026-07-30', variant: 'infuser', helpful: 119, verified: true,
        en: { name: 'Sayaka', title: 'The glass shows every bit of limescale', body: 'Our water in Tsukimi Onsen is hard, and within ten days the glass had a cloudy white ring and spots. You have to descale with citric acid every week to keep it looking like the photos. The infuser is nice for loose tea, but tea stains the glass as well.' },
        ja: { name: 'さやか', title: 'ガラスだと水あかが全部見える', body: '月見温泉の水は硬水で、10日ほどでガラスに白い輪と斑点ができました。写真のような見た目を保つには毎週クエン酸で洗う必要があります。茶こしはリーフティーに便利ですが、ガラスに茶渋も付きます。' } },
      { stars: 3, date: '2026-09-08', variant: 'standard', helpful: 64, verified: true,
        en: { name: 'Mari O.', title: 'Fine, but slow and heavy when full', body: 'A full kettle takes about six minutes. My old 1.0 L Corvo was much quicker for a single cup. Full, this one weighs almost 3 kg and is hard to lift with one hand. Good if you really need the volume.' },
        ja: { name: 'まり', title: '悪くないけど満水だと遅くて重い', body: '満水だと沸くまで6分くらいかかります。前に使っていたコルヴォの1.0Lのほうが1杯分ならずっと速かったです。満水だと3kg近くあり、片手で持ち上げるのはきつい。量が必要な人向けです。' } },
      { stars: 4, date: '2026-06-17', variant: 'infuser', helpful: 52, verified: true,
        en: { name: 'Lena', title: 'Infuser works well for herbal and barley tea', body: 'I boil 1.5 L, lower in the infuser with herbal tea and close the lid. The basket is big enough for a barley tea bag too. One star off because the basket handle gets hot and there is nowhere to hang it afterwards.' },
        ja: { name: 'レナ', title: '茶こしはハーブティーや麦茶に便利', body: '1.5L沸かしてから茶こしにハーブティーを入れ、ふたを閉めて蒸らしています。麦茶パックも入る大きさです。茶こしの持ち手が熱くなるのと、取り出した後に掛けておく場所がないので星4つ。' } },
      { stars: 1, date: '2026-09-19', variant: 'standard', helpful: 98, verified: true,
        en: { name: 'Goro', title: 'Could not return it after opening', body: 'I opened it, realised the glass gets far too hot to have around my toddler and wanted to return it. BrightDeal only accepts change-of-mind returns if the box is unopened, and Marketa\'s 30-day returns do not apply because the seller ships it. Read the returns box before you buy.' },
        ja: { name: 'ごろう', title: '開封後は返品できなかった', body: '開けてみたらガラスがかなり熱くなるので、小さい子がいるうちには怖いと思って返品しようとしました。ところがブライトディール商事はお客様都合の返品は未開封のみ。販売者からの発送なので、マルケタの30日返品も使えません。購入前に返品条件を必ず確認してください。' } },
      { stars: 5, date: '2026-10-01', variant: 'infuser', helpful: 7, verified: true,
        en: { name: 'Pon', title: 'Pretty with the Tokiya mugs', body: 'Bought the infuser version with the Tokiya mug pair from the same seller and they came in one box. Blue light and yellow and blue mugs look lovely together. Both cheap and cheerful.' },
        ja: { name: 'ぽん', title: 'トキヤのマグと合わせて', body: '同じ販売者のトキヤのマグペアと一緒に茶こし付きを購入したら、1つの箱で届きました。青いライトと黄色・青のマグの組み合わせがかわいいです。どちらも手頃で気に入っています。' } },
      { stars: 2, date: '2026-08-05', variant: 'standard', helpful: 71, verified: true,
        en: { name: 'Yoko N.', title: 'Switches off before boiling when full', body: 'Filled above about 1.5 L, it clicks off before the water is properly boiling, I think because the steam reaches the sensor early. I have to switch it on a second time. Below 1.5 L it is fine.' },
        ja: { name: 'ようこ', title: '満水だと沸騰前に切れる', body: '1.5Lくらいより多く入れると、しっかり沸騰する前にカチッと切れてしまいます。蒸気が早くセンサーに届くのだと思います。もう一度スイッチを入れ直す必要があります。1.5L以下なら問題ありません。' } },
      { stars: 4, date: '2026-07-11', variant: 'standard', helpful: 16, verified: true,
        en: { name: 'Aki', title: 'Chose it over the Hearth 1.5 L', body: 'I wanted a big kettle and the Hearth 1.5 L was out of stock at the time. The Vetrina is 0.2 L bigger and ¥1,000 cheaper, but it has no keep-warm or temperature presets and the glass gets hot. For plain boiling it is fine.' },
        ja: { name: 'あき', title: 'ハースの1.5Lと迷ってこちらに', body: '大きいケトルが欲しくて、当時ハースの1.5Lが在庫切れだったのでこちらに。ヴェトリーナのほうが0.2L大きく1,000円安いですが、保温や温度設定はなく、ガラスは熱くなります。沸かすだけなら十分です。' } },
      { stars: 4, date: '2026-05-02', variant: 'standard', helpful: 25, verified: false,
        en: { name: 'Satoshi', title: 'Bright enough to light the kitchen', body: 'At night the blue LED lights up the whole kitchen, which I like. Five months in, no problems with the light or the lid. Get the plain version unless you drink a lot of loose-leaf tea.' },
        ja: { name: 'さとし', title: '台所が明るくなるほどのLED', body: '夜は青いLEDで台所全体が明るくなり、気に入っています。5か月使ってライトもふたも問題なし。リーフティーをよく飲む人でなければ、通常モデルで十分だと思います。' } },
    ],
    qa: [
      { date: '2026-06-20', votes: 12,
        en: { q: 'How long does delivery to Harukawa take?', a: 'Mine came in two days, so I think it ships from the Marketa warehouse at Minori Port.', by: 'Marketa customer (Jun)' },
        ja: { q: '春川市まで何日くらいで届きますか？', a: '私は2日で届いたので、みのり港のマルケタ倉庫から発送されていると思います。', by: 'マルケタ購入者（じゅん）' } },
      { date: '2026-08-03', votes: 37,
        en: { q: 'Is this eligible for Marketa Fast next-day delivery?', a: 'No. We ship every order from our own warehouse in Kobe within 1–3 days, and delivery takes 4–8 days in total with free shipping. Marketa Fast benefits do not apply to this item.', by: 'BrightDeal Trading (seller)' },
        ja: { q: 'マルケタFastの翌日配送の対象ですか？', a: 'いいえ。すべてのご注文を当社の神戸倉庫から1〜3日で発送しており、お届けまで合計4〜8日です（送料無料）。マルケタFastの特典は本商品には適用されません。', by: 'ブライトディール商事（販売者）' } },
      { date: '2026-07-15', votes: 22,
        en: { q: 'Is the kettle in the infuser version different?', a: 'No, it is the same kettle (VT-G17). The only difference is the stainless mesh infuser, 70 mm across and holding about 300 mL. The infuser is not sold separately.', by: 'BrightDeal Trading (seller)' },
        ja: { q: '茶こし付きモデルはケトル本体も違いますか？', a: 'いいえ、本体は同じVT-G17です。違いはステンレス製メッシュの茶こし（直径70mm、容量約300mL）が付くことだけです。茶こし単品の販売はしておりません。', by: 'ブライトディール商事（販売者）' } },
      { date: '2026-09-09', votes: 18,
        en: { q: 'Can I set 80 °C for green tea or keep the water hot?', a: 'No, it only boils and switches off. I leave the lid open for 3–4 minutes to get to about 80 °C. The Hearth and the Tetsuyu kettles have temperature settings and keep-warm if you need them.', by: 'Marketa customer (Midori)' },
        ja: { q: '緑茶用に80℃に設定したり、保温したりできますか？', a: 'できません。沸騰したら切れるだけです。私はふたを開けて3〜4分置き、80℃くらいにしています。温度設定や保温が必要なら、ハースやテツユのケトルがおすすめです。', by: 'マルケタ購入者（みどり）' } },
      { date: '2026-09-24', votes: 9,
        en: { q: 'The blue LED stopped working. Is that covered?', a: 'Yes, within 6 months of delivery. Please message us from your order page with a short video. We reply within 2 business days with a prepaid label and send a replacement once the kettle reaches our warehouse.', by: 'BrightDeal Trading (seller)' },
        ja: { q: '青色LEDが点かなくなりました。保証の対象ですか？', a: 'はい、お届けから6か月以内であれば対象です。注文履歴から短い動画を添えてメッセージをお送りください。2営業日以内に着払い伝票をご案内し、ケトルが当社倉庫に到着しだい交換品を発送いたします。', by: 'ブライトディール商事（販売者）' } },
    ],
    similar: ['hearth-kettle', 'corvo-kettle', 'tetsuyu-gooseneck'],
    fbt: ['tokiya-mug-pair', 'kagami-tea-set'],
    alsoViewed: ['hearth-kettle', 'corvo-kettle', 'tetsuyu-gooseneck', 'tokiya-mug-pair', 'kagami-tea-set', 'aoba-mini'],
  },
  {
    id: 'tetsuyu-gooseneck',
    cat: 'kitchen',
    cluster: 'kettles',
    brand: { en: 'Tetsuyu', ja: 'テツユ' },
    seller: 'marketa',
    images: ['tetsuyu-gooseneck'],
    title: {
      en: 'Tetsuyu Electric Gooseneck Kettle 0.8 L for Pour-Over Coffee and Tea, 40–100 °C in 1 °C Steps, 60-Minute Keep Warm, Brew Timer, 1,000 W, Matte Stainless Steel',
      ja: 'テツユ 電気ケトル グースネック 0.8L 温度調節 40〜100℃ 1℃単位 60分保温 タイマー付き ハンドドリップ コーヒー 1000W マット仕上げ TY-G08',
    },
    short: { en: 'Tetsuyu Gooseneck Kettle 0.8 L', ja: 'テツユ グースネックケトル 0.8L' },
    rating: 4.6,
    ratings: 1102,
    hist: [76, 15, 4, 2, 3],
    added: '2024-06-01',
    badges: ['choice'],
    coupon: { amount: 500, member: true, en: 'Fast members: save ¥500 with coupon', ja: 'Fast会員限定 500円OFFクーポン' },
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'black', name: { en: 'Matte Black', ja: 'マットブラック' }, price: 8900, list: 10800, stock: 27, ship: 'fast' },
      { id: 'white', name: { en: 'Matte White', ja: 'マットホワイト' }, price: 8900, list: 10800, stock: 12, ship: 'fast2' },
    ],
    returns: {
      en: 'Returnable within 30 days of delivery: unused in its packaging for a full refund, or opened but not faulty, in like-new condition with all parts, minus a 15% restocking fee. If it is faulty or damaged on arrival, return it free within 30 days; after that the 2-year Tetsuyu warranty applies.',
      ja: 'お届けから30日以内なら返品できます。未使用・未開封品は全額返金、開封済みで故障のない商品は付属品がすべてそろった新品同様の状態に限り、返品手数料15％を差し引いて返金します。初期不良や配送中の破損は30日以内なら無料で返品でき、それ以降はテツユのメーカー保証（2年）の対象です。',
    },
    bullets: {
      en: [
        'SET THE EXACT TEMPERATURE: 40–100 °C in 1 °C steps on the base, for pour-over coffee (90–96 °C), green tea (70–80 °C), gyokuro (50–60 °C) or baby formula (70 °C). The display shows the current and the target temperature.',
        'GOOSENECK SPOUT FOR A SLOW, STEADY POUR: the 8 mm spout pours a thin stream for hand-drip coffee. It holds 0.8 L, but fill to 0.6 L for pouring: above that, water can dribble from the base of the spout as you start to pour.',
        'HOLDS THE TEMPERATURE FOR 60 MINUTES: press HOLD and it keeps your setting for up to an hour (at 100 °C it holds about 97 °C). Lift it off the base and put it back within 2 minutes and it carries on.',
        'BUILT-IN BREW TIMER: the display counts up from 0:00 when you press the timer button, so you can time the bloom and the pour without your phone.',
        'SMALLER, GENTLER HEATER: 1,000 W boils 0.6 L in about 3 min 10 s. The body is single-wall stainless steel with a matte coating and gets hot; the handle stays cool.',
        '2-YEAR WARRANTY from Tetsuyu. Matte Black and Matte White are identical apart from colour; black is stocked in Harukawa, white ships from a warehouse outside Minori Prefecture.',
      ],
      ja: [
        '【1℃単位で温度設定】ベースのボタンで40〜100℃を1℃刻みで設定。ハンドドリップ（90〜96℃）、緑茶（70〜80℃）、玉露（50〜60℃）、ミルク作り（70℃）に。ディスプレイに現在の温度と設定温度を表示します。',
        '【細く安定して注げるグースネック】注ぎ口の内径は8mm。ハンドドリップに必要な細いお湯で注げます。容量は0.8Lですが、注ぐときは0.6Lまでがおすすめ。それ以上入れると、注ぎ始めに注ぎ口の付け根からお湯が垂れることがあります。',
        '【60分保温】HOLDボタンを押すと設定温度を最大60分キープ（100℃設定時は約97℃で保温）。ベースから持ち上げても2分以内に戻せば保温を続けます。',
        '【ドリップ用タイマー内蔵】タイマーボタンを押すと0:00からカウントアップ。スマホなしで蒸らしや注湯の時間を計れます。',
        '【1000W・シングル構造】0.6Lを約3分10秒で沸騰。本体はマットコーティングを施したステンレスの一重構造で、加熱中は熱くなります。取っ手は熱くなりません。',
        '【メーカー保証2年】マットブラックとマットホワイトは色以外同じです。ブラックは春川の倉庫に在庫があり、ホワイトはみのり県外の倉庫から発送します。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Tetsuyu'], ['Model', 'TY-G08'], ['Capacity', '0.8 L maximum; 0.6 L recommended for pouring; minimum 0.3 L'], ['Power', '1,000 W, 100 V, 50/60 Hz'],
        ['Boil time', '0.6 L about 3 min 10 s; 0.8 L about 4 min; 0.3 L about 1 min 40 s'], ['Temperature settings', '40–100 °C in 1 °C steps (accuracy ±2 °C)'], ['Keep warm', 'Up to 60 min at the set temperature'],
        ['Spout', 'Gooseneck, 8 mm opening'], ['Body material', 'Stainless steel (SUS304), single wall; matte powder coating outside, bare steel inside'], ['Handle', 'Heat-resistant resin'],
        ['Display', 'Orange LED digits on the base, 9 mm high; current and target temperature, brew timer'],
        ['Safety', 'Auto shut-off, boil-dry protection, lift-off pause'], ['Cord length', '1.0 m'], ['Dimensions', '29 × 16 × 17.5 cm (including spout)'], ['Weight', '0.95 kg (1.4 kg with base)'],
        ['Country of origin', 'Taiwan'], ['Warranty', '2 years (manufacturer)'], ['In the box', 'Kettle, power base, quick guide, descaling guide'],
      ],
      ja: [
        ['ブランド', 'テツユ'], ['型番', 'TY-G08'], ['容量', '最大0.8L（注ぐときは0.6Lまで推奨、最小0.3L）'], ['消費電力', '1000W（100V 50/60Hz）'],
        ['沸騰時間', '0.6L 約3分10秒／0.8L 約4分／0.3L 約1分40秒'], ['温度設定', '40〜100℃（1℃単位、精度±2℃）'], ['保温', '設定温度で最大60分'],
        ['注ぎ口', 'グースネック（内径8mm）'], ['本体素材', 'ステンレス（SUS304）一重構造、外側マット粉体塗装、内側は無塗装'], ['取っ手', '耐熱樹脂'],
        ['表示', 'ベースにオレンジ色のLED数字（高さ9mm）、現在温度・設定温度・ドリップタイマー'],
        ['安全機能', '自動電源オフ、空焚き防止、持ち上げ時一時停止'], ['コード長', '1.0m'], ['サイズ', '幅29×奥行16×高さ17.5cm（注ぎ口含む）'], ['重量', '約0.95kg（ベース込み約1.4kg）'],
        ['原産国', '台湾'], ['保証', 'メーカー保証2年'], ['付属品', '本体、電源ベース、クイックガイド、お手入れガイド'],
      ],
    },
    compare: {
      en: ['0.8 L (0.6 L for pouring)', '1,000 W', 'Stainless, single wall, matte coated', '40–100 °C in 1 °C steps', '60 min', '2 years'],
      ja: ['0.8L（注ぐときは0.6L）', '1000W', 'ステンレス（シングル・マット塗装）', '40〜100℃（1℃単位）', '60分', '2年'],
    },
    description: {
      en: [
        'The Tetsuyu is made for pour-over coffee and Japanese tea, where both the water temperature and the speed of the pour change the taste. Set any temperature from 40 to 100 °C on the base, and the long gooseneck spout lets you pour a stream as thin as a pencil or as full as you like, without splashing the grounds.',
        'It is not a family kettle. It holds 0.8 L, but the comfortable pouring amount is 0.6 L, enough for two or three mugs of drip coffee. The 1,000 W heater is gentler than the 1,200–1,250 W of the other kettles here, so 0.6 L takes just over 3 minutes. If you mostly need a lot of hot water quickly, for cooking, cup noodles or a family pot of tea, a 1.2–1.7 L kettle will suit you better.',
        'To use: fill, place on the base, press the power button, set the temperature with + and – (hold to change 5 °C at a time) and press START. It beeps three times when it reaches the temperature. Press HOLD to keep it there for up to 60 minutes. To silence the beeps, hold HOLD and – together for 3 seconds. The base remembers your last temperature. The buttons are flat touch keys without raised marks.',
        'The outside is single-wall steel with a matte powder coating. It gets hot while heating, and the coating can mark if you scrub it: wipe it with a soft damp cloth, never an abrasive sponge. Matte White shows coffee splashes more readily; Matte Black shows white limescale drips. Descale the inside monthly: 1 teaspoon of citric acid in 0.5 L of water, heat to 100 °C, leave for an hour and rinse.',
        'Tetsuyu covers the kettle and base for two years from purchase, including the display. Wear to the outer coating is not covered. Keep your Marketa order confirmation as proof of purchase.',
      ],
      ja: [
        'テツユは、お湯の温度と注ぐ速さで味が変わるハンドドリップコーヒーや日本茶のためのケトルです。ベースで40〜100℃の好きな温度に設定でき、長いグースネックの注ぎ口で、鉛筆ほどの細さから太めまで、粉を跳ね上げずに注げます。',
        '家族向けのケトルではありません。容量は0.8Lですが、注ぎやすいのは0.6Lまで。ドリップコーヒーならマグカップ2〜3杯分です。ヒーターは1000Wと、ほかのケトル（1200〜1250W）より控えめなので、0.6Lで3分ちょっとかかります。料理やカップ麺、家族分のお茶など、たくさんのお湯をすぐに使いたい方には1.2〜1.7Lのケトルが向いています。',
        '使い方：水を入れてベースに置き、電源ボタンを押して「＋」「−」で温度を設定し（長押しで5℃ずつ変わります）、STARTを押します。設定温度になると3回ピーッと鳴ります。HOLDを押すと最大60分その温度を保ちます。HOLDと「−」を同時に3秒長押しすると操作音を消せます。最後に使った温度はベースが記憶します。ボタンは凹凸のない平らなタッチキーです。',
        '外側はマット粉体塗装をしたステンレスの一重構造です。加熱中は熱くなり、こすると塗装に跡が付くことがあるので、柔らかい布で水拭きしてください。研磨剤入りのスポンジは使えません。マットホワイトはコーヒーの跳ねが、マットブラックは水あかの白い跡が目立ちやすい傾向があります。内側は月に一度、水0.5Lにクエン酸小さじ1を入れて100℃に設定し、1時間置いてからすすいでください。',
        'メーカー保証は購入日から2年間（本体・ベース・表示部を含む）。外側の塗装の摩耗は保証の対象外です。マルケタの注文確認メールが購入証明になります。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-18', variant: 'black', helpful: 188, verified: true,
        en: { name: 'Takumi', title: 'Changed my morning coffee', body: 'I used to boil water in a Corvo and wait a minute for it to cool. Now I set 92 °C, bloom for 30 seconds with the built-in timer and pour slowly. The coffee is noticeably less bitter. Pour control is excellent.' },
        ja: { name: 'たくみ', title: '朝のコーヒーが変わった', body: '以前はコルヴォで沸かして1分待ってから淹れていました。今は92℃に設定し、内蔵タイマーで30秒蒸らしてからゆっくり注いでいます。苦みがはっきり減りました。注ぎやすさは抜群です。' } },
      { stars: 5, date: '2026-08-27', variant: 'white', helpful: 92, verified: true,
        en: { name: 'Midori', title: 'Perfect for gyokuro', body: 'I brew gyokuro at 55 °C in my Kagami Kiln kyusu. Getting the temperature right used to mean pouring between cups to cool it. Now I set 55 °C and press HOLD. The white matches my kitchen. It took three days because white ships from outside the prefecture; black would have come the next day.' },
        ja: { name: 'みどり', title: '玉露にぴったり', body: '鏡窯の急須で玉露を55℃で淹れています。以前は湯冷ましで何度も移し替えていましたが、今は55℃に設定してHOLDを押すだけ。ホワイトが台所に合っています。ホワイトは県外の倉庫からなので3日かかりました。ブラックなら翌日だったそうです。' } },
      { stars: 2, date: '2026-07-22', variant: 'black', helpful: 156, verified: true,
        en: { name: 'Kazuya', title: 'Coating chipped at the spout', body: 'After eight months the matte black coating has chipped where the spout joins the body and around the bottom of the handle, and the steel shows through. Tetsuyu says cosmetic wear is not covered by the 2-year warranty. At ¥8,900 I expected better.' },
        ja: { name: 'かずや', title: '注ぎ口の塗装がはげた', body: '8か月で、注ぎ口の付け根と取っ手の下のあたりのマットブラック塗装がはげ、ステンレスが見えています。テツユに問い合わせたところ、外観の摩耗は2年保証の対象外とのこと。8,900円ならもう少し丈夫であってほしかったです。' } },
      { stars: 1, date: '2026-09-06', variant: 'black', helpful: 141, verified: true,
        en: { name: 'Noriko H.', title: 'Display too small and dim for me', body: 'My eyesight is weak and the orange digits on the base are small and impossible to read in my bright kitchen. The + and – keys are flat with no bumps, so I cannot tell them apart by touch. The beeps help, but I could not set the temperature without my magnifier. I returned it and paid the 15% restocking fee because it had been opened.' },
        ja: { name: '畑中', title: '表示が小さく暗くて読めない', body: '視力が弱く、ベースのオレンジ色の数字が小さくて明るい台所では読めませんでした。「＋」「−」のキーは平らで凹凸がなく、触っても区別できません。音は助かりますが、ルーペなしでは温度設定ができませんでした。開封済みだったので、返品手数料15％を払って返品しました。' } },
      { stars: 5, date: '2026-09-29', variant: 'black', helpful: 22, verified: true,
        en: { name: 'Jun', title: 'Display is clear enough', body: 'I can read the temperature from the other side of the kitchen, and the beep when it is ready is loud. Easy to set once you know that holding the button jumps 5 °C.' },
        ja: { name: 'じゅん', title: '表示は十分見やすい', body: '台所の反対側からでも温度が読めますし、沸いたときの音も大きめです。ボタン長押しで5℃ずつ変わると分かれば設定も簡単です。' } },
      { stars: 2, date: '2026-06-30', variant: 'white', helpful: 87, verified: true,
        en: { name: 'Erika', title: 'Dribbles when filled to 0.8 L', body: 'It says 0.8 L, but past about 0.6 L water runs out from under the spout when you tilt it. The listing now says 0.6 L is recommended, but that is only two mugs. A bit small for two coffee drinkers.' },
        ja: { name: 'えりか', title: '0.8Lまで入れると垂れる', body: '0.8Lとありますが、0.6Lを超えると傾けたときに注ぎ口の下からお湯が垂れます。今は商品ページに「0.6Lまで推奨」とありますが、それだとマグ2杯分。コーヒー好き2人には少し小さいです。' } },
      { stars: 3, date: '2026-08-14', variant: 'black', helpful: 58, verified: true,
        en: { name: 'Masa', title: 'Great pour, slow heater', body: 'Love the pour and the temperature control. But 1,000 W is slow: 0.6 L takes over three minutes and a full kettle about four. On a cold morning I miss my old kettle\'s speed. Three stars for that.' },
        ja: { name: 'まさ', title: '注ぎやすいけど沸くのが遅い', body: '注ぎやすさと温度調節は最高です。ただ1000Wなので遅く、0.6Lで3分以上、満水だと約4分かかります。寒い朝は前のケトルの速さが恋しくなります。その分で星3つ。' } },
      { stars: 4, date: '2026-09-24', variant: 'black', helpful: 31, verified: true,
        en: { name: 'Haruka', title: 'Hold mode is the real feature', body: 'I set 70 °C for formula and press HOLD, and it stays at 70 °C for the night feed. It switches off after an hour, so I set it again for the second feed. I wish the hold lasted longer.' },
        ja: { name: 'はるか', title: '保温機能がいちばん便利', body: 'ミルク用に70℃に設定してHOLDを押すと、夜中の授乳まで70℃のまま。1時間で切れるので、2回目の授乳前にもう一度設定しています。保温がもっと長ければ満点でした。' } },
      { stars: 1, date: '2026-05-11', variant: 'white', helpful: 74, verified: true,
        en: { name: 'Kenta', title: 'Base died after 13 months', body: 'The display stopped turning on after 13 months. It was covered by the 2-year warranty, but I had to pay ¥900 to send the base to Tetsuyu and was without a kettle for 16 days.' },
        ja: { name: 'けんた', title: '13か月でベースが故障', body: '13か月で表示が点かなくなりました。2年保証の対象でしたが、ベースをテツユに送る送料900円は自己負担で、16日間ケトルなしの生活でした。' } },
      { stars: 4, date: '2026-07-03', variant: 'black', helpful: 19, verified: true,
        en: { name: 'Ryo', title: 'We kept this and the Hearth', body: 'We tried the Hearth as well: it only has 60/70/80/90/100 °C presets and a wide spout. For coffee the Tetsuyu is in a different league, but my wife prefers the Hearth for family tea because it holds 1.2 L and stays cool outside. We kept both.' },
        ja: { name: 'りょう', title: 'ハースと両方使っています', body: 'ハースも試しました。あちらは60・70・80・90・100℃の5段階だけで、注ぎ口も太め。コーヒーならテツユが段違いですが、妻は家族のお茶用に1.2L入って外側が熱くならないハースのほうが好きで、結局両方使っています。' } },
      { stars: 5, date: '2026-10-03', variant: 'black', helpful: 4, verified: true,
        en: { name: 'Ai', title: 'Member coupon and next-day delivery', body: 'Got ¥500 off with the Fast member coupon during the Lantern Festival Sale, ordered on Friday morning and it came on Saturday. Looks great next to my Kagami Kiln mugs.' },
        ja: { name: 'あい', title: '会員クーポンで翌日着', body: '灯籠まつりセール中にFast会員クーポンで500円引き。金曜の朝に注文して土曜に届きました。鏡窯のマグと並べるととても素敵です。' } },
      { stars: 2, date: '2026-08-31', variant: 'white', helpful: 46, verified: true,
        en: { name: 'Yumi', title: 'White coating stains', body: 'Coffee splashes left brown marks on the matte white that a cloth will not remove, and the manual says no abrasive sponges. After two months it already looks old.' },
        ja: { name: 'ゆみ', title: 'ホワイトは汚れが落ちない', body: 'コーヒーの跳ねが茶色いしみになり、布で拭いても落ちません。説明書には研磨スポンジ不可とあります。2か月でもう古びて見えます。' } },
    ],
    qa: [
      { date: '2026-04-22', votes: 33,
        en: { q: 'Can I turn off the beeps?', a: 'Yes. Hold HOLD and – together for 3 seconds to switch the button and ready beeps off, and again to switch them on. The warning beep if the kettle is switched on empty cannot be turned off.', by: 'Tetsuyu Customer Support' },
        ja: { q: '操作音は消せますか？', a: 'はい。HOLDと「−」を同時に3秒長押しすると、ボタン音とお知らせ音が消えます。もう一度長押しすると元に戻ります。空焚き時の警告音は消せません。', by: 'テツユ カスタマーサポート' } },
      { date: '2026-05-30', votes: 14,
        en: { q: 'Can I fill it right up to 0.8 L?', a: 'Yes, I fill it to the top line every time and it is fine.', by: 'Marketa customer (Shin)' },
        ja: { q: '0.8Lいっぱいまで入れても大丈夫ですか？', a: 'はい、毎回上の線まで入れていますが問題ありません。', by: 'マルケタ購入者（しん）' } },
      { date: '2026-07-08', votes: 29,
        en: { q: 'Why does the listing say 0.6 L is recommended?', a: 'The kettle holds 0.8 L, but above 0.6 L the water is higher than the base of the spout, so it can dribble when you start to pour. If you are only heating water to fill a teapot quickly, 0.8 L is fine. For slow pour-over, fill to 0.6 L.', by: 'Tetsuyu Customer Support' },
        ja: { q: '「0.6Lまで推奨」なのはなぜですか？', a: '容量は0.8Lですが、0.6Lを超えると水面が注ぎ口の付け根より高くなり、注ぎ始めに垂れることがあります。急須にお湯を移すだけなら0.8Lまで入れても問題ありません。ハンドドリップでゆっくり注ぐ場合は0.6Lまでにしてください。', by: 'テツユ カスタマーサポート' } },
      { date: '2026-08-19', votes: 11,
        en: { q: 'Does keep warm work at 100 °C?', a: 'Yes, but it holds about 97 °C so the water does not keep boiling away. Press START again to bring it back to a full boil.', by: 'Tetsuyu Customer Support' },
        ja: { q: '100℃でも保温できますか？', a: 'はい。ただし沸騰し続けないよう約97℃で保温します。もう一度STARTを押すと沸騰させられます。', by: 'テツユ カスタマーサポート' } },
      { date: '2026-09-15', votes: 8,
        en: { q: 'Is the inside coated as well?', a: 'No. Only the outside has the matte coating; the inside is bare SUS304 stainless steel. The lid knob is resin but it does not touch the water.', by: 'Marketa customer (Takumi)' },
        ja: { q: '内側も塗装されていますか？', a: 'いいえ。マット塗装は外側だけで、内側は無塗装のステンレス（SUS304）です。ふたのつまみは樹脂ですが、お湯には触れません。', by: 'マルケタ購入者（たくみ）' } },
    ],
    similar: ['hearth-kettle', 'corvo-kettle', 'vetrina-kettle'],
    fbt: ['kagami-mug-pair', 'kagami-tea-set'],
    alsoViewed: ['hearth-kettle', 'corvo-kettle', 'kagami-tea-set', 'kagami-mug-pair', 'vetrina-kettle', 'shiroshita-senbei'],
  },
  {
    id: 'hearth-kettle',
    cat: 'kitchen',
    cluster: 'kettles',
    brand: { en: 'Hearth', ja: 'ハース' },
    seller: 'marketa',
    images: ['hearth-kettle', 'hearth-kettle-2'],
    title: {
      en: 'Hearth Double-Wall Electric Kettle with 5 Temperature Presets (60/70/80/90/100 °C), Cool-Touch Body, 30-Minute Keep Warm, Water Window, Tip-Over Spill Protection, 1,200 W, Cream, 1.2 L or 1.5 L',
      ja: 'ハース 電気ケトル 二重構造 温度設定5段階 60/70/80/90/100℃ 30分保温 本体が熱くなりにくい 水量窓付き 転倒湯もれ防止 1200W クリーム 1.2L／1.5L HT-DW',
    },
    short: { en: 'Hearth Double-Wall Kettle', ja: 'ハース 二重構造ケトル' },
    rating: 4.5,
    ratings: 1587,
    hist: [70, 18, 5, 3, 4],
    added: '2023-09-15',
    badges: ['deal'],
    coupon: null,
    variantLabel: { en: 'Capacity', ja: '容量' },
    variants: [
      { id: '1-2l', name: { en: '1.2 L', ja: '1.2L' }, price: 4980, list: 5980, stock: 18, ship: 'fast' },
      { id: '1-5l', name: { en: '1.5 L', ja: '1.5L' }, price: 5480, list: 6480, stock: 3, ship: 'fast2' },
    ],
    returns: {
      en: 'Returnable within 30 days of delivery: unused in its packaging for a full refund, or opened but not faulty, in like-new condition with all parts, minus a 15% restocking fee. If it is faulty or damaged on arrival, return it free within 30 days; after that the 1-year Hearth warranty applies.',
      ja: 'お届けから30日以内なら返品できます。未使用・未開封品は全額返金、開封済みで故障のない商品は付属品がすべてそろった新品同様の状態に限り、返品手数料15％を差し引いて返金します。初期不良や配送中の破損は30日以内なら無料で返品でき、それ以降はハースのメーカー保証（1年）の対象です。',
    },
    bullets: {
      en: [
        'COOL-TOUCH DOUBLE WALL: stainless steel inside, a layer of air and a cream resin shell outside, so the sides stay warm rather than hot after boiling (about 45 °C). Safer around children than a single-wall kettle. The lid and spout still get hot.',
        'FIVE TEMPERATURE PRESETS: 60, 70, 80, 90 and 100 °C, one button each on top of the handle, for gyokuro, green tea, baby formula, black tea and coffee, or cup noodles.',
        'KEEPS WARM FOR 30 MINUTES: press KEEP WARM after choosing a temperature and it holds it for 30 minutes, then switches off.',
        'TIP-OVER SPILL PROTECTION: with the lid locked, a valve in the spout limits the spill to about 50 mL if the kettle is knocked over. Also auto shut-off, boil-dry protection and lift-off shut-off.',
        'WATER WINDOW: a window on the side shows the water level, so you can fill it without opening the lid.',
        'TWO SIZES, CREAM ONLY: 1.2 L (about 6 mugs) is stocked in Harukawa; 1.5 L (about 8 mugs) ships from a warehouse outside Minori Prefecture. 1-year warranty.',
      ],
      ja: [
        '【本体が熱くなりにくい二重構造】内側はステンレス、外側はクリーム色の樹脂で、間に空気の層があります。沸騰後も側面は約45℃と、触れても熱くなりにくい設計で、小さなお子さまのいるご家庭にも安心です。ふたと注ぎ口は熱くなります。',
        '【温度設定5段階】60・70・80・90・100℃を取っ手の上のボタンひとつで選択。玉露、緑茶、ミルク作り、紅茶・コーヒー、カップ麺に。',
        '【30分保温】温度を選んでから「保温」ボタンを押すと、その温度を30分キープしたあと自動でオフになります。',
        '【転倒湯もれ防止】ふたをロックした状態なら、万一倒れても注ぎ口の弁でこぼれるお湯を約50mLに抑えます。自動電源オフ、空焚き防止、持ち上げ時オフ機能付き。',
        '【水量窓付き】側面の窓で水の量を確認でき、ふたを開けずに給水できます。',
        '【2サイズ・カラーはクリームのみ】1.2L（マグカップ約6杯）は春川の倉庫に在庫あり。1.5L（約8杯）はみのり県外の倉庫から発送します。メーカー保証1年。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Hearth'], ['Model', 'HT-DW12 (1.2 L), HT-DW15 (1.5 L)'], ['Capacity', '1.2 L or 1.5 L (minimum 0.3 L)'], ['Power', '1,200 W, 100 V, 50/60 Hz'],
        ['Boil time', '1.2 L about 4 min 30 s; 1.5 L about 5 min 40 s; 140 mL about 1 min 15 s'],
        ['Body material', 'Double wall: stainless steel (SUS304) inside, polypropylene shell outside'],
        ['Parts touching water', 'Stainless steel, silicone lid seal, heat-resistant resin water window'],
        ['Temperature settings', '60, 70, 80, 90, 100 °C'], ['Keep warm', '30 min at the chosen temperature'], ['Water window', 'Yes, light-grey marks from 0.3 L to maximum'],
        ['Safety', 'Tip-over spill protection (lid locked), auto shut-off, boil-dry protection, lift-off shut-off'],
        ['Cord length', '1.0 m'], ['Dimensions', '1.2 L: 22 × 15.5 × 21 cm; 1.5 L: 23 × 16 × 23.5 cm'], ['Weight', '1.2 L: 1.1 kg; 1.5 L: 1.25 kg (kettle only)'],
        ['Colour', 'Cream (both sizes)'], ['Country of origin', 'China'], ['Warranty', '1 year (manufacturer)'], ['In the box', 'Kettle, power base, manual'],
      ],
      ja: [
        ['ブランド', 'ハース'], ['型番', 'HT-DW12（1.2L）、HT-DW15（1.5L）'], ['容量', '1.2Lまたは1.5L（最小0.3L）'], ['消費電力', '1200W（100V 50/60Hz）'],
        ['沸騰時間', '1.2L 約4分30秒／1.5L 約5分40秒／140mL 約1分15秒'],
        ['本体素材', '二重構造：内側ステンレス（SUS304）、外側ポリプロピレン'],
        ['水に触れる部分', 'ステンレス、シリコンパッキン、耐熱樹脂製の水量窓'],
        ['温度設定', '60・70・80・90・100℃'], ['保温', '選んだ温度で30分'], ['水量窓', 'あり（薄いグレーの目盛り、0.3L〜満水）'],
        ['安全機能', '転倒湯もれ防止（ふたロック時）、自動電源オフ、空焚き防止、持ち上げ時オフ'],
        ['コード長', '1.0m'], ['サイズ', '1.2L：幅22×奥行15.5×高さ21cm／1.5L：幅23×奥行16×高さ23.5cm'], ['重量', '1.2L：約1.1kg／1.5L：約1.25kg（本体のみ）'],
        ['カラー', 'クリーム（両サイズ共通）'], ['原産国', '中国'], ['保証', 'メーカー保証1年'], ['付属品', '本体、電源プレート、取扱説明書'],
      ],
    },
    compare: {
      en: ['1.2 L or 1.5 L', '1,200 W', 'Double wall, cool-touch', '5 presets (60–100 °C)', '30 min', '1 year'],
      ja: ['1.2L／1.5L', '1200W', '二重構造（熱くなりにくい）', '5段階（60〜100℃）', '30分', '1年'],
    },
    description: {
      en: [
        'The Hearth is the kettle to choose if you want something safe to leave on a family kitchen counter. Its double wall keeps the sides at around 45 °C after boiling, warm but not painful, and if a child pulls it over with the lid locked, a valve in the spout lets out only about 50 mL instead of the whole kettle. The lid and the spout are not insulated and do get hot.',
        'Five buttons on top of the handle choose 60, 70, 80, 90 or 100 °C, and a small light shows which one is on. It beeps once when you press a button and three times when the water is ready; the beeps cannot be switched off. Press KEEP WARM afterwards to hold that temperature for 30 minutes, after which it switches off. The presets cover most tea and coffee, but they are 10 °C apart and accurate to about ±3 °C: if you want 92 °C for pour-over coffee or exactly 55 °C for gyokuro, the Tetsuyu Gooseneck sets 1 °C steps.',
        'The two sizes are the same kettle at different heights. The 1.2 L makes about six mugs and suits one to three people; the 1.5 L makes about eight and suits a bigger family or a jug of barley tea, but it is 23.5 cm tall and may hit a low cupboard when the lid opens. The 1.2 L is stocked at Marketa\'s Harukawa warehouse and can arrive next day; the 1.5 L ships from a warehouse outside Minori Prefecture and takes about three days.',
        'The water touches stainless steel, the silicone lid seal and the inside of the resin water window. The window marks are printed in light grey on the cream body, which some people find hard to read; with the lid open the level is easier to see from above. Descale monthly with citric acid (1 tablespoon in 1.0 L, boil, leave for an hour and rinse). Hearth covers the kettle and base for one year.',
      ],
      ja: [
        'ハースは、家族の台所に置いても安心なケトルをお探しの方におすすめです。二重構造で沸騰後も側面は約45℃。温かいものの、やけどするほどではありません。ふたをロックしていれば、お子さまが倒してしまっても注ぎ口の弁でこぼれるお湯は約50mLに抑えられます。なお、ふたと注ぎ口は断熱されていないため熱くなります。',
        '取っ手の上に並んだ5つのボタンで60・70・80・90・100℃を選ぶと、選んだ温度の小さなランプが点灯します。ボタンを押すと1回、お湯が沸くと3回音が鳴ります（音は消せません）。続けて「保温」を押すと、その温度を30分保ってから自動でオフになります。お茶やコーヒーにはほぼ対応できますが、設定は10℃刻みで誤差は±3℃程度です。ハンドドリップ用に92℃、玉露用にぴったり55℃などを求める方には、1℃単位で設定できる「テツユ グースネックケトル」がおすすめです。',
        '2サイズは高さが違うだけの同じケトルです。1.2Lはマグカップ約6杯分で1〜3人向け。1.5Lは約8杯分で、大家族や麦茶づくりに向いていますが、高さが23.5cmあり、低い吊り戸棚の下ではふたを開けたときに当たることがあります。1.2Lはマルケタ春川倉庫に在庫があり翌日お届けが可能、1.5Lはみのり県外の倉庫から発送するため3日ほどかかります。',
        '水に触れるのはステンレス、ふたのシリコンパッキン、樹脂製水量窓の内側です。水量窓の目盛りはクリーム色の本体に薄いグレーで印刷されており、見えにくいと感じる方もいます。ふたを開けて上からのぞくと水位が確認しやすくなります。月に一度、水1.0Lにクエン酸大さじ1を入れて沸かし、1時間置いてからすすいでください。メーカー保証は1年間（本体・電源プレート）です。',
      ],
    },
    tables: [
      { title: { en: '1.2 L or 1.5 L?', ja: '1.2Lと1.5Lの違い' },
        en: [
          ['', '1.2 L', '1.5 L'],
          ['Mugs (200 mL)', 'About 6', 'About 8'],
          ['Boil time, full', 'About 4 min 30 s', 'About 5 min 40 s'],
          ['Size (W × D × H)', '22 × 15.5 × 21 cm', '23 × 16 × 23.5 cm'],
          ['Weight (kettle only)', '1.1 kg', '1.25 kg'],
          ['Price', '¥4,980', '¥5,480'],
          ['Ships from', 'Marketa Harukawa (HRK1), next day possible', 'Marketa warehouse outside Minori, about 3 days'],
        ],
        ja: [
          ['', '1.2L', '1.5L'],
          ['マグカップ（200mL）', '約6杯', '約8杯'],
          ['満水時の沸騰時間', '約4分30秒', '約5分40秒'],
          ['サイズ（幅×奥行×高さ）', '22×15.5×21cm', '23×16×23.5cm'],
          ['重量（本体のみ）', '約1.1kg', '約1.25kg'],
          ['価格', '4,980円', '5,480円'],
          ['発送元', 'マルケタ春川倉庫（HRK1）、翌日お届け可', 'みのり県外のマルケタ倉庫、約3日'],
        ] },
    ],
    reviews: [
      { stars: 5, date: '2026-09-12', variant: '1-2l', helpful: 203, verified: true,
        en: { name: 'Megumi', title: 'Finally a kettle I don\'t worry about', body: 'Two toddlers who grab everything. After boiling the sides are just warm. My son pulled it off the counter once with the lid locked and only a splash came out of the spout. Worth the extra ¥1,000 over the Corvo we had before.' },
        ja: { name: 'めぐみ', title: 'やっと安心して置けるケトル', body: '何でもつかむ2歳児が2人います。沸騰後も側面は温かい程度。一度息子が台から落としましたが、ふたをロックしていたので注ぎ口から少しこぼれただけでした。前に使っていたコルヴォより1,000円高いですが、その価値はあります。' } },
      { stars: 2, date: '2026-08-19', variant: '1-2l', helpful: 134, verified: true,
        en: { name: 'Taro I.', title: 'Presets are not accurate', body: 'I checked with a thermometer: the 80 °C setting gives 76–77 °C and 60 gives 63. Fine for most people, but if you care about tea, buy the Tetsuyu. Keep warm is only 30 minutes, which is too short for my mornings.' },
        ja: { name: '伊藤', title: '設定温度が正確ではない', body: '温度計で測ったら、80℃設定で76〜77℃、60℃設定で63℃でした。普通の使い方なら問題ないでしょうが、お茶にこだわるならテツユを買うべきです。保温も30分だけで、朝の支度には短すぎます。' } },
      { stars: 4, date: '2026-09-01', variant: '1-5l', helpful: 77, verified: true,
        en: { name: 'Chika', title: 'Glad I got the 1.5 L', body: 'Family of four, we make barley tea every day, and 1.5 L means one boil instead of two. It is taller than I expected and the lid touches the cupboard when it opens, so I slide it forward first. It took three days to arrive.' },
        ja: { name: 'ちか', title: '1.5Lにして正解', body: '4人家族で毎日麦茶を作るので、1.5Lなら1回で済みます。思ったより背が高く、ふたを開けると吊り戸棚に当たるので、手前に出してから開けています。届くまで3日かかりました。' } },
      { stars: 5, date: '2026-07-26', variant: '1-2l', helpful: 59, verified: true,
        en: { name: 'Shinji', title: '1.2 L is plenty for two', body: 'For the two of us 1.2 L is plenty, and it came the next morning. If you are wondering about the 1.5 L: unless you make jugs of tea, the smaller one is lighter and boils faster.' },
        ja: { name: 'しんじ', title: '2人なら1.2Lで十分', body: '2人暮らしなら1.2Lで十分で、翌朝に届きました。1.5Lと迷っている方へ：麦茶などをまとめて作らないなら、小さいほうが軽くて早く沸きます。' } },
      { stars: 1, date: '2026-06-15', variant: '1-2l', helpful: 162, verified: true,
        en: { name: 'Akemi', title: 'Water window useless for me', body: 'The marks on the window are pale grey on cream. I have cataracts and cannot see them at all, even with a torch. I overfilled it twice and boiling water spat out of the spout. Returned it.' },
        ja: { name: 'あけみ', title: '水量窓が見えません', body: '水量窓の目盛りはクリーム色に薄いグレー。白内障があるので、ライトを当ててもまったく見えません。2回入れすぎて、注ぎ口から熱湯が噴き出しました。返品しました。' } },
      { stars: 2, date: '2026-09-22', variant: '1-2l', helpful: 95, verified: true,
        en: { name: 'Daichi', title: 'Lid button sticks; "cool-touch" is only the sides', body: 'After four months the lid button sticks, and twice the lid sprang up while I was pouring and steam hit my hand. The sides do stay cool, but the lid and spout get very hot, so "cool-touch" is only half true.' },
        ja: { name: 'だいち', title: 'ふたのボタンが引っかかる／熱くないのは側面だけ', body: '4か月でふたのボタンが引っかかるようになり、注いでいる最中にふたが2回開いて蒸気が手にかかりました。側面は確かに熱くなりませんが、ふたと注ぎ口はかなり熱いので、「熱くなりにくい」は半分だけ本当です。' } },
      { stars: 3, date: '2026-08-04', variant: '1-2l', helpful: 41, verified: true,
        en: { name: 'Sora', title: 'Nice, but heavier than it looks', body: 'It is 1.1 kg empty, so with 1.2 L of water it is over 2 kg. My mother finds it heavy to pour. Otherwise good: quiet, cool sides, and keep warm is useful.' },
        ja: { name: 'そら', title: '良いけど見た目より重い', body: '本体だけで1.1kg、1.2L入れると2kg以上になります。母は注ぐのが重いと言っています。それ以外は静かで側面も熱くならず、保温も便利で満足です。' } },
      { stars: 5, date: '2026-09-30', variant: '1-2l', helpful: 18, verified: true,
        en: { name: 'Kana', title: 'Night feeds made easy', body: 'The 70 °C button plus keep warm for formula. I press it, do the feed, and it is still at temperature for the second bottle. Glad I did not get the Corvo, which only boils.' },
        ja: { name: 'かな', title: '夜中のミルク作りが楽に', body: '70℃ボタン＋保温でミルク作り。押して授乳して、2本目を作るときもまだ70℃。沸騰しかできないコルヴォにしなくて良かったです。' } },
      { stars: 4, date: '2026-05-28', variant: '1-2l', helpful: 27, verified: true,
        en: { name: 'Yuta', title: 'Good for green tea', body: 'I use 80 °C for sencha in my Kagami Kiln tea set. The only complaint is that the beeps cannot be turned off.' },
        ja: { name: 'ゆうた', title: '緑茶にちょうどいい', body: '鏡窯の急須セットで煎茶を淹れるのに80℃を使っています。不満は操作音を消せないことだけ。' } },
      { stars: 2, date: '2026-04-09', variant: '1-5l', helpful: 66, verified: true,
        en: { name: 'Hitomi', title: 'Plastic smell for three weeks', body: 'For the first three weeks there was a hot-plastic smell from the outer shell every time it boiled, and the kitchen smelled of it. It has gone now, but I almost sent it back.' },
        ja: { name: 'ひとみ', title: '3週間ほど樹脂のにおい', body: '最初の3週間は、沸かすたびに外側の樹脂から焼けたようなにおいがして、台所中ににおいました。今は消えましたが、返品する寸前でした。' } },
      { stars: 5, date: '2026-10-03', variant: '1-2l', helpful: 3, verified: true,
        en: { name: 'Nao', title: 'Lantern Festival Sale price', body: 'Ordered on Friday for ¥4,980 and it came on Saturday. The cream matches my Aoba Mini rice cooker in beige.' },
        ja: { name: 'なお', title: '灯籠まつりセールで購入', body: '金曜に4,980円で注文して土曜に届きました。ベージュのアオバ ミニ炊飯器とクリーム色がよく合います。' } },
      { stars: 4, date: '2026-06-22', variant: '1-5l', helpful: 21, verified: false,
        en: { name: 'Ito', title: 'The 1.5 L is often sold out', body: 'Waited two weeks for the 1.5 L to come back in stock. Worth it for our family, but if you need a kettle this week, the 1.2 L is usually available.' },
        ja: { name: 'いと', title: '1.5Lはよく品切れします', body: '1.5Lの再入荷を2週間待ちました。うちの家族には待つ価値がありましたが、今週中にケトルが必要なら1.2Lのほうがたいてい在庫があります。' } },
    ],
    qa: [
      { date: '2026-09-27', votes: 26,
        en: { q: 'Will the 1.5 L arrive next day like the 1.2 L?', a: 'No. When I ordered, the 1.2 L showed next-day delivery, but the 1.5 L came from a warehouse outside Minori and took three days even with Marketa Fast.', by: 'Marketa customer (Chika)' },
        ja: { q: '1.5Lも1.2Lのように翌日届きますか？', a: 'いいえ。私が注文したときは1.2Lは翌日配送でしたが、1.5Lはみのり県外の倉庫からの発送で、マルケタFast会員でも3日かかりました。', by: 'マルケタ購入者（ちか）' } },
      { date: '2026-03-14', votes: 7,
        en: { q: 'Is the inside plastic?', a: 'I think the whole kettle is plastic. It feels very light.', by: 'Marketa customer (Ken)' },
        ja: { q: '内側はプラスチックですか？', a: '全部プラスチックだと思います。とても軽いので。', by: 'マルケタ購入者（けん）' } },
      { date: '2026-05-06', votes: 31,
        en: { q: 'Which parts touch the water?', a: 'The inner wall and the bottom are SUS304 stainless steel. The water also touches the silicone lid seal and the inside of the water window, which is a heat-resistant, BPA-free resin. The cream outer shell is polypropylene and never touches the water.', by: 'Hearth Customer Support' },
        ja: { q: 'お湯が触れる部分の素材を教えてください。', a: '内壁と底面はステンレス（SUS304）です。そのほか、ふたのシリコンパッキンと水量窓の内側（BPAフリーの耐熱樹脂）にお湯が触れます。クリーム色の外側はポリプロピレンで、お湯には触れません。', by: 'ハース カスタマーサポート' } },
      { date: '2026-07-18', votes: 15,
        en: { q: 'Can I turn off the beeps?', a: 'No, the beeps cannot be switched off on this model.', by: 'Hearth Customer Support' },
        ja: { q: '操作音を消すことはできますか？', a: '申し訳ございませんが、本製品は操作音を消すことはできません。', by: 'ハース カスタマーサポート' } },
      { date: '2026-08-30', votes: 12,
        en: { q: 'Does keep warm work at 100 °C?', a: 'Keep warm works with every preset. At 100 °C it holds about 95 °C so the water does not boil away. After 30 minutes it switches off.', by: 'Hearth Customer Support' },
        ja: { q: '100℃でも保温できますか？', a: 'すべての設定温度で保温できます。100℃の場合は、お湯が減らないよう約95℃で保温します。30分たつと自動でオフになります。', by: 'ハース カスタマーサポート' } },
    ],
    similar: ['corvo-kettle', 'tetsuyu-gooseneck', 'vetrina-kettle'],
    fbt: ['kagami-mug-pair', 'minori-marmalade-set'],
    alsoViewed: ['corvo-kettle', 'tetsuyu-gooseneck', 'vetrina-kettle', 'komekko-ih', 'kagami-tea-set', 'minori-marmalade-set'],
  },
];
