// Power banks (Electronics). Same shape as kettles.mjs.
export const cluster = {
  id: 'power',
  compareRows: {
    en: ['Capacity', 'Watt-hours / flights', 'Max output', 'Ports', 'Weight', 'Warranty'],
    ja: ['容量', '定格容量（Wh）／機内持ち込み', '最大出力', 'ポート', '重量', '保証'],
  },
};

export default [
  {
    id: 'ampora-slim-10k',
    cat: 'electronics',
    cluster: 'power',
    brand: { en: 'Ampora', ja: 'アンポラ' },
    seller: 'marketa',
    images: ['ampora-slim-10k'],
    title: {
      en: 'Ampora Slim 10K Power Bank 10,000 mAh, 20 W USB-C PD Fast Charging, 180 g, 1.5 cm Thin, USB-C + USB-A, Low-Current Mode for Earbuds, Airline Carry-On OK (37 Wh)',
      ja: 'アンポラ モバイルバッテリー 10000mAh 20W USB PD 急速充電 軽量180g 薄型1.5cm USB-C/USB-A 2ポート 低電流モード搭載 機内持ち込み可（37Wh） PSE適合 AP-S10',
    },
    short: { en: 'Ampora Slim 10K Power Bank', ja: 'アンポラ Slim 10K モバイルバッテリー' },
    rating: 4.4,
    ratings: 6204,
    hist: [67, 18, 6, 4, 5],
    added: '2024-04-15',
    badges: ['bestseller', 'choice'],
    coupon: null,
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'silver', name: { en: 'Silver', ja: 'シルバー' }, price: 2980, list: 3990, stock: 60, ship: 'fast' },
      { id: 'pink', name: { en: 'Pink', ja: 'ピンク' }, price: 2980, list: 3990, stock: 34, ship: 'fast' },
    ],
    returns: {
      en: 'Returnable within 30 days of delivery: unused for a full refund, or opened and working in like-new condition with the cable, minus a 15% restocking fee (¥447) and ¥550 return shipping (free for paid Fast members). Defective units are returned free within 30 days; after that the 18-month Ampora warranty applies.',
      ja: 'お届けから30日以内なら返品できます。未使用品は全額返金、開封済みで正常に動作するものは付属ケーブルを含む新品同様の状態に限り、返品手数料15%（447円）と返送料550円（有料のFast会員は無料）を差し引いて返金します。初期不良は30日以内なら送料無料、その後はアンポラの18か月保証の対象です。',
    },
    bullets: {
      en: [
        'POCKET SIZE: 10.2 × 6.3 × 1.5 cm and 180 g, about the size and weight of a smartphone.',
        'CHARGES A PHONE ABOUT TWICE: 10,000 mAh at 3.7 V (37 Wh) delivers about 6,000 mAh to your phone after conversion losses: roughly two charges of a typical smartphone, or 1.3 of a large phone with a 5,000 mAh battery.',
        '20 W USB-C POWER DELIVERY: charges recent iPhones and Android phones from 0 to about 50% in 30 minutes. A USB-A port (12 W) for older cables. When both ports are used, they share 15 W.',
        'NOT FOR LAPTOPS: 20 W is too little to charge a laptop. For 13–14-inch laptops, see the Ampora Go 20K (65 W).',
        'LOW-CURRENT MODE: press the button twice to charge earbuds, smartwatches and fitness bands safely for up to 2 hours.',
        'FLIGHT-FRIENDLY: 37 Wh is well under 100 Wh, so it can go in your carry-on without airline approval. Power banks are never allowed in checked baggage. PSE certified. 18-month warranty.',
      ],
      ja: [
        '【スマホ並みのサイズ】幅10.2×高さ6.3×厚さ1.5cm、約180g。スマートフォンとほぼ同じ大きさと重さです。',
        '【スマホ約2回分】10000mAh（3.7V・37Wh）。変換ロスを除いて実際にスマホへ送れるのは約6000mAhで、一般的なスマホなら約2回、5000mAhクラスの大容量スマホなら約1.3回分です。',
        '【20W USB PD急速充電】最近のiPhoneやAndroidスマホを約30分で0%から約50%まで充電。古いケーブル用にUSB-Aポート（12W）も搭載。2ポート同時使用時は合計15Wを分け合います。',
        '【ノートPCには非対応】20WではノートPCは充電できません。13〜14インチのノートPCには65W出力の「アンポラ Go 20K」がおすすめです。',
        '【低電流モード】ボタンを2回押すと、ワイヤレスイヤホン・スマートウォッチ・活動量計などの小型機器を最大2時間、適切な電流で充電します。',
        '【機内持ち込みOK】37Whは100Wh未満のため、航空会社への申請なしで機内に持ち込めます。モバイルバッテリーはお預け荷物には入れられません。PSE適合。18か月保証。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Ampora'], ['Model', 'AP-S10'], ['Capacity', '10,000 mAh / 3.7 V (37 Wh)'], ['Usable output', 'About 6,000 mAh at 5 V'],
        ['Ports', 'USB-C (input/output), USB-A (output)'], ['Output', 'USB-C up to 20 W (5 V/3 A, 9 V/2.22 A, 12 V/1.67 A); USB-A up to 12 W; both ports 15 W total'],
        ['Input', 'USB-C up to 18 W'], ['Recharge time', 'About 3.5 h with an 18–20 W charger; about 6 h with a 5 V/2 A charger'],
        ['Pass-through charging', 'Yes (slower)'], ['Battery indicator', '4 LEDs'],
        ['Safety', 'PSE certified; overcharge, over-current, short-circuit and temperature protection'],
        ['Dimensions', '10.2 × 6.3 × 1.5 cm'], ['Weight', '180 g'], ['Country of origin', 'China'], ['Warranty', '18 months (manufacturer)'],
        ['In the box', 'Power bank, USB-C to USB-C cable (30 cm), quick guide'],
      ],
      ja: [
        ['ブランド', 'アンポラ'], ['型番', 'AP-S10'], ['容量', '10000mAh／3.7V（37Wh）'], ['実出力容量', '5V換算 約6000mAh'],
        ['ポート', 'USB-C（入出力）、USB-A（出力）'], ['出力', 'USB-C 最大20W（5V/3A、9V/2.22A、12V/1.67A）、USB-A 最大12W、2ポート同時使用時は合計15W'],
        ['入力', 'USB-C 最大18W'], ['本体充電時間', '18〜20W充電器で約3.5時間、5V/2A充電器で約6時間'],
        ['パススルー充電', '対応（充電速度は低下）'], ['残量表示', 'LED4つ'],
        ['安全機能', 'PSE適合、過充電・過電流・短絡・温度保護'],
        ['サイズ', '幅10.2×高さ6.3×厚さ1.5cm'], ['重量', '約180g'], ['原産国', '中国'], ['保証', 'メーカー保証18か月'],
        ['付属品', '本体、USB-C to USB-Cケーブル（30cm）、クイックガイド'],
      ],
    },
    compare: {
      en: ['10,000 mAh', '37 Wh: carry-on OK, no approval', '20 W', '1 × USB-C, 1 × USB-A', '180 g', '18 months'],
      ja: ['10000mAh', '37Wh：機内持ち込み可（申請不要）', '20W', 'USB-C×1、USB-A×1', '180g', '18か月'],
    },
    description: {
      en: [
        'The Ampora Slim 10K is a light everyday power bank for your phone. It is as thin as a phone in a case and weighs 180 g, so it slips into a jacket pocket or a small bag for a long day at university or an evening at the Lantern Festival.',
        'About capacity: as with every power bank, the 10,000 mAh figure is for the internal cells at 3.7 V. Your phone charges at 5 V or more, and some energy is lost as heat, so about 6,000 mAh reaches the phone. That is roughly two full charges of a phone with a 3,000–4,000 mAh battery, or 1.3 charges of a phone with a 5,000 mAh battery.',
        'Compatibility: the USB-C port supports USB Power Delivery up to 20 W, which fast-charges recent iPhones and Android phones. The included cable is USB-C at both ends; for an older iPhone, use your own cable in the USB-A or USB-C port. It cannot charge laptops: a laptop that needs 30 W or more will not start charging.',
        'To recharge it, use a USB-C charger of 18 W or more: about 3.5 hours. An old 5 V phone charger takes about 6 hours. It can charge your phone while it is being charged itself (pass-through), more slowly. Ampora covers it for 18 months from purchase; if the battery ever swells, stop using it and contact Ampora support for a free replacement.',
      ],
      ja: [
        'アンポラ Slim 10Kは、スマホ用の軽い毎日使いのモバイルバッテリーです。ケース付きのスマホと同じくらいの薄さで約180g。上着のポケットや小さなバッグに入れて、大学での長い一日や灯籠まつりの夜にも安心です。',
        '容量について：すべてのモバイルバッテリーと同様に、10000mAhは内部電池（3.7V）の容量です。スマホへの充電は5V以上で行われ、一部は熱として失われるため、スマホに届くのは約6000mAhです。3000〜4000mAhのスマホなら約2回、5000mAhのスマホなら約1.3回の満充電に相当します。',
        '対応機器：USB-Cポートは最大20WのUSB Power Deliveryに対応し、最近のiPhoneやAndroidスマホを急速充電できます。付属ケーブルは両端USB-Cです。古いiPhoneにはお手持ちのケーブルをUSB-AまたはUSB-Cポートにつないでお使いください。ノートPCは充電できません（30W以上を必要とするノートPCは充電が始まりません）。',
        '本体の充電には18W以上のUSB-C充電器で約3.5時間。古い5Vのスマホ用充電器では約6時間かかります。本体を充電しながらスマホを充電するパススルー充電にも対応しています（速度は低下します）。メーカー保証は購入日から18か月。万一バッテリーが膨らんだ場合は使用を中止し、アンポラのサポートにご連絡ください。無償で交換します。',
      ],
    },
    tables: [
      {
        title: { en: 'How many charges?', ja: '充電できる回数の目安' },
        en: [['Device', 'Battery', 'Approx. charges', 'Time, 0–100%'], ['Small smartphone', '3,000 mAh', 'About 2', 'About 1 h 30 min'], ['Large smartphone', '5,000 mAh', 'About 1.3', 'About 1 h 50 min'], ['Earbuds charging case', '500 mAh', 'About 10', 'About 1 h 20 min (low-current mode)'], ['10-inch tablet', '8,000 mAh', 'About 0.7', '—'], ['Laptop', '—', 'Not supported', '—']],
        ja: [['機器', 'バッテリー容量', '充電回数の目安', '0→100%の時間'], ['小型スマホ', '3000mAh', '約2回', '約1時間30分'], ['大容量スマホ', '5000mAh', '約1.3回', '約1時間50分'], ['イヤホンの充電ケース', '500mAh', '約10回', '約1時間20分（低電流モード）'], ['10インチタブレット', '8000mAh', '約0.7回', '—'], ['ノートPC', '—', '非対応', '—']],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-25', variant: 'silver', helpful: 241, verified: true,
        en: { name: 'Sakura', title: 'Lives in my pocket', body: 'Charges my phone about twice, weighs about the same as the phone, and the 20 W port takes me from 15% to 60% while I eat lunch. Took it to the Lantern Festival last year and filmed all evening without worrying.' },
        ja: { name: 'さくら', title: 'いつもポケットに', body: 'スマホ約2回分、重さはスマホと同じくらい。20Wポートならお昼を食べている間に15%から60%まで充電できます。去年の灯籠まつりでも一晩中動画を撮って安心でした。' } },
      { stars: 2, date: '2026-08-19', variant: 'pink', helpful: 178, verified: true,
        en: { name: 'Kohei', title: 'Real capacity is much lower than 10,000 mAh', body: 'My phone has a 5,000 mAh battery and I get one full charge plus about 30%. A USB meter shows 6,100 mAh coming out. The page explains why, but the box does not, so "10,000 mAh" feels like exaggeration to me.' },
        ja: { name: 'こうへい', title: '実容量は10000mAhよりかなり少ない', body: 'スマホのバッテリーは5000mAhですが、満充電1回と30%ほどしか充電できません。USBチェッカーで測ったら出力は約6100mAhでした。商品ページには理由が書いてありますが、箱には書いていないので「10000mAh」は誇大表示に感じます。' } },
      { stars: 4, date: '2026-09-03', variant: 'silver', helpful: 133, verified: true,
        en: { name: 'Tetsu', title: 'That is normal for every power bank', body: 'To the reviews about capacity: 10,000 mAh at 3.7 V is 37 Wh. At 5 V and about 85% efficiency, around 6,200 mAh is what you should expect, and I measured 6,250 mAh. That is actually good. Minus one star for the very short cable.' },
        ja: { name: 'てつ', title: 'どのモバイルバッテリーもこれが普通', body: '容量についてのレビューへ。3.7Vで10000mAh＝37Wh。5V換算で変換効率85%程度なら約6200mAhが妥当で、実測6250mAhでした。むしろ優秀です。付属ケーブルが短すぎるので星ひとつ減。' } },
      { stars: 1, date: '2026-07-06', variant: 'silver', helpful: 119, verified: true,
        en: { name: 'Nori', title: 'Stopped charging after eight months', body: 'One day it showed four lights but would not output anything. Ampora replaced it under the 18-month warranty after I sent a video, which took ten days. The replacement works. Still annoying when you rely on it for work.' },
        ja: { name: 'のり', title: '8か月で充電できなくなった', body: 'ある日、ランプは4つ点くのにまったく出力されなくなりました。動画を送って18か月保証で交換してもらえましたが、10日かかりました。交換品は正常です。仕事で頼りにしていたので困りました。' } },
      { stars: 3, date: '2026-08-26', variant: 'pink', helpful: 87, verified: true,
        en: { name: 'Ami', title: 'Takes forever to recharge with an old charger', body: 'With my old phone charger it took almost 7 hours to fill. With a 20 W USB-C charger it takes about 3.5 hours, as stated. Get a proper charger too, or you will start the day half empty.' },
        ja: { name: 'あみ', title: '古い充電器だと充電に時間がかかる', body: '昔のスマホ用充電器だと満充電まで7時間近くかかりました。20WのUSB-C充電器なら記載どおり3.5時間ほど。ちゃんとした充電器も用意しないと、朝になっても半分しか充電されていません。' } },
      { stars: 5, date: '2026-06-12', variant: 'silver', helpful: 72, verified: true,
        en: { name: 'Lucas', title: 'No questions at airport security', body: 'Carried it on flights to Sapporo and Okinawa. 37 Wh is printed on the back and security never asked anything. Just keep it in your carry-on, never in your suitcase.' },
        ja: { name: 'ルーカス', title: '保安検査で何も言われず', body: '札幌と沖縄へのフライトで機内に持ち込みました。背面に37Whと印字されていて、保安検査で何か聞かれたことはありません。スーツケースには入れず、必ず手荷物に。' } },
      { stars: 2, date: '2026-09-14', variant: 'silver', helpful: 81, verified: true,
        en: { name: 'Hikari', title: 'Slow and warm when charging two things', body: 'With my phone and my Nami Buds 2 case plugged in together, both charge slowly (15 W shared) and the power bank gets noticeably warm. Once the phone even stopped charging for a moment when I plugged in the earbuds. One device at a time is fine.' },
        ja: { name: 'ひかり', title: '2台同時だと遅くて熱くなる', body: 'スマホとナミ Buds 2のケースを同時につなぐと、合計15Wを分け合うのでどちらも遅く、本体もかなり温かくなります。イヤホンを挿した瞬間、スマホの充電が一瞬止まったことも。1台ずつなら問題ありません。' } },
      { stars: 4, date: '2026-07-24', variant: 'pink', helpful: 46, verified: true,
        en: { name: 'Mayu', title: 'Low-current mode works for my earbuds', body: 'With other power banks my earbuds stopped charging after a minute. Pressing the button twice keeps it going until they are full. Handy.' },
        ja: { name: 'まゆ', title: '低電流モードでイヤホンも充電できる', body: '他のモバイルバッテリーだとイヤホンが1分ほどで充電停止していましたが、ボタン2回押しで満充電まで充電されます。便利。' } },
      { stars: 2, date: '2026-05-03', variant: 'silver', helpful: 94, verified: true,
        en: { name: 'Shin', title: 'Does not charge my laptop', body: 'My laptop charges over USB-C, so I hoped for a top-up in emergencies. It shows the charging icon for a second and then stops. I should have bought the Ampora Go 20K, which does 65 W. My mistake, but "USB-C PD" in the title made me think it would work.' },
        ja: { name: 'しん', title: 'ノートPCは充電できない', body: 'ノートPCがUSB-C充電なので、いざというときに使えると思っていました。充電マークが一瞬出てすぐ止まります。65W出力のアンポラ Go 20Kにすべきでした。確認不足ですが、タイトルの「USB PD」で使えると思ってしまいました。' } },
      { stars: 5, date: '2026-09-29', variant: 'pink', helpful: 18, verified: true,
        en: { name: 'Mio', title: 'Pretty pink, arrived next day', body: 'The pink is a soft pastel, not bright. Ordered before 14:00 and it came the next day. Two phone charges is exactly what I need for weekend trips.' },
        ja: { name: 'みお', title: 'ピンクがかわいい、翌日到着', body: 'ピンクは派手すぎないパステル系。14時前に注文して翌日に届きました。週末の旅行ならスマホ2回分でちょうどいいです。' } },
      { stars: 4, date: '2026-04-20', variant: 'silver', helpful: 38, verified: false,
        en: { name: 'Ken T.', title: 'The cable is too short', body: 'Works well, but with the 30 cm cable the power bank dangles off the phone. I use a 1 m cable instead.' },
        ja: { name: 'けんいち', title: 'ケーブルが短い', body: '性能は満足ですが、30cmのケーブルだとスマホからバッテリーがぶら下がる感じ。1mのケーブルに替えて使っています。' } },
    ],
    qa: [
      { date: '2026-09-01', votes: 58,
        en: { q: 'Can I take this on a plane?', a: 'Yes. It is 37 Wh, under the 100 Wh limit, so you can take it in your carry-on without asking the airline. Power banks must never go in checked baggage.', by: 'Ampora Support' },
        ja: { q: '飛行機に持ち込めますか？', a: 'はい。37Whで100Wh未満のため、航空会社への申請なしで機内に持ち込めます。モバイルバッテリーはお預け荷物に入れることはできません。', by: 'アンポラ サポート' } },
      { date: '2026-07-18', votes: 34,
        en: { q: 'How many times can it charge my phone?', a: 'About twice for a phone with a 3,000–4,000 mAh battery, and about 1.3 times for a 5,000 mAh one. About 6,000 mAh reaches the phone after conversion losses.', by: 'Ampora Support' },
        ja: { q: 'スマホを何回充電できますか？', a: '3000〜4000mAhのスマホで約2回、5000mAhのスマホで約1.3回です。変換ロスを除くと、スマホに届くのは約6000mAhです。', by: 'アンポラ サポート' } },
      { date: '2026-06-05', votes: 29,
        en: { q: 'Will it charge my 13-inch laptop over USB-C?', a: 'No. It outputs up to 20 W, and most laptops need at least 30 W. The Ampora Go 20K (65 W) charges most 13–14-inch laptops.', by: 'Ampora Support' },
        ja: { q: '13インチのノートPCをUSB-Cで充電できますか？', a: 'いいえ。最大出力は20Wで、ほとんどのノートPCは30W以上が必要です。13〜14インチのノートPCには「アンポラ Go 20K」（65W）をご検討ください。', by: 'アンポラ サポート' } },
      { date: '2026-08-09', votes: 17,
        en: { q: 'Is there a cable for my older iPhone in the box?', a: 'Only a USB-C to USB-C cable is included. Plug your phone\'s own cable into the USB-A or USB-C port.', by: 'Marketa customer (Mio)' },
        ja: { q: '古いiPhone用のケーブルは付いていますか？', a: '付属しているのはUSB-C to USB-Cケーブルだけです。スマホに付いてきたケーブルをUSB-AかUSB-Cポートにつないで使っています。', by: 'マルケタ購入者（みお）' } },
      { date: '2026-03-11', votes: 12,
        en: { q: 'Can it charge itself and my phone at the same time?', a: 'Yes, pass-through works. The phone gets priority and the power bank fills more slowly.', by: 'Marketa customer (Tetsu)' },
        ja: { q: '本体を充電しながらスマホも充電できますか？', a: 'はい、パススルー充電できます。スマホが優先され、本体の充電はゆっくりになります。', by: 'マルケタ購入者（てつ）' } },
    ],
    similar: ['ampora-go-20k', 'kestrel-27k', 'titancell-40k'],
    fbt: ['nami-buds', 'kaze-openear'],
    alsoViewed: ['ampora-go-20k', 'kestrel-27k', 'titancell-40k', 'nami-buds', 'voltx-pods', 'kaze-openear'],
  },
  {
    id: 'ampora-go-20k',
    cat: 'electronics',
    cluster: 'power',
    brand: { en: 'Ampora', ja: 'アンポラ' },
    seller: 'marketa',
    images: ['ampora-go-20k'],
    title: {
      en: 'Ampora Go 20K Power Bank 20,000 mAh, 65 W USB-C PD Laptop Charging, 2 × USB-C + USB-A, Charges 3 Devices at Once, for 13–14-inch Laptops, Phones and Tablets, Carry-On OK (74 Wh)',
      ja: 'アンポラ モバイルバッテリー 20000mAh 65W USB PD ノートPC充電対応 USB-C×2 USB-A×1 3台同時充電 13〜14インチノートPC スマホ タブレット 機内持ち込み可（74Wh） PSE適合 AP-G20',
    },
    short: { en: 'Ampora Go 20K Power Bank', ja: 'アンポラ Go 20K モバイルバッテリー' },
    rating: 4.5,
    ratings: 3355,
    hist: [72, 16, 5, 3, 4],
    added: '2025-01-20',
    badges: ['deal'],
    coupon: { amount: 500, en: 'Save ¥500 with coupon', ja: '500円OFFクーポン' },
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'darkgrey', name: { en: 'Dark Grey', ja: 'ダークグレー' }, price: 5980, list: 7990, stock: 45, ship: 'fast' },
    ],
    returns: {
      en: 'Returnable within 30 days of delivery: unused for a full refund, or opened and working in like-new condition with the cable and pouch, minus a 15% restocking fee (¥897) and ¥550 return shipping (free for paid Fast members). Defective units are returned free within 30 days; after that the 18-month Ampora warranty applies.',
      ja: 'お届けから30日以内なら返品できます。未使用品は全額返金、開封済みで正常に動作するものはケーブル・ポーチを含む新品同様の状態に限り、返品手数料15%（897円）と返送料550円（有料のFast会員は無料）を差し引いて返金します。初期不良は30日以内なら送料無料、その後はアンポラの18か月保証の対象です。',
    },
    bullets: {
      en: [
        'CHARGES YOUR LAPTOP: 65 W USB-C Power Delivery charges most 13–14-inch laptops that charge over USB-C at full speed, and recent phones and tablets at their fastest.',
        'THREE DEVICES AT ONCE: USB-C1 up to 65 W, USB-C2 up to 30 W, USB-A up to 18 W; 65 W in total, for example 45 W to a laptop and 20 W to a phone.',
        'REAL-WORLD CAPACITY: 20,000 mAh at 3.7 V (74 Wh). About 4 charges of a typical phone, or one full charge of a 13-inch laptop with a 50 Wh battery.',
        'FAST TO REFILL: about 2 h 10 min with a 65 W USB-C charger, such as your laptop charger. A 20 W phone charger takes about 5 h 30 min.',
        'CARRY-ON OK: 74 Wh is under 100 Wh, so no airline approval is needed. Never in checked baggage. 360 g, 15.6 × 7.4 × 2.6 cm.',
        '18-MONTH WARRANTY from Ampora. A 100 W USB-C to USB-C cable (60 cm) and a pouch are included; no wall charger.',
      ],
      ja: [
        '【ノートPCも充電】65WのUSB Power Deliveryで、USB-C充電対応の13〜14インチノートPCの多くをフルスピードで充電。最近のスマホやタブレットも最速で充電できます。',
        '【3台同時充電】USB-C1は最大65W、USB-C2は最大30W、USB-Aは最大18W。合計65Wまで、たとえばノートPCに45W、スマホに20Wを同時に出力します。',
        '【実用的な容量】20000mAh（3.7V・74Wh）。一般的なスマホ約4回分、または50Whバッテリーの13インチノートPCを約1回満充電できます。',
        '【本体の充電も速い】65WのUSB-C充電器（ノートPCの充電器など）で約2時間10分。20Wのスマホ用充電器では約5時間30分です。',
        '【機内持ち込みOK】74Whは100Wh未満のため、航空会社への申請は不要です。お預け荷物には入れられません。約360g、15.6×7.4×2.6cm。',
        '【メーカー保証18か月】100W対応USB-C to USB-Cケーブル（60cm）とポーチ付き。ACアダプターは付属しません。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Ampora'], ['Model', 'AP-G20'], ['Capacity', '20,000 mAh / 3.7 V (74 Wh)'], ['Usable output', 'About 12,500 mAh at 5 V; about 55 Wh to a laptop'],
        ['Ports', '2 × USB-C (input/output), 1 × USB-A (output)'], ['Output', 'USB-C1 up to 65 W; USB-C2 up to 30 W; USB-A up to 18 W; 65 W total'],
        ['Input', 'USB-C1 up to 65 W; USB-C2 up to 30 W'], ['Recharge time', 'About 2 h 10 min (65 W charger); about 5 h 30 min (20 W charger)'],
        ['Pass-through charging', 'Yes'], ['Battery indicator', '4 LEDs'], ['Safety', 'PSE certified; temperature, over-current and short-circuit protection'],
        ['Dimensions', '15.6 × 7.4 × 2.6 cm'], ['Weight', '360 g'], ['Country of origin', 'China'], ['Warranty', '18 months (manufacturer)'],
        ['In the box', 'Power bank, 100 W USB-C to USB-C cable (60 cm), travel pouch, quick guide'],
      ],
      ja: [
        ['ブランド', 'アンポラ'], ['型番', 'AP-G20'], ['容量', '20000mAh／3.7V（74Wh）'], ['実出力容量', '5V換算 約12500mAh、ノートPCへは約55Wh'],
        ['ポート', 'USB-C×2（入出力）、USB-A×1（出力）'], ['出力', 'USB-C1 最大65W、USB-C2 最大30W、USB-A 最大18W、合計最大65W'],
        ['入力', 'USB-C1 最大65W、USB-C2 最大30W'], ['本体充電時間', '65W充電器で約2時間10分、20W充電器で約5時間30分'],
        ['パススルー充電', '対応'], ['残量表示', 'LED4つ'], ['安全機能', 'PSE適合、温度・過電流・短絡保護'],
        ['サイズ', '15.6×7.4×2.6cm'], ['重量', '約360g'], ['原産国', '中国'], ['保証', 'メーカー保証18か月'],
        ['付属品', '本体、100W対応USB-C to USB-Cケーブル（60cm）、収納ポーチ、クイックガイド'],
      ],
    },
    compare: {
      en: ['20,000 mAh', '74 Wh: carry-on OK, no approval', '65 W', '2 × USB-C, 1 × USB-A', '360 g', '18 months'],
      ja: ['20000mAh', '74Wh：機内持ち込み可（申請不要）', '65W', 'USB-C×2、USB-A×1', '360g', '18か月'],
    },
    description: {
      en: [
        'The Ampora Go 20K is a power bank for people who carry a laptop as well as a phone. Its main USB-C port delivers 65 W, the same as the charger that comes with most 13–14-inch laptops, so it charges them at normal speed even while you work.',
        'Which laptops? Any laptop that charges over USB-C Power Delivery. If your laptop\'s own charger is 65 W or less, the Go 20K charges it at full speed. Laptops that come with 90–140 W chargers, such as 15–16-inch performance and creator laptops, charge slowly when idle and may still lose charge under heavy load; for those, the Kestrel 27K (140 W) is the better choice. Laptops with a round barrel connector cannot be charged.',
        'When you connect or disconnect a second device, all ports pause for about a second while the power bank shares out the power again. A laptop simply runs on its own battery for that second. In a bag, the power bank gets warm when it delivers 65 W for a long time; keep it in an outside pocket, not wrapped in clothes.',
        'Capacity is 74 Wh. After conversion losses about 55 Wh reaches a laptop: one full charge of a 13-inch laptop with a 50 Wh battery, or about four charges of a typical phone. Ampora covers it for 18 months, and a swollen battery is always replaced free.',
      ],
      ja: [
        'アンポラ Go 20Kは、スマホだけでなくノートPCも持ち歩く方のためのモバイルバッテリーです。メインのUSB-Cポートは65W出力。13〜14インチのノートPCに付属する充電器の多くと同じなので、作業しながらでも通常の速さで充電できます。',
        '対応するノートPC：USB Power Deliveryで充電できるノートPCなら使えます。純正充電器が65W以下のノートPCならフルスピードで充電可能です。15〜16インチの高性能・クリエイター向けノートPCのように90〜140Wの充電器が付属する機種は、待機中はゆっくり充電されますが、高負荷時はバッテリーが減ることもあります。その場合は140W出力の「ケストレル 27K」がおすすめです。丸型のDCジャックで充電するノートPCには使えません。',
        '2台目の機器を抜き差しすると、出力を配分し直すため全ポートが1秒ほど停止します。ノートPCはその間、自分のバッテリーで動くだけなので問題ありません。65Wで長時間出力すると本体が温かくなるので、カバンの中では衣類で包まず、外側のポケットに入れてお使いください。',
        '定格容量は74Wh。変換ロスを除いてノートPCに届くのは約55Whで、50Whバッテリーの13インチノートPCを約1回、一般的なスマホなら約4回充電できます。メーカー保証は18か月で、バッテリーが膨張した場合は必ず無償交換します。',
      ],
    },
    tables: [
      {
        title: { en: 'Will it charge my laptop?', ja: 'ノートPCを充電できる？' },
        en: [['Your laptop\'s charger', 'Typical laptops', 'With the Go 20K'], ['30–45 W', '11–13-inch ultra-light', 'Full speed, about 1.3 charges'], ['65 W', '13–14-inch standard', 'Full speed, about 1 charge'], ['90–100 W', '15-inch performance', 'Slower; may only hold the level under load'], ['140 W', '16-inch creator and high-performance', 'Very slow; see the Kestrel 27K (140 W)'], ['Round barrel plug', 'Many gaming laptops', 'Not supported']],
        ja: [['ノートPCの純正充電器', '主な機種', 'Go 20Kでの充電'], ['30〜45W', '11〜13インチの軽量モデル', 'フルスピード、約1.3回'], ['65W', '13〜14インチの標準モデル', 'フルスピード、約1回'], ['90〜100W', '15インチの高性能モデル', '遅め。高負荷時は現状維持程度'], ['140W', '16インチのクリエイター・高性能モデル', 'かなり遅い。ケストレル 27K（140W）を推奨'], ['丸型DCジャック', 'ゲーミングノートPCの多く', '非対応']],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-22', variant: 'darkgrey', helpful: 188, verified: true,
        en: { name: 'Yosuke', title: 'A full workday on the train', body: 'My 14-inch laptop came with a 65 W charger, and the Go 20K charges it just as fast. It took the laptop from 20% to 85% on the trip to Moonview Spa while I worked, and then charged my phone too. Exactly what I needed.' },
        ja: { name: 'ようすけ', title: '電車で丸一日仕事できる', body: '14インチのノートPCの純正充電器は65Wで、Go 20Kでも同じ速さで充電できます。月見温泉への移動中、作業しながら20%から85%まで回復し、そのあとスマホも充電できました。まさに求めていたもの。' } },
      { stars: 2, date: '2026-08-14', variant: 'darkgrey', helpful: 154, verified: true,
        en: { name: 'Mika', title: 'Everything cuts out when I plug in a second device', body: 'Every time I plug in my phone while the laptop is charging, all ports switch off for a second. The laptop does not care, but a portable drive on the other port disconnected once and a file copy failed. Ampora says it is normal. It should be in big letters on the page.' },
        ja: { name: 'みか', title: '2台目を挿すと全部一瞬止まる', body: 'ノートPCの充電中にスマホを挿すたびに、全ポートの出力が1秒ほど止まります。PCは平気ですが、もう一方のポートにつないでいたポータブルドライブが切断され、コピー中のファイルが失敗したことも。アンポラは仕様だと言いますが、もっと目立つように書くべきです。' } },
      { stars: 1, date: '2026-07-27', variant: 'darkgrey', helpful: 121, verified: true,
        en: { name: 'Suzuki', title: 'Got too hot in my backpack', body: 'Charging my laptop at 65 W inside my backpack, with a jumper around it, the power bank got so hot I could barely hold it and it stopped charging. Out of the bag it stays warm, not hot. Still, I no longer trust it in a bag.' },
        ja: { name: '鈴木', title: 'リュックの中で熱くなりすぎた', body: 'リュックの中でセーターに包まれた状態で、65WでノートPCを充電していたら、持てないほど熱くなって充電が止まりました。外に出しておけば温かい程度ですが、もうカバンの中では使う気になれません。' } },
      { stars: 4, date: '2026-08-20', variant: 'darkgrey', helpful: 33, verified: true,
        en: { name: 'Sho', title: 'Only warm for me', body: 'After reading about overheating I tested it: charging my 65 W laptop for an hour from the side pocket of my backpack, it reached about 40 °C. Warm, but fine. Maybe just do not wrap it in clothes. Minus a star for the slippery finish.' },
        ja: { name: 'しょう', title: '私のは温かい程度', body: '熱くなるというレビューを見て試しました。リュックのサイドポケットに入れて65WのノートPCを1時間充電し、約40℃。温かいけれど問題なし。服で包まなければ大丈夫では。表面が滑りやすいので星4つ。' } },
      { stars: 4, date: '2026-09-10', variant: 'darkgrey', helpful: 92, verified: true,
        en: { name: 'Ryota', title: 'Works on my 16-inch, but slowly', body: 'My 16-inch laptop came with a 140 W charger. The Go 20K charges it when it is asleep or I am doing email, but during video editing the battery still goes down, just more slowly. Not the power bank\'s fault: it is 65 W. If you have a 140 W laptop, the Kestrel 27K is the one to get.' },
        ja: { name: 'りょうた', title: '16インチだとゆっくり', body: '16インチのノートPCは純正が140W。Go 20Kではスリープ中やメール程度なら充電されますが、動画編集中はバッテリーの減りが遅くなるだけです。65Wなので仕方ありません。140WのノートPCならケストレル 27Kのほうがいいです。' } },
      { stars: 3, date: '2026-06-25', variant: 'darkgrey', helpful: 77, verified: true,
        en: { name: 'Saori', title: 'Only one laptop charge', body: 'I thought 20,000 mAh would mean two laptop charges. My 13-inch laptop goes from 10% to 100% once, and then the power bank is down to one light. The page does say "one full charge", so fair enough, but the big number is misleading.' },
        ja: { name: 'さおり', title: 'ノートPCは1回分だけ', body: '20000mAhならノートPC2回分くらいかと思っていました。13インチPCを10%から100%にすると、残りランプは1つ。ページには「約1回分」と書いてあるので仕方ないですが、数字には惑わされます。' } },
      { stars: 2, date: '2026-08-30', variant: 'darkgrey', helpful: 63, verified: true,
        en: { name: 'Gen', title: 'Slow to recharge without a big charger', body: 'With my 20 W phone charger it took almost 6 hours to fill. With my 65 W laptop charger it takes around 2 hours. If you only own phone chargers, plan to charge it overnight.' },
        ja: { name: 'げん', title: '大きな充電器がないと充電が遅い', body: '20Wのスマホ用充電器だと満充電まで6時間近くかかりました。ノートPCの65W充電器なら約2時間。スマホ用の充電器しか持っていない人は、一晩かけて充電する前提で。' } },
      { stars: 5, date: '2026-07-11', variant: 'darkgrey', helpful: 58, verified: true,
        en: { name: 'Olivia', title: 'Flew with it, no problems', body: 'Took it on a domestic flight. 74 Wh is printed on the case and security did not look twice. Under 100 Wh you do not need to tell the airline.' },
        ja: { name: 'オリビア', title: '飛行機も問題なし', body: '国内線で機内に持ち込みました。本体に74Whと印字されていて、保安検査でも特に何も言われません。100Wh未満なら航空会社への申請は不要です。' } },
      { stars: 4, date: '2026-05-28', variant: 'darkgrey', helpful: 41, verified: true,
        en: { name: 'Kaito', title: 'Heavy compared with the Slim', body: 'I also have the Ampora Slim 10K. The Go is exactly twice the weight (360 g against 180 g) and too heavy for a trouser pocket. I carry the Slim on normal days and this one on laptop days.' },
        ja: { name: 'かいと', title: 'Slimと比べると重い', body: 'アンポラ Slim 10Kも持っています。Goは重さがちょうど2倍（360gと180g）で、ズボンのポケットには重すぎます。普段はSlim、ノートPCを持ち歩く日はこちら。' } },
      { stars: 1, date: '2026-09-28', variant: 'darkgrey', helpful: 37, verified: true,
        en: { name: 'Fumi', title: 'USB-A port dead on arrival', body: 'The USB-A port did not work at all from day one. Marketa sent a replacement the next day and took the faulty one back for free, so the service was good, but the quality control is not.' },
        ja: { name: 'ふみ', title: 'USB-Aポートが初期不良', body: '届いた日からUSB-Aポートがまったく使えませんでした。マルケタが翌日に交換品を送ってくれて、不良品の返送も無料だったので対応は良かったですが、品質管理は残念です。' } },
      { stars: 3, date: '2026-04-09', variant: 'darkgrey', helpful: 29, verified: true,
        en: { name: 'Hana', title: 'I wish it had a screen', body: 'Four lights do not tell you much: with one light left I never know whether I can charge my laptop again. The Kestrel 27K has a percentage display, but it costs ¥4,000 more.' },
        ja: { name: 'はな', title: '残量表示がほしい', body: 'ランプ4つだとよくわかりません。残り1つのとき、もう一度ノートPCを充電できるのか判断できない。ケストレル 27Kはパーセント表示がありますが、4,000円高いです。' } },
      { stars: 5, date: '2026-10-03', variant: 'darkgrey', helpful: 9, verified: true,
        en: { name: 'Taro', title: 'A bargain with the coupon', body: 'Used the ¥500 coupon in the Lantern Festival Sale and paid ¥5,480. On long drives it charges my laptop, my phone and the kids\' game console at the same time.' },
        ja: { name: 'たろう', title: 'クーポンでお得', body: '灯籠まつりセールで500円クーポンを使い、5,480円でした。長距離ドライブではノートPC、スマホ、子どものゲーム機を同時に充電しています。' } },
    ],
    qa: [
      { date: '2026-09-07', votes: 61,
        en: { q: 'Will it charge my laptop?', a: 'If your laptop charges over USB-C (USB Power Delivery), yes. Laptops whose own charger is 65 W or less charge at full speed from the USB-C1 port. Laptops that came with a 90–140 W charger charge slowly, or only hold their level under heavy use. Laptops with a round barrel plug are not supported.', by: 'Ampora Support' },
        ja: { q: 'ノートPCを充電できますか？', a: 'USB-C（USB Power Delivery）で充電できるノートPCなら可能です。純正充電器が65W以下の機種はUSB-C1ポートからフルスピードで充電できます。90〜140Wの充電器が付属する機種はゆっくり充電されるか、高負荷時は残量を維持する程度になります。丸型DCジャックの機種には対応していません。', by: 'アンポラ サポート' } },
      { date: '2026-06-19', votes: 28,
        en: { q: 'Can it charge a 16-inch laptop at full speed?', a: 'Yes, it charges my 16-inch at full speed with no problem.', by: 'Marketa customer (Ken)' },
        ja: { q: '16インチのノートPCもフルスピードで充電できますか？', a: 'はい、うちの16インチは問題なくフルスピードで充電できています。', by: 'マルケタ購入者（ケン）' } },
      { date: '2026-08-02', votes: 35,
        en: { q: 'Someone said it charges 16-inch laptops at full speed. Is that right?', a: 'Only if your 16-inch laptop came with a charger of 65 W or less. Most 16-inch performance laptops use 140 W chargers; the Go 20K gives them at most 65 W, so they charge slowly, especially under load. For full speed, choose the Kestrel 27K (140 W).', by: 'Ampora Support' },
        ja: { q: '16インチもフルスピードで充電できるという回答がありますが、本当ですか？', a: '純正充電器が65W以下の16インチ機種に限ります。16インチの高性能ノートPCの多くは140W充電器を使用しており、Go 20Kの最大65Wでは特に高負荷時にゆっくりとしか充電できません。フルスピードで充電したい場合は「ケストレル 27K」（140W）をお選びください。', by: 'アンポラ サポート' } },
      { date: '2026-07-30', votes: 22,
        en: { q: 'Can I take it on a plane?', a: 'Yes. 74 Wh is under 100 Wh, so you can carry it on without airline approval. Never pack it in checked baggage.', by: 'Ampora Support' },
        ja: { q: '飛行機に持ち込めますか？', a: 'はい。74Whで100Wh未満のため、航空会社への申請なしで機内に持ち込めます。お預け荷物には絶対に入れないでください。', by: 'アンポラ サポート' } },
      { date: '2026-05-14', votes: 15,
        en: { q: 'Does it come with a charger?', a: 'No, just a 60 cm 100 W USB-C cable and a pouch. I recharge it with my laptop\'s USB-C charger in about 2 hours.', by: 'Marketa customer (Yosuke)' },
        ja: { q: '充電器は付いていますか？', a: 'いいえ、付属は60cmの100W対応USB-Cケーブルとポーチだけです。私はノートPCのUSB-C充電器で約2時間で充電しています。', by: 'マルケタ購入者（ようすけ）' } },
    ],
    similar: ['ampora-slim-10k', 'kestrel-27k', 'titancell-40k'],
    fbt: ['seiran-headphones', 'nami-buds'],
    alsoViewed: ['kestrel-27k', 'ampora-slim-10k', 'titancell-40k', 'seiran-headphones', 'nami-buds', 'kaze-openear'],
  },
  {
    id: 'kestrel-27k',
    cat: 'electronics',
    cluster: 'power',
    brand: { en: 'Kestrel', ja: 'ケストレル' },
    seller: 'marketa',
    images: ['kestrel-27k'],
    title: {
      en: 'Kestrel 27K Laptop Power Bank 27,000 mAh, 140 W USB-C PD 3.1, Smart Display, 2 × USB-C + USB-A, Charges 16-inch Laptops at Full Speed, 99.9 Wh Carry-On Without Airline Approval',
      ja: 'ケストレル モバイルバッテリー 27000mAh 140W USB PD3.1 ノートPC充電 残量ディスプレイ付き USB-C×2 USB-A×1 16インチノートPC対応 99.9Wh 機内持ち込み可（申請不要） PSE適合 KS-27',
    },
    short: { en: 'Kestrel 27K Laptop Power Bank', ja: 'ケストレル 27K モバイルバッテリー' },
    rating: 4.6,
    ratings: 1214,
    hist: [75, 15, 4, 3, 3],
    added: '2025-08-05',
    badges: ['choice'],
    coupon: null,
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'black', name: { en: 'Black', ja: 'ブラック' }, price: 9980, list: 13800, stock: 8, ship: 'fast' },
    ],
    returns: {
      en: 'Returnable within 30 days of delivery: unused for a full refund, or opened and working in like-new condition with the cable and pouch, minus a 15% restocking fee (¥1,497) and ¥550 return shipping (free for paid Fast members). Defective units are returned free within 30 days; after that the 2-year Kestrel warranty applies.',
      ja: 'お届けから30日以内なら返品できます。未使用品は全額返金、開封済みで正常に動作するものはケーブル・ポーチを含む新品同様の状態に限り、返品手数料15%（1,497円）と返送料550円（有料のFast会員は無料）を差し引いて返金します。初期不良は30日以内なら送料無料、その後はケストレルの2年保証の対象です。',
    },
    bullets: {
      en: [
        '140 W FOR BIG LAPTOPS: USB PD 3.1 delivers up to 140 W from USB-C1, enough to charge 16-inch performance laptops at full speed, even while you edit video.',
        'THE LARGEST YOU CAN FLY WITH WITHOUT APPROVAL: 27,000 mAh is 99.9 Wh, just under the 100 Wh limit, so you can take it on board without asking the airline. Never in checked baggage.',
        'SEE WHAT IS HAPPENING: the display shows remaining percentage, watts in and out for each port, and estimated time left.',
        'THREE PORTS: USB-C1 140 W, USB-C2 100 W, USB-A 18 W; 140 W in total when you use several, for example 100 W + 40 W for two laptops.',
        'FAST REFILL: recharges in about 1 h 40 min with a USB-C charger of 100 W or more (about 2 h 30 min with 65 W).',
        'SOLID, NOT SMALL: aluminium shell, 18.2 × 8.0 × 2.7 cm, 610 g. 240 W USB-C cable (1 m) and pouch included. 2-year warranty.',
      ],
      ja: [
        '【大型ノートPCに140W】USB PD3.1対応で、USB-C1ポートから最大140W。16インチの高性能ノートPCも、動画編集中でもフルスピードで充電できます。',
        '【申請なしで機内に持ち込める最大クラス】27000mAhは99.9Whで、100Wh未満。航空会社への申請なしで機内に持ち込めます。お預け荷物には入れられません。',
        '【ひと目でわかるディスプレイ】残量（%）、ポートごとの入出力ワット数、残り時間の目安を表示します。',
        '【3ポート】USB-C1 140W、USB-C2 100W、USB-A 18W。複数使用時は合計140Wまで（例：ノートPC2台に100W＋40W）。',
        '【本体の充電も速い】100W以上のUSB-C充電器で約1時間40分（65W充電器では約2時間30分）。',
        '【頑丈なアルミボディ】18.2×8.0×2.7cm、約610g。240W対応USB-Cケーブル（1m）とポーチ付き。メーカー保証2年。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Kestrel'], ['Model', 'KS-27'], ['Capacity', '27,000 mAh / 3.7 V (99.9 Wh)'], ['Usable output', 'About 80 Wh to a laptop'],
        ['Ports', '2 × USB-C (input/output), 1 × USB-A (output)'], ['Output', 'USB-C1 up to 140 W (PD 3.1); USB-C2 up to 100 W; USB-A up to 18 W; 140 W total'],
        ['Input', 'USB-C1 or USB-C2, up to 100 W'], ['Recharge time', 'About 1 h 40 min (100 W charger); about 2 h 30 min (65 W); about 6 h (20 W)'],
        ['Display', 'Percentage, watts per port, time remaining'], ['Pass-through charging', 'Yes'],
        ['Safety', 'PSE certified; temperature monitoring, over-current and short-circuit protection'],
        ['Dimensions', '18.2 × 8.0 × 2.7 cm'], ['Weight', '610 g'], ['Country of origin', 'China'], ['Warranty', '2 years (manufacturer)'],
        ['In the box', 'Power bank, 240 W USB-C to USB-C cable (1 m), pouch, quick guide'],
      ],
      ja: [
        ['ブランド', 'ケストレル'], ['型番', 'KS-27'], ['容量', '27000mAh／3.7V（99.9Wh）'], ['実出力容量', 'ノートPCへ約80Wh'],
        ['ポート', 'USB-C×2（入出力）、USB-A×1（出力）'], ['出力', 'USB-C1 最大140W（PD3.1）、USB-C2 最大100W、USB-A 最大18W、合計最大140W'],
        ['入力', 'USB-C1またはUSB-C2 最大100W'], ['本体充電時間', '100W充電器で約1時間40分、65Wで約2時間30分、20Wで約6時間'],
        ['ディスプレイ', '残量（%）、ポート別ワット数、残り時間'], ['パススルー充電', '対応'],
        ['安全機能', 'PSE適合、温度監視、過電流・短絡保護'],
        ['サイズ', '18.2×8.0×2.7cm'], ['重量', '約610g'], ['原産国', '中国'], ['保証', 'メーカー保証2年'],
        ['付属品', '本体、240W対応USB-C to USB-Cケーブル（1m）、ポーチ、クイックガイド'],
      ],
    },
    compare: {
      en: ['27,000 mAh', '99.9 Wh: carry-on OK, no approval', '140 W', '2 × USB-C, 1 × USB-A', '610 g', '2 years'],
      ja: ['27000mAh', '99.9Wh：機内持ち込み可（申請不要）', '140W', 'USB-C×2、USB-A×1', '610g', '2年'],
    },
    description: {
      en: [
        'The Kestrel 27K is built for large laptops. Its USB-C1 port supports USB Power Delivery 3.1 at up to 140 W, the same as the chargers that come with 16-inch performance laptops, so they charge at full speed instead of slowly losing battery as they do on a 65 W power bank such as the Ampora Go 20K.',
        'To get 140 W you need a cable rated for 240 W (USB PD 3.1, often marked "EPR"). The included 1 m cable is; most ordinary USB-C cables top out at 60 W or 100 W, and the display will show the lower figure. 13–14-inch laptops, tablets and phones charge from any port at their own maximum speed.',
        'Flying: 99.9 Wh is printed on the case, just under the 100 Wh line, so you can carry it on without airline approval. Do not cover the label with stickers, because security staff check it. Power banks are never allowed in checked baggage. Between 100 and 160 Wh you would need the airline\'s approval and could carry at most two.',
        'At 140 W the aluminium shell gets warm, up to about 45 °C; this is normal and helps it shed heat. Use it on a table rather than inside a bag. For safety it ships at about 30–40% charge, so charge it fully before a trip. Kestrel covers it for two years from purchase.',
      ],
      ja: [
        'ケストレル 27Kは大型ノートPCのためのモバイルバッテリーです。USB-C1ポートはUSB Power Delivery 3.1で最大140W。16インチの高性能ノートPCに付属する充電器と同じ出力なので、「アンポラ Go 20K」のような65Wのモバイルバッテリーのように少しずつ減っていくことはなく、フルスピードで充電できます。',
        '140Wで充電するには240W対応（USB PD3.1、「EPR」と表記されることが多い）のケーブルが必要です。付属の1mケーブルは対応済み。一般的なUSB-Cケーブルは60Wか100Wまでで、その場合はディスプレイに低い数値が表示されます。13〜14インチのノートPC、タブレット、スマホはどのポートでもそれぞれの最大速度で充電できます。',
        '飛行機について：本体に99.9Whと表示されており、100Wh未満のため航空会社への申請なしで機内に持ち込めます。保安検査で表示を確認されることがあるので、シールなどで隠さないでください。モバイルバッテリーはお預け荷物には入れられません。100Wh以上160Wh以下の場合は航空会社の承認が必要で、持ち込みは2個までです。',
        '140W出力時はアルミボディが最大45℃程度まで温かくなりますが、放熱のための正常な動作です。カバンの中ではなく机の上でお使いください。安全のため残量30〜40%程度で出荷していますので、旅行前に満充電してください。メーカー保証は購入日から2年間です。',
      ],
    },
    tables: [
      {
        title: { en: 'Power banks and flights', ja: 'モバイルバッテリーと飛行機' },
        en: [['Rated energy', 'Carry-on', 'Checked baggage', 'Examples on Marketa'], ['Under 100 Wh', 'Yes, no approval needed', 'Never', 'Ampora Slim 10K (37 Wh), Ampora Go 20K (74 Wh), Kestrel 27K (99.9 Wh)'], ['100–160 Wh', 'Only with airline approval; at most two per person', 'Never', 'TitanCell 40000 (148 Wh)'], ['Over 160 Wh', 'Not allowed', 'Never', '—']],
        ja: [['定格容量', '機内持ち込み', 'お預け荷物', 'マルケタの例'], ['100Wh未満', '可（申請不要）', '不可', 'アンポラ Slim 10K（37Wh）、アンポラ Go 20K（74Wh）、ケストレル 27K（99.9Wh）'], ['100〜160Wh', '航空会社の承認があれば可（1人2個まで）', '不可', 'タイタンセル 40000（148Wh）'], ['160Wh超', '不可', '不可', '—']],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-20', variant: 'black', helpful: 156, verified: true,
        en: { name: 'Daisuke K.', title: 'Finally full speed for my 16-inch', body: 'My 16-inch laptop came with a 140 W charger, and every power bank I tried before only slowed the drain. The Kestrel shows 138 W on the display and the battery goes up even while I export video. Heavy, but worth it.' },
        ja: { name: '小林', title: '16インチがやっとフルスピードで充電', body: '16インチのノートPCは純正140W。今まで試したモバイルバッテリーは減りが遅くなるだけでした。ケストレルはディスプレイに138Wと表示され、動画を書き出しながらでもバッテリーが増えていきます。重いけれど買う価値あり。' } },
      { stars: 2, date: '2026-08-11', variant: 'black', helpful: 113, verified: true,
        en: { name: 'Ayumi', title: 'A heavy brick for a small laptop', body: 'At 610 g it weighs more than my 13-inch laptop\'s charger and cable together, and it does not fit the laptop sleeve in my bag. For a 13-inch laptop it is overkill. I returned it, paying the 15% restocking fee (¥1,497), and bought the Ampora Go 20K.' },
        ja: { name: 'あゆみ', title: '小さいノートPCには重すぎる', body: '610gは13インチPCの充電器とケーブルを合わせたより重く、カバンのPCスリーブにも入りません。13インチPCには大げさでした。返品手数料15%（1,497円）を払って返品し、アンポラ Go 20Kにしました。' } },
      { stars: 4, date: '2026-07-04', variant: 'black', helpful: 87, verified: true,
        en: { name: 'Mark', title: 'Through security with no questions', body: 'Two domestic flights and one international one. Staff looked at the 99.9 Wh label once and waved me through. That is exactly why I chose it over bigger ones. Minus a star for the weight.' },
        ja: { name: 'マーク', title: '保安検査も問題なし', body: '国内線2回、国際線1回で機内に持ち込み。99.9Whの表示を一度確認されただけで通過できました。これより大きいものを選ばなかったのはこのため。重さで星4つ。' } },
      { stars: 1, date: '2026-06-16', variant: 'black', helpful: 102, verified: true,
        en: { name: 'Yamato', title: 'Dead after five months', body: 'Stopped turning on after five months: the display stays black and nothing charges. Kestrel replaced it under the 2-year warranty, but it took 15 days, right in the middle of a business trip.' },
        ja: { name: 'やまと', title: '5か月で故障', body: '5か月で電源が入らなくなりました。ディスプレイは真っ暗で何も充電できません。2年保証で交換してもらえましたが、15日かかり、ちょうど出張と重なりました。' } },
      { stars: 2, date: '2026-09-15', variant: 'black', helpful: 74, verified: true,
        en: { name: 'Hitomi', title: 'Gets hot at 140 W', body: 'After an hour at 140 W my thermometer read 46 °C on the case. Too hot to keep on my lap. Kestrel says this is normal and safe. Fine on a desk, but more than I expected.' },
        ja: { name: 'ひとみ', title: '140Wだと熱い', body: '140Wで1時間使うと、温度計で本体が46℃に。ひざの上には置いていられません。メーカーは正常で安全とのこと。机の上なら問題ありませんが、想像以上でした。' } },
      { stars: 5, date: '2026-08-23', variant: 'black', helpful: 49, verified: true,
        en: { name: 'Tak', title: 'The display is the best part', body: 'I can see exactly how many watts each port is giving. That is how I found out my old cable only carried 60 W. With the included cable it is 140 W.' },
        ja: { name: 'たく', title: 'ディスプレイが一番便利', body: '各ポートの出力ワット数がひと目でわかります。手持ちの古いケーブルが60Wしか出ないことに、これで気づきました。付属ケーブルなら140W出ます。' } },
      { stars: 3, date: '2026-07-22', variant: 'black', helpful: 58, verified: true,
        en: { name: 'Yoshie', title: 'Slow to recharge with a small charger', body: 'With my 20 W phone charger it took about six hours. With the 140 W laptop charger it is under two hours. Not a problem once you know, but the box only gives the fastest time.' },
        ja: { name: 'よしえ', title: '小さい充電器だと充電が遅い', body: '20Wのスマホ用充電器だと約6時間かかりました。140WのノートPC用充電器なら2時間以内。わかっていれば問題ありませんが、箱には最速の時間しか書いていません。' } },
      { stars: 4, date: '2026-09-01', variant: 'black', helpful: 44, verified: true,
        en: { name: 'Ichiro', title: 'Chose it over the TitanCell for flying', body: 'I almost bought the TitanCell 40000 because it is cheaper and bigger. Then I saw it is 148 Wh, which needs airline approval, and only gives 22.5 W, so it cannot charge my laptop. The Kestrel is the largest you can carry on without asking, and it actually charges laptops.' },
        ja: { name: 'いちろう', title: '飛行機で使うならタイタンセルよりこちら', body: '安くて容量の大きいタイタンセル 40000を買いかけましたが、148Whで航空会社の承認が必要なうえ、出力22.5WではノートPCを充電できません。ケストレルは申請なしで持ち込める最大クラスで、ちゃんとノートPCも充電できます。' } },
      { stars: 2, date: '2026-05-19', variant: 'black', helpful: 39, verified: true,
        en: { name: 'Jin', title: 'The second USB-C port is loose', body: 'The USB-C2 port feels loose and the cable falls out if the power bank moves. USB-C1 is firm. It was within 30 days, so Marketa replaced it, and the new one is better.' },
        ja: { name: 'じん', title: 'USB-C2ポートがゆるい', body: 'USB-C2ポートがゆるく、本体が動くとケーブルが抜けてしまいます。USB-C1はしっかりしています。30日以内だったのでマルケタで交換してもらい、新しいものは大丈夫です。' } },
      { stars: 5, date: '2026-08-04', variant: 'black', helpful: 35, verified: true,
        en: { name: 'Kenji', title: 'Two nights near Mount Moonview', body: 'People complain about the weight, but 610 g for full laptop charges is nothing on a camping trip. Two nights near Mount Moonview with a laptop for photo editing, two phones and a headlamp, and it still had 18% when we got home.' },
        ja: { name: 'けんじ', title: '月見山で2泊', body: '重いという声もありますが、ノートPCを満充電できて610gならキャンプでは気になりません。月見山の近くで2泊、写真編集用のノートPC、スマホ2台、ヘッドライトを充電して、帰宅時にまだ18%残っていました。' } },
      { stars: 4, date: '2026-10-02', variant: 'black', helpful: 7, verified: true,
        en: { name: 'Sayaka', title: 'Bought it in the sale', body: 'Got it for ¥9,980 in the Lantern Festival Sale, and only a few were left. It charges my 14-inch laptop and my phone at the same time without trouble. It is heavy, so I only take it on long trips.' },
        ja: { name: 'さやか', title: 'セール中に購入', body: '灯籠まつりセールで9,980円で購入。残りわずかでした。14インチPCとスマホを同時に充電しても問題なし。重いので長距離の移動のときだけ持ち出しています。' } },
    ],
    qa: [
      { date: '2026-09-12', votes: 54,
        en: { q: 'Can I take this on a plane without telling the airline?', a: 'Yes. It is 99.9 Wh, under 100 Wh, so no airline approval is needed for carry-on. It must never go in checked baggage. If you carry several power banks, check your airline\'s limits.', by: 'Kestrel Support' },
        ja: { q: '航空会社に申請せずに機内に持ち込めますか？', a: 'はい。99.9Whで100Wh未満のため、機内持ち込みに申請は不要です。お預け荷物には入れられません。複数のモバイルバッテリーを持ち込む場合は、航空会社の個数制限をご確認ください。', by: 'ケストレル サポート' } },
      { date: '2026-08-18', votes: 37,
        en: { q: 'My 16-inch laptop came with a 140 W charger. Will this charge it at full speed?', a: 'Yes, from the USB-C1 port with the included 240 W cable. With a 100 W cable it is limited to 100 W.', by: 'Kestrel Support' },
        ja: { q: '16インチのノートPCに140Wの充電器が付いていました。フルスピードで充電できますか？', a: 'はい。USB-C1ポートに付属の240W対応ケーブルでつなげばフルスピードで充電できます。100W対応のケーブルでは100Wまでになります。', by: 'ケストレル サポート' } },
      { date: '2026-06-28', votes: 18,
        en: { q: 'Can it charge two laptops at 140 W each?', a: 'Yes, both USB-C ports do 140 W.', by: 'Marketa customer (Haru)' },
        ja: { q: 'ノートPC2台をそれぞれ140Wで充電できますか？', a: 'はい、USB-Cは2つとも140W出ます。', by: 'マルケタ購入者（はる）' } },
      { date: '2026-07-15', votes: 26,
        en: { q: 'Is it true that both ports give 140 W at the same time?', a: 'No. The total is 140 W. On its own, USB-C1 gives up to 140 W and USB-C2 up to 100 W; with two laptops connected the power is shared, for example 100 W + 40 W.', by: 'Kestrel Support' },
        ja: { q: '2つのポートで同時に140Wずつ出るというのは本当ですか？', a: 'いいえ。合計で最大140Wです。単独使用時はUSB-C1が最大140W、USB-C2が最大100Wで、ノートPC2台をつなぐと100W＋40Wのように配分されます。', by: 'ケストレル サポート' } },
      { date: '2026-05-06', votes: 12,
        en: { q: 'Does it charge gaming laptops?', a: 'Only ones that charge through USB-C. Mine has a round barrel plug, and it does not work with that.', by: 'Marketa customer (Ryota)' },
        ja: { q: 'ゲーミングノートPCも充電できますか？', a: 'USB-Cで充電できる機種だけです。私のは丸型のDCジャックなので使えませんでした。', by: 'マルケタ購入者（りょうた）' } },
    ],
    similar: ['ampora-go-20k', 'ampora-slim-10k', 'titancell-40k'],
    fbt: ['seiran-headphones', 'ampora-slim-10k'],
    alsoViewed: ['ampora-go-20k', 'titancell-40k', 'ampora-slim-10k', 'seiran-headphones', 'nami-buds', 'yamabiko-storm'],
  },
  {
    id: 'titancell-40k',
    cat: 'electronics',
    cluster: 'power',
    brand: { en: 'TitanCell', ja: 'タイタンセル' },
    seller: 'brightdeal',
    images: ['titancell-40k'],
    title: {
      en: 'TitanCell 40000mAh Power Bank Huge Capacity Portable Charger, 22.5W Fast Charging, 4 Ports, LED Flashlight, Charges Phones 8 Times, Camping Emergency Disaster Kit, for iPhone Android',
      ja: 'モバイルバッテリー 40000mAh 大容量 タイタンセル 22.5W 急速充電 4ポート LEDライト付き スマホ約8回充電 防災グッズ キャンプ 停電対策 iPhone Android対応 ブラック/オレンジ',
    },
    short: { en: 'TitanCell 40000 Power Bank', ja: 'タイタンセル 40000 モバイルバッテリー' },
    rating: 3.7,
    ratings: 958,
    hist: [46, 18, 10, 8, 18],
    added: '2025-10-14',
    badges: ['sponsored'],
    coupon: null,
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'black-orange', name: { en: 'Black/Orange', ja: 'ブラック/オレンジ' }, price: 6480, list: 12980, stock: 64, ship: 'brightdeal' },
    ],
    returns: {
      en: 'Sold and shipped by BrightDeal Trading, which uses its own policy: change-of-mind returns within 30 days only if unopened, and you pay ¥880 return shipping. If faulty, message the seller first and wait up to 2 business days for a prepaid label; if the seller does not reply or refuses a valid return, Marketa Purchase Protection applies.',
      ja: 'ブライトディール商事が販売・発送する商品のため、同社の返品条件が適用されます。お客様都合の返品は未開封品のみ30日以内で、返送料880円はお客様負担です。不良品の場合はまず出品者にメッセージで連絡し、返送用伝票の発行を最大2営業日お待ちください。返信がない場合や正当な返品を断られた場合は、マルケタ購入保証の対象になります。',
    },
    bullets: {
      en: [
        'HUGE 40,000 MAH CAPACITY: about 8 charges of a 3,000 mAh smartphone, or about 5 of a 5,000 mAh one. Great for camping, power cuts and emergency kits.',
        '4 PORTS: USB-C in/out (20 W PD), 2 × USB-A out (22.5 W fast charge) and a micro-USB input. Charge three devices at once (15 W shared when more than one is connected).',
        'BRIGHT LED FLASHLIGHT: double-press the button for the light; about 60 hours of light from a full charge.',
        'RECHARGING: about 11 h with a USB-C charger of 18 W or more, about 18 h through micro-USB. Charge it overnight before you need it.',
        'FLIGHTS: 148 Wh. This is over 100 Wh, so you need your airline\'s approval before you can take it on board (at most two per person). It can never go in checked baggage.',
        'NOT FOR LAPTOPS: maximum 22.5 W, for phones, tablets, earbuds, lights and fans. 880 g, 17.0 × 8.2 × 4.0 cm. 6-month seller warranty.',
      ],
      ja: [
        '【40000mAhの大容量】3000mAhのスマホなら約8回、5000mAhのスマホなら約5回充電できます。キャンプや停電対策、防災グッズに最適です。',
        '【4ポート搭載】USB-C入出力（20W PD）、USB-A出力×2（22.5W急速充電）、micro-USB入力。3台同時に充電できます（複数接続時は合計15W）。',
        '【明るいLEDライト】ボタンを2回押すと点灯。満充電で約60時間照らせます。',
        '【本体の充電】18W以上のUSB-C充電器で約11時間、micro-USBでは約18時間。使う前の晩から充電しておいてください。',
        '【飛行機について】148Whのため100Whを超えます。機内持ち込みには事前に航空会社の承認が必要です（1人2個まで）。お預け荷物には絶対に入れられません。',
        '【ノートPCには非対応】最大22.5W。スマホ・タブレット・イヤホン・ライト・扇風機向けです。約880g、17.0×8.2×4.0cm。6か月の販売店保証付き。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'TitanCell'], ['Model', 'TC-40000'], ['Capacity', '40,000 mAh / 3.7 V (148 Wh)'],
        ['Ports', 'USB-C (input/output), 2 × USB-A (output), micro-USB (input)'], ['Output', 'USB-C 20 W PD; USB-A 22.5 W; 15 W total with several devices'],
        ['Input', 'USB-C 18 W; micro-USB 10 W'], ['Recharge time', 'About 11 h (USB-C, 18 W); about 18 h (micro-USB)'],
        ['Battery indicator', '4 LEDs'], ['Flashlight', 'LED, about 60 h'], ['Flights', '148 Wh: carry-on only with airline approval; never in checked baggage'],
        ['Safety', 'PSE mark; overcharge and short-circuit protection'],
        ['Dimensions', '17.0 × 8.2 × 4.0 cm'], ['Weight', '880 g'], ['Country of origin', 'China'],
        ['Warranty', '6 months (BrightDeal Trading seller warranty)'], ['In the box', 'Power bank, USB-A to USB-C cable (50 cm), manual'],
      ],
      ja: [
        ['ブランド', 'タイタンセル'], ['型番', 'TC-40000'], ['容量', '40000mAh／3.7V（148Wh）'],
        ['ポート', 'USB-C（入出力）、USB-A×2（出力）、micro-USB（入力）'], ['出力', 'USB-C 20W PD、USB-A 22.5W、複数接続時は合計15W'],
        ['入力', 'USB-C 18W、micro-USB 10W'], ['本体充電時間', 'USB-C（18W）で約11時間、micro-USBで約18時間'],
        ['残量表示', 'LED4つ'], ['ライト', 'LED、約60時間点灯'], ['飛行機', '148Wh：航空会社の承認があれば機内持ち込み可、お預け荷物は不可'],
        ['安全機能', 'PSEマーク、過充電・短絡保護'],
        ['サイズ', '17.0×8.2×4.0cm'], ['重量', '約880g'], ['原産国', '中国'],
        ['保証', '6か月（ブライトディール商事による販売店保証）'], ['付属品', '本体、USB-A to USB-Cケーブル（50cm）、取扱説明書'],
      ],
    },
    compare: {
      en: ['40,000 mAh', '148 Wh: airline approval needed', '22.5 W', '1 × USB-C, 2 × USB-A, micro-USB (input)', '880 g', '6 months (seller)'],
      ja: ['40000mAh', '148Wh：航空会社の承認が必要', '22.5W', 'USB-C×1、USB-A×2、micro-USB（入力）', '880g', '6か月（販売店保証）'],
    },
    description: {
      en: [
        'The TitanCell 40000 is a large-capacity power bank for times when you are far from a socket: camping, festivals, long trips and power cuts after typhoons or earthquakes. Keep it charged in your emergency kit and you can keep a family\'s phones running for several days.',
        'Its maximum output is 22.5 W, which suits phones, tablets, earbuds, LED lanterns and USB fans. It cannot charge laptops. Each port gives its full speed only when used alone; with two or three devices connected, they share 15 W.',
        'Recharging a 148 Wh battery takes time: about 11 hours with a USB-C charger of 18 W or more, or about 18 hours through micro-USB. In storage a full charge drops by about 3% a month, so top it up every three months.',
        'Flying: at 148 Wh it is between 100 and 160 Wh. You must get approval from your airline before you fly, you may carry at most two such batteries, and it can never go in checked baggage. To fly without approval, choose a power bank under 100 Wh.',
        'Sold and shipped by BrightDeal Trading from Kobe: delivery takes 4–8 days and is not eligible for Marketa Fast. 6-month seller warranty; contact us by Marketa message, weekdays 10:00–17:00.',
      ],
      ja: [
        'タイタンセル 40000は、コンセントのない場所で頼れる大容量モバイルバッテリーです。キャンプやお祭り、長旅のほか、台風や地震による停電にも。充電した状態で防災バッグに入れておけば、家族のスマホを数日間使い続けられます。',
        '最大出力は22.5Wで、スマホ・タブレット・イヤホン・LEDランタン・USB扇風機などに向いています。ノートPCは充電できません。各ポートの最大出力は単独使用時のみで、2〜3台接続すると合計15Wを分け合います。',
        '148Whの大容量のため、本体の充電には時間がかかります。18W以上のUSB-C充電器で約11時間、micro-USBでは約18時間です。満充電で保管しても1か月に約3%ずつ減るので、3か月に1回は充電してください。',
        '飛行機について：148Whは100Wh以上160Wh以下にあたります。搭乗前に航空会社の承認が必要で、持ち込みは2個まで、お預け荷物には入れられません。申請なしで飛行機に持ち込みたい場合は、100Wh未満のモバイルバッテリーをお選びください。',
        'ブライトディール商事が神戸の倉庫から販売・発送します。お届けまで4〜8日で、マルケタFastの対象外です。販売店保証6か月。お問い合わせはマルケタのメッセージから（平日10:00〜17:00）。',
      ],
    },
    tables: [
      {
        title: { en: 'What it can charge (seller\'s figures)', ja: '充電・使用できる目安（出品者調べ）' },
        en: [['Device', 'Approx. charges or run time'], ['Smartphone, 3,000 mAh', 'About 8 charges'], ['Smartphone, 5,000 mAh', 'About 5 charges'], ['Tablet, 8,000 mAh', 'About 3 charges'], ['USB LED lantern (2 W)', 'About 45 h'], ['USB desk fan (2.5 W)', 'About 35 h'], ['Laptop', 'Not supported']],
        ja: [['機器', '充電回数・使用時間の目安'], ['スマホ（3000mAh）', '約8回'], ['スマホ（5000mAh）', '約5回'], ['タブレット（8000mAh）', '約3回'], ['USB LEDランタン（2W）', '約45時間'], ['USB卓上扇風機（2.5W）', '約35時間'], ['ノートPC', '非対応']],
      },
    ],
    reviews: [
      { stars: 5, date: '2026-09-18', variant: 'black-orange', helpful: 132, verified: true,
        en: { name: 'Kazuko', title: 'Kept our phones going after the typhoon', body: 'In the power cut after this month\'s typhoon we had no electricity for two days. This kept three phones and a small LED lantern going the whole time and still had one light left. Heavy, but that is the point.' },
        ja: { name: 'かずこ', title: '台風の停電で家族のスマホを守ってくれた', body: '今月の台風で2日間停電したとき、スマホ3台と小さなLEDランタンをずっと充電でき、それでもランプが1つ残っていました。重いですが、そのぶん頼りになります。' } },
      { stars: 1, date: '2026-08-07', variant: 'black-orange', helpful: 189, verified: true,
        en: { name: 'Tomo', title: 'Not allowed on my flight', body: 'At security I was told that 148 Wh needs approval from the airline in advance. I had not done that, so I had to give it up. It is in the bullet points, but the photos and title make it look like an ordinary travel power bank. If you fly, buy one under 100 Wh.' },
        ja: { name: 'とも', title: '飛行機に持ち込めなかった', body: '保安検査で、148Whは事前に航空会社の承認が必要と言われました。申請していなかったので放棄することに。箇条書きには書いてありますが、写真やタイトルからは普通の旅行用モバイルバッテリーに見えます。飛行機に乗るなら100Wh未満のものを。' } },
      { stars: 2, date: '2026-07-16', variant: 'black-orange', helpful: 121, verified: true,
        en: { name: 'Masao', title: 'Over eleven hours to recharge', body: 'With an 18 W USB-C charger it took 11.5 hours from empty. Through micro-USB it charged all night and all the next morning and still was not full. You cannot top it up quickly before a trip.' },
        ja: { name: 'まさお', title: '充電に11時間以上', body: '18WのUSB-C充電器で空から11時間半。micro-USBだと一晩と翌朝いっぱいかけても満充電になりませんでした。出発前にさっと充電するのは無理です。' } },
      { stars: 2, date: '2026-09-06', variant: 'black-orange', helpful: 104, verified: true,
        en: { name: 'Ryuji', title: 'Real capacity nowhere near 40,000', body: 'With a USB tester I measured 19,800 mAh at 5 V before it was empty, about half. I got four charges of my 5,000 mAh phone, not the five the listing promises.' },
        ja: { name: 'りゅうじ', title: '実容量は40000mAhにほど遠い', body: 'USBテスターで測ったら、空になるまでの出力は5V換算で19800mAh。約半分です。5000mAhのスマホで充電できたのは4回で、説明にある5回には届きませんでした。' } },
      { stars: 4, date: '2026-08-24', variant: 'black-orange', helpful: 62, verified: true,
        en: { name: 'Hideo', title: 'Measured 24,000 mAh, which is normal', body: 'I measured about 24,000 mAh at 5 V, around 60% of the rated capacity at 3.7 V. After conversion losses that is normal for any power bank. Maybe the reviewer above got a weak unit. For the price, fine.' },
        ja: { name: 'ひでお', title: '実測24000mAh、普通です', body: '実測で5V換算約24000mAh、3.7V定格の約60%です。変換ロスを考えればどのモバイルバッテリーも同じくらい。上のレビューの方は個体差かも。値段を考えれば十分。' } },
      { stars: 1, date: '2026-06-20', variant: 'black-orange', helpful: 147, verified: true,
        en: { name: 'Aiko', title: 'The case bulged after four months', body: 'After four months one side of the case started to bulge and it got hot while charging. I stopped using it at once. BrightDeal replied after two business days and sent a label, and I got a refund a week later. A swelling battery is dangerous; I will not buy this brand again.' },
        ja: { name: 'あいこ', title: '4か月で本体が膨らんだ', body: '4か月で本体の片側が膨らみ、充電中に熱くなるように。すぐに使用をやめました。ブライトディールからは2営業日後に返信があって伝票が届き、1週間後に返金されました。バッテリーの膨張は危険なので、このブランドはもう買いません。' } },
      { stars: 3, date: '2026-05-31', variant: 'black-orange', helpful: 58, verified: true,
        en: { name: 'Shige', title: 'Heavy, but the flashlight is handy', body: '880 g is like carrying a bottle of water, so it is not for every day. The flashlight is surprisingly bright and useful for garden work in the evening.' },
        ja: { name: 'しげ', title: '重いけどライトは便利', body: '880gはペットボトル1本を持ち歩くようなもの。普段使いには向きません。ライトは意外と明るく、夕方の庭仕事で役立っています。' } },
      { stars: 2, date: '2026-09-24', variant: 'black-orange', helpful: 73, verified: true,
        en: { name: 'Nobu', title: 'Will not charge my laptop', body: 'The laptop says "slow charger" and the battery still goes down. With 22.5 W maximum that is expected; I should have read more carefully. For a laptop, get something with 65 W or more, like the Ampora Go 20K.' },
        ja: { name: 'のぶ', title: 'ノートPCは充電できない', body: 'ノートPCに「低速の充電器」と表示され、バッテリーは減っていきます。最大22.5Wなので当然ですが、よく読むべきでした。ノートPCならアンポラ Go 20Kのような65W以上のものを。' } },
      { stars: 5, date: '2026-08-17', variant: 'black-orange', helpful: 45, verified: true,
        en: { name: 'Sae', title: 'Three nights at the Mount Moonview campsite', body: 'Phones for two people, a USB fan and a lantern for three nights without power, and it still had 25% left. At this price, unbeatable for camping.' },
        ja: { name: 'さえ', title: '月見山のキャンプ場で3泊', body: '電源なしで3泊、2人分のスマホ、USB扇風機、ランタンをまかなって、まだ25%残っていました。この値段ならキャンプ用に最高。' } },
      { stars: 3, date: '2026-07-29', variant: 'black-orange', helpful: 39, verified: true,
        en: { name: 'Kenzo', title: 'Cheaper than the Kestrel, but…', body: 'I compared it with the Kestrel 27K. The TitanCell is ¥3,500 cheaper and has more capacity on paper, but the Kestrel is 270 g lighter, charges laptops and can go on a plane without approval. I keep the TitanCell for the disaster kit only.' },
        ja: { name: 'けんぞう', title: 'ケストレルより安いけれど…', body: 'ケストレル 27Kと比べました。タイタンセルは3,500円安く、容量も数字の上では大きいですが、ケストレルは270g軽く、ノートPCも充電でき、申請なしで飛行機に持ち込めます。結局タイタンセルは防災用だけにしています。' } },
      { stars: 4, date: '2026-09-30', variant: 'black-orange', helpful: 22, verified: true,
        en: { name: 'Mai K.', title: 'Arrived from Kobe in five days', body: 'Ordered on Thursday, arrived on Tuesday, about half charged. Works as described so far.' },
        ja: { name: 'まい', title: '神戸から5日で到着', body: '木曜日に注文して火曜日に到着。半分くらい充電された状態で届きました。今のところ説明どおり使えています。' } },
      { stars: 1, date: '2026-04-12', variant: 'black-orange', helpful: 51, verified: false,
        en: { name: 'Goro', title: 'The micro-USB port broke', body: 'The micro-USB input came loose after two months, and now only USB-C charges it. The seller said it still charges, so it is not a fault. Why does a 2025 product even have micro-USB?' },
        ja: { name: 'ごろう', title: 'micro-USBポートが壊れた', body: '2か月でmicro-USBの差し込み口がぐらつき、今はUSB-Cでしか充電できません。出品者からは充電できているので故障ではないとの回答。そもそも今どきmicro-USBが付いているのはなぜ？' } },
    ],
    qa: [
      { date: '2026-03-20', votes: 14,
        en: { q: 'Can I take it on a plane?', a: 'Yes, you can take it in your carry-on luggage.', by: 'BrightDeal Trading' },
        ja: { q: '飛行機に持ち込めますか？', a: 'はい、機内持ち込み手荷物として持ち込めます。', by: 'ブライトディール商事' } },
      { date: '2026-08-08', votes: 57,
        en: { q: 'The seller says carry-on is fine. Do I need to do anything else?', a: 'Yes. At 148 Wh it is over 100 Wh, so you must get your airline\'s approval before the flight, and you may carry at most two. It can never go in checked baggage. I was stopped at security because I had not asked.', by: 'Marketa customer (Tomo)' },
        ja: { q: '出品者は機内持ち込みOKと言っていますが、ほかに必要なことはありますか？', a: 'あります。148Whで100Whを超えるので、搭乗前に航空会社の承認が必要で、持ち込みは2個までです。お預け荷物には入れられません。私は申請していなかったので保安検査で止められました。', by: 'マルケタ購入者（とも）' } },
      { date: '2026-06-11', votes: 33,
        en: { q: 'Can it charge a laptop?', a: 'No. The maximum output is 22.5 W, which is for phones, tablets and small devices.', by: 'BrightDeal Trading' },
        ja: { q: 'ノートPCを充電できますか？', a: 'いいえ。最大出力は22.5Wで、スマホ・タブレット・小型機器向けです。', by: 'ブライトディール商事' } },
      { date: '2026-07-03', votes: 21,
        en: { q: 'How long does it take to charge fully?', a: 'About 11 hours with a USB-C charger of 18 W or more, and about 18 hours through micro-USB. We recommend charging it overnight.', by: 'BrightDeal Trading' },
        ja: { q: '満充電まで何時間かかりますか？', a: '18W以上のUSB-C充電器で約11時間、micro-USBで約18時間です。一晩かけての充電をおすすめします。', by: 'ブライトディール商事' } },
      { date: '2026-09-15', votes: 18,
        en: { q: 'Can I return it if I opened it and no longer need it?', a: 'Change-of-mind returns are accepted only unopened, within 30 days, with ¥880 return shipping paid by the customer. For defective items, please message us and we will send a prepaid label within 2 business days.', by: 'BrightDeal Trading' },
        ja: { q: '開封後に不要になった場合、返品できますか？', a: 'お客様都合の返品は未開封品のみ、30日以内に承ります（返送料880円はお客様負担）。不良品の場合はメッセージでご連絡いただければ、2営業日以内に返送用伝票をお送りします。', by: 'ブライトディール商事' } },
    ],
    similar: ['kestrel-27k', 'ampora-go-20k', 'ampora-slim-10k'],
    fbt: ['voltx-pods', 'drizzle-pro'],
    alsoViewed: ['kestrel-27k', 'ampora-go-20k', 'ampora-slim-10k', 'voltx-pods', 'drizzle-pro', 'northpine-packable'],
  },
];
