// Rice cookers (Kitchen). Same shape as kettles.mjs.
export const cluster = {
  id: 'ricecookers',
  compareRows: {
    en: ['Capacity', 'Heating type', 'Power', 'Inner pot', 'Keep warm', 'Warranty'],
    ja: ['炊飯容量', '加熱方式', '消費電力', '内釜', '保温', '保証'],
  },
};

export default [
  {
    id: 'komekko-ih',
    cat: 'kitchen',
    cluster: 'ricecookers',
    brand: { en: 'Komekko', ja: 'コメッコ' },
    seller: 'marketa',
    images: ['komekko-ih'],
    title: {
      en: 'Komekko IH Rice Cooker 5.5 Cups (1.0 L), Induction Heating, 1.7 mm Non-Stick Inner Pot, 24-Hour Keep Warm, 2 Timer Presets, Quick Cook, Brown Rice and Porridge Modes',
      ja: 'コメッコ IH炊飯器 5.5合炊き 1.0L 1.7mm厚釜 24時間保温 予約タイマー2件 早炊き 玄米 おかゆ 炊き込み 3〜5人用 KM-IH10',
    },
    short: { en: 'Komekko IH Rice Cooker 5.5-cup', ja: 'コメッコ IH炊飯器 5.5合' },
    rating: 4.4,
    ratings: 3021,
    hist: [64, 21, 7, 3, 5],
    added: '2023-08-20',
    badges: ['bestseller', 'deal'],
    coupon: { amount: 1000, en: 'Save ¥1,000 with coupon', ja: '1,000円OFFクーポン' },
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'white', name: { en: 'White', ja: 'ホワイト' }, price: 14800, list: 19800, stock: 26, ship: 'fast' },
      { id: 'black', name: { en: 'Black', ja: 'ブラック' }, price: 14800, list: 19800, stock: 4, ship: 'fast' },
    ],
    returns: {
      en: 'Returnable within 30 days of delivery: unused in its packaging for a full refund, or opened but not faulty, in like-new condition with the inner pot and all accessories, minus a 15% restocking fee. If it is faulty or damaged on arrival, return it free within 30 days; after that the 1-year Komekko warranty applies.',
      ja: 'お届けから30日以内なら返品できます。未使用・未開封品は全額返金、開封済みで故障のない商品は内釜・付属品がすべてそろった新品同様の状態に限り、返品手数料15％を差し引いて返金します。初期不良や配送中の破損は30日以内なら無料で返品でき、それ以降はコメッコのメーカー保証（1年）の対象です。',
    },
    bullets: {
      en: [
        'COOKS 0.5 TO 5.5 CUPS: a "cup" is the Japanese rice cup (1 gō = 180 mL of uncooked rice, about 150 g). 5.5 cups make about 11 rice bowls, right for a family of three to five. "1.0 L" is the size class (5.5 × 180 mL), not the amount of cooked rice.',
        'IH HEATS THE WHOLE POT: an induction coil heats the sides of the pot as well as the bottom, so rice cooks more evenly and firmer than in a microcomputer cooker with a bottom heater only. 1,180 W while cooking.',
        '1.7 MM NON-STICK INNER POT: aluminium with a fluororesin coating, with water lines for white, wash-free and brown rice and porridge. Wash with a soft sponge; no metal spoons.',
        'SEVEN MENUS: white, wash-free, quick (3 cups in about 30 min), brown rice, mixed grains, takikomi (seasoned rice) and porridge.',
        'TWO TIMERS AND 24-HOUR KEEP WARM: set rice to be ready at a chosen time up to 13 hours ahead. Keep warm lasts up to 24 hours; rice tastes best within 12.',
        '1-YEAR WARRANTY from Komekko. White and Black are identical apart from colour; the Start button is the largest and has a raised dot.',
      ],
      ja: [
        '【0.5〜5.5合炊き】1合は米用計量カップ1杯（生米180mL・約150g）。5.5合でお茶碗約11杯分、3〜5人家族にちょうどよい容量です。「1.0L」は炊飯器のサイズ区分（5.5合×180mL）で、炊き上がりの量ではありません。',
        '【IHで釜全体を加熱】底だけでなく側面からも加熱するので、底面ヒーターだけのマイコン式よりムラなく、粒立ちよく炊き上がります。炊飯時消費電力1180W。',
        '【1.7mm厚 フッ素コート内釜】アルミ製で、白米・無洗米・玄米・おかゆの水位線入り。柔らかいスポンジで洗い、金属のスプーンなどは使わないでください。',
        '【7つの炊飯メニュー】白米、無洗米、早炊き（3合約30分）、玄米、雑穀米、炊き込み、おかゆ。',
        '【予約2件・24時間保温】最大13時間先まで炊き上がり時刻を予約できます。保温は最長24時間（おいしく食べられるのは12時間以内が目安）。',
        '【メーカー保証1年】ホワイトとブラックは色以外同じです。「炊飯」ボタンはいちばん大きく、凸点付きで指で探せます。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Komekko'], ['Model', 'KM-IH10'], ['Capacity', 'White rice 0.5–5.5 cups (1.0 L class); brown rice 0.5–4 cups; porridge 0.5–1.5 cups'],
        ['Heating type', 'IH (induction heating)'], ['Power', '1,180 W cooking; about 16 Wh per hour on keep warm'],
        ['Inner pot', '1.7 mm aluminium, fluororesin non-stick coating'], ['Cooking time (3 cups white)', 'About 48 min standard; about 30 min quick'],
        ['Menus', 'White, wash-free, quick, brown, mixed grains, takikomi, porridge'], ['Timer', '2 presets, up to 13 h ahead'], ['Keep warm', 'Up to 24 h (best within 12 h)'],
        ['Display', 'LCD, not backlit; raised dot on the Start button'], ['Cord', '1.0 m, retractable'], ['Dimensions', '25 × 32 × 20.5 cm (W × D × H); 44 cm high with the lid open'],
        ['Weight', '4.0 kg'], ['Country of origin', 'Thailand'], ['Warranty', '1 year (manufacturer); the inner pot coating is a consumable part'],
        ['In the box', 'Rice cooker, inner pot, rice cup (180 mL), rice paddle, paddle holder, manual with recipes'],
      ],
      ja: [
        ['ブランド', 'コメッコ'], ['型番', 'KM-IH10'], ['炊飯容量', '白米0.5〜5.5合（1.0Lタイプ）、玄米0.5〜4合、おかゆ0.5〜1.5合'],
        ['加熱方式', 'IH（電磁誘導加熱）'], ['消費電力', '炊飯時1180W、保温時 約16Wh/時'],
        ['内釜', '1.7mm厚 アルミ、フッ素樹脂コーティング'], ['炊飯時間（白米3合）', '標準 約48分、早炊き 約30分'],
        ['メニュー', '白米、無洗米、早炊き、玄米、雑穀米、炊き込み、おかゆ'], ['予約タイマー', '2件、最大13時間後まで'], ['保温', '最長24時間（おいしさの目安は12時間以内）'],
        ['表示', '液晶（バックライトなし）、炊飯ボタンに凸点'], ['電源コード', '1.0m、巻き取り式'], ['サイズ', '幅25×奥行32×高さ20.5cm（ふたを開けた高さ44cm）'],
        ['重量', '約4.0kg'], ['原産国', 'タイ'], ['保証', 'メーカー保証1年（内釜のコーティングは消耗品）'],
        ['付属品', '本体、内釜、計量カップ（180mL）、しゃもじ、しゃもじホルダー、取扱説明書（レシピ付き）'],
      ],
    },
    compare: {
      en: ['5.5 cups (1.0 L)', 'IH', '1,180 W', '1.7 mm coated aluminium', 'Up to 24 h', '1 year'],
      ja: ['5.5合（1.0L）', 'IH', '1180W', '1.7mm厚 フッ素コート', '最長24時間', '1年'],
    },
    description: {
      en: [
        'The Komekko IH is a standard family rice cooker: big enough for a family of four, small enough for a narrow counter, and simple to use. Choose the menu, press Start, and in about 48 minutes you have rice that stays warm and soft until dinner.',
        'Rice cooker sizes in Japan are given in cups (gō). One cup is the 180 mL measure in the box, about 150 g of uncooked rice, and makes about two rice bowls. "5.5 cups (1.0 L)" means it cooks up to 5.5 of these cups, about 990 mL of uncooked rice. It cooks well from 0.5 cup, so one person can use it too, although a 3-cup cooker such as the Aoba Mini takes less space and costs less.',
        'Induction heating warms the whole pot rather than only the bottom, which gives more even, firmer rice than a microcomputer cooker. It is not a pressure cooker: if you want stickier, sweeter rice and softer brown rice, the Inaho Pressure IH cooks under pressure but costs more than twice as much. Steam comes straight up from the vent at the back, so leave about 30 cm of space above the cooker and do not cook under a low cupboard.',
        'After each use, wash the inner pot, the removable inner lid and the steam cap. Use the paddle provided and a soft sponge: metal utensils, scouring pads and the dishwasher damage the coating. The coating is a consumable part and is not covered by the warranty if it wears or peels; a replacement pot is available from Komekko customer support.',
        'The display is a plain LCD without a backlight, so it can be hard to read in dim light; the Start button is the largest and has a raised dot. Komekko covers the cooker for one year from purchase. Keep your Marketa order confirmation as proof of purchase.',
      ],
      ja: [
        'コメッコ IH炊飯器は、4人家族に十分な容量がありながら、狭いキッチンにも置けるスタンダードな炊飯器です。メニューを選んで「炊飯」を押せば約48分で炊き上がり、夕食まで温かくやわらかいごはんを保ちます。',
        '炊飯器の容量は「合」で表します。1合は付属の計量カップ1杯（180mL）で、生米約150g、炊き上がるとお茶碗約2杯分です。「5.5合（1.0L）」は、この計量カップで5.5杯分、生米約990mLまで炊けるという意味です。0.5合からおいしく炊けるので一人暮らしでも使えますが、場所と価格を抑えたいなら「アオバ ミニ」のような3合炊きもおすすめです。',
        'IHは底だけでなく釜全体を加熱するので、マイコン式よりもムラなく粒立ちのよいごはんになります。圧力式ではないため、もっちり甘いごはんややわらかい玄米をお求めなら、価格は倍以上ですが「いなほ 圧力IH炊飯器」が向いています。蒸気は背面の蒸気口から真上に出るため、本体の上に30cmほどすき間をあけ、低い吊り戸棚の下では使わないでください。',
        '使用後は毎回、内釜・取り外せる内ぶた・蒸気キャップを洗ってください。付属のしゃもじと柔らかいスポンジを使い、金属製の道具や研磨たわし、食器洗い乾燥機は使わないでください。コーティングは消耗品のため、摩耗やはがれは保証の対象外です。交換用の内釜はコメッコのお客様窓口でお求めいただけます。',
        '表示はバックライトなしの液晶で、暗い場所では見えにくいことがあります。「炊飯」ボタンはいちばん大きく、凸点が付いています。メーカー保証は購入日から1年間。マルケタの注文確認メールが購入証明になります。',
      ],
    },
    tables: [
      { title: { en: 'How much rice is a "cup"?', ja: '「合」とお米の量のめやす' },
        en: [
          ['Cups (gō)', 'Uncooked rice', 'Cooked rice', 'Rice bowls (150 g)', 'Suits'],
          ['1', '180 mL / about 150 g', 'About 330 g', 'About 2', '1 person, one meal'],
          ['3', '540 mL / about 450 g', 'About 1.0 kg', 'About 6–7', '2–3 people'],
          ['5.5', '990 mL / about 825 g', 'About 1.8 kg', 'About 11–12', '3–5 people'],
          ['10', '1.8 L / about 1.5 kg', 'About 3.3 kg', 'About 22', '5 or more people'],
        ],
        ja: [
          ['合数', '生米', '炊き上がり', 'お茶碗（150g）', '人数のめやす'],
          ['1合', '180mL／約150g', '約330g', '約2杯', '1人・1食分'],
          ['3合', '540mL／約450g', '約1.0kg', '約6〜7杯', '2〜3人'],
          ['5.5合', '990mL／約825g', '約1.8kg', '約11〜12杯', '3〜5人'],
          ['10合（1升）', '1.8L／約1.5kg', '約3.3kg', '約22杯', '5人以上'],
        ] },
    ],
    reviews: [
      { stars: 5, date: '2026-09-15', variant: 'white', helpful: 312, verified: true,
        en: { name: 'Yoshiko', title: 'Rice as good as my mother\'s', body: 'Replaced a 12-year-old cooker. The rice is shiny and firm, and with the timer it is ready when we get home. Family of four; I cook 4 cups every evening and there is enough for the next day\'s bento.' },
        ja: { name: 'よしこ', title: '母の炊いたごはんのよう', body: '12年使った炊飯器から買い替えました。つやがあって粒がしっかりしたごはんで、予約しておけば帰宅時に炊き上がっています。4人家族で毎晩4合炊き、翌日のお弁当の分まで足ります。' } },
      { stars: 2, date: '2026-07-19', variant: 'white', helpful: 205, verified: true,
        en: { name: 'Hideo K.', title: 'Coating peeling after ten months', body: 'Small flakes of coating came off around the 3-cup line after ten months, and I only ever used the paddle that came with it. Komekko says the coating is a consumable and not covered by the warranty, and a new pot costs ¥4,950. Disappointing at this price.' },
        ja: { name: '加藤', title: '10か月でコーティングがはがれた', body: '10か月で3合の目盛りあたりのコーティングが小さくはがれてきました。付属のしゃもじしか使っていません。コメッコに問い合わせると、コーティングは消耗品で保証対象外、新しい内釜は4,950円とのこと。この価格帯でこれは残念です。' } },
      { stars: 1, date: '2026-08-28', variant: 'black', helpful: 140, verified: true,
        en: { name: 'Ayumi', title: 'I can\'t read the display', body: 'The grey LCD has no backlight, and on the black model the button labels are dark grey on black. In the evening I cannot see which menu is selected, so I have cooked porridge by mistake twice. The white model may be easier to read. I now use a torch.' },
        ja: { name: 'あゆみ', title: '表示が読めない', body: 'グレーの液晶にバックライトがなく、ブラックはボタンの文字も黒地に濃いグレー。夜はどのメニューを選んでいるのか見えず、間違えて2回おかゆを炊きました。ホワイトのほうが見やすいかもしれません。今は懐中電灯で照らして使っています。' } },
      { stars: 4, date: '2026-09-09', variant: 'white', helpful: 83, verified: true,
        en: { name: 'Kotaro', title: 'An upgrade from the Aoba Mini', body: 'I used an Aoba Mini all through university. When my partner moved in, 3 cups was not enough once we started taking bento. The Komekko\'s rice is clearly better: even, with no hard layer at the bottom. It takes a lot more counter space, though.' },
        ja: { name: 'こうたろう', title: 'アオバ ミニからの買い替え', body: '大学時代はずっとアオバ ミニを使っていました。同居を始めてお弁当も作るようになると3合では足りず、こちらに。コメッコは明らかにおいしく、ムラがなく底が固くなることもありません。ただ、置き場所はかなり取ります。' } },
      { stars: 5, date: '2026-06-21', variant: 'white', helpful: 66, verified: true,
        en: { name: 'Fumi', title: 'Firm, separate grains', body: 'I like firm rice and this is perfect at the standard water line. No need to adjust anything.' },
        ja: { name: 'ふみ', title: '粒がしっかり', body: '硬めのごはんが好きですが、標準の水位線でちょうどいい炊き上がり。何も調整していません。' } },
      { stars: 2, date: '2026-09-02', variant: 'white', helpful: 71, verified: true,
        en: { name: 'Ken', title: 'Rice too soft and sticky for me', body: 'Even with the water exactly at the line, the rice came out soft and sticky. I now use 2–3 mm less water than the line. It took a week of experiments to get it right.' },
        ja: { name: 'けん', title: 'やわらかすぎてべたつく', body: '水位線ぴったりでも、やわらかくてべたついたごはんになりました。今は線より2〜3mm少なめにしています。ちょうどよくなるまで1週間試行錯誤しました。' } },
      { stars: 3, date: '2026-08-11', variant: 'black', helpful: 48, verified: true,
        en: { name: 'Rina', title: 'Keep warm is fine for 12 hours, not 24', body: 'After about 12 hours on keep warm the rice turns yellowish and starts to smell. The 24 hours is only on paper. Otherwise a good cooker.' },
        ja: { name: 'りな', title: '保温は12時間まで', body: '保温12時間を過ぎるとごはんが黄ばみ、においも出てきます。24時間保温はカタログ上の話だと思います。それ以外は良い炊飯器です。' } },
      { stars: 1, date: '2026-05-06', variant: 'white', helpful: 97, verified: true,
        en: { name: 'M. Sato', title: 'Steam warped my cupboard', body: 'The steam goes straight up from the vent at the back and it has warped the edge of the cupboard above. The manual says to leave 30 cm clear, which my kitchen does not have. I returned it and paid the 15% restocking fee because I had used it.' },
        ja: { name: '佐藤', title: '蒸気で戸棚が変形', body: '背面の蒸気口から真上に蒸気が出て、上の戸棚の縁が変形してしまいました。説明書には上に30cmあけるよう書いてありますが、うちのキッチンでは無理です。使用済みだったので返品手数料15％を払って返品しました。' } },
      { stars: 5, date: '2026-09-26', variant: 'black', helpful: 21, verified: true,
        en: { name: 'Shota', title: 'Chose it over the Inaho', body: 'I tasted rice from a friend\'s Inaho pressure cooker. Slightly better and chewier, but ¥25,000 more. The Komekko is 90% of the way there. I used the ¥1,000 coupon as well.' },
        ja: { name: 'しょうた', title: 'いなほと迷ってこちらに', body: '友人宅のいなほ圧力IHで炊いたごはんを食べました。少しもちもちでおいしいけれど、2万5千円高い。コメッコでも9割がたの味です。1,000円クーポンも使えました。' } },
      { stars: 4, date: '2026-07-30', variant: 'white', helpful: 35, verified: true,
        en: { name: 'Mayu', title: 'Brown rice takes a long time', body: 'Brown rice takes about 100 minutes, so I use the timer. The takikomi menu is excellent. Wash the inner lid every time or it starts to smell.' },
        ja: { name: 'まゆ', title: '玄米は時間がかかる', body: '玄米は約100分かかるので予約して炊いています。炊き込みメニューはとても優秀。内ぶたは毎回洗わないとにおってきます。' } },
      { stars: 5, date: '2026-10-01', variant: 'black', helpful: 9, verified: true,
        en: { name: 'Kai', title: 'Black looks sleek', body: 'Got one of the last black ones in the Lantern Festival Sale and it arrived the next day. Looks smart on a dark counter.' },
        ja: { name: 'かい', title: 'ブラックがかっこいい', body: '灯籠まつりセールで残りわずかのブラックを購入、翌日届きました。暗い色のカウンターによく映えます。' } },
      { stars: 4, date: '2026-04-14', variant: 'white', helpful: 29, verified: true,
        en: { name: 'Nobu', title: 'Donabe at weekends, Komekko on weekdays', body: 'I love my Kagami Kiln donabe at the weekend, but on weekdays the Komekko with its timer wins. Rice from the donabe is better, but you have to stand by the stove.' },
        ja: { name: 'のぶ', title: '週末は土鍋、平日はコメッコ', body: '週末は鏡窯の土鍋で炊くのが楽しみですが、平日は予約できるコメッコの出番。土鍋のほうがおいしいけれど、コンロの前にいないといけないので。' } },
      { stars: 2, date: '2026-09-20', variant: 'white', helpful: 54, verified: true,
        en: { name: 'Emi', title: 'Arrived with a dented pot', body: 'The inner pot had a dent in the rim and the lid did not seal, so the first cook boiled over. Marketa replaced it within two days with no fuss, but check the pot as soon as it arrives.' },
        ja: { name: 'えみ', title: '内釜がへこんで届いた', body: '内釜の縁がへこんでいてふたがきちんと閉まらず、最初の炊飯で吹きこぼれました。マルケタがすぐ2日で交換してくれましたが、届いたらまず内釜を確認してください。' } },
    ],
    qa: [
      { date: '2026-06-11', votes: 44,
        en: { q: 'What does 5.5 cups mean in litres?', a: 'The cup is the Japanese rice cup (gō), 180 mL of uncooked rice. 5.5 cups is about 990 mL of uncooked rice, which is why cookers of this size are called the "1.0 L" type. Cooked, that is about 1.8 kg of rice, or 11–12 rice bowls.', by: 'Komekko Customer Support' },
        ja: { q: '5.5合はリットルにするとどのくらいですか？', a: '1合は生米180mLです。5.5合で生米約990mLとなるため、このクラスの炊飯器は「1.0Lタイプ」と呼ばれます。炊き上がりは約1.8kg、お茶碗11〜12杯分です。', by: 'コメッコ お客様窓口' } },
      { date: '2026-07-02', votes: 19,
        en: { q: 'Can I cook just 1 cup for myself?', a: 'Yes, I cook 1 cup most days and it comes out well. The minimum is 0.5 cup. It takes nearly as long as cooking 3 cups, though.', by: 'Marketa customer (Ren)' },
        ja: { q: '1人分の1合だけでも炊けますか？', a: 'はい、ほぼ毎日1合炊いていますがおいしく炊けます。最小は0.5合です。ただ、炊飯時間は3合とあまり変わりません。', by: 'マルケタ購入者（れん）' } },
      { date: '2026-08-06', votes: 23,
        en: { q: 'Can the inner pot go in the dishwasher?', a: 'No. Dishwasher detergent and water pressure damage the coating. Please wash the inner pot, inner lid and steam cap by hand with a soft sponge.', by: 'Komekko Customer Support' },
        ja: { q: '内釜は食器洗い乾燥機で洗えますか？', a: 'いいえ。食洗機用洗剤や水圧でコーティングが傷みます。内釜・内ぶた・蒸気キャップは、柔らかいスポンジで手洗いしてください。', by: 'コメッコ お客様窓口' } },
      { date: '2026-08-29', votes: 16,
        en: { q: 'Can I buy a replacement inner pot?', a: 'Yes, from Komekko Customer Support for ¥4,950 including delivery (part number KM-P10). The coating is a consumable part, so wear or peeling after normal use is not covered by the 1-year warranty.', by: 'Komekko Customer Support' },
        ja: { q: '交換用の内釜は買えますか？', a: 'はい、コメッコお客様窓口で送料込み4,950円（品番KM-P10）でお求めいただけます。コーティングは消耗品のため、通常使用による摩耗やはがれは1年保証の対象外です。', by: 'コメッコ お客様窓口' } },
      { date: '2026-09-12', votes: 6,
        en: { q: 'How much electricity does keep warm use?', a: 'Hardly any, about 1 W. I leave it on all day.', by: 'Marketa customer (Taichi)' },
        ja: { q: '保温中の電気代はどのくらいですか？', a: 'ほとんどかかりません。1Wくらいです。一日中つけっぱなしにしています。', by: 'マルケタ購入者（たいち）' } },
    ],
    similar: ['inaho-pressure', 'aoba-mini', 'kagami-donabe'],
    fbt: ['kagami-plate-set', 'minori-ponzu-set'],
    alsoViewed: ['inaho-pressure', 'aoba-mini', 'kagami-donabe', 'hearth-kettle', 'kagami-plate-set', 'shiroshita-senbei'],
  },
  {
    id: 'aoba-mini',
    cat: 'kitchen',
    cluster: 'ricecookers',
    brand: { en: 'Aoba', ja: 'アオバ' },
    seller: 'marketa',
    images: ['aoba-mini'],
    title: {
      en: 'Aoba Mini Rice Cooker 3 Cups (0.54 L), Microcomputer Control, Compact for One or Two, Carry Handle, Quick Cook, Steam Tray, Timer, 12-Hour Keep Warm',
      ja: 'アオバ ミニ 炊飯器 3合炊き 0.54L マイコン式 一人暮らし 二人暮らし コンパクト 持ち手付き 早炊き 蒸し料理 予約 12時間保温 AB-M3',
    },
    short: { en: 'Aoba Mini Rice Cooker 3-cup', ja: 'アオバ ミニ炊飯器 3合' },
    rating: 4.1,
    ratings: 1876,
    hist: [54, 21, 11, 6, 8],
    added: '2024-02-10',
    badges: [],
    coupon: null,
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'beige', name: { en: 'Beige', ja: 'ベージュ' }, price: 5980, list: 7480, stock: 33, ship: 'fast' },
      { id: 'mint', name: { en: 'Mint', ja: 'ミント' }, price: 5980, list: 7480, stock: 15, ship: 'fast2' },
    ],
    returns: {
      en: 'Returnable within 30 days of delivery: unused in its packaging for a full refund, or opened but not faulty, in like-new condition with the inner pot, steam tray and all accessories, minus a 15% restocking fee. If it is faulty or damaged on arrival, return it free within 30 days; after that the 1-year Aoba warranty applies.',
      ja: 'お届けから30日以内なら返品できます。未使用・未開封品は全額返金、開封済みで故障のない商品は内釜・蒸しトレー・付属品がすべてそろった新品同様の状態に限り、返品手数料15％を差し引いて返金します。初期不良や配送中の破損は30日以内なら無料で返品でき、それ以降はアオバのメーカー保証（1年）の対象です。',
    },
    bullets: {
      en: [
        'SMALL BUT ENOUGH FOR ONE OR TWO: cooks 0.5 to 3 cups (Japanese rice cups of 180 mL); 3 cups makes about six rice bowls. "0.54 L" is simply 3 × 180 mL of uncooked rice.',
        'MICROCOMPUTER, NOT IH: a 350 W heater plate under the pot does the cooking. The rice is good, but less even and softer than from an IH cooker such as the Komekko IH, and at the full 3 cups the bottom layer can be firmer.',
        'CARRY IT TO THE TABLE: a fold-down handle on top, 20 cm wide and 1.8 kg, with a magnetic cord that pulls off safely if someone trips on it.',
        'FIVE MENUS: white, quick (1 cup in about 25 min), porridge, takikomi and steam. A steam tray is included for vegetables, dumplings or reheating. No brown-rice menu.',
        'TIMER AND 12-HOUR KEEP WARM: set rice to be ready up to 12 hours ahead; keeps it warm for up to 12 hours.',
        '1-YEAR WARRANTY. Beige is stocked in Springvale; Mint ships from a warehouse outside Harvest Prefecture. Both are identical apart from colour.',
      ],
      ja: [
        '【1〜2人にちょうどいい3合炊き】0.5〜3合（1合＝生米180mL）まで。3合でお茶碗約6杯分です。「0.54L」は3合×180mLのことです。',
        '【IHではなくマイコン式】内釜の下の350Wヒーターで炊き上げます。おいしく炊けますが、「コメッコ IH炊飯器」などのIH式に比べるとムラが出やすくやわらかめで、3合いっぱいでは底が固めになることがあります。',
        '【食卓に運べる持ち手付き】折りたためる持ち手付き。幅20cm・約1.8kgと軽量で、コードに足を引っかけても外れるマグネットプラグ式です。',
        '【5つのメニュー】白米、早炊き（1合約25分）、おかゆ、炊き込み、蒸し。蒸しトレー付きで、野菜や点心、温め直しにも。玄米メニューはありません。',
        '【予約タイマー・12時間保温】最大12時間先まで予約でき、炊き上がり後は最長12時間保温します。',
        '【メーカー保証1年】ベージュは春川の倉庫に在庫あり、ミントはみのり県外の倉庫から発送します。色以外の違いはありません。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Aoba'], ['Model', 'AB-M3'], ['Capacity', 'White rice 0.5–3 cups (0.54 L); takikomi up to 2 cups; porridge up to 0.5 cup'],
        ['Heating type', 'Microcomputer, bottom heater plate (not IH)'], ['Power', '350 W'], ['Inner pot', '1.0 mm aluminium, fluororesin coating'],
        ['Cooking time', '1 cup about 35 min (quick about 25 min); 3 cups about 50 min'], ['Menus', 'White, quick, porridge, takikomi, steam (no brown-rice menu)'],
        ['Timer', '1 preset, up to 12 h ahead'], ['Keep warm', 'Up to 12 h'], ['Display', 'Small LCD with backlight; water lines printed in silver inside the pot'],
        ['Cord', '1.0 m, detachable magnetic plug'], ['Dimensions', '20 × 25 × 19 cm (W × D × H, handle folded)'], ['Weight', '1.8 kg'],
        ['Colours', 'Beige, Mint'], ['Country of origin', 'China'], ['Warranty', '1 year (manufacturer)'],
        ['In the box', 'Rice cooker, inner pot, steam tray, rice cup (180 mL), rice paddle, manual'],
      ],
      ja: [
        ['ブランド', 'アオバ'], ['型番', 'AB-M3'], ['炊飯容量', '白米0.5〜3合（0.54L）、炊き込み2合まで、おかゆ0.5合まで'],
        ['加熱方式', 'マイコン式（底面ヒーター、IHではありません）'], ['消費電力', '350W'], ['内釜', '1.0mm厚 アルミ、フッ素樹脂コーティング'],
        ['炊飯時間', '1合 約35分（早炊き 約25分）、3合 約50分'], ['メニュー', '白米、早炊き、おかゆ、炊き込み、蒸し（玄米メニューなし）'],
        ['予約タイマー', '1件、最大12時間後まで'], ['保温', '最長12時間'], ['表示', '小型液晶（バックライト付き）、内釜の水位線は銀色印刷'],
        ['電源コード', '1.0m、マグネット式着脱プラグ'], ['サイズ', '幅20×奥行25×高さ19cm（持ち手収納時）'], ['重量', '約1.8kg'],
        ['カラー', 'ベージュ、ミント'], ['原産国', '中国'], ['保証', 'メーカー保証1年'],
        ['付属品', '本体、内釜、蒸しトレー、計量カップ（180mL）、しゃもじ、取扱説明書'],
      ],
    },
    compare: {
      en: ['3 cups (0.54 L)', 'Microcomputer', '350 W', '1.0 mm coated aluminium', 'Up to 12 h', '1 year'],
      ja: ['3合（0.54L）', 'マイコン式', '350W', '1.0mm厚 フッ素コート', '最長12時間', '1年'],
    },
    description: {
      en: [
        'The Aoba Mini is a small, light rice cooker for one or two people, a student room, or a second cooker for the office. It cooks up to three Japanese rice cups (gō), about six bowls of rice, and takes up about as much space as a large saucepan.',
        'It is a microcomputer cooker, not IH: a 350 W heater plate under the pot does the work and a sensor adjusts the heat. It uses less than a third of the power of an IH cooker, and the rice is good, but a little softer and less even. At the full 3 cups the bottom layer can turn firm and starchy water can bubble out of the vent; for two people who eat rice every day, cooking 2 cups at a time gives the best results.',
        'There is no brown-rice menu, and brown rice cooked on the white setting stays hard. Porridge is limited to 0.5 cup of rice, about two bowls. The steam tray sits above the rice, so you can steam vegetables or reheat frozen gyoza while 1–2 cups of rice cook; with 3 cups the tray touches the rice.',
        'Wash the inner pot and inner lid after each use with a soft sponge. The water lines inside the pot are printed in silver on the grey coating and can be hard to see; if so, measure 200 mL of water per cup of rice with a jug. Beige and Mint are identical apart from colour. Aoba covers the cooker for one year.',
      ],
      ja: [
        'アオバ ミニは、一人暮らしや二人暮らし、学生のお部屋、職場用のサブ炊飯器にぴったりの小型・軽量炊飯器です。最大3合（お茶碗約6杯分）まで炊け、大きめの片手鍋ほどのスペースに置けます。',
        'IHではなくマイコン式で、内釜の下の350Wヒーターとセンサーで火加減を調整します。消費電力はIH炊飯器の3分の1以下。おいしく炊けますが、IHに比べるとややもっちり、ムラも出やすめです。3合いっぱいに炊くと底が固くなったり、蒸気口からおねばが吹き出したりすることがあるので、毎日ごはんを食べる2人暮らしなら2合ずつ炊くのがおすすめです。',
        '玄米メニューはなく、白米モードで炊いた玄米は固いままです。おかゆは0.5合（お茶碗約2杯分）まで。蒸しトレーはごはんの上にセットでき、1〜2合のごはんを炊きながら野菜を蒸したり冷凍餃子を温めたりできます。3合のときはトレーがごはんに触れます。',
        '使用後は内釜と内ぶたを柔らかいスポンジで洗ってください。内釜の水位線はグレーのコーティングに銀色の印刷で、見えにくい場合があります。その際は計量カップで米1合につき水200mLを量ってください。ベージュとミントは色以外同じです。メーカー保証は1年間です。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-10', variant: 'beige', helpful: 198, verified: true,
        en: { name: 'Haru (student)', title: 'Perfect for my tiny room', body: 'Springvale University student with a very small room. It cooks 1 cup in 35 minutes and the steam tray does gyoza at the same time. I signed up for the Fast Student trial and it came the next day.' },
        ja: { name: 'はる（大学生）', title: '狭い部屋にぴったり', body: '春川大学の学生で、部屋がとても狭いです。1合を35分で炊けて、蒸しトレーで同時に餃子も温められます。Fast Studentの無料体験に登録したら翌日に届きました。' } },
      { stars: 2, date: '2026-08-17', variant: 'beige', helpful: 162, verified: true,
        en: { name: 'Shingo', title: 'Spits starchy water at 3 cups', body: 'At the full 3 cups, starchy water bubbles out of the steam vent and runs down the back. I have to put a towel under it. At 2 cups it is fine, so effectively it is a 2-cup cooker.' },
        ja: { name: 'しんご', title: '3合だとおねばが吹き出す', body: '3合いっぱいで炊くと、蒸気口からおねばが吹き出して背面を伝います。毎回タオルを敷いています。2合なら問題ないので、実質2合炊きです。' } },
      { stars: 5, date: '2026-07-29', variant: 'mint', helpful: 74, verified: true,
        en: { name: 'Rie', title: '3 cups comes out perfectly', body: 'I always cook the full 3 cups to last two days and have never had it boil over. Rinse the rice until the water runs clear; that is the trick.' },
        ja: { name: 'りえ', title: '3合でもきれいに炊ける', body: 'いつも2日分を3合で炊いていますが、吹きこぼれたことは一度もありません。水が透明になるまでしっかり研ぐのがコツです。' } },
      { stars: 1, date: '2026-06-09', variant: 'beige', helpful: 121, verified: true,
        en: { name: 'Gen', title: 'Hard layer at the bottom every time', body: 'Every time, the bottom layer is hard and slightly brown. Not nice crispy okoge, just dry. Probably the bottom heater. I should have spent more on the Komekko IH.' },
        ja: { name: 'げん', title: '毎回底が固くなる', body: '毎回、底の層が固くて少し茶色くなります。香ばしいおこげではなく、ただ乾いた感じ。底面ヒーターのせいだと思います。コメッコのIHにすればよかった。' } },
      { stars: 3, date: '2026-09-04', variant: 'beige', helpful: 57, verified: true,
        en: { name: 'Asami', title: 'Fine for one, but keep warm dries the rice', body: 'Rice gets dry and yellowish after about 6 hours of keep warm, even though it says 12. I freeze leftovers now. Otherwise fine for one person.' },
        ja: { name: 'あさみ', title: '一人なら十分、でも保温で乾く', body: '保温12時間とありますが、6時間ほどでごはんが乾いて黄色っぽくなります。今は残りを冷凍しています。一人暮らしならそれ以外は十分です。' } },
      { stars: 4, date: '2026-08-23', variant: 'mint', helpful: 45, verified: true,
        en: { name: 'Lily', title: 'Mint is cute; arrived Thursday', body: 'Ordered on a Monday. Mint came from outside the prefecture, so it arrived on Thursday; beige would have come the next day. Lovely colour and the rice is decent.' },
        ja: { name: 'リリー', title: 'ミントがかわいい、木曜着', body: '月曜に注文。ミントは県外の倉庫からで木曜着でした。ベージュなら翌日だったようです。色がかわいく、ごはんもまずまずです。' } },
      { stars: 2, date: '2026-05-15', variant: 'beige', helpful: 88, verified: true,
        en: { name: 'Okada', title: 'Water lines are hard to see', body: 'The water lines are printed in silver on the grey pot and in my kitchen light I cannot see them at all. I now measure water with a jug, 200 mL per cup, which works, but it should not be necessary.' },
        ja: { name: '岡田', title: '水位線が見えにくい', body: 'グレーの内釜に銀色で水位線が印刷されていて、うちの台所の照明ではまったく見えません。今は計量カップで1合につき水200mLを量っています。それで炊けますが、本来は必要ないはずです。' } },
      { stars: 5, date: '2026-09-27', variant: 'beige', helpful: 16, verified: true,
        en: { name: 'Toshi', title: 'Bought with a Corvo kettle', body: 'Bought this with the Corvo kettle for my son starting his first job. Both came the next day, together just under ¥10,000.' },
        ja: { name: 'とし', title: 'コルヴォのケトルと一緒に', body: '社会人になる息子のために、コルヴォの電気ケトルと一緒に購入。どちらも翌日届き、2つで1万円弱でした。' } },
      { stars: 4, date: '2026-04-01', variant: 'beige', helpful: 31, verified: true,
        en: { name: 'Natsu', title: 'Good office cooker', body: 'I keep it at the office for lunch. The handle makes it easy to carry to the meeting table and the magnetic cord is reassuring in a busy room.' },
        ja: { name: 'なつ', title: '職場用にちょうどいい', body: '職場に置いてお昼に使っています。持ち手があるので打ち合わせテーブルへも運びやすく、人が多い部屋でもマグネットコードなので安心です。' } },
      { stars: 1, date: '2026-07-06', variant: 'mint', helpful: 69, verified: true,
        en: { name: 'Kazu', title: 'Stopped heating after seven months', body: 'Error E2 and it stopped heating after seven months. Aoba repaired it under warranty, but it took three weeks and I had to buy a pot to cook rice in the meantime.' },
        ja: { name: 'かず', title: '7か月で加熱しなくなった', body: '7か月でE2エラーが出て加熱しなくなりました。保証で修理してもらえましたが3週間かかり、その間は鍋を買ってごはんを炊きました。' } },
      { stars: 4, date: '2026-09-21', variant: 'beige', helpful: 12, verified: true,
        en: { name: 'Momo', title: 'The donabe is better, but this is easy', body: 'I cook in a 2-gō Kagami Kiln donabe at weekends and use the Aoba on weekdays. The rice is not as good, but I can set the timer and go to work.' },
        ja: { name: 'もも', title: '土鍋にはかなわないけど手軽', body: '週末は鏡窯の2合土鍋、平日はアオバ。味は土鍋にかないませんが、予約して出勤できるのが便利です。' } },
      { stars: 3, date: '2026-08-30', variant: 'beige', helpful: 26, verified: true,
        en: { name: 'Yusuke', title: 'No brown-rice menu', body: 'Tried brown rice on the white setting and it came out hard. Then I read the specs: no brown-rice menu. My fault, but worth knowing before you buy.' },
        ja: { name: 'ゆうすけ', title: '玄米メニューがない', body: '白米モードで玄米を炊いたら固くて食べられませんでした。仕様を見たら玄米メニューなし。確認しなかった自分も悪いですが、買う前に知っておくべき点です。' } },
    ],
    qa: [
      { date: '2026-03-20', votes: 38,
        en: { q: 'Is this an IH rice cooker?', a: 'No. The Aoba Mini is a microcomputer rice cooker: a 350 W heater plate under the pot heats from the bottom and a microcomputer controls the heat. IH cookers heat the whole pot by induction, which cooks more evenly but needs over 1,000 W.', by: 'Aoba Customer Centre' },
        ja: { q: 'IH炊飯器ですか？', a: 'いいえ。アオバ ミニはマイコン式炊飯器で、内釜の下の350Wヒーターで底から加熱し、マイコンが火加減を制御します。IH式は電磁誘導で釜全体を加熱するためムラなく炊けますが、1000W以上の電力が必要です。', by: 'アオバ お客様センター' } },
      { date: '2026-05-18', votes: 21,
        en: { q: 'Is 3 cups enough for three people?', a: '3 cups makes about six bowls, so one meal for three adults with nothing left over. If you want leftovers or bento, a 5.5-cup cooker is better.', by: 'Marketa customer (Kotaro)' },
        ja: { q: '3人家族でも足りますか？', a: '3合でお茶碗約6杯なので、大人3人の1食分でちょうどなくなります。残りやお弁当の分も考えるなら5.5合炊きのほうがいいです。', by: 'マルケタ購入者（こうたろう）' } },
      { date: '2026-06-25', votes: 9,
        en: { q: 'Can I cook brown rice?', a: 'Yes, just use the white rice setting and add a bit more water.', by: 'Marketa customer (Sho)' },
        ja: { q: '玄米は炊けますか？', a: 'はい、白米モードで水を少し多めにすれば炊けます。', by: 'マルケタ購入者（しょう）' } },
      { date: '2026-07-27', votes: 27,
        en: { q: 'Is there a brown-rice setting?', a: 'No. The Aoba Mini has no brown-rice menu, and brown rice cooked on the white or quick setting will be hard even with extra water. If you eat brown rice often, we recommend a cooker with a brown-rice menu.', by: 'Aoba Customer Centre' },
        ja: { q: '玄米モードはありますか？', a: 'ございません。アオバ ミニには玄米メニューがなく、白米や早炊きモードでは水を多めにしても玄米は固く炊き上がります。玄米をよく召し上がる方には、玄米メニューのある炊飯器をおすすめします。', by: 'アオバ お客様センター' } },
      { date: '2026-09-01', votes: 12,
        en: { q: 'Is the steam tray included, and can I steam and cook rice at the same time?', a: 'Yes, it is in the box. It sits on top of the pot; I steam vegetables or frozen gyoza while 1–2 cups of rice cook. With 3 cups the tray touches the rice.', by: 'Marketa customer (Haru)' },
        ja: { q: '蒸しトレーは付属していますか？ごはんと同時に使えますか？', a: 'はい、付属しています。内釜の上にのせて使い、1〜2合のごはんを炊きながら野菜や冷凍餃子を蒸しています。3合のときはトレーがごはんに触れます。', by: 'マルケタ購入者（はる）' } },
    ],
    similar: ['komekko-ih', 'inaho-pressure', 'kagami-donabe'],
    fbt: ['corvo-kettle', 'minori-ponzu-set'],
    alsoViewed: ['komekko-ih', 'corvo-kettle', 'kagami-donabe', 'inaho-pressure', 'hearth-kettle', 'ampora-slim-10k'],
  },
  {
    id: 'inaho-pressure',
    cat: 'kitchen',
    cluster: 'ricecookers',
    brand: { en: 'Inaho', ja: 'いなほ' },
    seller: 'marketa',
    images: ['inaho-pressure'],
    title: {
      en: 'Inaho Pressure IH Rice Cooker, Variable Pressure up to 1.2 atm, 2.5 mm Five-Layer Inner Pot, 3-Year Warranty Including Inner Pot, Voice Guide, Made in Japan, 5.5 Cups (1.0 L) or 10 Cups (1.8 L)',
      ja: 'いなほ 圧力IH炊飯器 可変圧力 最大1.2気圧 2.5mm厚 5層釜 内釜も3年保証 音声ガイド 日本製 5.5合（1.0L）／1升（1.8L） 炊き分け 玄米 IN-PR10 IN-PR18',
    },
    short: { en: 'Inaho Pressure IH Rice Cooker', ja: 'いなほ 圧力IH炊飯器' },
    rating: 4.7,
    ratings: 642,
    hist: [80, 13, 3, 2, 2],
    added: '2025-09-01',
    badges: ['choice'],
    coupon: { pct: 5, member: true, en: 'Fast members: 5% off with coupon', ja: 'Fast会員限定 5%OFFクーポン' },
    variantLabel: { en: 'Capacity', ja: '炊飯容量' },
    variants: [
      { id: '5-5', name: { en: '5.5 cups (1.0 L)', ja: '5.5合（1.0L）' }, price: 39800, list: 49800, stock: 14, ship: 'fast' },
      { id: '10', name: { en: '10 cups (1.8 L)', ja: '1升（1.8L）' }, price: 44800, list: 54800, stock: 2, ship: 'fast2' },
    ],
    returns: {
      en: 'Returnable within 30 days of delivery: unused in its packaging for a full refund, or opened but not faulty, in like-new condition with the inner pot and all accessories, minus a 15% restocking fee. If it is faulty or damaged on arrival, return it free within 30 days; after that the 3-year Inaho warranty applies.',
      ja: 'お届けから30日以内なら返品できます。未使用・未開封品は全額返金、開封済みで故障のない商品は内釜・付属品がすべてそろった新品同様の状態に限り、返品手数料15％を差し引いて返金します。初期不良や配送中の破損は30日以内なら無料で返品でき、それ以降はいなほのメーカー保証（3年）の対象です。',
    },
    bullets: {
      en: [
        'PRESSURE IH FOR STICKY, SWEET RICE: induction heats the whole pot while the sealed lid raises the pressure to up to 1.2 atm, so water boils at about 105 °C and the grains cook right through. White rice can be set to 5 levels of firmness and 3 of stickiness.',
        '3-YEAR WARRANTY, INNER POT INCLUDED: peeling of the 2.5 mm five-layer pot\'s coating in normal use is covered for three years, the longest warranty among the rice cookers here.',
        'BEST FOR BROWN RICE AND MIXED GRAINS: pressure makes brown rice soft in about 70 minutes without soaking. Twelve menus, including sushi rice, porridge, takikomi and a 23-minute quick cook.',
        'TWO SIZES: 5.5 cups (1.0 L, cooks 1–5.5 cups) for 2–4 people; 10 cups (1.8 L, cooks 2–10 cups) for 5 or more, or for cooking a big batch to freeze.',
        'MORE PARTS TO WASH: the inner lid, steam cap and pressure valve come off without tools and need washing after every cook. Replace the pressure seal about every 2 years (sold separately).',
        'HIGH POWER: 1,240 W (5.5 cups) or 1,410 W (10 cups). Plug it into a wall socket on its own, not a power strip shared with a kettle.',
        'MADE IN JAPAN, WITH VOICE GUIDE: a large white-backlit display, and a voice that reads out the menu, the texture setting and the minutes left (can be switched off).',
      ],
      ja: [
        '【圧力IHで甘くもっちり】IHで釜全体を加熱しながら、密閉したふたで最大1.2気圧まで加圧。約105℃の高温で芯までふっくら炊き上げます。白米は硬さ5段階・粘り3段階で炊き分けできます。',
        '【内釜も3年保証】2.5mm厚 5層釜のコーティングのはがれも、通常使用なら3年間保証。このカテゴリでいちばん長い保証です。',
        '【玄米・雑穀米が得意】圧力の力で、玄米も浸水なしで約70分でやわらかく。すし飯、おかゆ、炊き込み、約23分の早炊きなど12メニュー。',
        '【2サイズ】5.5合（1.0L、1〜5.5合）は2〜4人向け。1升（1.8L、2〜10合）は5人以上のご家庭や、まとめて炊いて冷凍する方に。',
        '【お手入れパーツは3点】内ぶた・蒸気キャップ・圧力弁は工具なしで外せ、炊飯のたびに洗います。圧力パッキンは約2年ごとの交換がおすすめです（別売）。',
        '【消費電力が大きめ】5.5合は1240W、1升は1410W。電気ケトルなどと同じ電源タップは避け、壁のコンセントに単独で差してください。',
        '【日本製・音声ガイド付き】白色バックライトの大きな液晶表示。メニュー、炊き分けの設定、残り時間を音声でお知らせします（オフにもできます）。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Inaho'], ['Model', 'IN-PR10 (5.5 cups), IN-PR18 (10 cups)'], ['Capacity', '5.5 cups: 1–5.5 cups white rice (1.0 L); 10 cups: 2–10 cups (1.8 L)'],
        ['Heating type', 'Pressure IH, variable 1.0–1.2 atm'], ['Power', '5.5 cups: 1,240 W; 10 cups: 1,410 W'],
        ['Inner pot', '2.5 mm five-layer pot (aluminium, iron, stainless steel), fluororesin coating'],
        ['Cooking time (white, standard)', '3 cups about 52 min; quick about 23 min; brown rice about 70 min'],
        ['Menus', '12: white, wash-free, quick, eco, brown, germinated brown, mixed grains, sushi rice, takikomi, porridge, sticky rice (okowa), slow cook'],
        ['Texture settings', 'Firmness 5 levels, stickiness 3 levels (white rice)'], ['Timer', '2 presets, up to 13 h ahead'], ['Keep warm', 'Up to 40 h (best within 24 h); reheat function'],
        ['Display and voice', 'Large white-backlit LCD; voice guide with 3 volume levels or off'],
        ['Dimensions', '5.5 cups: 27 × 33 × 22 cm; 10 cups: 30 × 37 × 26 cm (W × D × H)'], ['Weight', '5.5 cups: 5.6 kg; 10 cups: 7.1 kg'],
        ['Country of origin', 'Japan'], ['Warranty', '3 years (manufacturer), including the inner pot coating'],
        ['In the box', 'Rice cooker, inner pot, rice cup (180 mL), rice paddle, paddle holder, manual, recipe book'],
      ],
      ja: [
        ['ブランド', 'いなほ'], ['型番', 'IN-PR10（5.5合）、IN-PR18（1升）'], ['炊飯容量', '5.5合：白米1〜5.5合（1.0L）／1升：白米2〜10合（1.8L）'],
        ['加熱方式', '圧力IH（可変圧力 1.0〜1.2気圧）'], ['消費電力', '5.5合：1240W／1升：1410W'],
        ['内釜', '2.5mm厚 5層釜（アルミ・鉄・ステンレス）、フッ素樹脂コーティング'],
        ['炊飯時間（白米・標準）', '3合 約52分、早炊き 約23分、玄米 約70分'],
        ['メニュー', '12種：白米、無洗米、早炊き、エコ炊飯、玄米、発芽玄米、雑穀米、すし飯、炊き込み、おかゆ、おこわ、煮込み'],
        ['炊き分け', '硬さ5段階・粘り3段階（白米）'], ['予約タイマー', '2件、最大13時間後まで'], ['保温', '最長40時間（おいしさの目安は24時間以内）、再加熱機能付き'],
        ['表示・音声', '白色バックライト付き大型液晶、音声ガイド（音量3段階・オフ可）'],
        ['サイズ', '5.5合：幅27×奥行33×高さ22cm／1升：幅30×奥行37×高さ26cm'], ['重量', '5.5合：約5.6kg／1升：約7.1kg'],
        ['原産国', '日本'], ['保証', 'メーカー保証3年（内釜のコーティングを含む）'],
        ['付属品', '本体、内釜、計量カップ（180mL）、しゃもじ、しゃもじホルダー、取扱説明書、レシピブック'],
      ],
    },
    compare: {
      en: ['5.5 cups (1.0 L) or 10 cups (1.8 L)', 'Pressure IH', '1,240 W / 1,410 W', '2.5 mm five-layer, coated', 'Up to 40 h', '3 years incl. inner pot'],
      ja: ['5.5合（1.0L）／1升（1.8L）', '圧力IH', '1240W／1410W', '2.5mm厚 5層釜', '最長40時間', '3年（内釜含む）'],
    },
    description: {
      en: [
        'The Inaho is for people who eat rice every day and want it as good as it gets without a donabe. Pressure raises the boiling point to about 105 °C, so the grains cook right through and come out glossy, sweet and slightly sticky. You can make white rice firmer or softer and more or less sticky, and the cooker remembers the setting for each menu.',
        'Brown rice is where pressure helps most: about 70 minutes, soft enough for children, with no soaking. The 23-minute quick cook is also the fastest of the cookers here. If you like very firm, separate grains, the Komekko IH or a donabe may suit you better: even on the firmest setting, pressure-cooked rice is stickier.',
        'Choosing a size: the 5.5-cup model cooks 1 to 5.5 cups and suits most households of two to four. The 10-cup model (1.8 L, called "1 shō" in Japanese) is for five or more people, or for cooking a big batch to freeze. It needs at least 2 cups to cook properly, so it is not a good choice for one person, and it is 4 cm taller and 1.5 kg heavier. The 5.5-cup is stocked in Springvale; the 10-cup ships from a warehouse outside Harvest Prefecture.',
        'Care: after each cook, wash the inner pot, the inner lid, the steam cap and the pressure valve; all come off without tools. If the lid starts to smell of rice, the seal needs a wash. Replace the pressure seal about every two years (Inaho sells it for ¥1,650). At the end of cooking the cooker releases pressure with a short hiss and a puff of steam from the top. At 1,240–1,410 W it should have its own wall socket: sharing a power strip with a kettle can trip the breaker.',
        'Inaho gives a three-year warranty that includes the coating of the inner pot in normal use; damage from metal utensils, scouring pads or the dishwasher is not covered. The voice guide reads out the menu, the texture setting and the minutes left; hold MENU for 3 seconds to change its volume or switch it off.',
      ],
      ja: [
        'いなほは、毎日ごはんを食べる方が「土鍋を使わずに最高のごはんを」と選ぶ炊飯器です。圧力で沸点を約105℃まで上げるので、お米の芯まで火が通り、つやがあって甘く、ほどよくもっちりと炊き上がります。白米は硬さと粘りを調整でき、設定はメニューごとに記憶されます。',
        '圧力の効果がいちばん出るのが玄米です。浸水なしで約70分、お子さまでも食べやすいやわらかさに炊けます。約23分の早炊きもこのカテゴリで最速です。一方、かなり硬めでパラッとしたごはんがお好みなら、コメッコのIH炊飯器や土鍋のほうが合うかもしれません。いちばん硬い設定でも、圧力炊きのごはんは粘りが出ます。',
        'サイズ選び：5.5合タイプは1〜5.5合炊きで、2〜4人のご家庭に。1升（1.8L）タイプは5人以上のご家庭や、まとめて炊いて冷凍する方向けです。最低2合からなので一人暮らしには向かず、高さは4cm、重さは1.5kgほど増えます。5.5合は春川の倉庫に在庫があり、1升はみのり県外の倉庫から発送します。',
        'お手入れ：炊飯のたびに内釜・内ぶた・蒸気キャップ・圧力弁を洗ってください。どれも工具なしで外せます。ふたからごはんのにおいがしてきたらパッキンを洗うサインです。圧力パッキンは約2年ごとの交換がおすすめです（いなほで1,650円で販売）。炊き上がり前に圧力を抜くため、「シュッ」という音とともに上部から蒸気が出ます。消費電力が1240〜1410Wと大きいため、壁のコンセントに単独でつないでください。電気ケトルと同じ電源タップで使うとブレーカーが落ちることがあります。',
        'メーカー保証は3年間で、通常使用による内釜コーティングのはがれも対象です（金属製の道具、研磨たわし、食洗機による傷みは対象外）。音声ガイドはメニュー、炊き分けの設定、残り時間を読み上げます。「メニュー」ボタンを3秒長押しすると、音量の変更やオフの設定ができます。',
      ],
    },
    tables: [
      { title: { en: '5.5 cups or 10 cups?', ja: '5.5合と1升の違い' },
        en: [
          ['', '5.5 cups (1.0 L)', '10 cups (1.8 L)'],
          ['Rice per cook', '1–5.5 cups', '2–10 cups'],
          ['Rice bowls', 'Up to about 11', 'Up to about 22'],
          ['Suits', '2–4 people', '5 or more, or batch cooking to freeze'],
          ['Power', '1,240 W', '1,410 W'],
          ['Size (W × D × H)', '27 × 33 × 22 cm', '30 × 37 × 26 cm'],
          ['Weight', '5.6 kg', '7.1 kg'],
          ['Price', '¥39,800', '¥44,800'],
          ['Ships from', 'Marketa Springvale (HRK1)', 'Marketa warehouse outside Harvest'],
        ],
        ja: [
          ['', '5.5合（1.0L）', '1升（1.8L）'],
          ['1回に炊ける量', '1〜5.5合', '2〜10合'],
          ['お茶碗', '最大約11杯', '最大約22杯'],
          ['おすすめ', '2〜4人', '5人以上、まとめ炊き・冷凍用'],
          ['消費電力', '1240W', '1410W'],
          ['サイズ（幅×奥行×高さ）', '27×33×22cm', '30×37×26cm'],
          ['重量', '約5.6kg', '約7.1kg'],
          ['価格', '39,800円', '44,800円'],
          ['発送元', 'マルケタ春川倉庫（HRK1）', 'みのり県外のマルケタ倉庫'],
        ] },
    ],
    reviews: [
      { stars: 5, date: '2026-09-16', variant: '5-5', helpful: 156, verified: true,
        en: { name: 'Michiko', title: 'Worth every yen', body: 'We eat rice twice a day. The difference from our old microcomputer cooker is huge: glossy, sweet, and still good the next morning on keep warm. And brown rice my children actually eat.' },
        ja: { name: 'みちこ', title: '値段だけの価値あり', body: 'うちは1日2回ごはんを食べます。前のマイコン式とは段違いで、つやがあって甘く、翌朝まで保温してもおいしいまま。子どもたちが玄米を食べてくれるようになりました。' } },
      { stars: 5, date: '2026-08-25', variant: '5-5', helpful: 92, verified: true,
        en: { name: 'Tadashi', title: 'The voice guide is a real help', body: 'My eyesight is poor, and the voice tells me which menu is selected and how many minutes are left. The display is bright and the numbers are big. The Komekko I looked at in a shop had a dim screen I could not read.' },
        ja: { name: 'ただし', title: '音声ガイドに助けられています', body: '目が悪いのですが、選んだメニューや残り時間を声で教えてくれます。表示も明るく数字が大きい。お店で見たコメッコは画面が暗くて読めませんでした。' } },
      { stars: 1, date: '2026-07-12', variant: '5-5', helpful: 118, verified: true,
        en: { name: 'Kenichi', title: 'Tripped the breaker every morning', body: 'It shared a power strip with our Hearth kettle and the breaker went every morning when both were on. The manual says to use its own socket, but I missed it. We had to move it to the other side of the kitchen, where there is no counter space.' },
        ja: { name: 'けんいち', title: '毎朝ブレーカーが落ちた', body: 'ハースの電気ケトルと同じ電源タップにつないでいたら、両方使う朝は毎回ブレーカーが落ちました。説明書には単独のコンセントを使うようにとありましたが、見落としていました。結局、台所の反対側に移すことになり、置き場所に困っています。' } },
      { stars: 2, date: '2026-09-07', variant: '5-5', helpful: 86, verified: true,
        en: { name: 'Ayako', title: 'Too many parts to wash', body: 'The rice is delicious, but it is the inner lid, the steam cap and the valve every single time, and the valve has a tiny rubber ring that I have already lost once. I miss my simple cooker.' },
        ja: { name: 'あやこ', title: '洗う部品が多すぎる', body: 'ごはんはおいしいのですが、毎回内ぶた・蒸気キャップ・圧力弁を洗う必要があり、弁の小さなゴムリングは一度なくしました。シンプルな炊飯器が恋しいです。' } },
      { stars: 2, date: '2026-06-03', variant: '10', helpful: 74, verified: true,
        en: { name: 'Hiroko', title: 'Too sticky for my taste', body: 'Even on the firmest setting the rice is soft and sticky. My husband likes it; I do not. For ¥44,800 I expected to be able to make firm rice.' },
        ja: { name: 'ひろこ', title: '私には粘りが強すぎる', body: 'いちばん硬い設定にしても、やわらかくて粘りのあるごはんになります。夫は気に入っていますが、私は苦手。44,800円もするなら硬めにも炊けてほしかったです。' } },
      { stars: 4, date: '2026-09-23', variant: '5-5', helpful: 41, verified: true,
        en: { name: 'Gaku', title: 'The firm setting fixed it for me', body: 'At first it was too sticky, but firmness 5 and stickiness 1 gives exactly the firm rice I like. Give it a week of trying the settings before you decide.' },
        ja: { name: 'がく', title: '硬め設定で解決', body: '最初は粘りが強すぎると思いましたが、硬さ5・粘り1にしたら好みの硬めのごはんになりました。判断する前に1週間ほど設定を試してみてください。' } },
      { stars: 1, date: '2026-05-20', variant: '10', helpful: 63, verified: true,
        en: { name: 'Ishida', title: 'Arrived with a cracked hinge cover', body: 'The hinge cover was cracked in the box. I sent photos the day it came and Marketa replaced it, but the replacement took three days because the 10-cup ships from outside Harvest. The rice is good, but one star for the experience.' },
        ja: { name: '石田', title: 'ヒンジカバーが割れて届いた', body: '箱を開けたらヒンジカバーが割れていました。届いた日に写真を送りマルケタが交換してくれましたが、1升タイプはみのり県外からの発送なので交換品まで3日かかりました。ごはんはおいしいですが、この経験で星1つ。' } },
      { stars: 3, date: '2026-08-09', variant: '5-5', helpful: 37, verified: true,
        en: { name: 'Sachi', title: 'Great rice, loud hiss', body: 'At the end of cooking it lets the pressure out with a loud hiss and a jet of steam. It scares my cat every time. The rice is excellent.' },
        ja: { name: 'さち', title: 'ごはんは最高、でも音が大きい', body: '炊き上がり前に「シューッ」と大きな音とともに蒸気が噴き出します。毎回猫がびっくりして逃げます。ごはんはとてもおいしいです。' } },
      { stars: 5, date: '2026-09-19', variant: '5-5', helpful: 28, verified: true,
        en: { name: 'Ryota', title: 'Almost donabe level', body: 'I also have a Kagami Kiln donabe. The donabe still wins for texture and okoge, but the Inaho gets 90% of the way and I can set a timer. Bought it with the Fast member 5% coupon.' },
        ja: { name: 'りょうた', title: 'ほぼ土鍋レベル', body: '鏡窯の土鍋も持っています。食感とおこげはやはり土鍋の勝ちですが、いなほは9割がたの味で、しかも予約ができます。Fast会員限定の5％クーポンで購入しました。' } },
      { stars: 4, date: '2026-07-24', variant: '10', helpful: 22, verified: true,
        en: { name: 'Big family dad', title: 'The 10-cup for a family of six', body: 'We cook 7 cups every evening. It is heavy and tall, but nothing else does brown rice this well. Only buy the 10-cup if you really cook a lot; it does not do well with small amounts.' },
        ja: { name: '大家族パパ', title: '6人家族で1升タイプ', body: '毎晩7合炊いています。重くて背も高いですが、玄米がこれほどおいしく炊ける炊飯器はほかにありません。少量だとうまく炊けないので、本当にたくさん炊く家庭だけ1升タイプを選んでください。' } },
      { stars: 5, date: '2026-10-02', variant: '5-5', helpful: 5, verified: true,
        en: { name: 'Eri', title: 'Upgraded from the Komekko', body: 'Gave our Komekko IH to my sister. The Inaho is clearly better for brown rice, and the 3-year warranty covers the pot coating, which the Komekko\'s did not.' },
        ja: { name: 'えり', title: 'コメッコからの買い替え', body: 'コメッコのIH炊飯器は妹に譲りました。玄米はいなほが明らかに上。3年保証で内釜のコーティングまで対象なのも、コメッコにはなかった安心です。' } },
      { stars: 4, date: '2026-09-29', variant: '5-5', helpful: 9, verified: false,
        en: { name: 'Kitchen Nerd', title: 'Excellent but pricey', body: 'Excellent rice, but ¥39,800 is a lot. Wait for a sale or use the member coupon.' },
        ja: { name: '台所オタク', title: '最高だけど高い', body: 'ごはんは最高ですが、39,800円は高いです。セールか会員クーポンを狙うのがおすすめ。' } },
    ],
    qa: [
      { date: '2026-01-15', votes: 41,
        en: { q: 'Is the inner pot really covered for 3 years?', a: 'Yes. Peeling or blistering of the coating in normal use is covered for 3 years from purchase. Damage from metal utensils, scouring pads or a dishwasher is not covered.', by: 'Inaho Customer Support' },
        ja: { q: '内釜も本当に3年保証ですか？', a: 'はい。通常のご使用によるコーティングのはがれ・ふくれは、購入日から3年間保証いたします。金属製の道具、研磨たわし、食器洗い乾燥機による傷みは対象外です。', by: 'いなほ お客様相談室' } },
      { date: '2026-03-09', votes: 8,
        en: { q: 'Can I cook 1 cup in the 10-cup model?', a: 'Yes, I do it sometimes and it is fine.', by: 'Marketa customer (Masaru)' },
        ja: { q: '1升タイプで1合だけ炊けますか？', a: 'はい、たまに炊きますが問題ありません。', by: 'マルケタ購入者（まさる）' } },
      { date: '2026-04-02', votes: 24,
        en: { q: 'What is the minimum amount for the 10-cup model?', a: '2 cups. Below that the water level is too low for the pressure control, and the rice can be dry at the edges. If you often cook 1 cup, please choose the 5.5-cup model, which cooks 1 to 5.5 cups.', by: 'Inaho Customer Support' },
        ja: { q: '1升タイプは最低何合から炊けますか？', a: '2合からです。それより少ないと水位が低く圧力制御がうまく働かず、周りが乾いた炊き上がりになることがあります。1合炊きが多い方は、1〜5.5合炊ける5.5合タイプをお選びください。', by: 'いなほ お客様相談室' } },
      { date: '2026-06-14', votes: 19,
        en: { q: 'Can I turn the voice guide off or make it quieter?', a: 'Yes. Hold MENU for 3 seconds to open the settings and choose Voice: off, low, medium or high. The finish melody follows the same setting.', by: 'Inaho Customer Support' },
        ja: { q: '音声ガイドはオフにしたり小さくしたりできますか？', a: 'はい。「メニュー」ボタンを3秒長押しして設定画面を開き、音声を「切・小・中・大」から選べます。炊き上がりのメロディも同じ設定になります。', by: 'いなほ お客様相談室' } },
      { date: '2026-08-21', votes: 13,
        en: { q: 'Is it really made in Japan?', a: 'Yes, the label on the bottom and the box both say Made in Japan.', by: 'Marketa customer (Michiko)' },
        ja: { q: '本当に日本製ですか？', a: 'はい、本体底面のラベルにも箱にも「日本製」と書かれています。', by: 'マルケタ購入者（みちこ）' } },
    ],
    similar: ['komekko-ih', 'kagami-donabe', 'aoba-mini'],
    fbt: ['kagami-plate-set', 'minori-ponzu-set'],
    alsoViewed: ['komekko-ih', 'kagami-donabe', 'hearth-kettle', 'kagami-plate-set', 'aoba-mini', 'tetsuyu-gooseneck'],
  },
  {
    id: 'kagami-donabe',
    cat: 'kitchen',
    cluster: 'ricecookers',
    brand: { en: 'Kagami Kiln', ja: '鏡窯' },
    seller: 'kagami',
    images: ['kagami-donabe', 'kagami-donabe-2'],
    title: {
      en: 'Kagami Kiln Springvale Ware Donabe Rice Pot with Double Lid, Handmade in Springvale, Gas Flame Only, 2-gō or 3-gō, Iron Black Glaze or Made-to-Order Amber Glaze',
      ja: '鏡窯 春川焼 土鍋 ごはん鍋 二重蓋 手作り 直火（ガス火）専用 2合炊き／3合炊き 黒釉 飴釉（受注生産） 日本製',
    },
    short: { en: 'Kagami Kiln Donabe Rice Pot', ja: '鏡窯 春川焼 ごはん土鍋' },
    rating: 4.8,
    ratings: 214,
    hist: [86, 9, 2, 1, 2],
    added: '2022-11-03',
    badges: [],
    coupon: null,
    variantLabel: { en: 'Size and glaze', ja: 'サイズ・釉薬' },
    variants: [
      { id: '2go', name: { en: '2-gō, iron black', ja: '2合 黒釉' }, price: 12100, list: null, stock: 9, ship: 'kagami' },
      { id: '3go', name: { en: '3-gō, iron black', ja: '3合 黒釉' }, price: 14300, list: null, stock: 3, ship: 'kagami' },
      { id: '3go-amber', name: { en: '3-gō, amber glaze (made to order)', ja: '3合 飴釉（受注生産）' }, price: 15400, list: null, stock: 99, ship: 'kagami-mto' },
    ],
    returns: {
      en: 'Sold and shipped by Kagami Kiln, so the kiln\'s policy applies: change-of-mind returns only for unused pots within 14 days of delivery, with return shipping paid by you, and the made-to-order amber glaze cannot be returned. If it arrives broken, send photos within 48 hours for a replacement or refund without sending it back; variation in glaze, colour and size and small pinholes are the nature of handmade ware, not defects.',
      ja: '鏡窯が販売・発送する商品のため、鏡窯の返品条件が適用されます。お客様都合の返品はお届けから14日以内の未使用品に限り、返送料はお客様のご負担です。受注生産の飴釉は返品できません。配送中に割れていた場合は、48時間以内に写真を添えてご連絡いただければ、返送不要で交換または返金いたします。釉薬・色・サイズの個体差や小さなピンホールは手仕事の特徴であり、不良ではありません。',
    },
    bullets: {
      en: [
        'HANDMADE IN SPRINGVALE by fourth-generation potter Kagami Sōichi at Kagami Kiln (founded 1891) in the Kamagaoka pottery district, from heat-resistant clay. Each pot varies slightly in glaze and size.',
        'DOUBLE LID, NO BOIL-OVER: the inner lid holds the steam in and the heavy outer lid adds light pressure, so you do not need to watch the pot. Rice is ready in about 35 minutes after a 30-minute soak.',
        'GAS FLAME ONLY: for gas hobs and portable gas stoves. Not for IH, electric radiant or halogen hobs, the microwave, the oven or the dishwasher.',
        'SEASON IT BEFORE FIRST USE: simmer rice porridge in the pot for about an hour to seal the clay (medome). Instructions are included; allow an evening.',
        'TWO SIZES: 2-gō (21 cm across, for 1–2 people) and 3-gō (24 cm, for 2–4 people). The 3-gō also comes in an amber glaze, made to order in 3–4 weeks.',
        'SOLD AND SHIPPED BY KAGAMI KILN: dispatched within 2 business days, wrapped in recycled paper; shipping is free on Kagami Kiln orders of ¥5,000 or more, so free on every pot here. Not eligible for Marketa Fast.',
      ],
      ja: [
        '【春川・鏡窯の手づくり】1891年創業、窯ヶ丘の鏡窯で、四代目・鏡 宗一が耐熱性の高い土からひとつずつ作っています。釉薬の色やサイズには一点ごとに個体差があります。',
        '【二重蓋で吹きこぼれにくい】中蓋が蒸気を閉じ込め、重みのある外蓋がほどよい圧力をかけるので、火の番はほとんど不要。30分浸水したあと、約35分で炊き上がります。',
        '【ガス火専用】ガスコンロ・カセットコンロでお使いください。IH、電気・ハロゲンヒーター、電子レンジ、オーブン、食器洗い乾燥機には使えません。',
        '【はじめに目止めを】初めて使う前に、おかゆを約1時間炊いて土の目をふさぐ「目止め」が必要です。手順書付き。ひと晩みておいてください。',
        '【2サイズ】2合（直径21cm、1〜2人向け）と3合（直径24cm、2〜4人向け）。3合は飴釉もお選びいただけます（受注生産、3〜4週間）。',
        '【鏡窯が販売・発送】2営業日以内に再生紙で包んで発送します。鏡窯の商品5,000円以上で送料無料のため、この土鍋はどれも送料無料です。マルケタFastの対象外です。',
      ],
    },
    specs: {
      en: [
        ['Maker', 'Kagami Kiln (Kagami Sōichi), Springvale ware'], ['Capacity', '2-gō: 1–2 cups of rice; 3-gō: 1–3 cups (1 cup = 180 mL)'],
        ['Size (diameter × height with lid)', '2-gō: 21 × 15 cm; 3-gō: 24 × 17 cm (handles included)'], ['Weight', '2-gō: about 2.4 kg; 3-gō: about 3.1 kg (with lids)'],
        ['Material', 'Heat-resistant Springvale clay with petalite'], ['Glaze', 'Iron black (2-gō, 3-gō); amber (3-gō, made to order)'],
        ['Lid', 'Double lid (inner and outer), steam hole in the outer lid'], ['Heat source', 'Gas flame only (gas hob, portable gas stove)'],
        ['Not suitable for', 'IH, electric and halogen hobs, microwave, oven, dishwasher'],
        ['Cooking time', 'Soak 30 min; medium heat about 10–12 min (2-gō) or 12–14 min (3-gō); rest 20 min'],
        ['Before first use', 'Season with rice porridge (medome), about 1 hour plus cooling'], ['Keep warm', 'No heater; stays warm for about 1 hour with the lids on'],
        ['Made in', 'Japan (Springvale, Harvest Prefecture)'], ['Warranty', 'No manufacturer warranty; breakage in delivery replaced (report within 48 h)'],
        ['In the box', 'Pot, inner lid, outer lid, care and recipe leaflet (Japanese and English), gift box'],
      ],
      ja: [
        ['作り手', '鏡窯（鏡 宗一）、春川焼'], ['炊飯容量', '2合：1〜2合／3合：1〜3合（1合＝180mL）'],
        ['サイズ（直径×蓋込みの高さ）', '2合：21×15cm／3合：24×17cm（持ち手含む）'], ['重量', '2合：約2.4kg／3合：約3.1kg（蓋込み）'],
        ['素材', 'ペタライト入り耐熱陶土（春川産）'], ['釉薬', '黒釉（2合・3合）、飴釉（3合・受注生産）'],
        ['蓋', '二重蓋（中蓋・外蓋）、外蓋に蒸気穴'], ['熱源', 'ガス火専用（ガスコンロ・カセットコンロ）'],
        ['使用不可', 'IH、電気・ハロゲンヒーター、電子レンジ、オーブン、食器洗い乾燥機'],
        ['炊飯時間', '浸水30分、中火 約10〜12分（2合）／約12〜14分（3合）、蒸らし20分'],
        ['初回のお手入れ', 'おかゆで目止め（約1時間＋冷ます時間）'], ['保温', 'ヒーターなし（蓋をしておけば約1時間温かい）'],
        ['生産国', '日本（みのり県春川市）'], ['保証', 'メーカー保証なし。配送中の破損は交換（48時間以内にご連絡）'],
        ['付属品', '土鍋本体、中蓋、外蓋、お手入れ・レシピのしおり（日本語・英語）、化粧箱'],
      ],
    },
    compare: {
      en: ['2 or 3 cups (gō)', 'Gas flame (clay pot)', 'None (gas only)', 'Springvale ware clay, double lid', 'No (stays warm about 1 h)', 'Delivery breakage only'],
      ja: ['2合／3合', 'ガス火（土鍋）', 'なし（ガス火専用）', '春川焼の土鍋、二重蓋', 'なし（約1時間は温かい）', '配送中の破損のみ'],
    },
    description: {
      en: [
        'Kagami Kiln has made pots in the Kamagaoka pottery district of Springvale since 1891. This donabe is thrown and glazed by hand by Kagami Sōichi, the fourth-generation potter, from a heat-resistant clay that takes the heat slowly and spreads it evenly. Rice cooked in it has firm, glossy grains and, if you like, a thin crisp layer of okoge at the bottom.',
        'How to cook: rinse the rice and soak it in the pot with the water for 30 minutes (20 in summer). Put on both lids and heat over a medium flame for 10–14 minutes, until steam comes steadily out of the hole in the outer lid. Turn off the heat and leave it for 20 minutes without lifting the lid. For okoge, turn the flame up high for the last 30 seconds before switching off.',
        'Before first use, season the pot (medome): fill it 70% with water, add a bowl of cooked rice, simmer on a low flame for about an hour until it becomes porridge, leave it to cool overnight, then discard the porridge, wash and dry. This fills the fine pores of the clay so it does not seep or crack. If water ever seeps through the base, season it again.',
        'Care: gas flame only, never IH or the microwave. Never heat it empty or with the outside wet, do not put a hot pot on a cold or wet surface, and do not pour cold water into it while it is hot. Wash by hand with a soft sponge without soaking, and let the unglazed base dry upside down for a full day (two in the rainy season) before putting it away; storing it damp causes mould. Fine crackle lines in the glaze are normal.',
        'The 2-gō suits one or two people; the 3-gō suits a family, or two people who want leftovers for bento. The amber glaze is a warm honey brown and is made after you order, so it ships in 3–4 weeks (around early November) and cannot be returned. Kagami Kiln wraps each pot in recycled paper and dispatches within 2 business days; if it arrives broken, send photos within 48 hours.',
      ],
      ja: [
        '鏡窯は1891年から春川・窯ヶ丘で器を作り続けてきた窯元です。この土鍋は四代目・鏡 宗一が、ゆっくり熱を蓄えてむらなく伝える耐熱陶土を使い、ろくろ成形から施釉まで手作業で仕上げています。粒が立ってつやのあるごはんが炊け、お好みで底に薄く香ばしいおこげも作れます。',
        '炊き方：お米を研ぎ、分量の水と一緒に土鍋に入れて30分浸水させます（夏は20分）。中蓋と外蓋をして中火にかけ、外蓋の穴から蒸気が勢いよく出てくるまで10〜14分加熱します。火を止め、蓋を開けずに20分蒸らせば完成です。おこげを作るときは、火を止める前の30秒だけ強火にしてください。',
        '初めて使う前に「目止め」をしてください。土鍋の7分目まで水を入れ、ごはんをお茶碗1杯加えて弱火で約1時間、おかゆ状になるまで煮ます。そのままひと晩冷ましてからおかゆを捨て、洗って乾かします。土の細かな穴がふさがり、水漏れやひび割れを防ぎます。底から水がしみ出すようになったら、もう一度目止めをしてください。',
        'お手入れ：ガス火専用です。IHや電子レンジには絶対に使わないでください。空焚きや外側がぬれたままの加熱はせず、熱い土鍋を冷たい場所やぬれた場所に置いたり、熱いうちに冷水を注いだりしないでください。洗うときは浸け置きせず柔らかいスポンジで手洗いし、釉薬のかかっていない底を上にして丸1日（梅雨時は2日）乾かしてからしまってください。湿ったまましまうとカビの原因になります。釉薬の細かな貫入（ひび模様）は異常ではありません。',
        '2合は1〜2人、3合はご家族や、お弁当の分まで炊きたい2人暮らしに。飴釉は温かみのあるはちみつ色で、ご注文を受けてから制作するため発送まで3〜4週間（お届けは11月上旬ごろ）かかり、返品はできません。鏡窯が一点ずつ再生紙で包み、2営業日以内に発送します。万一割れて届いた場合は48時間以内に写真をお送りください。',
      ],
    },
    tables: [
      { title: { en: 'Sizes and cooking guide', ja: 'サイズと炊き方のめやす' },
        en: [
          ['', '2-gō', '3-gō'],
          ['Rice', '1–2 cups (gō)', '1–3 cups (gō)'],
          ['Water', '1 cup: 200 mL; 2 cups: 400 mL', '1.5 cups: 300 mL; 3 cups: 600 mL'],
          ['Medium heat after a 30-min soak', 'About 10–12 min, until steam comes out of the lid hole', 'About 12–14 min, until steam comes out of the lid hole'],
          ['Rest (heat off, lids on)', '20 min', '20 min'],
          ['Rice bowls', 'Up to about 4', 'Up to about 6'],
          ['Diameter / weight', '21 cm / 2.4 kg', '24 cm / 3.1 kg'],
          ['Price', '¥12,100', '¥14,300 (amber glaze ¥15,400, made to order)'],
        ],
        ja: [
          ['', '2合', '3合'],
          ['お米', '1〜2合', '1〜3合'],
          ['水', '1合：200mL／2合：400mL', '1.5合：300mL／3合：600mL'],
          ['中火の時間（30分浸水後）', '約10〜12分（蓋の穴から蒸気が出るまで）', '約12〜14分（蓋の穴から蒸気が出るまで）'],
          ['蒸らし（火を止め蓋をしたまま）', '20分', '20分'],
          ['お茶碗', '最大約4杯', '最大約6杯'],
          ['直径／重さ', '21cm／約2.4kg', '24cm／約3.1kg'],
          ['価格', '12,100円', '14,300円（飴釉は15,400円・受注生産）'],
        ] },
    ],
    reviews: [
      { stars: 5, date: '2026-09-20', variant: '2go', helpful: 64, verified: true,
        en: { name: 'Mariko', title: 'The best rice I have ever made', body: 'Glossy, every grain separate, and the okoge is wonderful. Seasoning it with porridge took an evening, but it was easy following the leaflet.' },
        ja: { name: 'まりこ', title: '今まででいちばんおいしいごはん', body: 'つやつやで一粒一粒が立っていて、おこげも最高です。おかゆでの目止めはひと晩かかりましたが、しおりのとおりにやれば簡単でした。' } },
      { stars: 3, date: '2026-08-16', variant: '2go', helpful: 39, verified: true,
        en: { name: 'Shun-chan', title: 'Seasoning was a whole evening of mess', body: 'The seasoning porridge boiled over twice and the kitchen smelled of burnt rice. Once that was done the rice is great, but it is not a weekday pot: 30 minutes of soaking plus 35 minutes of cooking and resting.' },
        ja: { name: 'しゅんちゃん', title: '目止めがひと晩がかりで大変', body: '目止めのおかゆが2回吹きこぼれ、台所が焦げたにおいに。それが済めばごはんはおいしいですが、浸水30分＋炊飯と蒸らしで35分なので、平日向きではありません。' } },
      { stars: 1, date: '2026-07-04', variant: '3go', helpful: 58, verified: true,
        en: { name: 'Junko', title: 'Cracked on the third use', body: 'A crack appeared across the base after the third use. The kiln asked how I had used it: I had put it straight from the stove onto a wet cloth. They said that was thermal shock, not a defect, so no replacement. Fair enough, but that warning should be in big letters.' },
        ja: { name: 'じゅんこ', title: '3回目でひびが入った', body: '3回目の使用後、底にひびが入りました。窯元に使い方を聞かれ、火から下ろしてすぐぬれ布巾の上に置いたと伝えると、急な温度変化によるもので不良ではないとのことで交換は不可。仕方ないですが、その注意はもっと大きく書いてほしいです。' } },
      { stars: 2, date: '2026-06-12', variant: '2go', helpful: 47, verified: true,
        en: { name: 'Ken T.', title: 'Mould on the base', body: 'I put it away after drying it for half a day and found black mould spots on the unglazed base a week later. I had to boil it out and season it again. You need to dry it for at least a full day, two in the rainy season.' },
        ja: { name: 'けんT', title: '底にカビが生えた', body: '半日乾かしてしまったら、1週間後に釉薬のない底に黒いカビが。煮沸して目止めをやり直しました。最低でも丸1日、梅雨時は2日は乾かす必要があります。' } },
      { stars: 5, date: '2026-09-02', variant: '3go-amber', helpful: 21, verified: true,
        en: { name: 'Hana', title: 'Worth the four-week wait', body: 'I ordered the amber glaze in early August and it arrived at the start of September. A beautiful honey colour with darker drips. It is not returnable, so I studied the photos for a long time first, but it is lovely.' },
        ja: { name: 'はな', title: '4週間待つ価値あり', body: '8月上旬に飴釉を注文し、9月の初めに届きました。はちみつのような色に濃い流れ模様がとてもきれい。返品できないので写真をじっくり見てから決めましたが、大満足です。' } },
      { stars: 2, date: '2026-08-29', variant: '2go', helpful: 52, verified: true,
        en: { name: 'Takeshi', title: 'Useless on my IH hob', body: 'I did not notice it is gas only, and my flat has an IH hob. I tried an IH heat plate: it took 40 minutes and the kiln told me that is not recommended and breakage on a plate is not covered. I could not return it because I had used it. Read the title carefully.' },
        ja: { name: 'たけし', title: 'IHでは使えなかった', body: 'ガス火専用だと気づかずに購入。うちはIHコンロです。IH用の熱伝導プレートを試したら40分かかり、窯元からはおすすめできない、プレート使用での破損は対象外と言われました。使ってしまったので返品もできません。商品名をよく読んでください。' } },
      { stars: 5, date: '2026-09-25', variant: '3go', helpful: 18, verified: true,
        en: { name: 'Chiyo', title: 'Ordered with the plate set', body: 'I ordered it with the Kagami Kiln set of five plates. Shipping was free, and it came two days later, carefully wrapped in recycled paper. The 3-gō is right for the four of us.' },
        ja: { name: 'ちよ', title: '取り皿セットと一緒に', body: '鏡窯の5枚組の取り皿と一緒に注文しました。送料無料で、2日後に再生紙で丁寧に包まれて届きました。4人家族には3合がちょうどいいです。' } },
      { stars: 4, date: '2026-07-21', variant: '2go', helpful: 26, verified: true,
        en: { name: 'Yuto', title: '2-gō is enough for two', body: 'There are two of us and 2 cups makes four bowls. It fits our small stove nicely and is lighter to lift.' },
        ja: { name: 'ゆうと', title: '2人なら2合で十分', body: '2人暮らしで、2合炊けばお茶碗4杯分。小さいコンロにもちょうどよく、持ち上げるのも軽いです。' } },
      { stars: 4, date: '2026-05-30', variant: '2go', helpful: 31, verified: true,
        en: { name: 'Aki & Sho', title: '2-gō is too small if you take bento', body: 'For two people who also take bento to work, the 2-gō is too small and we end up cooking twice. Get the 3-gō.' },
        ja: { name: 'あき＆しょう', title: 'お弁当も作るなら2合は小さい', body: '2人ともお弁当を持っていくので、2合では足りず1日2回炊くことに。3合をおすすめします。' } },
      { stars: 5, date: '2026-08-07', variant: '3go', helpful: 15, verified: true,
        en: { name: 'Kiyoshi', title: 'Better than our Inaho', body: 'We also have an Inaho pressure cooker. For flavour and texture, the donabe wins; the Inaho is for weekdays.' },
        ja: { name: 'きよし', title: 'いなほよりおいしい', body: 'いなほの圧力IH炊飯器も持っていますが、味と食感は土鍋の勝ち。いなほは平日用です。' } },
      { stars: 4, date: '2026-09-13', variant: '2go', helpful: 12, verified: true,
        en: { name: 'Ume', title: 'Glaze differs from the photo', body: 'Mine is more brown than black, with a few tiny pinholes. The kiln explained this is normal for handmade ware. It cooks perfectly, so I am happy with it.' },
        ja: { name: 'うめ', title: '写真と釉薬の色が違う', body: '届いたものは黒というより茶色に近く、小さなピンホールもいくつか。窯元からは手作りならではの個体差との説明でした。炊き上がりは完璧なので満足しています。' } },
      { stars: 5, date: '2026-09-28', variant: '2go', helpful: 9, verified: true,
        en: { name: 'Camper', title: 'Great on a camping stove', body: 'Used it on a portable gas stove at the Moonview campsite. The 2-gō fits well; the 3-gō would cover the gas canister, which the kiln warns against.' },
        ja: { name: 'キャンパー', title: 'カセットコンロでも活躍', body: '月見のキャンプ場でカセットコンロにのせて使いました。2合ならちょうどよいサイズ。3合だとボンベの上まで覆ってしまうので、窯元も注意を呼びかけています。' } },
    ],
    qa: [
      { date: '2026-02-11', votes: 47,
        en: { q: 'Can I use it on an IH hob with a heat-diffuser plate?', a: 'We do not recommend it. A plate heats the clay unevenly and slowly, which can crack the pot, and cracks from use on IH plates are not covered. This donabe is made for a gas flame only.', by: 'Kagami Kiln (seller)' },
        ja: { q: 'IH用の熱伝導プレートを使えばIHでも使えますか？', a: 'おすすめしておりません。プレートでは加熱にむらが出て時間もかかり、ひび割れの原因になります。IHプレートでのご使用による破損は対象外です。この土鍋はガス火専用です。', by: '鏡窯（販売者）' } },
      { date: '2026-04-05', votes: 6,
        en: { q: 'Can I reheat leftover rice in the microwave in it?', a: 'I do it all the time with leftover rice and it is fine.', by: 'Marketa customer (Ichiro)' },
        ja: { q: '残ったごはんを土鍋ごと電子レンジで温められますか？', a: 'いつもそうしていますが問題ありません。', by: 'マルケタ購入者（いちろう）' } },
      { date: '2026-05-21', votes: 29,
        en: { q: 'Is it safe in the microwave or dishwasher?', a: 'No. A microwave heats the water held in the clay unevenly and can crack the pot, and dishwasher detergent and long soaking let water into the unglazed base. Please move leftover rice to another bowl to reheat it, and wash the pot by hand.', by: 'Kagami Kiln (seller)' },
        ja: { q: '電子レンジや食洗機は使えますか？', a: '使えません。電子レンジでは土にしみ込んだ水分が不均一に加熱され、割れの原因になります。食洗機の洗剤や長時間の浸け置きは、釉薬のない底に水がしみ込む原因になります。残ったごはんは別の器に移して温め、土鍋は手洗いしてください。', by: '鏡窯（販売者）' } },
      { date: '2026-07-14', votes: 22,
        en: { q: 'What is the difference between the amber glaze and the iron black?', a: 'Only the glaze; the size is the same 3-gō. The amber is made after you order and ships in 3–4 weeks. As a made-to-order item it cannot be returned for change of mind, but breakage in delivery is still replaced.', by: 'Kagami Kiln (seller)' },
        ja: { q: '飴釉と黒釉の違いは何ですか？', a: '釉薬の違いのみで、サイズは同じ3合です。飴釉はご注文後に制作し、3〜4週間で発送します。受注生産品のためお客様都合の返品はお受けできませんが、配送中の破損は交換いたします。', by: '鏡窯（販売者）' } },
      { date: '2026-08-02', votes: 17,
        en: { q: 'Can I use it on a portable gas stove?', a: 'Yes. The 2-gō (21 cm) is fine on most portable stoves. With the 3-gō (24 cm), check your stove\'s maximum pot size: a pot that covers the gas canister cover can overheat the canister.', by: 'Kagami Kiln (seller)' },
        ja: { q: 'カセットコンロでも使えますか？', a: 'はい。2合（直径21cm）はたいていのカセットコンロでお使いいただけます。3合（直径24cm）は、お使いのコンロの使用できる鍋のサイズをご確認ください。ボンベカバーを覆うような鍋はボンベが過熱するおそれがあります。', by: '鏡窯（販売者）' } },
      { date: '2026-09-18', votes: 10,
        en: { q: 'Can you gift-wrap it?', a: 'Yes. Gift wrapping is ¥330 and noshi paper is free. Choose them at checkout or write your request in the order message.', by: 'Kagami Kiln (seller)' },
        ja: { q: 'ギフト包装はできますか？', a: 'はい。ギフト包装は330円、熨斗は無料で承ります。ご注文時に選択いただくか、注文メッセージにご希望をお書きください。', by: '鏡窯（販売者）' } },
    ],
    similar: ['inaho-pressure', 'komekko-ih', 'aoba-mini'],
    fbt: ['kagami-plate-set', 'kagami-mug-pair'],
    alsoViewed: ['kagami-plate-set', 'kagami-tea-set', 'kagami-sake-set', 'inaho-pressure', 'kagami-mug-pair', 'komekko-ih'],
  },
];
