// Harukawa ware tableware (Home). Same shape as kettles.mjs.
export const cluster = {
  id: 'tableware',
  compareRows: {
    en: ['Pieces', 'Capacity / size', 'Glaze', 'Microwave', 'Dishwasher', 'Made by'],
    ja: ['内容', '容量・サイズ', '釉薬', '電子レンジ', '食洗機', '製造'],
  },
};

export default [
  {
    id: 'kagami-mug-pair',
    cat: 'home',
    cluster: 'tableware',
    brand: { en: 'Kagami Kiln', ja: '鏡窯' },
    seller: 'kagami',
    images: ['kagami-mug-pair'],
    title: {
      en: 'Kagami Kiln Harukawa Ware Mug Pair, 300 mL Each, Handmade Stoneware, Yuzu-Yellow Ash Glaze and Indigo, Microwave and Dishwasher Safe, Gift Box, Made in Harukawa, Japan',
      ja: '鏡窯 春川焼 ペアマグカップ 300ml 柚子灰釉×藍釉 手作り 陶器 電子レンジ・食洗機対応 化粧箱入り 結婚祝い 贈り物 日本製',
    },
    short: { en: 'Kagami Kiln Mug Pair', ja: '鏡窯 春川焼 ペアマグ' },
    rating: 4.7,
    ratings: 388,
    hist: [80, 13, 3, 2, 2],
    added: '2023-04-10',
    badges: ['choice'],
    coupon: null,
    variantLabel: { en: 'Style', ja: 'タイプ' },
    variants: [
      { id: 'yellow-indigo', name: { en: 'Yellow & indigo', ja: '柚子黄×藍' }, price: 6600, list: null, stock: 7, ship: 'kagami' },
      { id: 'indigo-pair', name: { en: 'Two indigo', ja: '藍×藍' }, price: 6600, list: null, stock: 16, ship: 'kagami' },
      { id: 'engraved', name: { en: 'Pair with names engraved (made to order)', ja: '名入れペア（受注制作）' }, price: 7900, list: null, stock: 20, ship: 'kagami-mto' },
    ],
    returns: {
      en: 'Sold and shipped by Kagami Kiln: unused items can be returned within 14 days of delivery, and you pay return shipping for a change of mind. Breakage in delivery: send photos within 48 hours for a replacement or refund without sending the item back. Variation in glaze, colour and size is not a defect, and the engraved pair is made to order and cannot be returned.',
      ja: '鏡窯が販売・発送する商品です。未使用品に限り、到着後14日以内なら返品できます（お客様都合の場合、返送料はご負担ください）。配送中の破損は48時間以内に写真をお送りいただければ、返送不要で交換または返金いたします。釉薬・色・大きさの個体差は不良ではありません。名入れペアは受注制作のため返品できません。',
    },
    bullets: {
      en: [
        'GENUINE HARUKAWA WARE: thrown on the wheel and glazed by hand at Kagami Kiln, a family pottery in Harukawa’s Kamagaoka district since 1891. Each mug has the kiln’s 鏡 stamp on its unglazed foot.',
        'TWO HARUKAWA GLAZES: the soft yuzu-yellow ash glaze is made with ash from pruned yuzu branches from the Kagami River valley; the deep indigo glaze turns brown at the rim. Choose one of each, or two indigo.',
        'NO TWO ALIKE: each mug differs a little from the photos and from its partner: height ±3 mm, capacity ±15 mL, glaze tone, drips, iron specks and tiny pinholes. These are the nature of handmade ware, not defects.',
        '300 mL EACH filled to the brim (about 250 mL to a comfortable level), a standard mug of coffee or tea. 8.5 cm across, 9 cm tall, about 320 g each.',
        'EVERYDAY SAFE: microwave and dishwasher OK, but we recommend hand washing to keep the ash glaze’s soft sheen and protect the rims. Not for the oven or a direct flame.',
        'IN TIME FOR THE LANTERN FESTIVAL: the two in-stock styles ship within 2 business days and arrive Thu 8 – Fri 9 Oct with free shipping (Kagami Kiln orders of ¥5,000 or more). The engraved pair is made to order and arrives in early November.',
        'READY TO GIVE: in a paper gift box with a leaflet on Harukawa ware in English and Japanese. Noshi paper free; gift wrapping ¥330.',
      ],
      ja: [
        '【正真正銘の春川焼】1891年創業、春川・窯ヶ丘の家族経営の窯元「鏡窯」が、ろくろで成形し一つずつ手で釉掛けしています。素地のままの高台には鏡窯の「鏡」印。',
        '【春川焼を代表する2つの釉薬】やわらかな黄色の柚子灰釉は、鏡川流域の柚子畑で剪定した枝の灰から作ります。深い藍釉は口縁で茶色に変化します。柚子黄と藍のペア、または藍2客からお選びください。',
        '【ひとつとして同じものはありません】写真とも、相方のマグとも少しずつ違います（高さ±3mm、容量±15mL、色味、釉だれ、鉄粉、小さなピンホールなど）。手作りの器ならではの個性で、不良ではありません。',
        '【容量300mL】満水で300mL（実用量は約250mL）。コーヒーやお茶にちょうどよい標準サイズです。直径8.5×高さ9cm、1客約320g。',
        '【普段使いに】電子レンジ・食洗機OK。灰釉のしっとりした風合いを保ち、口縁の欠けを防ぐため、手洗いをおすすめします。オーブン・直火は使えません。',
        '【灯籠まつりに間に合います】在庫のある2タイプは2営業日以内に発送し、10月8日（木）〜9日（金）にお届け。鏡窯でのご注文5,000円以上で送料無料です。名入れペアは受注制作のため11月上旬のお届けとなります。',
        '【贈り物に】春川焼の由来を日英で紹介したしおり付きの化粧箱入り。のし無料、ギフトラッピングは330円。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Kagami Kiln (Harukawa, Minori Prefecture)'], ['Potter', 'Kagami Sōichi (4th generation) and workshop'], ['Ware', 'Harukawa ware (春川焼), stoneware'],
        ['Clay', 'Kamagaoka clay (iron-rich, from the Kagami River terraces)'], ['Glaze', 'Yuzu-yellow ash glaze, indigo glaze (lead-free)'],
        ['Capacity', '300 mL each to the brim (about 250 mL in use), ±15 mL'], ['Dimensions', 'Ø8.5 × H9 cm, 11.5 cm wide with handle (±3 mm)'],
        ['Weight', 'About 320 g each'], ['Microwave', 'Yes'], ['Dishwasher', 'Yes (hand wash recommended)'], ['Oven / direct flame', 'No'],
        ['Firing', 'Gas kiln, reduction firing at about 1,250 °C'], ['Engraving (made-to-order style)', 'Up to 6 Japanese characters or 10 letters per mug'],
        ['Country of origin', 'Japan (Harukawa)'], ['Warranty', 'No manufacturer warranty; breakage in delivery handled by the seller (report within 48 hours)'],
        ['In the box', '2 mugs, paper gift box, Harukawa ware leaflet (English/Japanese)'],
      ],
      ja: [
        ['ブランド', '鏡窯（みのり県春川市）'], ['作り手', '4代目 鏡 宗一と工房スタッフ'], ['種類', '春川焼（陶器）'],
        ['土', '窯ヶ丘の土（鏡川の河岸段丘で採れる鉄分の多い土）'], ['釉薬', '柚子灰釉、藍釉（無鉛）'],
        ['容量', '各300mL（満水）、実用量約250mL、個体差±15mL'], ['サイズ', '直径8.5×高さ9cm、取っ手を含む幅11.5cm（個体差±3mm）'],
        ['重量', '1客約320g'], ['電子レンジ', '使用可'], ['食洗機', '使用可（手洗い推奨）'], ['オーブン・直火', '使用不可'],
        ['焼成', 'ガス窯・約1,250℃で還元焼成'], ['名入れ（受注制作タイプ）', '1客につき漢字・かな6文字、または英字10文字まで'],
        ['原産国', '日本（春川市）'], ['保証', 'メーカー保証なし（配送中の破損は到着後48時間以内のご連絡で出品者が対応）'],
        ['付属品', 'マグ2客、化粧箱、春川焼のしおり（日英）'],
      ],
    },
    compare: {
      en: ['2 mugs', '300 mL each', 'Yuzu-yellow ash + indigo (handmade)', 'Yes', 'Yes (hand wash recommended)', 'Kagami Kiln, Harukawa'],
      ja: ['マグ2客', '各300mL', '柚子灰釉＋藍釉（手作り）', '可', '可（手洗い推奨）', '鏡窯（春川）'],
    },
    tables: [
      {
        title: { en: 'Which style?', ja: 'タイプ別のお届けと返品' },
        en: [
          ['Style', 'Price', 'Availability', 'Arrives if ordered today', 'Returns'],
          ['Yellow & indigo', '¥6,600', 'In stock (7 left)', 'Thu 8 – Fri 9 Oct', 'Unused, within 14 days'],
          ['Two indigo', '¥6,600', 'In stock', 'Thu 8 – Fri 9 Oct', 'Unused, within 14 days'],
          ['Names engraved (yellow & indigo)', '¥7,900', 'Made to order, 3–4 weeks', 'About 2–9 Nov', 'Not returnable'],
        ],
        ja: [
          ['タイプ', '価格', '在庫', '本日ご注文の場合のお届け', '返品'],
          ['柚子黄×藍', '6,600円', '在庫あり（残り7点）', '10月8日（木）〜9日（金）', '未使用品・到着後14日以内'],
          ['藍×藍', '6,600円', '在庫あり', '10月8日（木）〜9日（金）', '未使用品・到着後14日以内'],
          ['名入れペア（柚子黄×藍）', '7,900円', '受注制作（3〜4週間）', '11月2日〜9日頃', '返品不可'],
        ],
      },
    ],
    description: {
      en: [
        'Harukawa ware (春川焼) has been made on the hills of Kamagaoka, above the Kagami River, since the 1630s, when the lords of Harukawa Castle opened a domain kiln there to supply the castle. When the domain kiln closed in the 1870s, its potters set up their own family workshops. Kagami Kiln was founded in 1891 and is run today by the fourth generation, Kagami Sōichi, with his daughter and two apprentices.',
        'Each mug starts as iron-rich Kamagaoka clay that has been aged for a year. It is thrown on the wheel, trimmed when leather-hard and given a hand-pulled handle, then dried for about two weeks, bisque-fired at 800 °C, dipped in glaze by hand and fired again at about 1,250 °C in a gas kiln. In reduction firing the flame draws oxygen out of the glaze, which is why the yuzu-yellow ash glaze can come out anywhere from straw yellow to greenish yellow, and why the indigo ranges from blue-black to a brighter blue with brown edges. The foot is left unglazed and shows the reddish clay.',
        'Because every mug is made by hand, yours will not match the photos or each other exactly. Pinholes (tiny dots in the glaze), dark iron specks and glaze drips are part of the character of ash glaze. The mugs are microwave- and dishwasher-safe, but we recommend washing by hand with a soft sponge: strong dishwasher detergent slowly dulls ash glaze, and rims can chip if they knock against other dishes. The unglazed foot can scratch glass or lacquered tables, so use a coaster or smooth the foot with fine sandpaper. Soaking the mugs in water for 10 minutes before first use helps stop coffee and tea staining the pinholes.',
        'In the engraved pair (yellow & indigo), a name or short word is carved by hand into the side of each mug before glazing, so the glaze pools in the letters. Write the names in the order notes, up to 6 Japanese characters or 10 letters per mug; Kagami Kiln will message you within 2 business days to confirm the layout. Each pair is made from the clay up, so it takes 3–4 weeks and arrives in early November, after the Lantern Festival. Once production starts, engraved pairs cannot be cancelled or returned.',
        'The mugs are wrapped in recycled paper and packed in a paper gift box. Noshi paper is free (御祝, 結婚御祝, 内祝, 御礼 and others; write the inscription and name in the order notes) and gift wrapping is ¥330. Kagami Kiln ships its own orders: ¥700, free on Kagami Kiln orders of ¥5,000 or more, so both in-stock styles ship free. These orders are not Marketa Fast-eligible and arrive separately from items shipped by Marketa.',
      ],
      ja: [
        '春川焼は、1630年代に春川城の御用窯として、鏡川を見下ろす窯ヶ丘の丘陵に開かれたのが始まりです。明治初期に御用窯が閉じたあと、陶工たちはそれぞれ家族で窯を構えました。鏡窯は1891年（明治24年）の創業。現在は4代目の鏡 宗一が、娘と2人の弟子とともに器を作っています。',
        '原料は鉄分を多く含む窯ヶ丘の土。1年寝かせた土をろくろで挽き、半乾きのうちに削って形を整え、手で引いた取っ手を付けます。約2週間乾燥させて800℃で素焼きし、一つずつ手で釉薬に浸してから、ガス窯で約1,250℃の還元焼成を行います。還元焼成では炎が釉薬から酸素を奪うため、柚子灰釉は麦わら色から青みがかった黄色まで、藍釉は黒に近い藍から口縁が茶色に抜ける明るい藍まで、焼き上がりに幅が出ます。高台には釉薬を掛けず、赤みのある土肌をそのまま見せています。',
        '手作りのため、お届けするマグは写真とも、2客同士でも同じではありません。ピンホール（釉薬の小さな穴）や黒い鉄粉、釉だれは灰釉ならではの景色です。電子レンジ・食洗機に対応していますが、やわらかいスポンジでの手洗いをおすすめします。食洗機用の強い洗剤は少しずつ灰釉のつやを曇らせ、ほかの食器とぶつかると口縁が欠けることがあります。素地のままの高台はガラスや漆塗りのテーブルを傷つけることがあるため、コースターを使うか、目の細かい紙やすりで高台をならしてください。使い始める前に10分ほど水に浸けておくと、コーヒーや紅茶の色がピンホールに染みにくくなります。',
        '名入れペア（柚子黄×藍）は、釉掛けの前に1客ずつ手彫りでお名前や短い言葉を入れるため、文字に釉薬がたまって浮かび上がります。ご注文時の備考欄に、1客につき漢字・ひらがな・カタカナ6文字まで、または英字10文字までご記入ください。2営業日以内に鏡窯から配置確認のメッセージをお送りします。土から作るため制作に3〜4週間かかり、お届けは11月上旬。灯籠まつりには間に合いません。制作開始後のキャンセル・返品はお受けできません。',
        '再生紙で包み、化粧箱に入れてお送りします。のしは無料（御祝・結婚御祝・内祝・御礼など。表書きとお名前は備考欄へ）、ギフトラッピングは330円です。鏡窯からの直送で、送料は700円、鏡窯でのご注文5,000円以上で無料（在庫のある2タイプはどちらも送料無料）。マルケタFastの対象外のため、マルケタ発送の商品とは別にお届けします。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-26', variant: 'yellow-indigo', helpful: 142, verified: true,
        en: { name: 'Haruka', title: 'Wedding gift, and they loved it', body: 'Bought these for a friend’s wedding with the free 結婚御祝 noshi. They arrived two days later, wrapped in recycled paper inside a sturdy box with a leaflet about Harukawa ware in English and Japanese, which was perfect because the groom is from Canada. The yellow one is a soft, almost buttery yellow with tiny green drips near the foot.' },
        ja: { name: 'はるか', title: '結婚祝いに。とても喜ばれました', body: '友人の結婚祝いに、無料の「結婚御祝」ののしを付けて注文。2日後に届きました。再生紙でていねいに包まれ、しっかりした箱に春川焼のしおり（日英）が入っていて、新郎がカナダの方なのでちょうど良かったです。柚子黄はバターのようなやわらかい黄色で、高台の近くに小さな緑の釉だれがありました。' } },
      { stars: 2, date: '2026-09-14', variant: 'yellow-indigo', helpful: 118, verified: true,
        en: { name: 'Mariko', title: 'The yellow is nothing like the photo', body: 'The photo shows a bright yuzu yellow. Mine is a muddy greenish brown with a grey patch on one side. I asked Kagami Kiln to exchange it and they politely said glaze variation is the nature of handmade ware, not a defect, so my only option was to return it unused at my own cost within 14 days. To be fair the policy is on the page, but the photos should show the range of colours you might get.' },
        ja: { name: '真理子', title: '黄色が写真とまったく違う', body: '写真は明るい柚子色なのに、届いたのはくすんだ緑がかった茶色で、片側に灰色のむらがありました。交換をお願いしたところ、釉薬の個体差は手作りの器の特性で不良ではない、とていねいな返事。14日以内に未使用・送料自己負担で返品するしかありませんでした。ページに書いてはあるのですが、どのくらい色に幅があるのか写真で見せてほしいです。' } },
      { stars: 5, date: '2026-08-22', variant: 'indigo-pair', helpful: 64, verified: true,
        en: { name: 'Ken', title: 'The variation is the whole point', body: 'I don’t understand the complaints about colour. My two indigo mugs are completely different: one almost black, one with a bright blue pool in the bottom and a brown rim. That is what you pay for with handmade. If you want two identical mugs, buy factory ones.' },
        ja: { name: 'けん', title: '個体差こそが魅力', body: '色のことで低評価をつける人の気持ちがわかりません。うちの藍2客はまったく別物で、一つはほぼ黒、もう一つは底に明るい藍がたまり口縁が茶色。それが手作りの良さです。まったく同じものが欲しいなら工場製を買えばいいと思います。' } },
      { stars: 1, date: '2026-07-30', variant: 'yellow-indigo', helpful: 97, verified: true,
        en: { name: 'Aiko N.', title: 'Rim chipped after six weeks in the dishwasher', body: 'The listing says dishwasher OK, so I put them in every day. After six weeks the indigo one has a small chip on the rim and the yellow glaze has gone dull and slightly rough. The kiln told me hand washing is recommended. At ¥6,600 for two I expected them to survive the dishwasher.' },
        ja: { name: 'あいこ', title: '食洗機で6週間、口縁が欠けました', body: '食洗機OKと書いてあったので毎日入れていたら、6週間で藍のほうの口縁が小さく欠け、柚子黄はつやがなくなってざらつくようになりました。窯元からは手洗いを推奨していますとの返事。2客で6,600円なら食洗機くらい耐えてほしかったです。' } },
      { stars: 1, date: '2026-09-30', variant: 'engraved', helpful: 83, verified: true,
        en: { name: 'Takuya', title: 'Engraved pair won’t arrive for our anniversary', body: 'Our anniversary is on the Saturday of the Lantern Festival. I ordered the engraved pair on 28 Sep without noticing it is made to order, and confirmed the names when the kiln messaged me the next day. Only then did I see the delivery date: early November. I asked to switch to the in-stock pair, but production had started and engraved items cannot be cancelled or returned. My mistake, but the delivery date should be much more visible.' },
        ja: { name: '拓也', title: '名入れは記念日に間に合わず', body: '結婚記念日が灯籠まつりの土曜日で、9月28日に名入れペアを注文。受注制作だと気づかず、翌日窯元から届いたメッセージで名前も確定してしまいました。そこで初めてお届けが11月上旬だと知り、在庫品への変更をお願いしましたが、すでに制作に入っていて名入れ品はキャンセル・返品不可とのこと。自分の確認不足ですが、お届け日はもっと目立つように書いてほしいです。' } },
      { stars: 3, date: '2026-08-05', variant: 'yellow-indigo', helpful: 45, verified: true,
        en: { name: 'Nao', title: 'Lovely, but smaller and heavier than I thought', body: '300 mL is to the very brim; leaving room for milk it holds about 230 mL. They are also heavy, about 320 g each, so my mother, who has arthritis in her hands, finds the yellow one tiring to lift when full. Beautiful glaze though.' },
        ja: { name: 'なお', title: 'きれいだけど、思ったより小さくて重い', body: '300mLは縁までいっぱいの量で、ミルクを入れる余裕を残すと230mLくらいです。1客約320gと重めなので、手にリウマチのある母は柚子黄のほうを満杯で持ち上げるのがつらいそうです。釉薬はとてもきれいです。' } },
      { stars: 4, date: '2026-09-08', variant: 'yellow-indigo', helpful: 132, verified: true,
        en: { name: 'Junko', title: 'Not the same thing as the Tokiya mugs', body: 'Last year I bought the Tokiya “Harukawa-style” mugs from BrightDeal for ¥2,480, thinking they were Harukawa ware. My mother, who grew up in Kamagaoka, turned one over and laughed: glossy, perfectly even, and a Made in China sticker on the base. These Kagami Kiln mugs are the real thing, with the kiln stamp on the unglazed foot and an ash glaze that changes in the light. Four stars only because the yellow one has two pinholes that collect coffee.' },
        ja: { name: 'じゅんこ', title: 'トキヤのマグとは別物です', body: '去年、ブライトディールでトキヤの「春川焼風」マグを2,480円で買い、春川焼だと思い込んでいました。窯ヶ丘育ちの母が裏返して笑ったのを覚えています。つやつやで均一、底には「中国製」のシール。こちらの鏡窯のマグは本物で、素地の高台に窯印があり、灰釉は光の加減で表情が変わります。柚子黄にピンホールが2つあってコーヒーがたまるので星4つ。' } },
      { stars: 5, date: '2026-06-18', variant: 'indigo-pair', helpful: 22, verified: true,
        en: { name: 'Sota', title: 'Fine in the microwave', body: 'I reheat coffee in these twice a day, one minute in the microwave, no problem, and the handle stays cool enough to hold. I wash them by hand and after a year they still look new.' },
        ja: { name: 'そうた', title: 'レンジでも問題なし', body: '1日2回、コーヒーをレンジで1分温め直していますが問題なし。取っ手も持てる程度の熱さです。手洗いで1年使って、まだ新品のようです。' } },
      { stars: 2, date: '2026-05-27', variant: 'indigo-pair', helpful: 51, verified: true,
        en: { name: 'K. Fujimoto', title: 'The unglazed foot scratched our table', body: 'The bottom is rough unglazed clay and left fine scratches on our glass dining table within days. The leaflet suggests sandpaper or a coaster, which works, but I wish I had known before buying.' },
        ja: { name: '藤本', title: '高台でテーブルに傷が', body: '底がざらざらの素地のままで、数日でガラスのダイニングテーブルに細かい傷がつきました。しおりにある紙やすりやコースターで解決はしましたが、買う前に知りたかったです。' } },
      { stars: 5, date: '2025-11-12', variant: 'engraved', helpful: 58, verified: true,
        en: { name: 'Emi', title: 'Engraved pair was worth the wait', body: 'Ordered in mid-October for my parents’ 40th wedding anniversary. Kagami Kiln messaged the next day to check the kanji, and the mugs arrived on 8 November. The names are carved under the glaze, so the indigo pools in the letters. Exactly as promised; just order a month ahead.' },
        ja: { name: 'えみ', title: '待った甲斐がありました', body: '両親のルビー婚のお祝いに10月半ばに注文。翌日、窯元から漢字の確認の連絡があり、11月8日に届きました。名前が釉薬の下に彫られていて、文字に藍がたまってきれいです。説明どおり。1か月前には注文しておきましょう。' } },
      { stars: 3, date: '2026-09-20', variant: 'yellow-indigo', helpful: 37, verified: true,
        en: { name: 'Taro', title: 'Gift box arrived creased, mugs fine', body: 'The outer carton was dented at one corner and the gift box inside was creased, so I could not give it as it was. The mugs were fine thanks to the thick paper wrapping, and since nothing was broken it did not count as breakage. If it is a gift, check it the day it arrives: the kiln only takes breakage reports within 48 hours.' },
        ja: { name: 'たろう', title: '化粧箱がつぶれていた（マグは無事）', body: '外箱の角がへこんでいて、中の化粧箱も折れ目がつき、そのままでは贈れない状態でした。厚い紙で包まれていたのでマグは無事で、割れていない以上「破損」にはなりませんでした。贈り物なら届いた日に確認を。破損の連絡は48時間以内しか受け付けてもらえません。' } },
      { stars: 4, date: '2026-10-02', variant: 'yellow-indigo', helpful: 6, verified: true,
        en: { name: 'Lily', title: 'For our festival guests, with a Corvo kettle', body: 'Ordered with a Corvo kettle for the guest room before the Lantern Festival. The kettle came the next day from Marketa and the mugs two days later in a separate box from the kiln. Lovely pair; the indigo is darker than the photo.' },
        ja: { name: 'りり', title: 'まつりのお客さま用に、コルヴォのケトルと', body: '灯籠まつりに泊まりに来る客用に、コルヴォの電気ケトルと一緒に注文。ケトルはマルケタから翌日、マグは窯元から別便でその2日後に届きました。すてきなペアです。藍は写真より濃いめ。' } },
    ],
    qa: [
      { date: '2026-09-29', votes: 34,
        en: { q: 'If I order this week, will they arrive before the Lantern Festival?', a: 'The yellow & indigo and two-indigo pairs are in stock: we ship within 2 business days, and they reach Harukawa city 2–4 days after you order, well before 10–11 Oct. The engraved pair is made to order (3–4 weeks), so it will not be in time.', by: 'Kagami Kiln' },
        ja: { q: '今週注文すれば灯籠まつりまでに届きますか？', a: '柚子黄×藍と藍×藍は在庫がございます。2営業日以内に発送し、春川市内ならご注文から2〜4日でお届けしますので、10月10日・11日には十分間に合います。名入れペアは受注制作（3〜4週間）のため間に合いません。', by: '鏡窯' } },
      { date: '2026-07-15', votes: 41,
        en: { q: 'Are they really microwave and dishwasher safe?', a: 'Yes. Both glazes are fired at about 1,250 °C and contain no metal, so the microwave is fine. They can go in the dishwasher too, but we recommend hand washing: alkaline dishwasher detergent slowly dulls ash glaze, and rims can chip if they knock together. Please do not use them in an oven or on a flame.', by: 'Kagami Kiln (Kagami Sōichi)' },
        ja: { q: '本当に電子レンジ・食洗機で使えますか？', a: 'はい。どちらの釉薬も約1,250℃で焼成しており金属を含まないため、電子レンジは問題ありません。食洗機もお使いいただけますが、アルカリ性の洗剤で灰釉のつやが徐々に落ちることや、器同士がぶつかって口縁が欠けることがあるため、手洗いをおすすめしています。オーブン・直火ではお使いにならないでください。', by: '鏡窯（鏡 宗一）' } },
      { date: '2026-03-10', votes: 12,
        en: { q: 'Is the Tokiya Harukawa-style mug pair a cheaper line from the same kiln?', a: 'I think so. The colours look the same and it’s much cheaper.', by: 'Marketa customer (Yoshi)' },
        ja: { q: 'トキヤの「春川焼風」ペアマグは、同じ窯元の廉価版ですか？', a: 'たぶんそうだと思います。色が同じで、ずっと安いので。', by: 'マルケタ購入者（よし）' } },
      { date: '2026-03-12', votes: 57,
        en: { q: 'Are Tokiya mugs made by Kagami Kiln?', a: 'No, and an earlier answer here is mistaken. We have no connection with Tokiya. Their mugs are factory-made in China and are not Harukawa ware. Everything from Kagami Kiln is made in our workshop in Kamagaoka and has the 鏡 stamp on the foot.', by: 'Kagami Kiln' },
        ja: { q: 'トキヤのマグは鏡窯で作っているのですか？', a: 'いいえ。上のご回答は誤りです。当窯はトキヤとは一切関係がございません。トキヤのマグは中国の工場製で、春川焼ではありません。鏡窯の器はすべて窯ヶ丘の工房で作り、高台に「鏡」の印を入れています。', by: '鏡窯' } },
      { date: '2026-08-20', votes: 19,
        en: { q: 'How many characters can I engrave? Can I use kanji?', a: 'Up to 6 Japanese characters (kanji, hiragana or katakana) or 10 letters per mug. Write them in the order notes and we will message you within 2 business days with the layout. Once you confirm, production starts and the order cannot be cancelled or returned.', by: 'Kagami Kiln' },
        ja: { q: '名入れは何文字までですか？漢字も入りますか？', a: '1客につき漢字・ひらがな・カタカナで6文字まで、または英字10文字までです。ご注文時の備考欄にご記入いただければ、2営業日以内に配置案をメッセージでお送りします。ご確認後に制作を始めるため、それ以降はキャンセル・返品はできません。', by: '鏡窯' } },
    ],
    similar: ['kagami-tea-set', 'kagami-plate-set', 'tokiya-mug-pair'],
    fbt: ['kagami-plate-set', 'minori-marmalade-set'],
    alsoViewed: ['tokiya-mug-pair', 'kagami-tea-set', 'kagami-plate-set', 'kagami-sake-set', 'kagami-donabe', 'corvo-kettle'],
  },
  {
    id: 'kagami-tea-set',
    cat: 'home',
    cluster: 'tableware',
    brand: { en: 'Kagami Kiln', ja: '鏡窯' },
    seller: 'kagami',
    images: ['kagami-tea-set'],
    title: {
      en: 'Kagami Kiln Harukawa Ware Kyusu Tea Set, Side-Handle Teapot 360 mL with Built-In Ceramic Strainer and 2 Yunomi Cups 150 mL, Celadon Crackle Glaze, Handmade in Harukawa, Japan',
      ja: '鏡窯 春川焼 急須 湯呑み セット 横手急須 360ml 陶製茶こし（ささめ） 湯呑 150ml×2客 青磁貫入 手作り 化粧箱入り 日本製',
    },
    short: { en: 'Kagami Kiln Kyusu Tea Set', ja: '鏡窯 青磁貫入 急須セット' },
    rating: 4.6,
    ratings: 97,
    hist: [76, 14, 5, 2, 3],
    added: '2024-02-01',
    badges: [],
    coupon: null,
    variantLabel: { en: 'Set', ja: 'セット内容' },
    variants: [
      { id: 'celadon', name: { en: 'Teapot + 2 yunomi, celadon crackle', ja: '急須＋湯呑2客（青磁貫入）' }, price: 11000, list: null, stock: 2, ship: 'kagami' },
    ],
    returns: {
      en: 'Sold and shipped by Kagami Kiln: unused items can be returned within 14 days of delivery, with return shipping paid by you for a change of mind. Breakage in delivery: send photos within 48 hours for a replacement or refund without returning it. Crackle lines, tea staining in the crackle and glaze variation are not defects.',
      ja: '鏡窯が販売・発送する商品です。未使用品に限り到着後14日以内なら返品できます（お客様都合の返送料はご負担ください）。配送中の破損は48時間以内に写真をお送りいただければ、返送不要で交換または返金いたします。貫入やそこへのお茶の色の染み込み、釉薬の個体差は不良ではありません。',
    },
    bullets: {
      en: [
        'A COMPLETE SET FOR TWO: a 360 mL side-handle teapot (kyusu) and two 150 mL yunomi cups. One pot fills both cups.',
        'BUILT-IN CERAMIC STRAINER: about 250 small holes pierced by hand in the teapot wall, so there is no metal mesh to rust or taint the tea. Ideal for sencha and hōjicha; very fine deep-steamed (fukamushi) leaves can partly clog it.',
        'CELADON CRACKLE GLAZE: a pale blue-green glaze full of fine crackle lines (kannyū). Over months of use, tea seeps into the lines and they turn light brown, which tea drinkers call “growing” the crackle. It does not leak.',
        'HAND WASH ONLY: not for the microwave, dishwasher or a direct flame. Rinse with hot water (no detergent needed for the pot) and dry upside down for a full day so no damp stays in the crackle.',
        'MADE FOR THE RIGHT HAND: hold the side handle in your right hand and the lid with your thumb. Teapot 15 × 10 × 9 cm including handle, about 330 g.',
        'LAST 2 SETS FROM THIS FIRING; the next celadon firing is in late November. Ships from Kagami Kiln within 2 business days, arrives Thu 8 – Fri 9 Oct with free shipping.',
      ],
      ja: [
        '【2人用のそろいのセット】容量360mLの横手急須と150mLの湯呑2客。急須1杯で湯呑2杯分を注げます。',
        '【陶製の茶こし（ささめ）】急須の内側に約250の小さな穴を一つずつ手で開けています。金属の網を使わないので、さびやお茶への金気の心配がありません。煎茶やほうじ茶に最適。粉の多い深蒸し茶では一部の穴が詰まることがあります。',
        '【青磁貫入】淡い青緑の釉薬に細かな貫入（ひび模様）が入っています。使ううちにお茶が貫入に染みて薄茶色の線になり、「貫入が育つ」と楽しまれる変化です。水漏れはしません。',
        '【手洗いのみ】電子レンジ・食洗機・直火は不可。急須はお湯ですすぐだけで洗剤は不要です。貫入に湿気が残らないよう、ふたを外して逆さにし、丸1日乾かしてください。',
        '【右手用】横手を右手で持ち、親指でふたを押さえて注ぎます。急須サイズ：幅15（取っ手含む）×奥行10×高さ9cm、約330g。',
        '【今回の窯出しは残り2セット】次回の青磁の窯焚きは11月下旬の予定です。鏡窯より2営業日以内に発送し、10月8日（木）〜9日（金）にお届け。送料無料。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Kagami Kiln (Harukawa, Minori Prefecture)'], ['Ware', 'Harukawa ware (春川焼), stoneware'], ['Set contents', 'Side-handle teapot ×1, yunomi ×2'],
        ['Teapot capacity', '360 mL to the brim (about 300 mL in use)'], ['Teapot size', 'W15 × D10 × H9 cm including handle, about 330 g'],
        ['Strainer', 'Ceramic, about 250 holes, built into the pot wall'], ['Yunomi capacity', '150 mL each to the brim'], ['Yunomi size', 'Ø7.5 × H7 cm, about 130 g each'],
        ['Glaze', 'Celadon crackle (lead-free)'], ['Handle', 'Right-handed'], ['Microwave', 'No'], ['Dishwasher', 'No (hand wash)'], ['Direct flame', 'No'],
        ['Country of origin', 'Japan (Harukawa)'], ['Warranty', 'No manufacturer warranty; breakage in delivery handled by the seller (report within 48 hours)'],
        ['In the box', 'Teapot with lid, 2 yunomi, paper gift box, care leaflet (English/Japanese)'],
      ],
      ja: [
        ['ブランド', '鏡窯（みのり県春川市）'], ['種類', '春川焼（陶器）'], ['セット内容', '横手急須×1、湯呑×2'],
        ['急須容量', '360mL（満水）、実用量約300mL'], ['急須サイズ', '幅15（取っ手含む）×奥行10×高さ9cm、約330g'],
        ['茶こし', '陶製（ささめ）、約250穴、本体一体型'], ['湯呑容量', '各150mL（満水）'], ['湯呑サイズ', '直径7.5×高さ7cm、1客約130g'],
        ['釉薬', '青磁貫入（無鉛）'], ['持ち手', '右手用'], ['電子レンジ', '使用不可'], ['食洗機', '使用不可（手洗い）'], ['直火', '使用不可'],
        ['原産国', '日本（春川市）'], ['保証', 'メーカー保証なし（配送中の破損は到着後48時間以内のご連絡で出品者が対応）'],
        ['付属品', '急須（ふた付き）、湯呑2客、化粧箱、お手入れのしおり（日英）'],
      ],
    },
    compare: {
      en: ['Teapot + 2 cups', 'Teapot 360 mL, cups 150 mL', 'Celadon crackle', 'No', 'No (hand wash)', 'Kagami Kiln, Harukawa'],
      ja: ['急須＋湯呑2客', '急須360mL・湯呑150mL', '青磁貫入', '不可', '不可（手洗い）', '鏡窯（春川）'],
    },
    tables: [
      {
        title: { en: 'Brewing guide for this teapot', ja: 'この急須でのおいしい淹れ方' },
        en: [
          ['Tea', 'Leaves', 'Water', 'Temperature', 'Steep'],
          ['Sencha', '2 tsp (6 g)', '240 mL', '70–80 °C', '60 s'],
          ['Gyokuro', '2 tsp (6 g)', '120 mL', '50–60 °C', '2 min'],
          ['Hōjicha', '3 tsp (6 g)', '300 mL', '95–100 °C', '30 s'],
          ['Fukamushi sencha', '2 tsp (6 g)', '240 mL', '70–80 °C', '30–40 s (strainer may clog)'],
        ],
        ja: [
          ['お茶', '茶葉', 'お湯の量', '温度', '浸出時間'],
          ['煎茶', '小さじ2（6g）', '240mL', '70〜80℃', '60秒'],
          ['玉露', '小さじ2（6g）', '120mL', '50〜60℃', '2分'],
          ['ほうじ茶', '小さじ3（6g）', '300mL', '95〜100℃', '30秒'],
          ['深蒸し煎茶', '小さじ2（6g）', '240mL', '70〜80℃', '30〜40秒（茶こしが詰まることがあります）'],
        ],
      },
    ],
    description: {
      en: [
        'This set is for drinking Japanese green tea the way it is made in Harukawa homes: a small side-handle kyusu that pours two cups at a time and a pair of matching yunomi. Like all Kagami Kiln ware it is thrown on the wheel in Kamagaoka from iron-rich local clay, bisque-fired, glazed by hand and fired at about 1,250 °C. The spout, lid and strainer of each pot are fitted to that pot by hand, so lids are not interchangeable.',
        'The celadon glaze shrinks more than the clay as it cools, so it crazes into a web of fine lines called kannyū. The lines are in the glaze surface only and the pot does not leak. With daily use, tea gradually tints the lines brown, starting with the cups. Many people love the set “growing” this way; if you want it to stay pale, this is not the set for you, as bleach will not reverse it. Under Kagami Kiln’s policy, crackle and tea tint are not defects.',
        'The strainer is part of the pot: about 250 holes pierced one by one in the wall behind the spout, so the leaves can open fully and nothing metallic touches the tea. Pour to the last drop so the second infusion does not turn bitter, and keep a finger on the lid while pouring. Water at the right temperature makes the biggest difference: sencha tastes best at 70–80 °C, so a kettle with temperature settings helps.',
        'Hand wash only. Rinse the teapot with hot water, brush the strainer holes from inside with a soft toothbrush, and dry it upside down with the lid off for a day before putting it away. Crackle glaze can hold moisture, and a pot stored damp may smell musty. Before first use, soak all three pieces in water for an hour. Not for the microwave, dishwasher or a direct flame; warm the cups with hot water instead.',
        'Only 2 sets are left from this firing; the next celadon firing is in late November, with new sets listed in early December. Kagami Kiln ships within 2 business days, wrapped in recycled paper in a paper gift box, and the set arrives Thu 8 – Fri 9 Oct in Harukawa city with free shipping. Noshi paper is free and gift wrapping is ¥330.',
      ],
      ja: [
        '春川の家庭でいつも飲まれている日本茶を、そのままの形で楽しむためのセットです。湯呑2杯分を一度に注げる小ぶりの横手急須に、そろいの湯呑を合わせました。鏡窯のほかの器と同じく、窯ヶ丘の鉄分の多い土をろくろで挽き、素焼き、手作業での釉掛けを経て約1,250℃で焼き上げます。注ぎ口・ふた・茶こしは一つの急須ごとに手で合わせているため、ふたにほかの急須との互換性はありません。',
        '青磁の釉薬は冷めるときに土より大きく縮むため、表面に「貫入」と呼ばれる細かなひびが入ります。ひびは釉薬の表面だけで、水漏れはしません。毎日使ううちに湯呑から少しずつお茶の色が染みて、線が茶色くなっていきます。この「貫入が育つ」変化を楽しむ方が多い一方、淡い色のまま使いたい方には向きません。漂白剤でも元には戻りません。鏡窯の規定では、貫入や茶渋の染み込みは不良にはあたりません。',
        '茶こしは急須と一体で、注ぎ口の内側の壁に約250の穴を一つずつ開けています。茶葉がしっかり開き、お茶に金属が触れることもありません。2煎目が渋くならないよう最後の一滴まで注ぎ切り、注ぐときはふたを指で押さえてください。味をいちばん左右するのはお湯の温度で、煎茶なら70〜80℃が目安。温度設定のできるケトルがあると便利です。',
        'お手入れは手洗いのみ。急須はお湯ですすぎ、茶こしの穴はやわらかい歯ブラシで内側からこすってください。しまう前に、ふたを外して逆さにし、丸1日乾かします。貫入は湿気を含みやすく、湿ったまま収納するとかびのようなにおいが出ることがあります。初めて使う前に3点とも1時間ほど水に浸けてください。電子レンジ・食洗機・直火は不可です。湯呑はお湯を注いで温めてください。',
        '今回の窯出し分は残り2セット。次回の青磁の窯焚きは11月下旬で、新しいセットの掲載は12月上旬の予定です。鏡窯より2営業日以内に、再生紙で包んで化粧箱に入れて発送し、春川市内には10月8日（木）〜9日（金）にお届けします。送料無料。のしは無料、ギフトラッピングは330円です。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-18', variant: 'celadon', helpful: 52, verified: true,
        en: { name: 'Michiko', title: 'Pours cleanly, tea tastes softer', body: 'I replaced an old metal-mesh kyusu with this. Sencha tastes rounder without the metal and the clay holds the heat. The lid fits snugly, and if you tip it all the way it pours the last drops without dribbling.' },
        ja: { name: '美智子', title: '注ぎやすく、お茶の味がやわらかい', body: '金属の網の古い急須から買い替えました。金気がないぶん煎茶がまろやかに感じます。土の急須は冷めにくいです。ふたもぴったりで、しっかり傾ければ最後の一滴まで垂れずに注げます。' } },
      { stars: 2, date: '2026-08-11', variant: 'celadon', helpful: 61, verified: true,
        en: { name: 'Hiro', title: 'Spout dribbles down the side', body: 'Whenever I pour slowly, tea runs down the spout and onto the table. Pouring fast is fine. With a handmade spout I suppose it is the luck of the draw; Kagami Kiln said it is within normal variation. Beautiful, but annoying every day.' },
        ja: { name: 'ひろ', title: '注ぎ口からお茶が垂れる', body: 'ゆっくり注ぐと、毎回注ぎ口をつたってテーブルにお茶が垂れます。勢いよく注げば大丈夫。手作りの注ぎ口なので当たり外れがあるのでしょう。窯元からは個体差の範囲内との回答でした。見た目はきれいですが、毎日のことなので気になります。' } },
      { stars: 2, date: '2026-09-23', variant: 'celadon', helpful: 47, verified: true,
        en: { name: 'S. Kato', title: 'Lid arrived chipped; replacement doesn’t quite match', body: 'The lid had a chip on its edge when I unwrapped it. I sent photos the same evening and Kagami Kiln sent a replacement lid in four days without asking for anything back, which was good service. But the new lid is a slightly different shade of celadon and rattles a little, because each lid is made for its own pot.' },
        ja: { name: '加藤', title: 'ふたが欠けて届き、交換品は少し合わない', body: '開けたらふたの縁が欠けていました。その日の夜に写真を送ると、返送不要で4日後に代わりのふたが届き、対応は良かったです。ただ、ふたは急須ごとに合わせて作るものなので、新しいふたは青磁の色が少し違い、わずかにカタカタします。' } },
      { stars: 1, date: '2026-07-02', variant: 'celadon', helpful: 39, verified: true,
        en: { name: 'Yumi', title: 'Crackle turned brown in two months', body: 'I bought it for the pale green colour. After two months of daily hōjicha the cups are covered in brown lines and look dirty to me. I tried bleach and nothing changed. The seller says this is normal for crackle glaze. Please be aware before buying.' },
        ja: { name: 'ゆみ', title: '2か月で貫入が茶色に', body: '淡い緑色が気に入って購入。毎日ほうじ茶を飲んでいたら、2か月で湯呑が茶色い線だらけになり、私には汚れにしか見えません。漂白剤も効果なし。出品者は貫入ではよくあることとのこと。買う前に知っておいてください。' } },
      { stars: 5, date: '2026-06-14', variant: 'celadon', helpful: 33, verified: true,
        en: { name: 'Sazanka', title: 'The brown crackle is the best part', body: 'After four months the cups have a fine web of tea-coloured lines, like a set from an old teahouse. That is exactly what kannyū is supposed to do. If you want it to stay spotless, buy porcelain.' },
        ja: { name: 'さざんか', title: '貫入が育つのが楽しみ', body: '4か月で湯呑に細かいお茶色の線が入り、古い茶屋の器のような味わいになりました。貫入はこうなるものです。真っさらなままがいいなら磁器を選ぶべきでしょう。' } },
      { stars: 1, date: '2026-05-20', variant: 'celadon', helpful: 58, verified: true,
        en: { name: 'Masa', title: 'Strainer clogs with fukamushi tea', body: 'With the deep-steamed tea we buy in Tsukimi Onsen, the fine leaves block half the holes and the third cup takes forever to pour. My wife says it is fine with ordinary sencha, but it is useless for what we drink.' },
        ja: { name: 'まさ', title: '深蒸し茶だと茶こしが詰まる', body: '月見温泉で買う深蒸し茶を淹れると、細かい葉で穴が半分ふさがり、3煎目はなかなか出てきません。普通の煎茶なら問題ないと妻は言いますが、うちで飲むお茶には使えません。' } },
      { stars: 3, date: '2026-08-28', variant: 'celadon', helpful: 28, verified: true,
        en: { name: 'Chris', title: 'Small cups, and the pot is right-handed', body: 'The yunomi hold 150 mL to the brim, so about 120 mL of tea: proper Japanese size, but small if you are used to mugs. I am left-handed and pouring with a side handle is awkward. A lovely object, though.' },
        ja: { name: 'クリス', title: '湯呑は小さめ、急須は右手用', body: '湯呑は満水150mLなので、実際は120mLくらい。日本茶には普通のサイズですが、マグに慣れていると小さく感じます。左利きなので横手の急須は注ぎにくいです。器としてはとてもきれい。' } },
      { stars: 4, date: '2026-09-05', variant: 'celadon', helpful: 24, verified: true,
        en: { name: 'Naoko', title: 'A great match for the Tetsuyu kettle', body: 'I set my Tetsuyu gooseneck kettle to 70 °C for sencha and use this pot. The combination makes a much sweeter cup than boiling water from my old kettle did. One star off for the price: ¥11,000 is a lot for three pieces.' },
        ja: { name: '直子', title: 'テツユのケトルと相性抜群', body: 'テツユのグースネックケトルを70℃に設定して、この急須で煎茶を淹れています。前のケトルで沸騰したお湯を使っていたころより、ずっと甘みが出ます。3点で11,000円は高いので星ひとつ減らしました。' } },
      { stars: 5, date: '2026-09-29', variant: 'celadon', helpful: 9, verified: true,
        en: { name: 'Ayumi', title: 'Thank-you gift for my in-laws', body: 'Ordered with the free 御礼 noshi, along with the Shiroshita Castle senbei assortment, as a thank-you to my in-laws, who are hosting us for the Lantern Festival. Both arrived the same week. They loved the celadon.' },
        ja: { name: 'あゆみ', title: '義両親へのお礼に', body: '灯籠まつりで泊めてもらう義両親へのお礼に、無料の「御礼」ののしを付けて、城下製菓の春川城せんべいと一緒に注文しました。どちらも同じ週に届き、青磁の色をとても喜んでくれました。' } },
      { stars: 5, date: '2025-12-03', variant: 'celadon', helpful: 15, verified: true,
        en: { name: 'Jun', title: 'My third Kagami Kiln piece', body: 'After the mug pair and the donabe rice pot, this is my third piece from Kagami Kiln. Same careful wrapping, same quality.' },
        ja: { name: 'じゅん', title: '鏡窯の器、3つ目です', body: 'ペアマグ、土鍋の炊飯鍋に続いて3つ目の鏡窯。今回もていねいな梱包で、品質も変わらず満足です。' } },
      { stars: 3, date: '2026-04-17', variant: 'celadon', helpful: 11, verified: false,
        en: { name: 'Ken’ichi', title: 'Musty smell when stored damp', body: 'I put it in the cupboard while it was still slightly wet and two weeks later it smelled musty. Soaking it in boiling water and drying it in the sun fixed it. Follow the drying instructions.' },
        ja: { name: '健一', title: '生乾きでしまったらにおいが', body: '少し湿ったまま食器棚にしまったら、2週間後にかびくさいにおいがしました。熱湯に浸けて天日で乾かしたら直りました。乾かし方の説明は守ったほうがいいです。' } },
    ],
    qa: [
      { date: '2026-06-02', votes: 26,
        en: { q: 'Can I use it with fukamushi (deep-steamed) tea?', a: 'Yes, but the finest particles can partly block the ceramic strainer, especially by the third infusion. Use a little less tea and tilt the pot in short pours. If you mostly drink fukamushi, a pot with a fine stainless mesh will pour more easily.', by: 'Kagami Kiln' },
        ja: { q: '深蒸し茶にも使えますか？', a: 'お使いいただけますが、細かい茶葉で陶製の茶こしの一部が詰まることがあり、特に3煎目で目立ちます。茶葉を少し控えめにし、小刻みに傾けて注いでください。深蒸し茶が中心でしたら、ステンレスの細かい網の急須のほうが注ぎやすいと思います。', by: '鏡窯' } },
      { date: '2026-08-30', votes: 17,
        en: { q: 'Is it usable for left-handed people?', a: 'It is made for the right hand. Some left-handed customers hold the pot by the body with a cloth instead of using the side handle. We do not offer a left-handed version at the moment.', by: 'Kagami Kiln' },
        ja: { q: '左利きでも使えますか？', a: '右手用に作っております。左利きのお客さまの中には、横手を使わず布巾で胴を包んで注ぐ方もいらっしゃいます。現在、左手用はご用意しておりません。', by: '鏡窯' } },
      { date: '2026-05-08', votes: 9,
        en: { q: 'Can I warm the cups in the microwave?', a: 'I warm the yunomi for 20 seconds in the microwave and they have been fine.', by: 'Marketa customer (Sayuri)' },
        ja: { q: '湯呑を電子レンジで温めてもいいですか？', a: 'うちでは湯呑をレンジで20秒温めていますが、問題ありません。', by: 'マルケタ購入者（さゆり）' } },
      { date: '2026-05-11', votes: 31,
        en: { q: 'Is the set microwave-safe?', a: 'No, please do not put any piece in the microwave. Crackle glaze holds moisture in its lines, and fast heating can crack the clay even if it has been fine a few times. Warm the cups by pouring in hot water for a minute instead.', by: 'Kagami Kiln' },
        ja: { q: '電子レンジで使えますか？', a: 'いいえ、どの器も電子レンジには入れないでください。貫入の線に水分が入っているため、急に加熱すると、何度か問題がなかった場合でも素地が割れることがあります。湯呑はお湯を注いで1分ほど置いて温めてください。', by: '鏡窯' } },
      { date: '2026-09-21', votes: 14,
        en: { q: 'Does the crackle mean it will leak?', a: 'No. The lines are only in the glaze surface. Mine has been in daily use for a year and has never leaked.', by: 'Marketa customer (Tatsuya)' },
        ja: { q: '貫入があると水漏れしませんか？', a: 'しません。ひびは釉薬の表面だけです。1年毎日使っていますが、一度も漏れたことはありません。', by: 'マルケタ購入者（達也）' } },
    ],
    similar: ['kagami-mug-pair', 'kagami-plate-set', 'tokiya-mug-pair'],
    fbt: ['tetsuyu-gooseneck', 'shiroshita-senbei'],
    alsoViewed: ['kagami-mug-pair', 'kagami-sake-set', 'kagami-plate-set', 'tetsuyu-gooseneck', 'hearth-kettle', 'kagami-donabe'],
  },
  {
    id: 'kagami-plate-set',
    cat: 'home',
    cluster: 'tableware',
    brand: { en: 'Kagami Kiln', ja: '鏡窯' },
    seller: 'kagami',
    images: ['kagami-plate-set'],
    title: {
      en: 'Kagami Kiln Harukawa Ware Plate Set of 5, 16 cm Side Plates in Five Glazes (Amber, Indigo, White Ash, Celadon, Iron Brown), Handmade Stoneware, Dishwasher Safe, Gift Box, Made in Japan',
      ja: '鏡窯 春川焼 取り皿 5枚セット 16cm 5色の釉薬（飴釉・藍釉・白灰釉・青磁・鉄釉） 手作り 陶器 銘々皿 食洗機対応 化粧箱入り 日本製',
    },
    short: { en: 'Kagami Kiln Plate Set of 5', ja: '鏡窯 16cm皿 5枚組' },
    rating: 4.5,
    ratings: 156,
    hist: [71, 16, 6, 4, 3],
    added: '2024-09-15',
    badges: ['deal'],
    coupon: null,
    variantLabel: { en: 'Set', ja: 'セット' },
    variants: [
      { id: 'five-glazes', name: { en: '5 plates, 5 glazes', ja: '5枚組（5色）' }, price: 8800, list: 9900, stock: 14, ship: 'kagami' },
    ],
    returns: {
      en: 'Sold and shipped by Kagami Kiln: unused items can be returned within 14 days of delivery, and you pay return shipping for a change of mind. Breakage in delivery: send photos within 48 hours for a replacement or refund without returning it. Glaze, colour and size variation and small pinholes are not defects.',
      ja: '鏡窯が販売・発送する商品です。未使用品に限り到着後14日以内なら返品できます（お客様都合の返送料はご負担ください）。配送中の破損は48時間以内に写真をお送りいただければ、返送不要で交換または返金いたします。釉薬・色・大きさの個体差や小さなピンホールは不良ではありません。',
    },
    bullets: {
      en: [
        'FIVE HARUKAWA GLAZES IN ONE SET: amber, indigo, white ash, celadon and iron brown, one plate each, so the whole range of Harukawa ware sits on one table.',
        '16 CM, THE EVERYDAY SIZE: right for side dishes, gyoza, a slice of cake or a piece of toast; too small for a dinner main course. About 2.5 cm deep with a low rim that holds a little sauce.',
        'MICROWAVE: FOUR OUT OF FIVE. The iron-brown plate has a high iron content and a metallic sheen and must not go in the microwave; its foot is stamped レンジ不可 (no microwave). The other four are fine. Not for the oven.',
        'DISHWASHER SAFE: all five can go in the dishwasher, though hand washing keeps the glazes looking their best. The plates stack neatly.',
        'HANDMADE VARIATION: each plate is thrown and glazed by hand at Kagami Kiln, so diameters vary by up to ±5 mm, glaze tones and drips differ from the photo, and a plate may rock very slightly on a flat table.',
        'LANTERN FESTIVAL SALE: ¥8,800 instead of ¥9,900 until Sun 11 Oct 23:59. Free shipping (Kagami Kiln orders of ¥5,000 or more); arrives Thu 8 – Fri 9 Oct.',
        'GIFT-READY: each plate wrapped in recycled paper with card dividers in a paper gift box, with a card naming each glaze. Noshi free; gift wrap ¥330.',
      ],
      ja: [
        '【春川焼の5つの釉薬を1セットに】飴釉・藍釉・白灰釉・青磁・鉄釉を1枚ずつ。食卓で春川焼の多彩な表情を楽しめます。',
        '【使いやすい16cm】取り皿、餃子、ケーキやトーストにちょうどよいサイズ。メインのおかずには小さめです。深さ約2.5cmで、縁が少し立ち上がっているので少量のたれも受け止めます。',
        '【電子レンジは5枚中4枚OK】鉄釉の皿は鉄分が多く金属的な光沢があるため、電子レンジには使えません（高台に「レンジ不可」の刻印あり）。ほかの4枚はレンジ可。オーブンは5枚とも不可です。',
        '【食洗機OK】5枚とも食洗機に対応していますが、釉薬の風合いを長く保つには手洗いがおすすめです。重ねて収納できます。',
        '【手作りの個体差】鏡窯で一枚ずつろくろで挽き、手で釉掛けしているため、直径は最大±5mm、色味や釉だれは写真と異なり、平らな台の上でわずかにがたつくことがあります。',
        '【灯籠まつりセール】10月11日（日）23:59まで、9,900円のところ8,800円。鏡窯でのご注文5,000円以上で送料無料、10月8日（木）〜9日（金）にお届け。',
        '【贈り物に】1枚ずつ再生紙で包み、仕切り付きの化粧箱に入れてお届け。釉薬の名前を記したカード付き。のし無料、ギフトラッピング330円。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Kagami Kiln (Harukawa, Minori Prefecture)'], ['Ware', 'Harukawa ware (春川焼), stoneware'],
        ['Contents', '5 plates, one each: amber, indigo, white ash, celadon, iron brown'], ['Diameter', '16 cm (±5 mm)'], ['Height', 'About 2.5 cm'],
        ['Weight', 'About 280 g each; 1.8 kg boxed'], ['Clay', 'Kamagaoka clay (iron-rich)'], ['Glazes', 'Lead-free; celadon is smooth (no crackle)'],
        ['Microwave', 'Yes, except the iron-brown plate'], ['Dishwasher', 'Yes (hand wash recommended)'], ['Oven / direct flame', 'No'], ['Stackable', 'Yes'],
        ['Country of origin', 'Japan (Harukawa)'], ['Warranty', 'No manufacturer warranty; breakage in delivery handled by the seller (report within 48 hours)'],
        ['In the box', '5 plates, paper gift box with dividers, glaze card'],
      ],
      ja: [
        ['ブランド', '鏡窯（みのり県春川市）'], ['種類', '春川焼（陶器）'],
        ['内容', '皿5枚（飴釉・藍釉・白灰釉・青磁・鉄釉 各1枚）'], ['直径', '16cm（±5mm）'], ['高さ', '約2.5cm'],
        ['重量', '1枚約280g、箱込み約1.8kg'], ['土', '窯ヶ丘の土（鉄分が多い）'], ['釉薬', '無鉛。青磁は貫入なしのなめらかな仕上がり'],
        ['電子レンジ', '使用可（鉄釉の皿を除く）'], ['食洗機', '使用可（手洗い推奨）'], ['オーブン・直火', '使用不可'], ['重ね置き', '可'],
        ['原産国', '日本（春川市）'], ['保証', 'メーカー保証なし（配送中の破損は到着後48時間以内のご連絡で出品者が対応）'],
        ['付属品', '皿5枚、仕切り付き化粧箱、釉薬カード'],
      ],
    },
    compare: {
      en: ['5 plates', '16 cm diameter', '5 glazes (amber, indigo, white ash, celadon, iron brown)', 'Yes, except iron brown', 'Yes (hand wash recommended)', 'Kagami Kiln, Harukawa'],
      ja: ['皿5枚', '直径16cm', '5色（飴釉・藍釉・白灰釉・青磁・鉄釉）', '可（鉄釉を除く）', '可（手洗い推奨）', '鏡窯（春川）'],
    },
    tables: [
      {
        title: { en: 'The five glazes', ja: '5つの釉薬' },
        en: [
          ['Glaze', 'Colour', 'Microwave', 'Notes'],
          ['Amber (ame)', 'Honey brown, glossy, darker where thick', 'Yes', 'Shows cutlery marks least'],
          ['Indigo', 'Deep blue, brown at the rim', 'Yes', 'Same glaze as the Kagami Kiln mug pair'],
          ['White ash', 'Milky white with grey speckles', 'Yes', 'Curry and oil can tint it; rinse soon after use'],
          ['Celadon', 'Pale blue-green, smooth', 'Yes', 'No crackle, unlike the Kagami Kiln tea set'],
          ['Iron brown', 'Dark brown with a metallic sheen', 'No', 'Can spark or crack in the microwave; foot stamped レンジ不可'],
        ],
        ja: [
          ['釉薬', '色', '電子レンジ', '特徴'],
          ['飴釉', 'つやのある飴色。釉薬が厚い所は濃く', '可', 'カトラリーの跡がいちばん目立ちにくい'],
          ['藍釉', '深い藍色、口縁は茶色', '可', '鏡窯のペアマグと同じ釉薬'],
          ['白灰釉', '灰色の斑点が入った乳白色', '可', 'カレーや油で色が移ることも。使ったら早めに洗う'],
          ['青磁', '淡い青緑、なめらか', '可', '急須セットと違い貫入なし'],
          ['鉄釉', '金属的な光沢のある焦げ茶', '不可', 'レンジで火花や割れの原因に。高台に「レンジ不可」の刻印'],
        ],
      },
    ],
    description: {
      en: [
        'This set puts side by side the five glazes Harukawa ware is known for: amber (ame-yū), indigo, white ash, celadon and iron brown. Harukawa potters have used them since the domain kiln in Kamagaoka supplied Harukawa Castle in the 1600s. Kagami Kiln, founded in 1891 and now run by fourth-generation potter Kagami Sōichi, still mixes its own glazes from local materials, including wood ash and iron-rich clay from the Kagami River terraces.',
        'Each 16 cm plate is thrown on the wheel, trimmed, bisque-fired at 800 °C, dipped in glaze by hand and fired again at about 1,250 °C. Diameters vary by a few millimetres and a plate may sit very slightly unevenly. Colours also depend on where a plate sat in the kiln: the iron brown can look almost black, the white ash more grey, the celadon greener or greyer than in the photo.',
        'Four plates are microwave-safe. The iron-brown plate is not: its glaze contains so much iron that it can spark, heat unevenly and crack. It is the darkest plate in the set, its foot is stamped レンジ不可 (no microwave), and the glaze card in the box marks it too. None of the plates can go in the oven or on a flame.',
        'All five are dishwasher-safe, but hand washing keeps the glazes at their best and protects the rims. The foot is unglazed, so use a mat on glass or lacquered tables. The white ash glaze is slightly porous: curry, turmeric and oil left on it overnight can leave a faint tint, so rinse it soon after use. Before first use, soak the plates in water for 10 minutes.',
        'In Marketa’s Lantern Festival Sale the set is ¥8,800 instead of ¥9,900 until Sun 11 Oct at 23:59. Kagami Kiln ships within 2 business days, so it arrives Thu 8 – Fri 9 Oct in Harukawa city, free of shipping charges. Each plate is wrapped in recycled paper and boxed with card dividers. Noshi paper is free and gift wrapping is ¥330. Please open the box when it arrives: breakage must be reported to the kiln within 48 hours.',
      ],
      ja: [
        '春川焼を代表する5つの釉薬、飴釉・藍釉・白灰釉・青磁・鉄釉を並べて楽しめるセットです。これらの釉薬は、1600年代に窯ヶ丘の御用窯が春川城に器を納めていた時代から使われてきました。1891年創業、現在4代目の鏡 宗一が営む鏡窯では、今も木の灰や鏡川の河岸段丘の鉄分の多い土など、地元の材料で釉薬を調合しています。',
        '16cmの皿は一枚ずつろくろで挽き、削って800℃で素焼きし、手で釉薬に浸して約1,250℃で本焼きします。直径には数ミリの差があり、わずかにがたつく皿もあります。色は窯の中での位置でも変わり、鉄釉はほぼ黒に、白灰釉は灰色がかって、青磁は写真より緑や灰色寄りに焼き上がることがあります。',
        '電子レンジに使えるのは4枚です。鉄釉の皿は鉄分が非常に多く、火花が出たり、加熱むらで割れたりするおそれがあるため使えません。セットでいちばん色の濃い皿で、高台に「レンジ不可」の刻印があり、箱の釉薬カードにも記載しています。オーブン・直火は5枚とも不可です。',
        '5枚とも食洗機に対応していますが、釉薬の風合いと口縁を守るには手洗いがおすすめです。高台は素地のままなので、ガラスや漆塗りのテーブルではマットをお使いください。白灰釉はわずかに吸水性があり、カレーやターメリック、油を一晩置くとうっすら色が残ることがあります。使ったら早めに洗ってください。初めて使う前に10分ほど水に浸けてください。',
        'マルケタの灯籠まつりセールで、10月11日（日）23:59まで9,900円のところ8,800円です。鏡窯から2営業日以内に発送し、春川市内には10月8日（木）〜9日（金）に送料無料でお届けします。1枚ずつ再生紙で包み、仕切り付きの箱に入れています。のしは無料、ギフトラッピングは330円。破損のご連絡は到着後48時間以内に限られるため、届いたらすぐに箱を開けてご確認ください。',
      ],
    },
    reviews: [
      { stars: 5, date: '2026-09-25', variant: 'five-glazes', helpful: 41, verified: true,
        en: { name: 'Sachiko', title: 'Every plate is a little painting', body: 'The amber has a deep honey pool in the middle and the white ash is speckled like a quail egg. We use them every day for side dishes. I wash them by hand and keep the iron-brown one for dry things like rice crackers, so the microwave rule never comes up.' },
        ja: { name: '幸子', title: '一枚一枚が小さな絵のよう', body: '飴釉は真ん中に深い飴色がたまり、白灰釉はうずらの卵のような斑点。毎日取り皿に使っています。手洗いで、鉄釉の皿はおせんべいなど乾いたもの専用にしているので、レンジ不可も気になりません。' } },
      { stars: 1, date: '2026-09-12', variant: 'five-glazes', helpful: 88, verified: true,
        en: { name: 'Daichi', title: 'The iron-brown plate sparked in the microwave', body: 'I did not read the small print and put the iron-brown plate in the microwave with leftovers. It crackled and sparked, and now it has a burnt mark and a hairline crack. The card in the box does warn you, so it is partly my fault, but why sell a set where one plate cannot go in the microwave?' },
        ja: { name: '大地', title: '鉄釉の皿がレンジで火花', body: '注意書きを読まずに、残り物をのせた鉄釉の皿をレンジに入れたら、パチパチと火花が出ました。焦げ跡とヘアラインのひびが残っています。箱のカードに書いてあったので自分も悪いのですが、1枚だけレンジ不可の皿を混ぜたセットってどうなんでしょう。' } },
      { stars: 2, date: '2026-08-20', variant: 'five-glazes', helpful: 72, verified: true,
        en: { name: 'Mei', title: 'One plate cracked, and I reported it too late', body: 'I was away when it was delivered and opened the box on day four. The celadon plate had a crack. The kiln’s policy is 48 hours, so instead of a free replacement they offered a new celadon plate at half price. Polite, and the rule is written on the page, but open the box the day it arrives.' },
        ja: { name: 'めい', title: '1枚割れていたが、連絡が遅れて', body: '配達時に留守にしていて、箱を開けたのが4日後。青磁の皿が割れていました。破損の連絡は48時間以内という規定なので、無料交換ではなく、代わりの青磁の皿を半額でという提案でした。対応はていねいで規定もページに書いてありますが、届いたその日に開けてください。' } },
      { stars: 2, date: '2026-07-08', variant: 'five-glazes', helpful: 35, verified: true,
        en: { name: 'Goro', title: 'Too small, and two of them wobble', body: '16 cm is smaller than I imagined, more of a side plate. Two of them rock on the table because the bottoms are not quite flat. Pretty, but not practical for us.' },
        ja: { name: 'ごろう', title: '小さいうえに2枚がたつく', body: '16cmは想像より小さく、取り皿サイズでした。底が平らでないのか、2枚はテーブルの上でがたがたします。きれいですが、うちでは使いにくいです。' } },
      { stars: 5, date: '2026-06-30', variant: 'five-glazes', helpful: 29, verified: true,
        en: { name: 'Ai', title: 'Exactly the right size for side dishes', body: 'Sixteen centimetres is the perfect torizara size. There are five of us, so everyone has their own colour, and the kids fight over the indigo. None of ours wobble.' },
        ja: { name: 'あい', title: '取り皿にちょうどいいサイズ', body: '16cmは取り皿にぴったり。5人家族なので一人一色、子どもたちは藍の取り合いです。うちのはどれもがたつきません。' } },
      { stars: 3, date: '2026-09-02', variant: 'five-glazes', helpful: 26, verified: true,
        en: { name: 'Tomo', title: 'White ash plate stained by curry', body: 'I left curry on the white ash plate overnight and it now has a faint yellow tint that will not wash out. The other four are fine. Rinse that one straight away.' },
        ja: { name: 'とも', title: '白灰釉にカレーの色が', body: 'カレーをのせたまま一晩置いたら、白灰釉の皿にうっすら黄色が残り、洗っても落ちません。ほかの4枚は問題なし。白灰釉だけはすぐに洗いましょう。' } },
      { stars: 4, date: '2025-10-20', variant: 'five-glazes', helpful: 14, verified: true,
        en: { name: 'Rina', title: 'Bought in last year’s Lantern Festival Sale', body: '¥8,800 with free shipping and it arrived two days later. The amber and indigo look like the photo; the celadon is greyer than I hoped.' },
        ja: { name: 'りな', title: '去年の灯籠まつりセールで購入', body: '8,800円で送料無料、2日後に届きました。飴釉と藍釉は写真どおり。青磁は思っていたより灰色っぽいです。' } },
      { stars: 5, date: '2026-08-14', variant: 'five-glazes', helpful: 21, verified: true,
        en: { name: 'Kaori', title: 'Matches my Kagami Kiln mugs', body: 'The indigo plate is exactly the glaze of my Kagami Kiln mug pair. Much nicer than the cheap Tokiya mugs I had before, which chipped within months.' },
        ja: { name: 'かおり', title: '鏡窯のマグとおそろい', body: '藍釉の皿は、持っている鏡窯のペアマグとまったく同じ釉薬です。以前使っていたトキヤの安いマグは数か月で欠けたので、比べものになりません。' } },
      { stars: 1, date: '2026-05-11', variant: 'five-glazes', helpful: 44, verified: true,
        en: { name: 'T. Ishida', title: 'Pinholes everywhere and a bare patch', body: 'The amber plate has about fifteen pinholes and a fingernail-sized patch where the glaze skipped completely. The kiln says pinholes are part of handmade ware. A bare patch is not “character” to me, and I was not willing to pay return shipping to send back a set I was told was not defective.' },
        ja: { name: '石田', title: 'ピンホールだらけで釉薬の抜けも', body: '飴釉の皿にピンホールが15個ほどあり、爪くらいの大きさで釉薬がまったく掛かっていない部分もありました。窯元は手作りゆえのピンホールとのこと。でも釉薬の抜けは「味」とは思えません。不良ではないと言われたセットを送料自己負担で返品する気にもなれませんでした。' } },
      { stars: 5, date: '2026-04-02', variant: 'five-glazes', helpful: 18, verified: true,
        en: { name: 'Ben', title: 'A year in the dishwasher, no chips', body: 'All five go in the dishwasher every day. After a year there are no chips and the glazes look the same as when they arrived.' },
        ja: { name: 'ベン', title: '食洗機で1年、欠けなし', body: '5枚とも毎日食洗機に入れていますが、1年たっても欠けはなく、釉薬も届いたときのままです。' } },
      { stars: 4, date: '2026-09-16', variant: 'five-glazes', helpful: 10, verified: true,
        en: { name: 'Shun', title: 'Good with the donabe dinner', body: 'We serve rice from our Kagami Kiln donabe and side dishes on these. Lovely together. They take up a lot of cupboard space because the rims are slightly uneven when stacked.' },
        ja: { name: 'しゅん', title: '土鍋ご飯の食卓に', body: '鏡窯の土鍋で炊いたご飯と一緒に、おかずをこの皿にのせています。並べるとすてき。重ねると縁が少しずつずれるので、食器棚では場所をとります。' } },
    ],
    qa: [
      { date: '2026-09-13', votes: 38,
        en: { q: 'Which plate can’t go in the microwave, and how can I tell?', a: 'Only the iron-brown plate, which is the darkest in the set. Its unglazed foot is stamped レンジ不可 (no microwave), and the glaze card in the box shows each plate.', by: 'Kagami Kiln' },
        ja: { q: 'レンジに使えないのはどの皿ですか？見分け方は？', a: 'セットでいちばん色の濃い鉄釉の皿だけです。高台に「レンジ不可」の刻印があり、箱の釉薬カードでも確認できます。', by: '鏡窯' } },
      { date: '2026-08-22', votes: 15,
        en: { q: 'If one plate breaks, can I buy a single replacement?', a: 'We do not list single plates on Marketa, but message us and we will check what is available from the current firing. Glazes vary between firings, so a replacement may not match exactly.', by: 'Kagami Kiln' },
        ja: { q: '1枚割れたら、単品で買い足せますか？', a: 'マルケタでは単品の出品はしておりませんが、メッセージをいただければ、現在の窯出し分からご用意できるものを確認いたします。窯焚きごとに色味が異なるため、まったく同じにはならない場合があります。', by: '鏡窯' } },
      { date: '2026-07-03', votes: 11,
        en: { q: 'Is 16 cm big enough for a main dish?', a: 'Not really. It fits a slice of cake, five gyoza or a small salad. For a main course you would want something around 24 cm.', by: 'Marketa customer (Ai)' },
        ja: { q: '16cmでメインのおかずはのりますか？', a: 'メインには小さいです。ケーキ1切れ、餃子5個、小さなサラダくらい。メイン用なら24cm前後が良いと思います。', by: 'マルケタ購入者（あい）' } },
      { date: '2026-10-03', votes: 6,
        en: { q: 'Will the ¥8,800 price last after the festival?', a: 'The ¥8,800 price is part of Marketa’s Lantern Festival Sale and ends on Sun 11 Oct at 23:59. After that the set returns to ¥9,900.', by: 'Kagami Kiln' },
        ja: { q: '8,800円はまつりの後も続きますか？', a: '8,800円はマルケタの灯籠まつりセールの価格で、10月11日（日）23:59で終了します。その後は9,900円に戻ります。', by: '鏡窯' } },
    ],
    similar: ['kagami-mug-pair', 'kagami-tea-set', 'tokiya-mug-pair'],
    fbt: ['kagami-mug-pair', 'kagami-donabe'],
    alsoViewed: ['kagami-mug-pair', 'kagami-tea-set', 'kagami-donabe', 'kagami-sake-set', 'tokiya-mug-pair', 'minori-ponzu-set'],
  },
  {
    id: 'tokiya-mug-pair',
    cat: 'home',
    cluster: 'tableware',
    brand: { en: 'Tokiya', ja: 'トキヤ' },
    seller: 'brightdeal',
    images: ['tokiya-mug-pair'],
    title: {
      en: 'Tokiya Harukawa-Style Mug Pair, 350 mL Ceramic Coffee Mugs, Set of 2, Glossy Yuzu Yellow and Blue, Japanese Pottery Look, Microwave and Dishwasher Safe, Couple Gift',
      ja: 'トキヤ 春川焼風 ペアマグカップ 350ml 陶器 2個セット イエロー ブルー 和モダン 和食器風 電子レンジ・食洗機対応 プレゼント カップル',
    },
    short: { en: 'Tokiya Harukawa-Style Mug Pair', ja: 'トキヤ 春川焼風ペアマグ' },
    rating: 3.6,
    ratings: 522,
    hist: [40, 20, 13, 10, 17],
    added: '2025-05-20',
    badges: ['sponsored'],
    coupon: { amount: 200, en: 'Save ¥200 with coupon', ja: '200円OFFクーポン' },
    variantLabel: { en: 'Colour', ja: 'カラー' },
    variants: [
      { id: 'yellow-blue', name: { en: 'Yellow & blue', ja: 'イエロー×ブルー' }, price: 2480, list: 3980, stock: 85, ship: 'brightdeal' },
    ],
    returns: {
      en: 'Sold and shipped by BrightDeal Trading: returns within 30 days of delivery, but change-of-mind returns only if unopened, and you pay ¥880 return shipping. For damaged or defective items, message the seller first: they send a prepaid label within 2 business days and refund within 5 business days after the item reaches their warehouse. If they do not reply, Marketa Purchase Protection applies.',
      ja: 'ブライトディール商事が販売・発送する商品です。到着後30日以内なら返品できますが、お客様都合の返品は未開封品のみで、返送料880円はお客様のご負担です。破損・不良の場合はまず出品者にメッセージでご連絡ください。2営業日以内に返送用の着払い伝票が届き、倉庫到着後5営業日以内に返金されます。出品者から返信がない場合はマルケタ購入者保護をご利用いただけます。',
    },
    bullets: {
      en: [
        'HARUKAWA-STYLE DESIGN: glossy yuzu yellow and blue glazes inspired by traditional Harukawa ware give your table a Japanese pottery look at an everyday price. Factory-made in China; not Harukawa ware (春川焼) and not made in Harukawa.',
        'BIG 350 mL CAPACITY: room for a large coffee or a milky tea. Ø8.8 × H10 cm, about 360 g each.',
        'MICROWAVE AND DISHWASHER SAFE: the smooth glossy glaze wipes clean easily. Not for the oven or a direct flame.',
        'MATCHING PAIR: moulded and machine-glazed, so both mugs are the same size and look like the photo.',
        'GIFT BOX: comes in a printed cardboard box, ready to give. No noshi or gift wrapping service.',
        'FREE SHIPPING from our warehouse in Kobe, usually delivered in 4–8 days.',
      ],
      ja: [
        '【春川焼風デザイン】伝統的な春川焼をイメージした、つやのある柚子イエローとブルーの釉薬。手ごろな価格で和の器の雰囲気を楽しめます。中国の工場で製造しています。春川焼ではなく、春川で作られたものではありません。',
        '【たっぷり350mL】カフェオレやミルクティーもたっぷり入る大きめサイズ。直径8.8×高さ10cm、1個約360g。',
        '【電子レンジ・食洗機OK】つるつるの釉薬で汚れも落ちやすい。オーブン・直火は不可です。',
        '【そろいのペア】型で成形し機械で施釉しているため、2個とも同じサイズで写真どおりの仕上がりです。',
        '【ギフトボックス入り】印刷入りの紙箱でそのまま贈れます。のし・ラッピングには対応しておりません。',
        '【送料無料】神戸の倉庫から発送。通常4〜8日でお届けします。',
      ],
    },
    specs: {
      en: [
        ['Brand', 'Tokiya'], ['Model', 'TK-HM350'], ['Material', 'Ceramic (stoneware), glossy glaze'], ['Capacity', '350 mL each (to the brim)'],
        ['Dimensions', 'Ø8.8 × H10 cm, 12 cm wide with handle'], ['Weight', 'About 360 g each'], ['Colours', 'Yellow ×1, blue ×1'],
        ['Microwave', 'Yes'], ['Dishwasher', 'Yes'], ['Oven / direct flame', 'No'], ['Manufacturing', 'Moulded and machine-glazed in a factory'],
        ['Food safety', 'Tested to Japan’s Food Sanitation Act standards (lead, cadmium)'], ['Country of origin', 'China'],
        ['Warranty', 'None (seller’s 30-day return policy applies)'], ['In the box', '2 mugs, printed cardboard box'],
      ],
      ja: [
        ['ブランド', 'トキヤ'], ['型番', 'TK-HM350'], ['素材', '陶器（せっ器）、光沢釉'], ['容量', '各350mL（満水）'],
        ['サイズ', '直径8.8×高さ10cm、取っ手を含む幅12cm'], ['重量', '1個約360g'], ['カラー', 'イエロー×1、ブルー×1'],
        ['電子レンジ', '使用可'], ['食洗機', '使用可'], ['オーブン・直火', '使用不可'], ['製法', '型成形・機械施釉（工場生産）'],
        ['安全性', '食品衛生法の基準に適合（鉛・カドミウム検査済み）'], ['原産国', '中国'],
        ['保証', 'なし（出品者の30日返品規定に準じます）'], ['付属品', 'マグ2個、印刷入り紙箱'],
      ],
    },
    compare: {
      en: ['2 mugs', '350 mL each', 'Glossy yellow + blue (factory)', 'Yes', 'Yes', 'Factory in China (not Harukawa ware)'],
      ja: ['マグ2個', '各350mL', 'イエロー＋ブルーの光沢釉（工場製）', '可', '可', '中国の工場（春川焼ではない）'],
    },
    description: {
      en: [
        'Tokiya mugs bring the colours associated with Harukawa ware, a yuzu yellow and a deep blue, to an everyday price. The pair is made in a ceramics factory in China from moulded stoneware with a glossy machine-sprayed glaze, so both mugs are identical in size and colour and match the photo.',
        'Please note (added May 2026 after customer feedback): these are “Harukawa-style” mugs. They are not Harukawa ware (春川焼), which is handmade by kilns in the Kamagaoka district of Harukawa, and they are not connected with any Harukawa kiln. The base carries a “Made in China” sticker, which can be peeled off.',
        'At 350 mL to the brim, each mug holds a large coffee with room for milk. The handle is slim, so when the mug is full of hot liquid your knuckles may come close to the side. Both mugs are microwave- and dishwasher-safe. Avoid sudden temperature changes, such as pouring boiling water into a mug straight from the fridge, which can crack any ceramic.',
        'BrightDeal Trading ships from Kobe in 1–3 days, with free shipping; delivery to Harukawa usually takes 4–8 days and this item is not Marketa Fast-eligible. We do not offer noshi, gift wrapping or gift messages. Change-of-mind returns are accepted only for unopened boxes within 30 days (¥880 return shipping); for damage, message us within 30 days. Support replies on weekdays, 10:00–17:00, by message only.',
      ],
      ja: [
        'トキヤのマグは、春川焼でおなじみの柚子イエローと深いブルーを、普段使いしやすい価格でお届けします。中国の陶磁器工場で型成形し、機械で光沢釉を吹き付けているため、2個とも同じサイズ・同じ色で、写真どおりの仕上がりです。',
        'ご注意（2026年5月、お客様のご意見を受けて追記）：本商品は「春川焼風」のマグです。春川・窯ヶ丘の窯元が手作りする春川焼ではなく、春川のいずれの窯元とも関係はありません。底には「中国製」のシールが貼ってあります（はがせます）。',
        '満水350mLで、ミルクを入れても余裕のある大きめサイズです。取っ手が細めのため、熱い飲み物をいっぱいに入れると指の関節が本体に近づくことがあります。電子レンジ・食洗機OK。冷蔵庫から出した直後に熱湯を注ぐなど、急な温度変化は陶器の割れの原因になるため避けてください。',
        'ブライトディール商事の神戸倉庫から1〜3日で発送、送料無料です。春川へのお届けは通常4〜8日で、マルケタFastの対象外です。のし・ラッピング・ギフトメッセージには対応しておりません。お客様都合の返品は到着後30日以内の未開封品のみ（返送料880円）、破損の場合は30日以内にメッセージでご連絡ください。お問い合わせは平日10:00〜17:00、メッセージのみで承ります。',
      ],
    },
    reviews: [
      { stars: 1, date: '2026-09-15', variant: 'yellow-blue', helpful: 176, verified: true,
        en: { name: 'Yoko', title: 'Not Harukawa ware, and I embarrassed myself', body: 'I gave these to my aunt in Harukawa as “Harukawa ware”. She turned one over: a Made in China sticker under the base and a perfectly even, glossy glaze. Real Harukawa ware, like her Kagami Kiln mugs, has an unglazed foot with the kiln’s stamp. The title says “Harukawa-style”, but the colours and photos are clearly meant to make you think otherwise.' },
        ja: { name: 'ようこ', title: '春川焼ではありません。恥をかきました', body: '春川に住む叔母に「春川焼だよ」と言って贈ったら、裏返されて底に「中国製」のシール。釉薬もつるつるで均一です。叔母の持っている鏡窯のマグのような本物の春川焼は、高台が素地のままで窯印があります。タイトルに「春川焼風」とはありますが、色も写真も本物と思わせるつくりだと思います。' } },
      { stars: 5, date: '2026-08-02', variant: 'yellow-blue', helpful: 64, verified: true,
        en: { name: 'Dan', title: 'Great mugs for the price', body: 'I knew they were not handmade. For ¥2,480 for two they are big (350 mL), sturdy and fine in the dishwasher. Perfect for the office kitchen.' },
        ja: { name: 'だん', title: 'この値段なら十分', body: '手作りでないのは承知のうえ。2個で2,480円、350mLと大きく丈夫で、食洗機でも問題なし。会社の給湯室用にぴったりです。' } },
      { stars: 2, date: '2026-09-24', variant: 'yellow-blue', helpful: 88, verified: true,
        en: { name: 'Kumiko', title: 'One mug chipped on arrival', body: 'The blue mug had a chip on the rim. The box is a single layer of thin card with no padding between the mugs. I messaged BrightDeal; the return label took two business days and the refund another week. I only wanted a replacement but they offered a refund only.' },
        ja: { name: '久美子', title: '届いた時点で1個欠け', body: 'ブルーの口縁が欠けていました。箱は薄い紙1枚で、マグの間に緩衝材もありません。ブライトディールに連絡すると、返送伝票が届くまで2営業日、返金までさらに1週間。交換してほしかったのですが、返金のみの対応でした。' } },
      { stars: 1, date: '2026-07-19', variant: 'yellow-blue', helpful: 71, verified: true,
        en: { name: 'Shota', title: 'Cracked in the microwave after three months', body: 'A crack appeared across the base of the yellow mug after reheating milk for a minute. It was past the 30 days, so no return and no warranty.' },
        ja: { name: '翔太', title: '3か月でレンジ加熱中にひび', body: '牛乳を1分温めたら、イエローの底にひびが入りました。30日を過ぎていたので返品もできず、保証もありません。' } },
      { stars: 4, date: '2026-06-22', variant: 'yellow-blue', helpful: 30, verified: true,
        en: { name: 'Mika', title: 'Bigger than the real thing, less than half the price', body: 'Compared with my friend’s Kagami Kiln pair (300 mL), these hold more and cost less than half as much. The yellow is more lemon than yuzu and very shiny. Fine for daily coffee as long as you are not expecting handmade pottery.' },
        ja: { name: 'みか', title: '本物より大きく、値段は半分以下', body: '友人の鏡窯のペアマグ（300mL）と比べると、こちらのほうが容量は大きく、値段は半分以下。イエローは柚子というよりレモン色で、かなりてかてかです。手作りの器を期待しなければ、毎日のコーヒーには十分。' } },
      { stars: 3, date: '2025-10-16', variant: 'yellow-blue', helpful: 22, verified: true,
        en: { name: 'Riku', title: 'Arrived after the date I needed', body: 'Ordered on the Monday before last year’s Lantern Festival for visiting friends; it arrived the following Tuesday, eight days later. The mugs are fine. If it is for a specific date, order early or buy something that ships from Marketa.' },
        ja: { name: 'りく', title: '必要な日に間に合わず', body: '去年の灯籠まつりの前の月曜に、来客用に注文。届いたのは8日後、まつり明けの火曜日でした。マグ自体は問題なし。日にちが決まっているなら早めに注文するか、マルケタ発送の商品を選んだほうがいいです。' } },
      { stars: 2, date: '2026-05-30', variant: 'yellow-blue', helpful: 19, verified: true,
        en: { name: 'Paul', title: 'Thin handle, hot knuckles', body: 'The handle is thin and close to the body, so my knuckles touch the hot side when it is full. There was also a chemical smell from the box for a few days.' },
        ja: { name: 'ポール', title: '取っ手が細く、指が熱い', body: '取っ手が細くて本体に近いので、いっぱいに入れると指の関節が熱い側面に当たります。箱から数日間、薬品のようなにおいもしました。' } },
      { stars: 5, date: '2026-09-09', variant: 'yellow-blue', helpful: 12, verified: true,
        en: { name: 'Mama of two', title: 'The kids love them', body: 'Bought two pairs for the children’s hot chocolate. Bright colours, and they have survived several drops onto the tatami.' },
        ja: { name: '2児のママ', title: '子どもたちのお気に入り', body: '子どものココア用に2セット購入。明るい色で、畳に何度か落としても割れていません。' } },
      { stars: 3, date: '2026-04-14', variant: 'yellow-blue', helpful: 25, verified: true,
        en: { name: 'Hana', title: 'Much shinier than the photos', body: 'In the photos they look soft and matte. In person they are very glossy, almost plastic-looking. The colours themselves are fine.' },
        ja: { name: 'はな', title: '写真よりかなりてかてか', body: '写真ではしっとりしたマットな質感に見えますが、実物はつやつやで、少しプラスチックっぽく見えます。色は悪くないです。' } },
      { stars: 1, date: '2026-09-01', variant: 'yellow-blue', helpful: 54, verified: true,
        en: { name: 'Kenji', title: 'Can’t return them once opened', body: 'I opened the box, did not like how they looked, and asked to return them unused. BrightDeal refused because change-of-mind returns are for unopened items only. How are you supposed to judge mugs without opening the box?' },
        ja: { name: '健二', title: '開封したら返品できない', body: '箱を開けて見た目が気に入らず、未使用のまま返品を申し込んだら、お客様都合の返品は未開封品のみと断られました。箱を開けずにマグの良し悪しなんて判断できません。' } },
      { stars: 4, date: '2026-08-17', variant: 'yellow-blue', helpful: 14, verified: true,
        en: { name: 'Saki', title: 'Six months in the dishwasher, still glossy', body: 'Unlike handmade mugs, these have been through the dishwasher every day for six months and the glaze has not dulled at all. No chips so far.' },
        ja: { name: 'さき', title: '食洗機で半年、つやも健在', body: '手作りのマグと違って、半年間毎日食洗機に入れても釉薬のつやがまったく落ちません。今のところ欠けもなし。' } },
      { stars: 5, date: '2026-07-27', variant: 'yellow-blue', helpful: 8, verified: false,
        en: { name: 'Alex', title: 'Fine if you know what you are buying', body: 'They are cheap factory mugs with nice colours. That is all they claim to be, if you read the description.' },
        ja: { name: 'アレックス', title: 'わかって買えば問題なし', body: '色がきれいな安い工場製のマグです。説明を読めば、それ以上のものだとは書いていません。' } },
    ],
    qa: [
      { date: '2026-05-14', votes: 63,
        en: { q: 'Is this genuine Harukawa ware?', a: 'No. This is a Harukawa-style design produced by our partner factory in China. It is not made in Harukawa.', by: 'BrightDeal Trading' },
        ja: { q: '本物の春川焼ですか？', a: 'いいえ。中国の提携工場で製造した春川焼風デザインの商品です。春川で作られたものではありません。', by: 'ブライトディール商事' } },
      { date: '2026-10-03', votes: 7,
        en: { q: 'Will it arrive in Harukawa before 10 October?', a: 'Mine took 6 days from Kobe. They don’t promise a date, so if it’s for the festival I wouldn’t count on it.', by: 'Marketa customer (Riku)' },
        ja: { q: '10月10日までに春川に届きますか？', a: '私のときは神戸から6日かかりました。日付の保証はないので、まつりに使うなら当てにしないほうがいいと思います。', by: 'マルケタ購入者（りく）' } },
      { date: '2026-06-09', votes: 21,
        en: { q: 'Can you add noshi or gift wrapping?', a: 'Sorry, we do not offer noshi, gift wrapping or gift messages. The mugs come in a printed gift box.', by: 'BrightDeal Trading' },
        ja: { q: 'のしやラッピングはできますか？', a: '申し訳ございませんが、のし・ラッピング・メッセージカードには対応しておりません。マグは印刷入りのギフトボックスに入っています。', by: 'ブライトディール商事' } },
      { date: '2026-03-28', votes: 12,
        en: { q: 'Is the glaze lead-free?', a: 'Yes. The mugs are tested for lead and cadmium to Japan’s Food Sanitation Act standards.', by: 'BrightDeal Trading' },
        ja: { q: '釉薬に鉛は含まれていませんか？', a: 'はい。食品衛生法の基準に基づき、鉛・カドミウムの検査を行っております。', by: 'ブライトディール商事' } },
      { date: '2026-08-04', votes: 18,
        en: { q: 'Is this the same as the Kagami Kiln mug pair, just cheaper?', a: 'No. The Kagami Kiln mugs are handmade in Harukawa, 300 mL, with an unglazed foot and different colours each time. These are factory-made, 350 mL, glossy and identical.', by: 'Marketa customer (Mika)' },
        ja: { q: '鏡窯のペアマグの安い版ですか？', a: '違います。鏡窯のマグは春川で手作りされた300mLで、高台が素地のまま、色も一つずつ違います。こちらは工場製の350mLで、つやつや・均一です。', by: 'マルケタ購入者（みか）' } },
    ],
    similar: ['kagami-mug-pair', 'kagami-tea-set', 'kagami-plate-set'],
    fbt: ['vetrina-kettle', 'shiroshita-senbei'],
    alsoViewed: ['kagami-mug-pair', 'kagami-plate-set', 'vetrina-kettle', 'kagami-tea-set', 'corvo-kettle', 'kagami-sake-set'],
  },
];
