name: Main branch backup

on:
  push:
    branches:
      - main

env:
  GIT_PATH: "tomfluff/unilens-backup"
  BACKUP_TOKEN: ${{ secrets.BACKUP_TOKEN }}

jobs:
  ci-check:
    runs-on: ubuntu-latest

    steps:
      - name: Run CI check
        run: make check

  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensures full history for snapshotting
          persist-credentials: false # guarantees PAT is preferred

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add backup remote
        run: |
          set -x
          git remote add backup "https://github.com/$GIT_PATH.git"
          git remote -v
          git config --get remote.backup.url

      - name: Test token access
        run: |
          set -x
          echo "Token is ${#BACKUP_TOKEN} characters long"
          curl -s -o /dev/null -w "%{http_code}\n" \
            -H "Authorization: Bearer $BACKUP_TOKEN" \
            https://api.github.com/repos/$GIT_PATH

      - name: Run ls remote
        env:
          SNAPSHOT_BRANCH: ${{ steps.vars.outputs.branch }}
        run: |
          set -x
          echo "ls-remote"
          git ls-remote "https://x-access-token:$BACKUP_TOKEN@github.com/$GIT_PATH.git"

      - name: Push snapshot to backup repo
        run: |
          set -x
          echo "Snapshot branch name:"
          SNAPSHOT_BRANCH="snapshot-$(date +'%Y-%m-%d')-$(git rev-parse --short HEAD)"

          echo "Running dry run"
          git push --verbose --dry-run "https://x-access-token:$BACKUP_TOKEN@github.com/$GIT_PATH.git" "main:refs/heads/$SNAPSHOT_BRANCH"
          echo "Running full push :D"
          git push --verbose "https://x-access-token:$BACKUP_TOKEN@github.com/$GIT_PATH.git" "main:refs/heads/$SNAPSHOT_BRANCH"
          echo "Reflecting to remote main"
          git push --verbose "https://x-access-token:$BACKUP_TOKEN@github.com/$GIT_PATH.git" main -f
